### ISSUE TITLE
Embeddings

### ISSUE THREAD

**Issue by sunvoyage** [langchain4j/langchain4j#1]
is it possible to add hugging face embeddings as well with support for multiple transformers .

Additionally trying to take a look into the code section
Found that the import dev.ai4j.openai4j.*; package is not migrated to run the samples to test more

**Comment by langchain4j** [comment]
Hi @sunvoyage I will work on huggingface integration next week, will share updates with you.

Regarding the imports, could you please elaborate what is wrong?

**Comment by sunvoyage** [comment]
Hugging face embeddings would be great. 👍 

I was trying to import the project did receive an error 
The screen shot provides the details the ai4j package isn't found on the repo..

https://github.com/langchain4j/langchain4j/blob/main/langchain4j/src/main/java/dev/langchain4j/model/openai/OpenAiChatModel.java

![package_not_in_repository](https://github.com/langchain4j/langchain4j/assets/62082409/b4c86296-d9ae-4eee-be74-97ec46441ed2)

**Comment by langchain4j** [comment]
It seems that openai4j dependency was not pulled automatically. Can you right-click on the project, then "Maven > Update Project...", then select "Force Update of Snapshots/Releases", then click ok? Or try doing "mvn clean install". But make a pull before that, I have just pushed parent pom. Please let me know if it worked or not.

**Comment by langchain4j** [comment]
@sunvoyage just added support for HF embeddings, pelase take a look: https://github.com/langchain4j/langchain4j-examples/blob/main/src/main/java/ChatWithDocumentsExamples.java

BTW, what do you mean by "support for multiple transformers"?

**Comment by sunvoyage** [comment]
Got it. Maven clean install 

> It seems that openai4j dependency was not pulled automatically. Can you right-click on the project, then "Maven > Update Project...", then select "Force Update of Snapshots/Releases", then click ok? Or try doing "mvn clean install". But make a pull before that, I have just pushed parent pom. Please let me know if it worked or not.

**Comment by sunvoyage** [comment]
> @sunvoyage just added support for HF embeddings, pelase take a look: https://github.com/langchain4j/langchain4j-examples/blob/main/src/main/java/ChatWithDocumentsExamples.java
> 
> BTW, what do you mean by "support for multiple transformers"?

That's so cool will check it out .... You rock .. :thumbsup:
I was thinking of Pytorch transformer... 

Additionally it would be great to add CSV support as well..

**Comment by langchain4j** [comment]
> I was thinking of Pytorch transformer...

Do you want to donwload models from HF in a pytorch format and run locally? Via llama.cpp or something like this?
Or do you want to run it remotely on HF (via their Inference API, for free)?

> Additionally it would be great to add CSV support as well..

Could you provide more info? Which use case do you have in mind? How your data looks like?

**Comment by sunvoyage** [comment]
> pytorch format and run locally



> > I was thinking of Pytorch transformer...
> 
> Do you want to donwload models from HF in a pytorch format and run locally? Via llama.cpp or something like this? Or do you want to run it remotely on HF (via their Inference API, for free)?

Pytorch format and to run locally. I actually didn't know there is a free API from HF
> 
> > Additionally it would be great to add CSV support as well..
> 
> Could you provide more info? Which use case do you have in mind? How your data looks like?
Currently in your use cases do see a PDF and TXT support. The CSV could be any data all it does it creates and adds a embedding column at the end of csv and this embedding could queried and we could ask question about the data and total or sum a record column.

**Comment by langchain4j** [comment]
How do you run models locally? Using what software? I can easily add integration with https://github.com/go-skynet/LocalAI if it will be useful for you.

**Comment by langchain4j** [comment]
@sunvoyage There is now support for local models via [LocalAI](https://localai.io/). You can also use in-process embedding models (run them directly in your JVM process): https://github.com/langchain4j/langchain4j-examples/blob/main/other-examples/src/main/java/InProcessEmbeddingModelExamples.java
