### ISSUE TITLE
[FEATURE] How to building custom agent using local LLM?

### ISSUE THREAD

**Issue by Zhouuuuo** [langchain4j/langchain4j#1001]
I'd like to customize an agent using a local LLM without relying on OpenAI's Assistants API. Do you have any examples or development plans?

**Comment by langchain4j** [comment]
@Zhouuuuo what do you mean by "agent"? Which exactly features are required?

**Comment by langchain4j** [comment]
@Zhouuuuo please open a discussion and reply [here](https://github.com/langchain4j/langchain4j/discussions)
