### ISSUE TITLE
[BUG]  Cannot read field "inputTokenCount" because "that" is null langchain4j 0.29.1

### ISSUE THREAD

**Issue by Colin4k1024** [langchain4j/langchain4j#1008]
the local ai llm  not support tokenusage in streaming call

**Comment by langchain4j** [comment]
Hi, could you please provide code to reproduce this issue?

**Comment by Colin4k1024** [comment]
I find the mistake , we use the local ai the chat api no return token usage in streaming chat ,so on add token completionHandler.accept(Response.from(
                        aiMessage,
                        tokenUsage.add(response.tokenUsage()),
                        response.finishReason())
                ); response.tokenUsage() is null

**Comment by langchain4j** [comment]
@fanjia1024 could you please provide the code to **_reproduce_** this bug?

It is probably already [fixed](https://github.com/langchain4j/langchain4j/pull/939/files).

**Comment by Colin4k1024** [comment]
ok I will upgraded version  0.30  thanks
