### ISSUE TITLE
If I want to modify the InternalOpenAiHelper.OPENAI_URL address, what should I do

### ISSUE THREAD

**Issue by stoneLee81** [langchain4j/langchain4j#102]
Because I use openai’s domestic proxy domain name, OPENAI_URL is not https://api.openai.com, if I want to change the address of openai_url value, what should I do? In the code, this parameter is final。

**Comment by langchain4j** [comment]
@stoneLee81 we are adding an option to define baseUrl for OpenAi*Model classes. Should be released today evening.
