### ISSUE TITLE
[BUG]   Some functional module classes published to the warehouse are not public

### ISSUE THREAD

**Issue by 195070811** [langchain4j/langchain4j#1025]
When I was testing the Ollama module in a Spring Boot project, I found that it was not possible to add the Langchain4j Ollama module through Maven dependency because I found that the classes in this module were not public and could not be referenced. I don't know if other modules have the same problem. Why not use public public classes

**Comment by langchain4j** [comment]
@195070811 what classes exactly?

**Comment by langchain4j** [comment]
@195070811 closing as there is no answer. Feel free to reopen
