### ISSUE TITLE
[BUG] FileSystemDocumentLoader#loadDocuments has a potential issue when using ApacheTikaDocumentParser

### ISSUE THREAD

**Issue by vprudnikov** [langchain4j/langchain4j#1026]
**Describe the bug**
`FileSystemDocumentLoader#loadDocuments` has a potential issue when using ApacheTikaDocumentParser
As shown in the `langchain4j-examples`, this line of code doesn't work as expected:
`List<Document> documents = loadDocuments(directoryPath, new ApacheTikaDocumentParser());`

**To Reproduce**
Try to load at least 2 documents using the provided example.

**Expected behavior**
Each document is loaded independently.

**Current behavior**

* The first document contains its parsed content
* The second document contains the content of the first document plus its content
* The third document contains the content of the previous documents plus its content
* ... and so on

**Please complete the following information:**
- LangChain4j version: 0.30.0
- LLM(s) used: NA
- Java version: 21
- Spring Boot version (if applicable): NA

**Additional context**
It looks like the ApacheTikaDocumentParser is a stateful object. That's why it cannot be reused across all documents.
Probably, a better solution would be using a Supplier like so:
`List<Document> documents = loadDocuments(directoryPath, () -> new ApacheTikaDocumentParser());`
or
`List<Document> documents = loadDocuments(directoryPath, filePath -> new ApacheTikaDocumentParser());`
As a result, a new fresh instance of the parser will be provided each time.

**Comment by langchain4j** [comment]
@vprudnikov thank you so much for reporting!

**Comment by langchain4j** [comment]
Fixed by https://github.com/langchain4j/langchain4j/pull/1031
