### ISSUE TITLE
How can I implement a ChatMemoryStore to store data item by item? please help me

### ISSUE THREAD

**Issue by LiuYuPeng1101** [langchain4j/langchain4j#1027]
`public class PersistentChatMemoryStore implements ChatMemoryStore {

    @Resource
    private SessionChatRecordService sessionChatRecordService;

    @Override
    public List<ChatMessage> getMessages(Object memoryId) {
        SessionChatRecord chatRecord = sessionChatRecordService.getOne(new LambdaQueryWrapper<SessionChatRecord>().eq(SessionChatRecord::getSessionId, Convert.toLong(memoryId)));
        if (ObjectUtil.isNull(chatRecord)) {
            return  new ArrayList<>();
        }
        return messagesFromJson(chatRecord.getContent());
    }

    @Override
    public void updateMessages(Object memoryId, List<ChatMessage> messages) {
        String json = messagesToJson(messages);
        SessionChatRecord sessionChatRecord = SessionChatRecord.builder().sessionId(Convert.toLong(memoryId)).content(json).build();
        sessionChatRecordService.saveOrUpdate(sessionChatRecord,new LambdaUpdateWrapper<SessionChatRecord>()
                .eq(SessionChatRecord::getSessionId,Convert.toLong(memoryId)).set(SessionChatRecord::getContent,sessionChatRecord.getContent()));
    }

    @Override
    public void deleteMessages(Object memoryId) {}

}`
**As mentioned in my code above, I store all chat records in the 'content' field of a MySQL database. However, I now want to store chat records one by one. How can I implement this?**

**Comment by langchain4j** [comment]
@LiuYuPeng1101 there is a similar `messageToJson()` method that converts each message to json. Then you can store each one as a separate record in the DB.

Please note that this is not a chat **_history_**, it is a chat **_memory_**, it does not store all the messages in the conversation, only those that fit into the configured message/token window.

**Comment by LiuYuPeng1101** [comment]
@langchain4j  Thank you for the reminder. I used the following code for the dialogue with the large model:
`@GetMapping("/assistant")
public String assistant(@RequestParam(value = "memoryId") Long memoryId,
                           @RequestParam(value = "message") String message) {
    return assistant.chat(memoryId,message);`
**I plan to use MySQL to store chat records one by one. Are there any examples I can refer to? If not MySQL, are there any references for storing chat records in general?**

**Comment by langchain4j** [comment]
@LiuYuPeng1101 may I ask you why do you want to store chat messages separately?

There is a `CassandraChatMemoryStore` as an example of storing messages separately, but honestly there is nothing LangChain4j-specific here, this is a "how do I store multiple related entries in a relational database" type of problem, there should be a lot of material on that online.

**Comment by langchain4j** [comment]
@LiuYuPeng1101 I am closing htis issue, please use discord or discussions in the future.

**Comment by cmasantos** [comment]
Hi, 

In current interface of the `ChatMemoryStore` store you can only get and a list and update a list. When we just want to add a item, we need to get the list, add and element to end of the list and update the list. If the interface had one more method like `void updateMessage(Object memoryId, ChatMessage messages);` this logic could be implemented by the interface implementation and removed from the business logic.

**Comment by langchain4j** [comment]
@cmasantos do you mean something like this?

```java
public interface ChatMemoryStore {

    List<ChatMessage> getMessages(Object memoryId);

    void updateMessages(Object memoryId, List<ChatMessage> messages);

    default void addMessage(Object memoryId, ChatMessage message) {
        List<ChatMessage> messages = getMessages(memoryId);
        messages.add(message);
        updateMessages(memoryId, messages);
    }

    ...
}
```

**Comment by cmasantos** [comment]
> @cmasantos do you mean something like this?
> 
> ```java
> public interface ChatMemoryStore {
> 
>     List<ChatMessage> getMessages(Object memoryId);
> 
>     void updateMessages(Object memoryId, List<ChatMessage> messages);
> 
>     default void addMessage(Object memoryId, ChatMessage message) {
>         List<ChatMessage> messages = getMessages(memoryId);
>         messages.add(message);
>         updateMessages(memoryId, messages);
>     }
> 
>     ...
> }
> ```

Yes, I think this would be ok.

**Comment by langchain4j** [comment]
How do you plan to use it? Callind the method directly?

---

Current implementations of `ChatMemory` evict old messages that no longer fit into the sliding window. This is why the whole list gets updated in the `getMessages` and `updateMessages`.

**Comment by cmasantos** [comment]
Sorry, you are right, I failed to understand the correct abstractions and was doing it the wrong way. The `ChatMemory` interface is the one responsibly for this kind of operations.
