### ISSUE TITLE
No Dependencies in POM file?

### ISSUE THREAD

**Issue by LobsterMan123** [langchain4j/langchain4j#1029]
Hello everyone, I'd like to use langchain4j and I took a look at the provided pom file but I noticed there were no dependencies only so-called modules.  I've only ever seen dependencies in the pom files for java packages I've used.  Would someone please tell me why there is no dependencies section in the pom file and if these so-called modules are a replacement/substitute for the typical dependencies?  I was expecting to see a standard maven dependencies section I could just add to my existing pom file but it seems to be different for langchain4j.

**Comment by LizeRaes** [comment]
Hi @LobsterMan123 if you want to use LangChain4j in your projects, have a look at our example repository https://github.com/langchain4j/langchain4j-examples
A good place to start is the /tutorials folder, where you'll find a pom file with the dependency import you're looking for. Note, if you want to use other models than OpenAI ones, have a look in the examples for those models/integration to get the dependencies right.
I can also recommend or Get Started and Tutorials in the documentation (linked in the README).
Hope it helps.
