### ISSUE TITLE
[BUG] When Maven calls Stream output directly using langchain4j's jar package, there is a problem with the okhttp dependency package that causes the call to fail. The call can be completed by removing the default okhttp version (3.14.9) and replacing it with, say, 4.9.3

### ISSUE THREAD

**Issue by wuyuhuangquan** [langchain4j/langchain4j#1039]
**Describe the bug**

Using the langchainjar package default okhttp dependency (3.14.9) will cause the invocation of large model streaming output to fail; After replacing the okhttp dependency version (4.9.3), streaming output can be achieved successfully.

**Log and Stack trace**

Exception in thread "main" java.lang.NoSuchMethodError: okhttp3.RequestBody.create(Ljava/lang/String;Lokhttp3/MediaType;)Lokhttp3/RequestBody;
at dev.langchain4j.model.qianfan.client.StreamingRequestExecutor.stream(StreamingRequestExecutor.java:89)
at dev.langchain4j.model.qianfan.client.StreamingRequestExecutor.access$000(StreamingRequestExecutor.java:17)
at dev.langchain4j.model.qianfan.client.StreamingRequestExecutor$1$1$1.execute(StreamingRequestExecutor.java:45)
at dev.langchain4j.model.qianfan.QianfanStreamingChatModel.generate(QianfanStreamingChatModel.java:134)
at dev.langchain4j.model.qianfan.QianfanStreamingChatModel.generate(QianfanStreamingChatModel.java:86)
at dev.langchain4j.model.chat.StreamingChatLanguageModel.generate(StreamingChatLanguageModel.java:25)
at generator.test$StreamingLanguageModel_Example.main(test.java:57)

**To Reproduce**

 static class StreamingLanguageModel_Example {

        public static void main(String[] args) {
            // Sorry, "demo" API key does not support streaming (yet). Please use your own key.
//            StreamingLanguageModel model = OpenAiStreamingLanguageModel.builder()
//                    .apiKey(ApiKeys.OPENAI_API_KEY)
//                    .baseUrl(ApiKeys.OPENAI_BASE_URL)
//                    .modelName("gpt-3.5-turbo")
//                    .temperature(0.7).build();
            QianfanStreamingChatModel model = QianfanStreamingChatModel.builder()
                    .apiKey(ApiKeys.BAIDU_API_KEY)
                    .secretKey(ApiKeys.BAIDU_SECRET_KEY)
                    .modelName("ERNIE-Bot")
                    .temperature(0.01)
                    .build();

            model.generate("帮我写一篇500字的秋游总结", new StreamingResponseHandler<AiMessage>() {
                @Override
                public void onNext(String s) {
                    System.out.print(s);
                }

                @Override
                public void onError(Throwable throwable) {
                    throw new RuntimeException(throwable);
                }
            });
        }
    }

**Expected behavior**

Replace the langchain4j default okhttpjar package dependency version to eliminate this BUG.

**Please complete the following information:**
- LangChain4j version:0.30.0
- LLM(s) used: ERNIE-Bot(百度文心)
- Java version: 1.8.0_241
- Spring Boot version (if applicable): 2.4.3

**Additional context**

**Comment by langchain4j** [comment]
@wuyuhuangquan LangChain4j uses okhttp 4.12.0, where did you get 3.14.9 and 4.9.3 from?

**Comment by wuyuhuangquan** [comment]
When I directly use Maven to reference the 0.30.0 dependency of langchain4j, the okhttp dependency in the 0.30.0 dependency of this langchain4j is 3.14.9, and the above error appears. So I excluded the OKhttp dependency in langchain4j and referenced the OKhttp dependency of 4.9.3 myself, and it was successful. Is there a problem with saving me alone?

**Comment by wuyuhuangquan** [comment]
@langchain4j When I directly use Maven to reference the 0.30.0 dependency of langchain4j, the okhttp dependency in the 0.30.0 dependency of this langchain4j is 3.14.9, and the above error appears. So I excluded the OKhttp dependency in langchain4j and referenced the OKhttp dependency of 4.9.3 myself, and it was successful. Is there a problem with saving me alone?

**Comment by langchain4j** [comment]
@wuyuhuangquan could you please provide the output of `mvn dependency:tree -Dverbose` on your project?

**Comment by wuyuhuangquan** [comment]
[INFO] +- dev.langchain4j:langchain4j:jar:0.30.0:compile
[INFO] |  +- dev.langchain4j:langchain4j-core:jar:0.30.0:compile
[INFO] |  |  +- com.google.code.gson:gson:jar:2.8.6:compile (version managed from 2.10.1)
[INFO] |  |  \- (org.slf4j:slf4j-api:jar:1.7.30:compile - version managed from 2.0.7; omitted for duplicate)
[INFO] |  +- com.squareup.retrofit2:retrofit:jar:2.9.0:compile
[INFO] |  |  \- (com.squareup.okhttp3:okhttp:jar:3.14.9:compile - version managed from 4.12.0; omitted for duplicate)
[INFO] |  +- com.squareup.okhttp3:okhttp:jar:3.14.9:compile
[INFO] |  |  \- com.squareup.okio:okio:jar:1.17.2:compile
[INFO] |  +- org.apache.opennlp:opennlp-tools:jar:1.9.4:compile
[INFO] |  +- org.jsoup:jsoup:jar:1.16.1:compile
[INFO] |  \- (org.slf4j:slf4j-api:jar:1.7.30:compile - version managed from 2.0.7; omitted for duplicate)
[INFO] +- dev.langchain4j:langchain4j-open-ai:jar:0.30.0:compile
[INFO] |  +- (dev.langchain4j:langchain4j-core:jar:0.30.0:compile - omitted for duplicate)
[INFO] |  +- dev.ai4j:openai4j:jar:0.17.0:compile
[INFO] |  |  +- (com.squareup.retrofit2:retrofit:jar:2.9.0:compile - omitted for duplicate)
[INFO] |  |  +- (com.squareup.retrofit2:converter-gson:jar:2.9.0:compile - omitted for duplicate)
[INFO] |  |  +- (com.google.code.gson:gson:jar:2.8.6:compile - version managed from 2.8.9; omitted for duplicate)
[INFO] |  |  +- (com.squareup.okhttp3:okhttp:jar:3.14.9:compile - version managed from 4.12.0; omitted for duplicate)
[INFO] |  |  +- (com.squareup.okhttp3:okhttp-sse:jar:3.14.9:compile - version managed from 4.12.0; omitted for duplicate)
[INFO] |  |  \- (org.slf4j:slf4j-api:jar:1.7.30:compile - version managed from 2.0.7; omitted for duplicate)
[INFO] |  \- com.knuddels:jtokkit:jar:1.0.0:compile
[INFO] +- dev.langchain4j:langchain4j-qianfan:jar:0.30.0:compile
[INFO] |  +- (dev.langchain4j:langchain4j-core:jar:0.30.0:compile - omitted for duplicate)
[INFO] |  +- (com.squareup.retrofit2:retrofit:jar:2.9.0:compile - omitted for duplicate)
[INFO] |  +- com.squareup.retr




@langchain4j 


Yes, there should be a dependency conflict that overwrites the default okhttp version of langchain4j 4.12.0, then this is a problem of my own project. Thank.
