### ISSUE TITLE
[FEATURE] Extract Judge0 classes into a separate module

### ISSUE THREAD

**Issue by langchain4j** [langchain4j/langchain4j#1048]
The following classes should be extracted into a separate module `langchain4j-code-execution-engine-judge0`, similarly to `langchain4j-code-execution-engine-graalvm-polyglot`:
- `Judge0JavaScriptEngine`
- `JavaScriptCodeFixer`
- `Judge0JavaScriptExecutionTool`
- `JavaScriptCodeFixerTest`

`com.squareup.okhttp3:okhttp` dependency should be removed from main (`langchain4j`) module.

**Comment by anunnakian** [comment]
I'll work on that

**Comment by langchain4j** [comment]
Implemented in https://github.com/langchain4j/langchain4j/pull/1051
