### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by singletoint** [langchain4j/langchain4j#105]
Please provide as much details as possible, this will help us to deliver a fix as soon as possible.
Thank you!

**Describe the bug**
ParagraphSplitter class
String[] paragraphs = text.split("\\R\\R");
There is no \R\R in Linux, this is a bug, please fix it.

**Log and Stack trace**
Please provide a log and a stack trace (with exception), if applicable.

**To Reproduce**
Please provide a relevant code snippets to reproduce this bug.

**Expected behavior**

**Please complete the following information:**
- LangChain4j version: e.g. 0.20.0
- Java version: e.g. 11
- Spring Boot version (if applicable): e.g. 2.7.13

**Additional context**

**Comment by langchain4j** [comment]
@singletoint I have just tested this code on ubuntu and it works fine. What do you mean by "There is no \R\R in Linux"? See https://www.baeldung.com/java-string-split-by-newline#split%20java%20string%20by%20new%20line%20in%20java%208

**Comment by singletoint** [comment]
> @singletoint I have just tested this code on ubuntu and it works fine. What do you mean by "There is no \R\R in Linux"? See https://www.baeldung.com/java-string-split-by-newline#split%20java%20string%20by%20new%20line%20in%20java%208

Thank you for your response! I apologize for any confusion. What I meant to say was that I tested the paragraph splitter in CentOS 7.9, and I found that the result is returning the entire PDF document directly.

**Comment by langchain4j** [comment]
@singletoint this is how pdfbox library outputs it... unfortunately we have no control over it.

**Comment by singletoint** [comment]
> @singletoint this is how pdfbox library outputs it... unfortunately we have no control over it.

I understand now, thank you for your response again!
