### ISSUE TITLE
[FEATURE] Figure out what to do with opennlp-tools dependency

### ISSUE THREAD

**Issue by langchain4j** [langchain4j/langchain4j#1050]
`org.apache.opennlp:opennlp-tools` dependency (~1.3 MB) is used only in `DocumentBySentenceSplitter` and recursive splitter, but this class is most probably widely used for RAG use case.

Options:
- Make it an optional dependency (breaking change)
- Extract it into a separate module (breaking change)
- Replace the library with some more primitive sentence-splitting logic?
- Copy required classes from `opennlp-tools` into lc4j?
- Something else?

**Comment by kpavlov** [comment]
Making the dependency optional is the easiest and, I believe, the right change #1947. Users should add it themself, if needed.

**Comment by glaforge** [comment]
Sentence splitting is my favorite splitter. 
I understand that we want to reduce the number of dependencies though.
I agree with @kpavlov that making the dependency optional is probably the easiest, but it's sad that it's a breaking change.
At least, if we go this route, it has to be clearly documented.
And maybe at the cost of some `Class.forname()` call, when instantiating or calling the `DocumentBySentenceSplitter`, we could throw a very explicit and meaningful exception?

**Comment by langchain4j** [comment]
Obviously I have no numbers, but my gut feeling is that `DocumentBySentenceSplitter` (either standalone or as a part of a recursive splitter) is used a lot, perharps even more people use it than not (RAG is a very popular use case).
If this is true, perharps we should just keep it?
Those who don't need it and care about extra dependencies can always exclude it.
But those who use it (assuming it is a majority) will not have to fix breaking changes.
WDYT?

**Comment by jmartisk** [comment]
> Obviously I have no numbers, but my gut feeling is that `DocumentBySentenceSplitter` (either standalone or as a part of a recursive splitter) is used a lot, perharps even more people use it than not (RAG is a very popular use case). If this is true, perharps we should just keep it? Those who don't need it and care about extra dependencies can always exclude it. But those who use it (assuming it is a majority) will not have to fix breaking changes. WDYT?

+1 if it's used a lot, best to just keep it and let people exclude it if necessary (this can be suggested somewhere in the documentation)

**Comment by glaforge** [comment]
I suspect that 90% of the RAG users are using the recursive splitter almost by default, which uses the sentence splitter, and thus this `opennlp` library. 

I like the idea of having a good sentence splitter, rather than reinventing the wheel with a lesser good implementation, or not staying up-to-date with the latest improvements in opennlp in case we copy over their code.

**Comment by jmartisk** [comment]
> I like the idea of having a good sentence splitter, rather than reinventing the wheel with a lesser good implementation, or not staying up-to-date with the latest improvements in opennlp in case we copy over their code.

+1000, copying code from a library is bad for a multitude of reasons

**Comment by langchain4j** [comment]
So can we agree to keep things as-is for now (`opennlp-tools` is a normal dependency of `langchain4j` module) and close this issue? We can revisit this again if there will be complaints from users in the future

**Comment by glaforge** [comment]
I'm fine with the status quo, yes.

**Comment by behrica** [comment]
The opennlp dependency is a bit old. (1.9.4)
I get conflicts when having a newer version org.apache.opennlp/opennlp-tools 1.9.4 on classpath

Maybe it should be upgraded.
