### ISSUE TITLE
[FEATURE] Declaring Hugging Face model Id type as an Enum

### ISSUE THREAD

**Issue by anunnakian** [langchain4j/langchain4j#1071]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I think that anyone can put any string as a model Id to build a Hugging Face Model.
Here is an example : 
 
```java
HuggingFaceEmbeddingModel.builder()
          .accessToken(API_KEY)
          .modelId("Hellow world! Feel free to put any string here :D")
          .timeout(ofSeconds(120))
          .waitForModel(true)
          .build();
```

**Describe the solution you'd like**
I propose to force the type here by transforming the type of that field into an Enum.

**For example :**
Before:
```java
public final class HuggingFaceModelName {
    public static final String TII_UAE_FALCON_7B_INSTRUCT = "tiiuae/falcon-7b-instruct";
    public static final String SENTENCE_TRANSFORMERS_ALL_MINI_LM_L6_V2 = "sentence-transformers/all-MiniLM-L6-v2";

    private HuggingFaceModelName() {
    }
}
```

After: 
```java
public enum HuggingFaceModelName {
    TII_UAE_FALCON_7B_INSTRUCT("tiiuae/falcon-7b-instruct"),
    SENTENCE_TRANSFORMERS_ALL_MINI_LM_L6_V2("sentence-transformers/all-MiniLM-L6-v2");
    
    @Getter
    private String name;

    private HuggingFaceModelName(String name) {
         this.name = name;
    }
}
```

P.S: I'm glad the `timeout` field is declared as a `Duration`, not an `Integer` 🤓 

All your remarks are welcome !

**Comment by langchain4j** [comment]
Hi @anunnakian I am not sure should enforce an enum there as `modelId` can be one of **_thousands_** available on HF hub.

**Comment by anunnakian** [comment]
Ok, my bad, I didn't see that 😄
