### ISSUE TITLE
[BUG] Unable to create custom PromptTemplate 

### ISSUE THREAD

**Issue by jayshetti** [langchain4j/langchain4j#1075]
**Describe the bug**
I am trying langchain4J in Android and Upon creation new PromptTemplate as below, I see exception java.lang.ExceptionInInitializerError

```
 PromptTemplate prompt = new PromptTemplate(
                "Read and understand the conversation between the User and the AI. " +
                        "Then, analyze the new query from the User. " +
                        "Identify all relevant details, terms, and context from both the conversation and the new query. " +
                        "Reformulate this query into a clear, concise, and self-contained format suitable for information retrieval.\n" +
                        "\n" +
                        "Conversation:\n" +
                        "{{chatMemory}}\n" +
                        "\n" +
                        "User query: {{query}}\n" +
                        "\n" +
                        "It is very important that you provide only reformulated query and nothing else! " +
                        "Do not prepend a query with anything!"
        );
```
        

**Log and Stack trace**
java.lang.ExceptionInInitializerError
                                                                                                    	at dev.langchain4j.model.input.DefaultPromptTemplateFactory.create(DefaultPromptTemplateFactory.java:18)
                                                                                                    	at dev.langchain4j.model.input.DefaultPromptTemplateFactory.create(DefaultPromptTemplateFactory.java:14)
                                                                                                    	at dev.langchain4j.model.input.PromptTemplate.<init>(PromptTemplate.java:62)
                                                                                                    	at dev.langchain4j.model.input.PromptTemplate.<init>(PromptTemplate.java:51)

 Caused by: java.util.regex.PatternSyntaxException: Syntax error in regexp pattern near index 10
                                                                                                    \{\{(.+?)}}
                                                                                                              ^
**To Reproduce**
Just try to create the PromptTemplate 

**Expected behavior**
PromptTemplate  should be created.

**Please complete the following information:**
- LangChain4j version: 0.30
- LLM(s) used: Azure openAI
- Java version: Android Q

**Comment by jayshetti** [comment]
> The `java.lang.ExceptionInInitializerError` you're encountering seems to be related to the static initialization phase of the `PromptTemplate` class in LangChain4j, specifically when it tries to initialize a `PromptTemplateFactory`. This error can occur due to several reasons, such as service loading failure, exceptions in factory implementations, or compatibility issues with Android.
> 
> To address this issue, you should:
> 
> 1. **Verify Service Provider Configuration**: Ensure any custom `PromptTemplateFactory` implementations are correctly specified in `META-INF/services`. The service provider configuration file should be named `dev.langchain4j.spi.prompt.PromptTemplateFactory` and contain the fully qualified name of your implementation class.
> 2. **Review Factory Implementations**: Make sure that any custom implementations of `PromptTemplateFactory` do not throw exceptions during instantiation and are compatible with Android.
> 3. **Check Android Compatibility**: Ensure all Java features used in your `PromptTemplateFactory` implementations and the `loadFactories` method are compatible with the Android version you are targeting.
> 4. **Debug Static Initialization**: Consider adding logging or try-catch blocks around the static initialization code to identify the exact cause of the error.
> 
> If these steps do not resolve the issue, you might need to provide a custom initialization path for Android that avoids problematic static initialization or uses alternatives compatible with Android.
> 
> #### Details
> _To continue the conversation, mention @dosu._

The root cause seems to be due to 

 private static final Pattern VARIABLE_PATTERN = Pattern.compile("\\{\\{(.+?)}}");
 
Caused by: java.util.regex.PatternSyntaxException: Syntax error in regexp pattern near index 10 {{(.+?)}} ^ this is happening can u see why

**Comment by langchain4j** [comment]
Hi @jayshetti, thanks a lot for reporting! I tried the `PromptTemplate` you provided in plain Java and it works fine. Assuming that this is an AndroidQ-specific issue, could you please provide steps to reproduce it in Androind Q environment? Could be also a github project, thanks!

**Comment by jayshetti** [comment]
> Hi @jayshetti, thanks a lot for reporting! I tried the `PromptTemplate` you provided in plain Java and it works fine. Assuming that this is an AndroidQ-specific issue, could you please provide steps to reproduce it in Androind Q environment? Could be also a github project, thanks!

Hi @langchain4j ,

Still the same issue after lot of debugging i can see that apk which i am building does not the have service PromptTemplateFactory under META-INF/services/.
Can this be an issue? I tried adding it manually also but no luck for me on this.

**Comment by langchain4j** [comment]
If you want to use the `DefaultPromptTemplateFactory`, there is no need to have anything under `META-INF/services/`.

Can you provide code to reproduce this problem? I will be able to debug it then.

**Comment by jayshetti** [comment]
@langchain4j 
                
                Please find the below code snippet, which is causing crash while creating the new  PromptTemplate itself.
				
		```
		ChatLanguageModel chatLanguageModel =  AzureOpenAiChatModel.builder()
                .apiKey("API_KEY")
                .endpoint("END_POINT")
                .deploymentName("MODEL_NAME")
                .temperature(0.3)
                .logRequestsAndResponses(true)
                .build();
				
				PromptTemplate prompt = new PromptTemplate(
                "Read and understand the conversation between the User and the AI. " +
                        "Then, analyze the new query from the User. " +
                        "Identify all relevant details, terms, and context from both the conversation and the new query. " +
                        "Reformulate this query into a clear, concise, and self-contained format suitable for information retrieval.\n" +
                        "\n" +
                        "Conversation:\n" +
                        "{{chatMemory}}\n" +
                        "\n" +
                        "User query: {{query}}\n" +
                        "\n" +
                        "It is very important that you provide only reformulated query and nothing else! " +
                        "Do not prepend a query with anything!"
                );
				
				QueryTransformer queryTransformer = new CompressingQueryTransformer(chatLanguageModel, prompt);
				
		
```		
If i don't pass prompt for  CompressingQueryTransformer its same issue, the crash is observed , below is the back trace.
  
                              at dev.langchain4j.model.input.DefaultPromptTemplateFactory.create(DefaultPromptTemplateFactory.java:18)
                                                                                                    	at dev.langchain4j.model.input.DefaultPromptTemplateFactory.create(DefaultPromptTemplateFactory.java:14)
                                                                                                    	at dev.langchain4j.model.input.PromptTemplate.<init>(PromptTemplate.java:62)
                                                                                                    	at dev.langchain4j.model.input.PromptTemplate.<init>(PromptTemplate.java:51)
                                                                                                    	at dev.langchain4j.model.input.PromptTemplate.from(PromptTemplate.java:126)
                                                                                                    	at dev.langchain4j.rag.query.transformer.CompressingQueryTransformer.<clinit>(CompressingQueryTransformer.java:36)

**Comment by langchain4j** [comment]
Does this happen only in Android-Q? Can yo ureproduce it outside of Android? In plain Java

**Comment by jayshetti** [comment]
> Does this happen only in Android-Q? Can yo ureproduce it outside of Android? In plain Java

@langchain4j If i use the regex present in the DefaultTemplate  then I am encountering the issue, for Android regex should be `"\\{\\{(.+?)\\}\\}"`

This issue will not be there in the Java due to https://stackoverflow.com/a/45075252, and the current Prompttemplate will not work in Android. Do we have any work around for this?

Would be really helpful if I can get any work around or fix for this, I have tried to create diff PromptTemplateFactory to by pass this issue but adding META-INF/Services is difficult task in Android.

**Comment by langchain4j** [comment]
Well, if I understand it correctly, we can just add (unnecessary for java) escapes to both "}" in the regex. Feel free to do this change and open a PR
