### ISSUE TITLE
[BUG] Use ZhipuAiChatModel to input sensitive words

### ISSUE THREAD

**Issue by yongxingMa** [langchain4j/langchain4j#1079]
**Describe the bug**

Use ZhipuAiChatModel to input some sensitive words，error message not returned properly，Leads to a direct interruption of the programme, I would like to be able to return it normally via Response<AiMessage> .

The error message is as follows：
status code: 400; body: {"error":{"code":"1301","message":"系统检测到输入或生成内容可能包含不安全或敏感内容，请您避免输入易产生敏感内容的提示语，感谢您的配合。"}}

` Response<AiMessage> resMessage = zhipuAiChatModel.generate(asList(systemMessage,userMessage));
`

**Comment by langchain4j** [comment]
cc @1402564807
