### ISSUE TITLE
[FEATURE] Support Oracle 23ai as vector database

### ISSUE THREAD

**Issue by aalmiray** [langchain4j/langchain4j#1091]
Oracle 23ai added vector as datatype, it also includes vector search algorithms.

**Additional context**

Oracle 23ai is available for free at https://www.oracle.com/database/free
Docker images can be found at https://github.com/gvenzl/oci-oracle-free

**Comment by geoand** [comment]
cc @jmartisk

**Comment by loiclefevre** [comment]
Great achievment!
