### ISSUE TITLE
[FEATURE] Make MessageWindowChatMemory not to remove evicted messages from ChatMemoryStore

### ISSUE THREAD

**Issue by InAnYan** [langchain4j/langchain4j#1107]
**Is your feature request related to a problem? Please describe.**

In `langchain4j` there are two main interfaces for maintaining chat history: `ChatMemory` and `ChatMemoryStore`.

`ChatMemory` handles the chat history from a high level. It is an algorithm for limiting the chat history for an AI request.

`ChatMemoryStore` is a low-level interface for storing the messages. For now, there is only `InMemoryChatMemoryStore` implementation, but this can be extended for storing the chats, for example, in a database.

While developing an application with `langchain4j`, a question arose in my head: `MessageWindowChatMemory` holds only `N` last messages of the conversation, but does it delete the previous messages from `ChatMemoryStore`? 

I've made an application to test this, and the answer to my question is "yes". And, truly speaking, I don't like this behaviour.

**Describe the solution you'd like**

I'll try to explain what I think is right:
- The `langchain4j` under the hood maintans a message window in order to fit into context limit.
- But the user of my application can see all the converstation they had so far with the AI.

In the current implementation, if my application UI relies on `ChatMemoryStore`, then the past messages will be deleted and the user cannot see them.

How I see this from a programmer perspective:
- Let `ChatMemoryStore` store the whole conversations.
- Let `MessageWindowChatMemory` implementation send only last `N` messages. So, for example, if `N = 10` and the whole message count is `S = 20`, then the `MessageWindowChatMemory` will only send messages on indices `[10, 11, 12, ... 19]`. So it won't delete messages, but only add them.

**Describe alternatives you've considered**

An alternative for this issue would be:
- Let `langchain4j` classes do their own thing.
- Let the UI and the logic of an application maintain their own list of messages that is not connected to `langchain4j` classes/objects in any way.

This would actually solve the issue. But there are many problems with this strategy:
- `langchain4j` provides many interfaces for extending the code. With this strategy there is no sense for extending `langchain4j` code.
- There would be two copies of messages: one in the internal UI list with all the messages, and the other in `InMemoryChatStore` with only last `N` messages.

**Additional context**

I've made a simple app `ChatWithPDFs` for learning how to use `langchain4j`. In this app you can talk to one PDF or a folder with several PDFs. It's a very simple and dumb application. There are three kind of prompts: `User` (for user question), `AI` (for AI answer), `Info` (this shows the count of messages in `ChatMemory` and in `ChatMemoryStore`).

Here is a screenshot that illustrates my issue (I've set up `MessageWindowChatMemory.maxMessages` to 4):
![изображение](https://github.com/langchain4j/langchain4j/assets/13097618/3e9cf5e2-44dd-476c-b81f-a77fee9ff26f)

I am okay that an LLM model will forget what we talked about in previous messages. Actually, users of OpenAI ChatGPT have talked a lot about how AI forgets information in a long converstation. Even I had this experience, when I asked ChatGPT to transform a complex table to JSON format according to special rules. I sent data in batches in messages, and after some time ChatGPT would forget the rules I told it.

`MessageMemoryChatWindow` also maintains a `SystemMessage`. If it exists, then it should always remain and be only one and unique. What I think about it:
- This would complicate my initial algorithm suggestion. But, nevertheless, if we generate a list of message indices, then we can find the index of a `SystemMessage` and just replace the first index in indices list with the index of found `SystemMessage`.
- This thing is annoying. Class should do only one thing. But it turns out that `ChatMemory` child classes have to maintain two things: 1) limiting the request for AI; 2) maintaining a `SystemMessage`. But that's another topic and I understand that this issue may be hard to solve from architectural point of view.

**Post Scriptum**
I am only a beginner contributor, and my English is not professional.

Maybe I miss something? Maybe I use the classes the wrong way?

If you have any questions, don't hesitate to ask, I'll explain everything on my mind. I'm ready to contribute and help `langchain4j`.

**Comment by langchain4j** [comment]
Hi @InAnYan, thanks for bringing it up, I think we have 2 concepts here:
- Chat history: it stores **all messages, unmodified, as user sees them**.
- Chat memory: it stores **some information that LLM should see in order to provide meaningful experience**. It also can maintain additional system message (that user must not see) and can do different things like summarizing not fitting messages, dropping some messages in the middle, injecting extra information (e.g. RAG) or instructions (e.g. structured outputs) in the messages, etc. There are lots of possible strategies, LC4j provides only simple ones at the moment.

As you can see, these 2 concepts are quite different and serve different purposes. I understand that this might be confusing, so I will do a better job documenting this distinction.

I am not sure it is a good idea to mix those 2 things in one place. It is already pretty complicated, adding an option to store all messages **intact** will make it even worse.

I think it is completely fine to have a bit of data duplication, it is not always a bad idea, especially considering that this data can be quite different due to extra injected info, instructions, system message, summarised messages, etc.

WDYT?

**Comment by InAnYan** [comment]
Yep, I get it, you've explained it well.

What I propose:
- Let `ChatMemoryStore` act as chat history as you said.
- Let `ChatMemory` be the chat memory as you said.

But I see, I misunderstood the concepts.

It's just, if I implement a `ChatMemoryStore` with a connection to database, I won't expect it will delete past messages.

If you propose to maintain the chat history externally from `langchain4j` (which is okay), then why create two interfaces `ChatMemoryStore` and `ChatMemory`? Why not `ChatMemory` maintain its own `List<ChatMessages>` and then in my application code I will write something like this:
```java
public void askAI(String question) {
	this.myChatHistory.addMessage(new UserMessage(question));
	this.ai.execute(question);
}
```

And I think it should be mentioned in documentation that `ChatMemory` instances will delete the messages, so the users won't try to extend `ChatMemoryStore` to be a chat history as I thought

**Comment by langchain4j** [comment]
> It's just, if I implement a ChatMemoryStore with a connection to database, I won't expect it will delete past messages.

> And I think it should be mentioned in documentation that ChatMemory instances will delete the messages, so the users won't try to extend ChatMemoryStore to be a chat history as I thought

I have just added this section: https://docs.langchain4j.dev/tutorials/chat-memory#memory-vs-history and a note in this section https://docs.langchain4j.dev/tutorials/chat-memory#persistence 
Do you think this will suffice?

> If you propose to maintain the chat history externally from langchain4j (which is okay), then why create two interfaces ChatMemoryStore and ChatMemory?

`ChatMemory` is responsible for the strategy of maintaining the memory (e.g. eviction, summarization, etc.), while `ChatMemoryStore` is responsible for storing it (e.g. in memory or in some persistent store).

**Comment by InAnYan** [comment]
Super!

Thanks for the cooperation!
