### ISSUE TITLE
Why can't I find the component AISerivices or ConversationalRetrievalChain?[BUG] 

### ISSUE THREAD

**Issue by jscksy** [langchain4j/langchain4j#1112]
I can't import the related package

**Comment by langchain4j** [comment]
Please import "langchain4j" dependency: https://docs.langchain4j.dev/intro#library-structure

**Comment by jscksy** [comment]
> Please import "langchain4j" dependency: https://docs.langchain4j.dev/intro#library-structure

thanks

**Comment by gonggbb** [comment]
<dependency>
    <groupId>dev.langchain4j</groupId>
    <artifactId>langchain4j-spring-boot-starter</artifactId>
</dependency>
