### ISSUE TITLE
[FEATURE] LOCAL EMBEDDING MODEL RUN 

### ISSUE THREAD

**Issue by oguzhanglb** [langchain4j/langchain4j#1117]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Hello, first of all, thank you for creating such a library.

I couldn't see an example here where we could take any embedding model and run it locally.

You have a few examples of onnx, but when I implemented it, I could not achieve it very well.
Example;
https://github.com/langchain4j/langchain4j-examples/blob/main/other-examples/src/main/java/embedding/model/InProcessEmbeddingModelExamples.java

If it can run locally, do you have a detailed example where we can run it locally?

Thank you in advance for your help.

**Describe alternatives you've considered**

**Additional context**

**Comment by langchain4j** [comment]
Hi, what was the problem with onnx?

You can run embedding models locally with Ollama, here is an example: https://github.com/langchain4j/langchain4j/blob/a5b168f061fd24e86dde87ae53857bf991e9fbe0/langchain4j-ollama/src/test/java/dev/langchain4j/model/ollama/OllamaEmbeddingModelIT.java#L19

I am closing this issue, next time please open a discussion [here](https://github.com/langchain4j/langchain4j/discussions) or on [Discord](https://discord.gg/JzTFvyjG6R).
But feel free to respond here.
