### ISSUE TITLE
[BUG] Query metadata are lost when using the query compression technique

### ISSUE THREAD

**Issue by ruizrube** [langchain4j/langchain4j#1124]
Hi

I have created an assistant using a EmbeddingStoreContentRetriever based on a dynamic metadata filter, like this:

Function<Query, Filter> filterByUserId =
                (query) -> metadataKey("userId").isEqualTo(query.metadata().chatMemoryId().toString());

(https://github.com/langchain4j/langchain4j-examples/blob/main/rag-examples/src/main/java/_3_advanced/_05_Advanced_RAG_with_Metadata_Filtering_Examples.java)

The filter works fine, but when I added a query compression step, and I chat to the assistant for the second time, it fails because query.metadata() is always null. It seems that during query compression, the metadata of the query are missing.  

- LangChain4j version: 0.30
- LLM(s) used:  LLama3
- Java version:  21
- Spring Boot version: 3.2.4 

thanks

**Comment by langchain4j** [comment]
Hi @ruizrube thanks a lot for reporting!
