### ISSUE TITLE
[BUG] AI Service fails when user message contains template variables

### ISSUE THREAD

**Issue by langchain4j** [langchain4j/langchain4j#1125]
**Describe the bug**
AI Service fails when user message contains template variables.

**Log and Stack trace**
```
dev.langchain4j.exception.IllegalConfigurationException: Error: cannot find the value of the prompt template variable "{{it}}".
    at dev.langchain4j.exception.IllegalConfigurationException.illegalConfiguration(IllegalConfigurationException.java:12)
    at dev.langchain4j.service.DefaultAiServices.getValueOfVariableIt(DefaultAiServices.java:247)
    at dev.langchain4j.service.DefaultAiServices.findTemplateVariables(DefaultAiServices.java:223)
    at dev.langchain4j.service.DefaultAiServices.prepareUserMessage(DefaultAiServices.java:258)
```

**To Reproduce**
```java
@AiService
public interface AiAssistant {

    TokenStream chat(@MemoryId String chatId, @UserMessage String userMessage);
}

assistant.chat("12345", "Text containing {{it}}");
```

**Please complete the following information:**
- LangChain4j version: latest

**Comment by KaisNeffati** [comment]
Hey ! Could you please clarify the expected behavior for this issue ?

**Comment by langchain4j** [comment]
Hi @KaisNeffati, it should not fail. In this case `{{it}}` (or any other variable) should not be treated as variable, but as a text

**Comment by anunnakian** [comment]
Hello @KaisNeffati, are you going to work on this issue ?

**Comment by KaisNeffati** [comment]
@anunnakian I was planning to do that, but I didn't have the time. Feel free to go for it if you'd like to

**Comment by anunnakian** [comment]
Ok thanks! @langchain4j could you assign me to this issue, I'll work on it today

**Comment by langchain4j** [comment]
Not a bug, current behavior is correct

**Comment by lylala8** [comment]
This is a very big issue, if users manually enter template symbols, all LangChin4j constructed projects will report errors
