### ISSUE TITLE
[FEATURE] Logging requests to the LLM using OllamaChatModel 

### ISSUE THREAD

**Issue by ruizrube** [langchain4j/langchain4j#1129]
Hi all.

I think that there is no way to capture the requests and response logs using Ollama.

https://docs.langchain4j.dev/tutorials/logging

thanks

**Comment by langchain4j** [comment]
Hey, there is a PR already: https://github.com/langchain4j/langchain4j/pull/662

**Comment by langchain4j** [comment]
Closing this issue as it was implemented in #662
