### ISSUE TITLE
Local LLM supports LANGCHIAN function calls

### ISSUE THREAD

**Issue by leleZeng** [langchain4j/langchain4j#1134]
I deployed LlaMa3 using DJL locally. How can Langchian4j support Function calls.

**Comment by langchain4j** [comment]
Hi, you can use [LocalAI](https://localai.io/features/openai-functions/), here is an example how you cna create the model: https://github.com/langchain4j/langchain4j-examples/pull/82/files
Here is an example how to use tools: https://docs.langchain4j.dev/tutorials/ai-services/#tools-function-calling
