### ISSUE TITLE
Does langchain4j support Kotlin programming language for development on Android platform?

### ISSUE THREAD

**Issue by zxxsong** [langchain4j/langchain4j#1135]
Hi! I'm currently developing an Android application with an AI agent, so I want to know: Does langchain4j support the Kotlin programming language for development on Android platform? And can I create AI agent using langchain4j similar to langchain (https://python.langchain.com/v0.1/docs/modules/agents/quick_start/) ? Thank you so much.

**Comment by zxxsong** [comment]
@dosubot Thanks, I have some knowledge about langchain4j. It seems like that langchain4j doesn't support ReAct agent, so I want to know: If ReAct is not implemented, how does the language model autonomously choose which tools can be called？

**Comment by langchain4j** [comment]
Hi, not sure about kotlin, never tried it. But I guess it should work, worth trying.

ReAct is not implemented, but many model providers support tools/functions out of the box, see [here](https://docs.langchain4j.dev/integrations/language-models/) column "tools".

I am closing this issue for now, feel free to continue here or open a discussions or use discord for questions/discussions.
