### ISSUE TITLE
[FEATURE]  QwenEmbeddingModel limit texts size, it need batch embed method

### ISSUE THREAD

**Issue by noday** [langchain4j/langchain4j#1140]
**Is your feature request related to a problem? Please describe.**
{"statusCode":400,"message":"batch size is invalid, it should not be larger than 25.: payload.input.contents","code":"InvalidParameter","isJson":true,"requestId":"62b84a0b-2929-9977-ae0d-2ae028d7bb23"}

**Describe the solution you'd like**
support like ingestor.ingest(document, batchSize);

**Describe alternatives you've considered**

**Additional context**

**Comment by langchain4j** [comment]
cc @jiangsier-xyz
