### ISSUE TITLE
[BUG] DocumentSplitter use QwenTokenizer size of joinSeparator error

### ISSUE THREAD

**Issue by noday** [langchain4j/langchain4j#1147]
**Describe the bug**

`DocumentSplitters.recursive(300, 0, new QwenTokenizer("sk*****", Tokenization.Models.TEXT_EMBEDDING_V2))`
use DocumentSplitter with QwenTokenizer, in SegmentBuilder the `sizeOf(joinSeparator)`  will throw exception
`{"statusCode":400,"message":"Missing prompt and messages and texts in input","code":"InvalidParameter","isJson":true,"requestId":"28c9f576-e351-92a8-b2c3-273c552525b0"}`

see the image \n\n can not Tokenization
**Log and Stack trace**

**To Reproduce**

**Expected behavior**

**Please complete the following information:**
- LangChain4j version: 0.30.0
- LLM(s) used: dashscope qwen
- Java version: 17
- Spring Boot version (if applicable): 2.7

**Additional context**

![image](https://github.com/langchain4j/langchain4j/assets/892768/c1c72b58-170e-40ff-9c7f-76ba8ffc3f76)

**Comment by noday** [comment]
QwenTokenizer
```java
public int estimateTokenCountInText(String text) {
  if (text.replaceAll("\n", "")=="") {
    return 0;
  }
  ...
}
```

**Comment by jiangsier-xyz** [comment]
It seems that Qwen's online tokenizer service doesn't support strings made up of whitespace characters. You can test it on Dashscope's [online calcultor page](https://dashscope.console.aliyun.com/tokenizer). When input consists only of whitespace characters, including spaces and newlines, the result also produces an error.

However, the OpenAiTokenizer can support this scenario.

I have a workaround: when the input is detected to be a string composed of whitespace characters, add a character to the end of the string before calling the API. Then, subtract 1 from the result returned by the API to get the final result.
