### ISSUE TITLE
have a few consulting questions？

### ISSUE THREAD

**Issue by stoneLee81** [langchain4j/langchain4j#116]
Questions:
1 How to enable the debug parameter mode in langchain4j, just like verbose = True in langchain-py, you can know the specific execution status.
2 Is there a function that can call back the tokens consumed by the model calculation, so that it is easy to know the cost of each user execution.
> Is it the function estimateTokenCount, which can be used to calculate the number of tokens consumed by the model?

3 If I want to define other custom tools, refer to ServiceWithToolsExample, the customerService tool is defined, but it is not executed.

**Comment by langchain4j** [comment]
Hi @stoneLee81 
1. You can set `.logRequests(true)` and `.logResponses(true)` in the `*Model` builder
2. Unfortunately there is no such thing (yet) to know **total** tokens for the request and response, but each `*Model` class has multiple `estimateTokenCount(...)` methods which provide a pretty accurate estimate on tokens, so you can estimate it manually at the moment. I will work on adding a better way soon, want to hear your ideas. Should it be a callback which is called after each response from LLM?
3. Can you elaborate? Which model are you using? What is the tool, what's the prompt?

**Comment by stoneLee81** [comment]
point 2， I think callbacks may be more appropriate. After using the model, get the number of input & output tokens used。

**Comment by langchain4j** [comment]
for 3: try defining a good and clear description for the tool:
```
@Tool("this function is needed to...")
String service() {
    return "转人工中";
}
```

**Comment by stoneLee81** [comment]
> for 3: try defining a good and clear description for the tool:
> 
> ```
> @Tool("this function is needed to...")
> String service() {
>     return "转人工中";
> }
> ```

this works fine, Whether supports return directly from the tool rather than continuing the agent loop，Because, although I returned the logic, I still executed the model and returned the result I didn't expect， What I want to return is ‘转人工中‘，but model return is '对不起，作为AI助手，我无法提供人工服务。请问您有什么需要我帮助的吗？也许我可以为您提供其他方面的帮助。'

**Comment by langchain4j** [comment]
@stoneLee81 I am not sure I understand you. Please explain in more details and with examples what are you trying to achieve.

**Comment by stoneLee81** [comment]
> static class CustomerService {
        @Tool("客户有转客服人工的指令时，比如 转人工，人工")
        String service(String str) {
            return "转人工中";
        }
    }

> Assistant assistant = AiServices.builder(Assistant.class)
>                 .chatLanguageModel(model)
>                 .tools(new CustomerService())
>                 .chatMemory(MessageWindowChatMemory.withMaxMessages(10))
>                 .build();
> 
>         String answer = assistant.chat("人工");
>         System.out.println(answer);

What I want to return is ‘转人工中‘，because the tool service function returns, but model return is '对不起，作为AI助手，我无法提供人工服务。请问您有什么需要我帮助的吗？也许我可以为您提供其他方面的帮助。'
I want to call the tool to return my string instead of the model itself。

**Comment by langchain4j** [comment]
@stoneLee81 I am not entirely sure what is your high-level goal. Do you want to build a customer support agent? I don't understand why do you need to call a tool that returns a static string. Please explain.

In any case, it seems that the models does not recognize your intent. What you can try is to add a system prompt that will explain the model how it sohuld behave, for example:

```
interface Assistant {

    @SystemMessage("You are a customer support representative. When user asks you about XXX, do YYY. ...")
    String chat(String userMessage);
}
```

Which model are you using? gpt-3.5-turbo? Try gpt-4, it is much more steerable.

**Comment by stoneLee81** [comment]
I used gpt-3.5-turbo model. yes, I want to build a custom agent and let model to determine to call it, Sometimes, it is necessary to call a custom tool to return the result to the client, for instance, order service custom tool, user wants to search order info by order no, the model call the custom order service tool, and return order info as string to user. this string info is returned by custom tool, not model itself, In langchain-py, i remember,  it had a **return_direct** parameter in @tool to return directly from the tool.
And I used debug to ensure that the model recognize the custom tool, but return is not the tool return string, it's model itself message.

**Comment by langchain4j** [comment]
@stoneLee81 I see your point. We will add a "return_direct" feature soon.

**Comment by langchain4j** [comment]
@stoneLee81 BTW currently you can use lower-level approach with *ChatLanguageModel.sendMessages(List<ChatMessage> messages, List<ToolSpecification> toolSpecifications) and in case LLM will decide to call the tool/function, you will get AiMessage with ToolExecutionRequest inside.

**Comment by stoneLee81** [comment]
thanks, i will try
