### ISSUE TITLE
[FEATURE] Ability to provide a DataSource to PgVectorEmbeddingStore

### ISSUE THREAD

**Issue by stephan-vollmer** [langchain4j/langchain4j#1160]
**Is your feature request related to a problem? Please describe.**
It should be possible to pass an existing `DataSource` instead of providing all connection parameters separately.
Benefits:
* Easier integration in environments that manage databases as `DataSource`, e.g. in application servers or environments like Quarkus.
* Benefit from other features like connection pooling that the runtime environments provide out-of-the-box. At the moment, a `PGSimpleDataSource` is used. This class does not use connection pooling and creates a new connection for each operation.
* More connection options can be used and `PgVectorEmbeddingStore` does not need to implement additional parameters.

**Describe the solution you'd like**
The builder class `PgVectorEmbeddingStoreBuilder` should have a `dataSource(DataSource)` method.
If a DataSource is provided in the builder, it should be used instead of creating an internal DataSource with the individual connection parameters.

In code, it could look as follows:
```
// with individual connection parameters
EmbeddingStore<TextSegment> embeddingStore = 
               PgVectorEmbeddingStore.builder()
                                     .host(host)
                                     .port(port)
                                     .database("embeddings")
                                     .user(user)
                                     .password(password)
                                     .table(table)
                                     .dimension(dimension)
                                     .build();

// with DataSource
EmbeddingStore<TextSegment> embeddingStore = 
               PgVectorEmbeddingStore.builder()
                                     .dataSource(dataSource)
                                     .table(table)
                                     .dimension(dimension)
                                     .build();
```

**Describe alternatives you've considered**

[#893 - Ability to provide entire connection string for pgvector](https://github.com/langchain4j/langchain4j/issues/893)

This issue would make it possible to provide other connection options. But it would not provide the other advantages outlined above.

**Additional context**
n/a

**Comment by langchain4j** [comment]
Hi @stephan-vollmer there is such constructor already, please check the latest (0.31.0) version:
```java
PgVectorEmbeddingStore.datasourceBuilder()
                .datasource(dataSource)
                ...
                .build();
```
