### ISSUE TITLE
[FEATURE] Metadata UUID Support

### ISSUE THREAD

**Issue by humcqc** [langchain4j/langchain4j#1164]
**Is your feature request related to a problem? Please describe.**
Metadata method to add Object Value has been deprecated:

```
    @Deprecated
    public Metadata add(String key, Object value) {
        return put(key, value.toString());
    }
```
And I would like to store UUID

**Describe the solution you'd like**
Add UUID as supported metadata

**Describe alternatives you've considered**
Using String for the moment

**Comment by humcqc** [comment]
Issue with InMemoryEmbeddingStore that use GsonInMemoryEmbeddingStoreJsonCodec so serialize and deserialize the store.

But as Metadata is a Map<String, Object>,  deserialization retrieve UUID as String.

**Comment by langchain4j** [comment]
@humcqc could you please clarify?

**Comment by humcqc** [comment]
I've implemented it and added some tests, but i face a blocking issue in InMemoryEmbeddingStoreSerializedTest

when the store is [serialized and deserialized ](https://github.com/langchain4j/langchain4j/blob/main/langchain4j/src/test/java/dev/langchain4j/store/embedding/inmemory/InMemoryEmbeddingStoreSerializedTest.java#L21) it transform UUIDs in Metadata values to Strings and then the [filter test ](https://github.com/langchain4j/langchain4j/blob/main/langchain4j-core/src/main/java/dev/langchain4j/store/embedding/filter/comparison/IsEqualTo.java#L45) throws an [exception](https://github.com/langchain4j/langchain4j/blob/main/langchain4j-core/src/main/java/dev/langchain4j/store/embedding/filter/comparison/TypeChecker.java#L13)

Not sure how we can fix.

**Comment by langchain4j** [comment]
Could you open a draft PR with your changes? I guess we can handle this case in `ensureTypesAreCompatible`, similar to how we do with numbers:
```java
if (actualValue instanceof Number && comparisonValue instanceof Number) {
            return;
        }
```

Do you know which vector stores support UUID as a data type?

**Comment by humcqc** [comment]
> Could you open a draft PR with your changes? I guess we can handle this case in `ensureTypesAreCompatible`, similar to how we do with numbers:
> 
> ```java
> if (actualValue instanceof Number && comparisonValue instanceof Number) {
>             return;
>         }
> ```

Yes i've tried this, but it fails after. 

> Do you know which vector stores support UUID as a data type?

I've fixed all store that have a test extending EmbeddingStoreWithFilteringIT, just the serialized InMemoryEmbeddingStore still not work.

Draft PR : https://github.com/langchain4j/langchain4j/pull/1211

**Comment by humcqc** [comment]
Finally got it working adding a hack, to check if it's ok for you : https://github.com/langchain4j/langchain4j/pull/1211/files#r1622090514

**Comment by langchain4j** [comment]
Implemented in https://github.com/langchain4j/langchain4j/pull/1211
