### ISSUE TITLE
[FEATURE] Implement embedding removal methods for Milvus embedding store

### ISSUE THREAD

**Issue by langchain4j** [langchain4j/langchain4j#1168]
`MilvusEmbeddingStore` should have `remove(String id)`, `removeAll(Collection<String> ids)`, `removeAll(Filter filter)` and `removeAll()` methods implemented, similarly to `PgVectorEmbeddingStore`.

**Comment by xermaor** [comment]
@langchain4j Hello, can you assign this to me?

**Comment by langchain4j** [comment]
Implemented in https://github.com/langchain4j/langchain4j/pull/1172
