### ISSUE TITLE
[FEATURE] Implement embedding removal methods for Elasticsearch embedding store

### ISSUE THREAD

**Issue by langchain4j** [langchain4j/langchain4j#1170]
`ElasticsearchEmbeddingStore` should have `remove(String id)`, `removeAll(Collection<String> ids)`, `removeAll(Filter filter)` and `removeAll()` methods implemented, similarly to `PgVectorEmbeddingStore`.

**Comment by zambrinf** [comment]
May I work on this issue?

**Comment by langchain4j** [comment]
@zambrinf of course, thank you!
