### ISSUE TITLE
[FEATURE] Gemini: JSON output mode

### ISSUE THREAD

**Issue by langchain4j** [langchain4j/langchain4j#1208]
Gemini now supports JSON output, more details: https://ai.google.dev/gemini-api/docs/api-overview#json

**Comment by langchain4j** [comment]
cc @glaforge will this be available in Gemini SDK?

**Comment by glaforge** [comment]
Yes, it should be available soon.
The function calling mode is also coming soon.

**Comment by langchain4j** [comment]
Implemented in https://github.com/langchain4j/langchain4j/pull/1278
