### ISSUE TITLE
[FEATURE] Support Tongyi Qianwen

### ISSUE THREAD

**Issue by xigexb** [langchain4j/langchain4j#1210]
能否支持通义千问

**Comment by sunxiaojian** [comment]
It should already be supported, the 'langchain4j-dashscope' module

**Comment by xigexb** [comment]
三克油


> 在 2024年6月1日，18:14，Xiaojian Sun ***@***.***> 写道：
> 
> module

**Comment by xigexb** [comment]
Tools are currently not supported by this model

**Comment by Kugaaa** [comment]
Implement the QianWen function call.
I can work on it.

**Comment by langchain4j** [comment]
Implemented in https://github.com/langchain4j/langchain4j/pull/1254

**Comment by leungchao** [comment]
Does springboot not work directly with the QianWen model?

langchain4j.open-ai.chat-model.model-name=???

**Comment by langchain4j** [comment]
Next release (0.35.0, this Wednesday) should include https://github.com/langchain4j/langchain4j-spring/pull/38, so it iwll be supported
