### ISSUE TITLE
[FEATURE] Implement searching on docs website

### ISSUE THREAD

**Issue by InAnYan** [langchain4j/langchain4j#1219]
**Is your feature request related to a problem? Please describe.**
[https://docs.langchain4j.dev/](https://docs.langchain4j.dev/) contains lot's of useful information. I often combine information from the code documentation and tutorials. But in order to do this I need to search in the comboboxes (or accordions, or some UI elements) on the website, while I think a search feature would be easier.

**Describe the solution you'd like**
Implement search feature in [https://docs.langchain4j.dev/](https://docs.langchain4j.dev/).

**Describe alternatives you've considered**
*Mind reading* - currently impossible.

**Additional context**

**Comment by agoncal** [comment]
Another easy option is to have the ability to also get a one-html-page format (and why not having also a PDF format so it can be easily downloaded). Image that you have the entire documentation (from https://docs.langchain4j.dev/intro) into a one-single page, then you can easily search. And it's perfect when being offline.

**Comment by langchain4j** [comment]
@agoncal do you know how to do that?

**Comment by agoncal** [comment]
So that means that we can close this issue, right ?

https://github.com/langchain4j/langchain4j/pull/1221
