### ISSUE TITLE
[FEATURE] logging implementation change to slf4j + 1 implementation

### ISSUE THREAD

**Issue by du00cs** [langchain4j/langchain4j#122]
**Is your feature request related to a problem? Please describe.**
I find that langchain4j use tinylog instead of more popular combination solution of slf4j and one implementation. That may be ok, but also makes it difficult to integrate with existed logging system in java projects.

**Describe the solution you'd like**
Change tinylog to slf4j+logback or something else.

**Comment by langchain4j** [comment]
Hi @du00cs we use tinylog only for tests and examples, there is no compile- or runtime-dependency on tinylog, so you are free to plug in logback or any other implementation of your choice.
