### ISSUE TITLE
[FEATURE] it would be good if there is a pdf uploading and summarizing model using vertex gemini ai

### ISSUE THREAD

**Issue by SRUJAL13** [langchain4j/langchain4j#1223]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by langchain4j** [comment]
Hi @SRUJAL13. the description is not clear, please add more details

**Comment by SRUJAL13** [comment]
Hi @langchain4j 
Uploading  a pdf and getting the pdfs text summarization using vertex gemini ai would be good

**Comment by langchain4j** [comment]
@SRUJAL13 this is already supported.
Loading PDFs: https://github.com/langchain4j/langchain4j-examples/blob/cd3594fd21c78042e4a16083e95dc98a594c09b0/other-examples/src/main/java/DocumentLoaderExamples.java#L31
Using Gemini: https://github.com/langchain4j/langchain4j-examples/blob/cd3594fd21c78042e4a16083e95dc98a594c09b0/vertex-ai-gemini-examples/src/main/java/VertexAiGeminiChatModelExamples.java#L28

**Comment by SRUJAL13** [comment]
Can we use these all in android studio to create an java application ??

**Comment by langchain4j** [comment]
@SRUJAL13 should work, but there might be some issue with android

**Comment by SRUJAL13** [comment]
So what is the best way to implement text summarization by uploading a pdf using gemini key
