### ISSUE TITLE
[BUG] Elastic Search Index Creation failing when both Langchain and Elastic client is used.

### ISSUE THREAD

**Issue by pranith12345** [langchain4j/langchain4j#1225]
Elastic Search Index Creation with dimensions is  failing when both Langchain(0.31.0) and Elastic client(8.13.4) is used. Currently we are using both  as delete documents functionality is missing in Langchain . 

If we downgrade the elasticclient to version 8.12.0 , Index is created successfully . 

Below is the error 

NoSuchMethod Error 
`co.elastic.clients.elasticsearch._types.mapping.DenseVectorProperty$Builder co.elastic.clients.elasticsearch._types.mapping.DenseVectorProperty$Builder.dims(int)`

**To Reproduce**
```
ElasticsearchEmbeddingStore.builder()
                        .serverUrl(elasticSearchUrl)
                        .indexName(indexName)
                        .userName(elasticSearchUsername)
                        .password(elasticSearchPassword)
                        .dimension(384)
                        .build();
```

**Expected behavior**
Index should be created .

**Comment by langchain4j** [comment]
@pranith12345 LangChain4j 0.31.0 uses elastic client version 8.9.0, so please use this version for the moment.

BTW, removal is being implemented in [this PR](https://github.com/langchain4j/langchain4j/pull/1198), could you please check/review if this will be sufficient for you?

**Comment by pranith12345** [comment]
Yes . This helps . But additionally Upsert of the documents logic is also required .

**Comment by langchain4j** [comment]
@pranith12345 what is your use case for upserts?

**Comment by pranith12345** [comment]
Currently i think the updating of existing documents in elastic store is missing in LangChain. So if the same document is inserted again using **AddAll** , it is creating a duplicate in the Store .

**Comment by langchain4j** [comment]
Do you provide IDs when inserting second time?
Or do you expect `EmbeddingStore` to find existing segments by matching text?
