### ISSUE TITLE
[FEATURE] Support Markdown document splitter

### ISSUE THREAD

**Issue by xigexb** [langchain4j/langchain4j#1227]
支持Markdown格式文档

**Comment by thesteve0** [comment]
@langchain4j can you please assign this to me for now

**Comment by langchain4j** [comment]
Duplicate of https://github.com/langchain4j/langchain4j/issues/574

**Comment by thesteve0** [comment]
Hey - I haven't forgot about this but I went on Holiday and now my paid consulting work is piled up. Sorry for the delay - please feel free to reassign if needed
