### ISSUE TITLE
[FEATURE] Missing interface for Document Loaders?

### ISSUE THREAD

**Issue by anders-swanson** [langchain4j/langchain4j#1230]
I'm in the process of implementing langchain4j providers, and noticed the [Document Loaders](https://github.com/langchain4j/langchain4j/blob/main/document-loaders/langchain4j-document-loader-amazon-s3/src/main/java/dev/langchain4j/data/document/loader/amazon/s3/AmazonS3DocumentLoader.java) don't implement any specific interface.

Should there be an interface for this? It might be useful in the future, or currently to standardize the API.

**Comment by langchain4j** [comment]
Hi @anders-swanson what is the reason for the same interface? Please check existing document loaders, they all have different APIs.

**Comment by anders-swanson** [comment]
Taking a look at some of the non-bucket loaders, this makes a lot more sense. I was only thinking from the bucket perspective.
