### ISSUE TITLE
[FEATURE] How to summarize ultra long texts?

### ISSUE THREAD

**Issue by 47018222w8** [langchain4j/langchain4j#1235]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by langchain4j** [comment]
You can either use a long-context LLMs (e.g. Gemini) or implement one of map-reduce/refine strategies: https://python.langchain.com/v0.2/docs/tutorials/summarization/
