### ISSUE TITLE
[FEATURE] Support douyin's Doubao Model

### ISSUE THREAD

**Issue by yao-wenbin** [langchain4j/langchain4j#1237]
**Is your feature request related to a problem? Please describe.**

Can it support the Doubao large model of Douyin?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by noday** [comment]
Is it have a plan? how to named module, langchain4j-ark?

**Comment by noday** [comment]
@langchain4j I want to implement this feature, Do you have any suggestions?
https://www.volcengine.com/
https://console.volcengine.com/ark

**Comment by noday** [comment]
I will use SDK V3, https://www.volcengine.com/docs/82379/1263482

**Comment by langchain4j** [comment]
> how to named module, langchain4j-ark?

What is ark? Is it a name of the LLM? A name of the company? A name of the company product? Something else?

**Comment by noday** [comment]
> > how to named module, langchain4j-ark?
> 
> What is ark? Is it a name of the LLM? A name of the company? A name of the company product? Something else?

ark(火山方舟大模型服务平台) is llm service platform on volcengine, like dashscope of aliyun.

**Comment by langchain4j** [comment]
langchain4j-volcengine-ark or langchain4j-ark are both fine I guess
