### ISSUE TITLE
[FEATURE REQUEST/Question] Whats best practice when doing findRelevant?

### ISSUE THREAD

**Issue by AbdullahGheith** [langchain4j/langchain4j#125]
Is there a best practice when searching for relevant embeddings in the vector db?

I see in the examples, its just searching for the question. But imagine a case like this:

Q: How tall is it?
A: What do you mean by 'it'?
Q: The eiffel tower
A: I am not sure how tall it is given the current context.

This happens because in the second question, i am simply searching for "the eiffel tower" in the vector database and not finding relevant context.
Would be cool if we could have a method, that would actually descibe what the question is, that we could search for in the vector db.

**Comment by langchain4j** [comment]
@AbdullahGheith how do you see this method working? One of the simplest options could be to take into account X (configurable) previous messages (from user or AI or both) and then searching DB by the embedding of all messages combined (or by each message and then combining results). Might help in the situation like this, but might also degrade the performance for other use cases (regular full questions). Another option would be to have an agent that would summarize the question on each interaction (so it would be able to provide something like "How tall is the Eiffel tower?" after this interaction:
> Q: How tall is it?
> A: What do you mean by 'it'?
> Q: The eiffel tower

Please share your thoughts

**Comment by AbdullahGheith** [comment]
Afaik, every time a prompt is sent, all history is sent along with it (if memory is enabled).

Of course, memory has to be enabled for this to work. Agents are a good idea.

If we can (somehow) figure out when the model got confused, and send that part of the history to an agent that will summarize a question.

For instance:

Q: hello!
A: hello!
Q: how are you?
A: I am fine thanks!
Q: how tall is it?
A: I am not sure what you mean by 'it', can you be more specific? <- confusion starts
Q: the Eiffel tower

Then the following will be sent to the agent:
Q: how tall is it
Q: the Eiffel tower
And the agent will return: how tall is the Eiffel tower

And this will be what is searched in the vector db

**Comment by langchain4j** [comment]
@AbdullahGheith good idea. But to detect the confusion, you will have to take every response from LLM and send it to itself (or other, cheaper/free LLM) in a separate thread of conversation for classification (confusion/not). This will cost in money and in latency. Another random idea: give the vector DB to the LLM as a tool and instruct it to use it when LLM does not know/is unsure.

**Comment by langchain4j** [comment]
I would suggest you to search langchain/openai/etc forums/reddits/discords and see what people say. I am sure htis problem has been solved in many ways already and most probably there is a good solution already.

**Comment by AbdullahGheith** [comment]
I will try and find a solution and will report back how they do it

**Comment by langchain4j** [comment]
Hi @AbdullahGheith, this is now supported: https://github.com/langchain4j/langchain4j/pull/538
Please check `DefaultRetrievalAugmentor` and `CompressingQueryTransformer` and in version 0.26.1.
I am closing this issue, but feel free to reopen if needed.
Cheers!

**Comment by AbdullahGheith** [comment]
Thanks for notifying me. This looks amazing. Good job!

ons. 31. jan. 2024 08.06 skrev LangChain4j ***@***.***>:
