### ISSUE TITLE
[FEATURE]  OpenAI LLM hosted on Azure miss logStreamingResponses parameter

### ISSUE THREAD

**Issue by wzhj2326** [langchain4j/langchain4j#126]
OpenAI LLM hosted on Azure miss logStreamingResponses parameter，the same goes for others

**Comment by langchain4j** [comment]
@wzhj2326 thanks a lot for reporting, fix is on the way

**Comment by langchain4j** [comment]
@wzhj2326 was fixed in 0.22.0, please check
