### ISSUE TITLE
[FEATURE] Support Metadata filtering with Azure AI Search

### ISSUE THREAD

**Issue by JSON-OBJECT** [langchain4j/langchain4j#1263]
**Is your feature request related to a problem? Please describe.**
With the ability to filter metadata in Azure AI Search, applications can narrow down searches to specific files, teams, or users.

**Additional context**
https://docs.llamaindex.ai/en/stable/examples/vector_stores/AzureAISearchIndexDemo/

**Comment by langchain4j** [comment]
cc @jdubois @agoncal

**Comment by jdubois** [comment]
Can you assign this to me?
Maybe @yoshioterada will also be interested - let's talk about this Yoshio-san!

**Comment by jdubois** [comment]
@langchain4j as @fb33 is doing all the work, can you assign this ticket to him?

**Comment by langchain4j** [comment]
Hmm I can't assign @fb33 for some reason:
![image](https://github.com/langchain4j/langchain4j/assets/132277850/dc5c6f42-9595-4925-81f8-41c6c116f040)

**Comment by fb33** [comment]
Weird....

**Comment by agoncal** [comment]
@fb33 @jdubois Any progress on this one ?

**Comment by fb33** [comment]
For my point view, it's done. I answered the remarks from @langchain4j  : https://github.com/langchain4j/langchain4j/pull/1291#pullrequestreview-2142091065

**Comment by agoncal** [comment]
@langchain4j does this mean we can close this issue ?
