### ISSUE TITLE
[FEATURE] Gemini — Support Google Search and Vertex AI Search grounding

### ISSUE THREAD

**Issue by glaforge** [langchain4j/langchain4j#1269]
The Gemini model has the ability to search 
* into Google Search to ground its responses, or 
* in the Google Cloud Vertex AI Search (to search on custom/personal/company documents)

See this [page](https://cloud.google.com/vertex-ai/generative-ai/docs/multimodal/ground-gemini) for more information.

**Comment by langchain4j** [comment]
Implemented in https://github.com/langchain4j/langchain4j/pull/1278
