### ISSUE TITLE
[BUG]  AzureOpenAiStreamingChatModel  occur IndexOutOfBoundsException 

### ISSUE THREAD

**Issue by wzhj2326** [langchain4j/langchain4j#127]
LangChain4j version:  0.21.0

![image](https://github.com/langchain4j/langchain4j/assets/15643447/d6dbfcc8-96f7-4fdf-b159-a444fc1f2924)

![image](https://github.com/langchain4j/langchain4j/assets/15643447/d07d3411-0249-4a25-aabd-fd644f3192a7)

**Comment by langchain4j** [comment]
@wzhj2326 thanks for reporting! will investigate

**Comment by langchain4j** [comment]
@wzhj2326 could you please provide more details? Does it happen every time? When exactly does it happen? Thanks

**Comment by wzhj2326** [comment]
> @wzhj2326 could you please provide more details? Does it happen every time? When exactly does it happen? Thanks

no every time ,when i use Azure model gpt-35-turbo-16k,api version 2023-07-01-preview,it occur. 
I find it  returned first  message is as follows：
`data: {"id":"","object":"","created":0,"model":"","prompt_annotations":[{"prompt_index":0,"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}}}],"choices":[],"usage":null}`

choices is empty array,but line 138 code get index 0

https://github.com/langchain4j/langchain4j/blob/97d7d0c7551da43c000885888e6b7286a31ba0ce/langchain4j/src/main/java/dev/langchain4j/model/azure/AzureOpenAiStreamingChatModel.java#L138

**Comment by langchain4j** [comment]
@wzhj2326 should be fixed in 0.22.0, please check
