### ISSUE TITLE
hope that some embedding store APIs can be better enriched

### ISSUE THREAD

**Issue by stoneLee81** [langchain4j/langchain4j#128]
1 EmbeddingStoreIngestor.ingest, Whether to consider adding some return data processed by embeddingstore. for instance, some cases need to store return values by embedding and store it to other storage. 

2 chroma/milvus/pinecone, miss update/delete functions

**Comment by langchain4j** [comment]
Hi @stoneLee81 please describe point number 1 in more details. What exactly do you want to store in other place? Thanks!

**Comment by stoneLee81** [comment]
for instance, i need to store id and content to mysql/es in order to get some related search in business or fuzzy query or update/delete.

**Comment by langchain4j** [comment]
@stoneLee81 you mean id of each embedding? by content you mean the text that was embedded?

**Comment by stoneLee81** [comment]
yes, I store it in mysql in order to do some search that  vector db is not good at.
