### ISSUE TITLE
[FEATURE] Integrate TypeChat, which is an alternative to the OpenAI function

### ISSUE THREAD

**Issue by chenhaoqiang** [langchain4j/langchain4j#129]
To the best of my knowledge, only OpenAI provides the function capability, while other LLMs do not have this feature. However, I recently discovered that Microsoft has an open-source project called TypeChat: [https://github.com/microsoft/TypeChat](https://github.com/microsoft/TypeChat), which aims to address this issue. TypeChat allows functions to be decoupled from any specific LLM. I hope to see this feature added. Thank you!

**Comment by langchain4j** [comment]
Hi @chenhaoqiang as far as I can see from TypeChat docu, it is more about the structured outputs from LLM than function calling. If you need function calling with opensource LLMs, you can use our integration with [LocalAI](https://localai.io/), they support OpenAI-like functions for quite a while now. If you want structured outputs, LangChain4j supports it already without need for functions, please see examples [here](https://github.com/langchain4j/langchain4j-examples/blob/main/other-examples/src/main/java/OtherServiceExamples.java).

**Comment by chenhaoqiang** [comment]
> Hi @chenhaoqiang as far as I can see from TypeChat docu, it is more about the structured outputs from LLM than function calling. If you need function calling with opensource LLMs, you can use our integration with [LocalAI](https://localai.io/), they support OpenAI-like functions for quite a while now. If you want structured outputs, LangChain4j supports it already without need for functions, please see examples [here](https://github.com/langchain4j/langchain4j-examples/blob/main/other-examples/src/main/java/OtherServiceExamples.java).

@langchain4j  Sorry, I misunderstood. What I want is structured output, and I have also found the relevant implementation principles of structured output in langchain4j. However, I have some doubts about the difference between structured output and function call. If we have structured output, does it mean that we no longer need function call?

**Comment by langchain4j** [comment]
Hi @chenhaoqiang, structured output was possible with regular prompting even before functions appeared in OpenAI API. With the introduction of functions in OpenAI API structured output became very popular. It is nice, but it is not required for structured output. Currently, structured output is implemented with prompting in LangChain4j and it seems to work reliably.

**Comment by chenhaoqiang** [comment]
> Hi @chenhaoqiang, structured output was possible with regular prompting even before functions appeared in OpenAI API. With the introduction of functions in OpenAI API structured output became very popular. It is nice, but it is not required for structured output. Currently, structured output is implemented with prompting in LangChain4j and it seems to work reliably.

Okay, thank you! I understand!
