### ISSUE TITLE
[suggestion]  Some suggestions

### ISSUE THREAD

**Issue by xuning888** [langchain4j/langchain4j#1292]
**Is your feature request related to a problem? Please describe.**
First of all, I want to thank all the contributors to the open-source repository for your hard work and contributions. Your efforts have made it convenient for us to use Java to access LLM.

I have tried langchaingo and langchain4j in addition to langchain, and I had a better experience with langchaingo as it well replicates the ideas of langchain. When using langchain4j, AiServices allowed me to quickly write "hello world", but the dynamic proxy of AiServices made my program feel like a black box. When I really wanted to use it in a production environment, I had to read the source code of AiServices to understand the internal workings.

While simplicity and ease of use are important, observability and transparent logic are even more critical. Could you add more support for Chains?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by langchain4j** [comment]
HI @xuning888 thank you a lot for your feedback!

Would a diagram of AI Services internals help? Could you please expand on the "black box"? Which parts are not clear/obvious/well documented?
BTW, there is a [documentation](https://docs.langchain4j.dev/tutorials/ai-services) about AI Services, did it help? We are also working on adding observability hooks everywhere.

As for the chains, we don't plan to support this concept any more, the same way as LangChain (python) replaced them with other concepts like LCEL. I am not sure chains would be more helpful, as they also hide a lot of (boilerplate) logic from the user.

While AI Services are helpful in many cases, you don't **_have_** to use them, you could still use lower-level components like `ChatLanguageModel`, `ChatMemory`, `EmbeddingStore`, `ContentRetriever`, etc, and glue them together as you wish. And still benefit from numerous implementations/integrations with different LLM providers, embedding stores, etc.

Looking forward for more feedback, thank you in advance!
