### ISSUE TITLE
[FEATURE] `toolSpecificationFrom` method support configuration of optional parameters

### ISSUE THREAD

**Issue by Kugaaa** [langchain4j/langchain4j#1293]
**Is your feature request related to a problem? Please describe.**

dev.langchain4j.agent.tool.ToolSpecifications#toolSpecificationFrom
Returns the `ToolSpecification` for the given method annotated with `@Tool`
But there is no way to control optional params

**Describe the solution you'd like**

Define a annotation like `ToolParam`
```java
@Target({ElementType.FIELD})
@Retention(RetentionPolicy.RUNTIME)
public @interface ToolParam {
    String name();
    String description();
    boolean required() default false;
}
```

**Describe alternatives you've considered**

/

**Additional context**

It would be even better if it could support parameter validation

**Comment by langchain4j** [comment]
There is a PR already: https://github.com/langchain4j/langchain4j/pull/922

**Comment by langchain4j** [comment]
@Kugaaa #922 seems to be stuck and not the best solution.

Would you like to implement your proposal?

BTW, there is already a `@P` annotation where you can add this new `required()`/`optional()` attribute.

**Comment by Kugaaa** [comment]
@langchain4j No problem, I'll try to handle it as soon as possible.

**Comment by Kugaaa** [comment]
Sorry, the changes are bigger than I expected. @langchain4j 
According to the [JSON schema DOC](https://json-schema.org/learn/getting-started-step-by-step#create-a-nested-data-structure), nested data structure also need a `required` key, like
```json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://example.com/product.schema.json",
  "title": "Product",
  "description": "A product from Acme's catalog",
  "type": "object",
  "properties": {
    "productId": {
      "description": "The unique identifier for a product",
      "type": "integer"
    },
    "dimensions": {
      "type": "object",
      "properties": {
        "length": {
          "type": "number"
        },
        "width": {
          "type": "number"
        },
        "height": {
          "type": "number"
        }
      },
      // here
      "required": [ "length", "width", "height" ]
    }
  },
  "required": [ "productId" ]
}
```
The current implementation seems unsupported `dev.langchain4j.agent.tool.ToolSpecifications#schema(java.lang.Class<?>, java.util.Set<java.lang.Class<?>>)`

I would like to confirm the scope of influence:
1. Whether to support optional fields in `Object`, It seems that there is no support `required` yet
2. Whether to use third-party library directly
3. Whether to support validate params from LLM

**Comment by langchain4j** [comment]
Hi @Kugaaa 
1. I would first implement `@P(required = false)` for the arguments of a `@Tool` method, without POJOs or nesting. After this is done, we can make it more complex
2. Please clarify this question
3. Please clarify this question

**Comment by Kugaaa** [comment]
supplement
2. Use open-source tools, such as [JSON Schema Tools](https://json-schema.org/implementations)
3. Validating the parameters called by the LLM tool calling with JSON Schema

**Comment by langchain4j** [comment]
@Kugaaa

2. There is already a [PR](https://github.com/langchain4j/langchain4j/pull/941) for this
3. This probably depends on 2

**Comment by langchain4j** [comment]
Implemented in https://github.com/langchain4j/langchain4j/pull/1370
