### ISSUE TITLE
[BUG] [AzureOpenAI] TokenUsage set to null 

### ISSUE THREAD

**Issue by fb33** [langchain4j/langchain4j#1294]
If we define a AI Assistant with 

```
import dev.langchain4j.service.Result;

public interface Assistant {
    Result<String> answer(String query);
}
```

When an error occurs during the generate phase, then the Response built got a null TokenUsage.
See here for example line 268: https://github.com/langchain4j/langchain4j/blob/25e4d6de4932fc23bdd92a2c9c9fc2613169f125/langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiChatModel.java#L256-L270

But, the AiService will try to map the response into a Result (following the interface)
https://github.com/langchain4j/langchain4j/blob/25e4d6de4932fc23bdd92a2c9c9fc2613169f125/langchain4j/src/main/java/dev/langchain4j/service/DefaultAiServices.java#L202-L210

and there is a rule in Result constructor to avoid null for TokenUsage
https://github.com/langchain4j/langchain4j/blob/25e4d6de4932fc23bdd92a2c9c9fc2613169f125/langchain4j/src/main/java/dev/langchain4j/service/Result.java#L27-L31

To fix that, can we create an empty instance of TokenUsage in the catch block ?
```
            return Response.from(
                    aiMessage(httpResponseException.getMessage()),
                    new TokenUsage(),
                    exceptionFinishReason
            );
```

**Comment by fb33** [comment]
ping @jdubois @agoncal 

I made the small PR with the proposal

**Comment by agoncal** [comment]
I wasn't aware of this API. 

Looking at https://github.com/langchain4j/langchain4j/blob/main/langchain4j-open-ai/src/main/java/dev/langchain4j/model/openai/OpenAiChatModel.java#L181 I can see that OpenAI uses the `InternalOpenAiHelper.tokenUsageFrom()` method.

Azure OpenAI also has this method in `InternalAzureOpenAiHelper`. I wonder if we should use it?  https://github.com/langchain4j/langchain4j/blob/main/langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/InternalAzureOpenAiHelper.java#L299

**Comment by langchain4j** [comment]
I guess we should relax the `ensureNotNull(tokenUsage, "tokenUsage")` requirement, not all models return it

**Comment by fb33** [comment]
> Azure OpenAI also has this method in InternalAzureOpenAiHelper. I wonder if we should use it? https://github.com/langchain4j/langchain4j/blob/main/langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/InternalAzureOpenAiHelper.java#L299

Yes, I missed this. It should be the good place to create an empty TokenUsage. Or may be the `ensureNotNull(tokenUsage, "tokenUsage")` could be remove and there is no thing to do on AzureOpenAI part.

On my side, I don't know the impact of removing this constraint. 
If we keep the constraint, @agoncal I'll update the PR to modify and use the helper.
If we remove the constraint, we can close the PR :-)
