### ISSUE TITLE
[FEATURE] Add API to EmbeddingStore to allow updating an embedding by ID

### ISSUE THREAD

**Issue by sjivan** [langchain4j/langchain4j#1299]
I need to update an embedding and text for a given ID. The API below is missing in EmbeddingStore

void add(String id, Embedding embedding, TextSegment textSegment);

And the implementation would be 

  public void add(String id, Embedding embedding, TextSegment textSegment) {
        addInternal(id, embedding, textSegment);
   }

EmbeddingStore currently only has

void add(String id, Embedding embedding)

which does not let me pass the text.  In the case of PgVectorEmbeddingStore the proposed API will be able to store and update the text and embedding in the embedding table for the specified ID.

**Comment by langchain4j** [comment]
CLosing as a diplicate of https://github.com/langchain4j/langchain4j/issues/301
