### ISSUE TITLE
[FEATURE] Add a builder to PgVectorEmbeddingStore that supports setting DataSource

### ISSUE THREAD

**Issue by sjivan** [langchain4j/langchain4j#1300]
The current builder on PgVectorEmbeddingStore does not support setting a DataSource and creates and closes connections based on DB host / port information passed to it. This is not ideal as I'd like to have Spring Boot create my Hikari Pool based DataSource and set this on the PgVectorEmbeddingStore.

**Comment by jmartisk** [comment]
There's a builder for that, you just need to call `PgVectorEmbeddingStore.datasourceBuilder()` instead of `PgVectorEmbeddingStore.builder()`

**Comment by langchain4j** [comment]
Should we add `.datasource()` to the `PgVectorEmbeddingStore.builder()` and validate that either datasource or other connection params are set? `PgVectorEmbeddingStore.datasourceBuilder()` feels not intuitive

**Comment by jmartisk** [comment]
That is subjective, the way it currently is it's more typesafe, because you choose one approach upfront (either datasource or connection details) and then you can only call methods that are valid for that approach... but yeah generally I agree that one builder is better than two

**Comment by humcqc** [comment]
My 2 cents, I think it's preferable to have two distinct builder as you don't build them from the same inputs. 
If we want just one, I will just keep the datasource one and force the user to create a datasource in his side. 
I think in real life product we will always use a datasource with connection management.

**Comment by langchain4j** [comment]
Please use `PgVectorEmbeddingStore.datasourceBuilder()`
