### ISSUE TITLE
[BUG] Nightly and release jobs should not be run on fork repositories

### ISSUE THREAD

**Issue by Wadimz** [langchain4j/langchain4j#1302]
Release and nightly jobs are failing in forked repositories producing unnecessary notifications.
This is expected as credentials are not configured on forks.

This behavior can be adjusted by adding condition on the repository source:
` if: github.repository == 'langchain4j/langchain4j'`

**Log and Stack trace**
![image](https://github.com/langchain4j/langchain4j/assets/2750435/b5aebda6-b734-4270-a9db-1589efc81753)

**To Reproduce**
- fork repository
- wait next nightly run

**Expected behavior**
- no runs performed

**Please complete the following information:**
- LangChain4j version: 0.31.0
- LLM(s) used: N/A
- Java version: N/A
- Spring Boot version (if applicable): N/A

**Comment by langchain4j** [comment]
@Wadimz thank you! I wasn't aware this was happening

**Comment by langchain4j** [comment]
Fixed by https://github.com/langchain4j/langchain4j/pull/1303
