### ISSUE TITLE
[FEATURE] sql agent

### ISSUE THREAD

**Issue by JCASTANO** [langchain4j/langchain4j#1308]
Hello good morning

It would be excellent to have this functionality in the version of java that currently exists in python and js

https://python.langchain.com/v0.2/docs/integrations/toolkits/sql_database/#use-sqldatabasetoolkit-within-an-agent

https://js.langchain.com/v0.1/docs/use_cases/sql/agents/

allows chatting with an agent to a relational database

**Comment by langchain4j** [comment]
Hi, this is somewhat supported, please check https://github.com/langchain4j/langchain4j-examples/blob/main/rag-examples/src/main/java/_3_advanced/_10_Advanced_RAG_SQL_Database_Retreiver_Example.java
