### ISSUE TITLE
[BUG] An attempt was made to call a method that does not exist (Builder.dimensions of ElasticSearchEmbeddingStore)

### ISSUE THREAD

**Issue by jasonxu1888** [langchain4j/langchain4j#1310]
**Describe the bug**
![image](https://github.com/langchain4j/langchain4j/assets/112231046/b8dd7d92-afb1-4c7e-aa30-b9ffd5c80507)
Creating an Elastic Search instance is fine (the docker part works fine), but when trying to instantiate the ElasticsearchEmbeddingStore object to interact with the vector storage instance, it fails giving the error below.

**Log and Stack trace**

An attempt was made to call a method that does not exist. The attempt was made from the following location:
    dev.langchain4j.store.embedding.elasticsearch.ElasticsearchEmbeddingStore.lambda$getDefaultMappings$14(ElasticsearchEmbeddingStore.java:340)
The following method did not exist:
    'co.elastic.clients.elasticsearch._types.mapping.DenseVectorProperty$Builder co.elastic.clients.elasticsearch._types.mapping.DenseVectorProperty$Builder.dims(int)'
The calling method's class, dev.langchain4j.store.embedding.elasticsearch.ElasticsearchEmbeddingStore, was loaded from the following location:
    jar:file:/Users/jaxu/.gradle/caches/modules-2/files-2.1/dev.langchain4j/langchain4j-elasticsearch/0.28.0/51667b991092942a075b078f3f52c43fd4b8399e/langchain4j-elasticsearch-0.28.0.jar!/dev/langchain4j/store/embedding/elasticsearch/ElasticsearchEmbeddingStore.class
The called method's class, co.elastic.clients.elasticsearch._types.mapping.DenseVectorProperty$Builder, is available from the following locations:
    jar:file:/Users/jaxu/.gradle/caches/modules-2/files-2.1/co.elastic.clients/elasticsearch-java/8.13.4/3c8e5b92bef09595d94dd607810a1c2697a743ad/elasticsearch-java-8.13.4.jar!/co/elastic/clients/elasticsearch/_types/mapping/DenseVectorProperty$Builder.class
The called method's class hierarchy was loaded from the following locations:
    co.elastic.clients.elasticsearch._types.mapping.DenseVectorProperty.Builder: file:/Users/jaxu/.gradle/caches/modules-2/files-2.1/co.elastic.clients/elasticsearch-java/8.13.4/3c8e5b92bef09595d94dd607810a1c2697a743ad/elasticsearch-java-8.13.4.jar
    co.elastic.clients.elasticsearch._types.mapping.PropertyBase.AbstractBuilder: file:/Users/jaxu/.gradle/caches/modules-2/files-2.1/co.elastic.clients/elasticsearch-java/8.13.4/3c8e5b92bef09595d94dd607810a1c2697a743ad/elasticsearch-java-8.13.4.jar
    co.elastic.clients.util.WithJsonObjectBuilderBase: file:/Users/jaxu/.gradle/caches/modules-2/files-2.1/co.elastic.clients/elasticsearch-java/8.13.4/3c8e5b92bef09595d94dd607810a1c2697a743ad/elasticsearch-java-8.13.4.jar
    co.elastic.clients.util.ObjectBuilderBase: file:/Users/jaxu/.gradle/caches/modules-2/files-2.1/co.elastic.clients/elasticsearch-java/8.13.4/3c8e5b92bef09595d94dd607810a1c2697a743ad/elasticsearch-java-8.13.4.jar
Action:
Correct the classpath of your application so that it contains compatible versions of the classes dev.langchain4j.store.embedding.elasticsearch.ElasticsearchEmbeddingStore and co.elastic.clients.elasticsearch._types.mapping.DenseVectorProperty$Builder

**To Reproduce**
<img width="898" alt="image" src="https://github.com/langchain4j/langchain4j/assets/112231046/f5a0fb87-afcd-49d7-b5fe-25e3da9a60b3">
These are the dependencies I am using, and run the code in the image above.

**Expected behavior**
in image here: 
<img width="815" alt="image" src="https://github.com/langchain4j/langchain4j/assets/112231046/17ff1d45-f880-4a46-8809-c907ba80ae3b">

**Please complete the following information:**
- LangChain4j version: 0.28.0
- LLM(s) used: 
- Java version: 17
- Spring Boot version (if applicable): 3.3.0

**Additional context**

https://github.com/langchain4j/langchain4j-examples/blob/main/elasticsearch-example/src/main/java/ElasticsearchEmbeddingStoreExample.java

Here is the example the code is based on.

**Comment by langchain4j** [comment]
Hi, could you please check the latest version (0.31.0)?

**Comment by jasonxu1888** [comment]
same issue

**Comment by langchain4j** [comment]
Could you please provide the output of `./gradlew dependencyInsight` and the full contents of your gradle file?

**Comment by jasonxu1888** [comment]
Sorry for the delay in response; this is similar to issue #1225 . If the index is already created, the builder proceeds with no issue, but if not, if throws the "dim" error and does not create the index. Downgraded elastic client to what was recommended in #1225 and issue solved.
