### ISSUE TITLE
[FEATURE] Improve document to mention AI Service intefaces can support streaming and non-streaming together

### ISSUE THREAD

**Issue by sjivan** [langchain4j/langchain4j#1318]
I recently read this blog and found it interesting that a single AI Service can support streaming and non-streaming API's. I think this is a pretty cool feature that should be documented.

public interface CustomerServiceAgent {
    /**
     * Non-streaming
     */
    String chat(String userMessage);

   /**
     * Streaming
     */
    TokenStream chatStream(String userMessage);

}

https://chalise-arun.medium.com/streaming-with-rest-api-for-langchain-applications-f3a164a207d7

**Comment by langchain4j** [comment]
It is documented for quite a while: https://docs.langchain4j.dev/tutorials/ai-services#streaming
