### ISSUE TITLE
[FEATURE] MessageWindowChatMemory support conversational exchange

### ISSUE THREAD

**Issue by noday** [langchain4j/langchain4j#1326]
**Is your feature request related to a problem? Please describe.**

use maxMessages, it may start with AiMessage like below, and llm will has exception'messages must strat will Humen message '
AI:*****
Humen:****
AI:*****

**Describe the solution you'd like**

like langchain's ConversationBufferWindowMemory(k=), k is  conversational exchange
**Describe alternatives you've considered**

**Additional context**

![image](https://github.com/langchain4j/langchain4j/assets/892768/608fec11-965b-4727-94ec-4666dbad8028)

**Comment by langchain4j** [comment]
Hi @noday, which LLM are you using that has this restriction?

**Comment by noday** [comment]
@langchain4j qwen and bedrock-anthropic has, this is test:
![image](https://github.com/langchain4j/langchain4j/assets/892768/8c0015d9-1bf9-4cb8-b1f1-8db366bb4a7f)

**Comment by noday** [comment]
if set maxMessages 4, it throw exception always.

**Comment by langchain4j** [comment]
This issue has been fixed for Anthropic: https://github.com/langchain4j/langchain4j/pull/1197
We could port the fix for qwen and bedrock as well

**Comment by noday** [comment]
Perhaps having a ConversationMessageWindowChatMemory would be better
