### ISSUE TITLE
[BUG] easy-rag maven dependency : FileSystemDocumentLoader not able to retrieve anything

### ISSUE THREAD

**Issue by yro7** [langchain4j/langchain4j#1330]
**Issue**

Adding the easy-rag maven dependency seems to alter how FileSystemDocumentLoader behaves. With the dependency, i'm not able to retrieve documents:

**To Reproduce**
```
Path directoryPath = Path.of("/home/yroo/Spigot/1.12/plugins");
List<Document> documents = FileSystemDocumentLoader.loadDocumentsRecursively();
System.out.println("documents : " + documents.size());
```
outputs `documents : 209` without the dependency, and documents : 209`with it.

**Pom.xml**
```
        <dependency>
            <groupId>dev.langchain4j</groupId>
            <artifactId>langchain4j</artifactId>
            <version>0.31.0</version>
        </dependency>
        <dependency>
            <groupId>dev.langchain4j</groupId>
            <artifactId>langchain4j-open-ai</artifactId>
            <version>0.31.0</version>
        </dependency>
        <dependency>
            <groupId>dev.langchain4j</groupId>
            <artifactId>langchain4j-anthropic</artifactId>
            <version>0.31.0</version>
        </dependency>

```
**Dependency used :**

```
        <dependency>
            <groupId>dev.langchain4j</groupId>
            <artifactId>langchain4j-easy-rag</artifactId>
            <version>0.31.0</version>
        </dependency>

```
**Additional information:**
- LangChain4j version: 0.31.0
- LLM(s) used: OpenAI GPT 3.5 Turbo
- Java version: 22

**Comment by langchain4j** [comment]
Hi @yro7 

> Adding the easy-rag maven dependency seems to alter how FileSystemDocumentLoader behaves.

This is true, when `langchain4j-easy-rag` dependency is included, it transitively imports `langchain4j-document-parser-apache-tika` which does the parsing of documents if no specific `DocumentParser` is specified in the `loadDocumentsRecursively()` method.

> outputs documents : 209 without the dependency, and documents : 209`with it.

I am not sure I understand what is the exact problem. 209 both with and without?

**Comment by yro7** [comment]
> Hi @yro7
> 
> > Adding the easy-rag maven dependency seems to alter how FileSystemDocumentLoader behaves.
> 
> This is true, when `langchain4j-easy-rag` dependency is included, it transitively imports `langchain4j-document-parser-apache-tika` which does the parsing of documents if no specific `DocumentParser` is specified in the `loadDocumentsRecursively()` method.
> 
> > outputs documents : 209 without the dependency, and documents : 209`with it.
> 
> I am not sure I understand what is the exact problem. 209 both with and without?

Hey, thanks for your quick reply.

My bad copy/pasting error sorry! With the dependency, no document is retrieved at all.
![image](https://github.com/langchain4j/langchain4j/assets/52044171/b6a22d7b-0d23-4898-b3ab-3d70dba9d827)

Passing in argument a new TextDocumentParser() in the FileSystemDocumentLoader works fine. Weird that the ApacheTikaDocumentParser don't, the files are mostly .yml or .json.

Thanks again for your help.

**Comment by langchain4j** [comment]
Hmm, that is strange, I've just tried to load documents including yml file and it works fine. Could you share your setup?

**Comment by yro7** [comment]
What additional info do you need ? 
You can see the whole code 

 here: https://github.com/yro7/LLM-craft/blob/master/src/main/java/fr/yro/llmcraft/Helper/Helper.java

As for the loaded files, I'm sorry I can not share them with you here but the folder contains .jar, .json and .yml files mostly (I keep only .yml files in the end)

**Comment by yro7** [comment]
Okay I reproduced the set-up from another project and I don't have any problem. It might be my maven that acts weirdly when it shades the dependency but in any case, it's on my side. Thanks you again!

**Comment by langchain4j** [comment]
@yro7 ok, then I will close this issue
