### ISSUE TITLE
[BUG] Documentation "intro" page is resulting in 404

### ISSUE THREAD

**Issue by jesuino** [langchain4j/langchain4j#1337]
**Describe the bug**
From the home Page I clicked on Introduction button and it directed me to a 404 page

**Log and Stack trace**
n/a

**To Reproduce**
Go to https://docs.langchain4j.dev/ and click on Introduction. It will direct you to https://docs.langchain4j.dev/intro - which currently is a 404

**Expected behavior**
I wanted to see the introduction page.

**Please complete the following information:**
n/a

**Additional context**
Pardon me if this is not the right place to file an issue for this.

**Comment by langchain4j** [comment]
@jesuino thansk a lot for raising this issue! I've fixed it, re-deploying documentation.
