### ISSUE TITLE
[BUG] RedisEmbeddingStore returns embeddings from different indexes

### ISSUE THREAD

**Issue by Rommek** [langchain4j/langchain4j#1340]
**Describe the bug**
During  search RedisEmbeddingStore finds embeddings in all existing Redis embedding stores, in the same instance of Redis (not only current one) .
Bug was noticed around version 0.23.0, when TODO comment was added in the RedisEmbeddingStoreIT:
```
// TODO fix: why redis returns embeddings from different indexes?
```

**To Reproduce**
Create at least two Redis storages using the same Redis instance.
Embeddings added to the first storage would be found when search is done with use of second storage.

It's also possible to run this test (can be added to RedisEmbeddingStoreIT):
 ```	
    @Test
    void should_find_embedding_in_proper_store() {
       final EmbeddingStore<TextSegment> firstStore = createStore("first-store");
       final EmbeddingStore<TextSegment> secondStore = createStore("second-store");

       Embedding embedding = embeddingModel().embed("hello").content();
       
       String id = firstStore.add(embedding);
       assertThat(id).isNotBlank();

       List<EmbeddingMatch<TextSegment>> relevant = firstStore.findRelevant(embedding, 10);
       assertThat(relevant).hasSize(1);
       assertThat(secondStore.findRelevant(embedding, 10)).hasSize(0);

       // new API
       assertThat(firstStore.search(EmbeddingSearchRequest.builder()
               .queryEmbedding(embedding)
               .maxResults(10)
               .build()).matches()).isEqualTo(relevant);
       assertThat(secondStore.search(EmbeddingSearchRequest.builder()
               .queryEmbedding(embedding)
               .maxResults(10)
               .build()).matches()).hasSize(0);
    }
    
    private EmbeddingStore<TextSegment> createStore(String name) {
      return RedisEmbeddingStore.builder()
          .host(redis.getHost())
          .port(redis.getFirstMappedPort())
          .indexName(name)
          .dimension(384)
          .metadataKeys(createMetadata().toMap().keySet())
          .build();      
  }
```    

Current tests in the RedisEmbeddingStoreIT  can also be used to reproduce, when lines:
```
        try (JedisPooled jedis = new JedisPooled(redis.getHost(), redis.getFirstMappedPort())) {
            jedis.flushDB(); // TODO fix: why redis returns embeddings from different indexes?
        }
```
are removed.

**Expected behavior**
RedisEmbeddingStore should only return embeddings from current storage

**Please complete the following information:**
- LangChain4j version: 0.31.0 
- LLM(s) used: llama3
- Java version: openjdk 21.0.2 2024-01-16 LTS
- Spring Boot version (if applicable): 3.2.5

**Additional context**
Problem is caused by having the same key prefix (defined in RedisSchema as "embedding:") for all embeddings stored in the Redis.
Since that all Redis indexes created by langchain4j are searching through the same embedding source.
(I'm currently working on PR)

**Comment by Martin7-1** [comment]
Thank you! Please let me know if you finish the PR. @Rommek

**Comment by Rommek** [comment]
Hi @Martin7-1 , 
I just created PR - https://github.com/langchain4j/langchain4j/pull/1347 with the fix.
I put question-marks in the description next to the points I wasn't fully sure (i.e. I had to skip local tests with api key and I was curious if my change meets requirements for backward compatibility).
