### ISSUE TITLE
[FEATURE] finishReason in Result

### ISSUE THREAD

**Issue by fb33** [langchain4j/langchain4j#1341]
Hi,

I use Result class as a the return type of my method from my AI service, so I can have the content from the AI response and also the sources retrieved from the Rag.
But if there is a problem with LLM request, I have no access to the cause.

What about having the finishReason of the ai response in the Result class ?

I'll quickly create a PR for that.

Thanks

**Comment by langchain4j** [comment]
Implemented in https://github.com/langchain4j/langchain4j/pull/1342
