### ISSUE TITLE
Does it support callback functions similar to langchain? For example, callbacks during tool calls

### ISSUE THREAD

**Issue by java668** [langchain4j/langchain4j#1349]
Does it support callback functions similar to langchain? For example, callbacks during tool calls

**Comment by langchain4j** [comment]
Hi, this feature is in progress. [Callbacks for llm requests/responses/errors](https://github.com/langchain4j/langchain4j/pull/1058) are already supported. Next steps are to implement callbacks for RAG and tools. Could you please provide more details about the required functionality? How do you plan to use this feature? Thanks!
