### ISSUE TITLE
[FEATURE] Support JDK specific modules

### ISSUE THREAD

**Issue by tjake** [langchain4j/langchain4j#1350]
**Is your feature request related to a problem? Please describe.**
Langchain4j only supports Java8 compiler

**Describe the solution you'd like**
I would like to add jdk specific profiles for modules that require higher JDK versions

**Describe alternatives you've considered**
These could be hosted in a separate repo?  I see quarkus-langchain4j does this for Java 17+

**Additional context**
I'm the creator of [Jlama](https://github.com/tjake/Jlama) which requires Java 21+ and would like to contribute a langchain4j module for HF safetensor embeddings and models natively in Java.

Thanks!

**Comment by langchain4j** [comment]
Hi @tjake, LangChain4j is released with JDK 21, so there should be no problem to integrate Jlama, looking forward to your PRs!

**Comment by langchain4j** [comment]
Implemented in https://github.com/langchain4j/langchain4j/pull/1379
