### ISSUE TITLE
[FEATURE]-ai4j updates

### ISSUE THREAD

**Issue by fmatar** [langchain4j/langchain4j#1357]
**Is your feature request related to a problem? Please describe.**
I frequently need to serialize/deserialize the underlying model classes of ai4j using Jackson, but I'm encountering issues due to missing constructors and creators.

**Describe the solution you'd like**
I would like the ai4j model classes to be made serializable using Jackson without requiring custom deserializers. This includes adding default constructors, annotated creators, and any necessary annotations for proper serialization/deserialization.

**Describe alternatives you've considered**
I have considered writing custom deserializers to handle serialization manually, but this approach is cumbersome and requires maintenance as the models evolve.

**Additional context**
Serialization of these model classes is critical for seamless integration with various components in my application, including storage and messaging systems. It would greatly enhance the usability and maintainability of ai4j if these changes were implemented.

**Comment by fmatar** [comment]
@langchain4j happy to tackle this issue, thoughts? I see this project being part of langchain4j but it's not getting any love it deserves

**Comment by langchain4j** [comment]
@fmatar hmm, what about migrating ai4j from Gson to Jackson? We have started this migration for some of lc4j modules, and it seems to work well.

cc @geoand do you see any problems for Quarkus?

**Comment by geoand** [comment]
> cc @geoand do you see any problems for Quarkus?

Nope, only upside for Quarkus as we'll be able to remove alot of code :)

**Comment by fmatar** [comment]
Got some bandwidth on me now and this is a major issue I want fixed. 

Want me to tackle it? Also happy to add a lot of missing driver features

**Comment by fmatar** [comment]
> > cc @geoand do you see any problems for Quarkus?
> 
> 
> 
> Nope, only upside for Quarkus as we'll be able to remove alot of code :)

And hopefully get rid of the empty mixins?

**Comment by langchain4j** [comment]
@fmatar sounds awesome, please go ahead (with migrating to Jackson)!
Regarding "driver features", what do you mean?

**Comment by fmatar** [comment]
A few parameters added to OpenAI Chat api are missing from the library. I'll push a PR against https://github.com/ai-for-java/openai4j

**Comment by langchain4j** [comment]
openai4j is using Jackson now
