### ISSUE TITLE
[ADMIN] Tag Azure OpenAI issues with the new Azure label 

### ISSUE THREAD

**Issue by agoncal** [langchain4j/langchain4j#1361]
Hey @langchain4j and @LizeRaes . Now that we have an _Azure_ label, could you tag the following closed/opened issues so we can get accurate statistics on Azure related issues. 

Thanks

https://github.com/langchain4j/langchain4j/issues/1311
https://github.com/langchain4j/langchain4j/issues/1274
https://github.com/langchain4j/langchain4j/issues/1249
https://github.com/langchain4j/langchain4j/issues/1206
https://github.com/langchain4j/langchain4j/issues/1155
https://github.com/langchain4j/langchain4j/issues/1106
https://github.com/langchain4j/langchain4j/issues/1098
https://github.com/langchain4j/langchain4j/issues/1068
https://github.com/langchain4j/langchain4j/issues/989
https://github.com/langchain4j/langchain4j/issues/794
https://github.com/langchain4j/langchain4j/issues/738
https://github.com/langchain4j/langchain4j/issues/688
https://github.com/langchain4j/langchain4j/issues/614
https://github.com/langchain4j/langchain4j/issues/597
https://github.com/langchain4j/langchain4j/issues/576
https://github.com/langchain4j/langchain4j/issues/521
https://github.com/langchain4j/langchain4j/issues/442
https://github.com/langchain4j/langchain4j/issues/438
https://github.com/langchain4j/langchain4j/issues/422
https://github.com/langchain4j/langchain4j/issues/340
https://github.com/langchain4j/langchain4j/issues/325
https://github.com/langchain4j/langchain4j/issues/307
https://github.com/langchain4j/langchain4j/issues/216
https://github.com/langchain4j/langchain4j/issues/127
https://github.com/langchain4j/langchain4j/issues/126
https://github.com/langchain4j/langchain4j/issues/98
https://github.com/langchain4j/langchain4j/issues/96
https://github.com/langchain4j/langchain4j/issues/43

**Comment by LizeRaes** [comment]
Done :)
@glaforge I can do the same for Gemini if it helps you

**Comment by glaforge** [comment]
I found the following issues (open & closed) that either cover Vertex AI or Gemini:

#82
#252
#259
#362
#440
#444
#461
#651
#757
#827
#828
#882
#899
#1010
#1090
#1167
#1182
#1208
#1223
#1269
#1270
#1272
#1363

Do you think we should have 2 different tags? One for Gemini and one for Vertex AI?
For example, the non-Gemini or custom models, embedding models, or the Imagen image generation models are all the the `vertex-ai` module, but Gemini specific models are in the `vertex-ai-gemini` module.
In the future, there will also likely be support for things like Vertex AI Search (vector database), which will likely be in the `vertex-ai` module, and is not necessarily related to Gemini.
Thoughts?

**Comment by agoncal** [comment]
Thank you @lize

@jdubois now it's easier to have some stats about Azure related issues that are opened or closed:

https://github.com/langchain4j/langchain4j/labels/Azure

**Comment by langchain4j** [comment]
@glaforge makes sense, let me know a complete list of labels you prefer to have, I will add them

**Comment by glaforge** [comment]
In my opinion, `vertex` and `gemini` labels would be fine, and they would correspond to the two modules we currently have.

**Comment by LizeRaes** [comment]
I added `Vertex` label and tagged @glaforge's list of repositories. Let me know if anything should be changed.
Also, should we update the langchain4j-github-bot to support `Vertex` tagging, or is it that overkill?

**Comment by langchain4j** [comment]
@LizeRaes thank you! Yes, it makes sense to update github bot rules then

**Comment by agoncal** [comment]
@LizeRaes sorry to bother you again. But could you add the Azure label to the following PRs please:

https://github.com/langchain4j/langchain4j/pull/1403
https://github.com/langchain4j/langchain4j/pull/1295
https://github.com/langchain4j/langchain4j/pull/1273
https://github.com/langchain4j/langchain4j/pull/1271
https://github.com/langchain4j/langchain4j/pull/1257
https://github.com/langchain4j/langchain4j/pull/1256
https://github.com/langchain4j/langchain4j/pull/1222
https://github.com/langchain4j/langchain4j/pull/1205
https://github.com/langchain4j/langchain4j/pull/1200
https://github.com/langchain4j/langchain4j/pull/1195
https://github.com/langchain4j/langchain4j/pull/1144
https://github.com/langchain4j/langchain4j/pull/1131
https://github.com/langchain4j/langchain4j/pull/1130
https://github.com/langchain4j/langchain4j/pull/1127
https://github.com/langchain4j/langchain4j/pull/1115
https://github.com/langchain4j/langchain4j/pull/1082
https://github.com/langchain4j/langchain4j/pull/1046
https://github.com/langchain4j/langchain4j/pull/1021
https://github.com/langchain4j/langchain4j/pull/1018
https://github.com/langchain4j/langchain4j/pull/1017
https://github.com/langchain4j/langchain4j/pull/1016
https://github.com/langchain4j/langchain4j/pull/991
https://github.com/langchain4j/langchain4j/pull/912
https://github.com/langchain4j/langchain4j/pull/879
https://github.com/langchain4j/langchain4j/pull/822
https://github.com/langchain4j/langchain4j/pull/811
https://github.com/langchain4j/langchain4j/pull/810
https://github.com/langchain4j/langchain4j/pull/809
https://github.com/langchain4j/langchain4j/pull/796
https://github.com/langchain4j/langchain4j/pull/764
https://github.com/langchain4j/langchain4j/pull/762
https://github.com/langchain4j/langchain4j/pull/758
https://github.com/langchain4j/langchain4j/pull/700
https://github.com/langchain4j/langchain4j/pull/700
https://github.com/langchain4j/langchain4j/pull/691
https://github.com/langchain4j/langchain4j/pull/677
https://github.com/langchain4j/langchain4j/pull/664
https://github.com/langchain4j/langchain4j/pull/636
https://github.com/langchain4j/langchain4j/pull/629
https://github.com/langchain4j/langchain4j/pull/616
https://github.com/langchain4j/langchain4j/pull/611
https://github.com/langchain4j/langchain4j/pull/607
https://github.com/langchain4j/langchain4j/pull/591
https://github.com/langchain4j/langchain4j/pull/587
https://github.com/langchain4j/langchain4j/pull/573
https://github.com/langchain4j/langchain4j/pull/530
https://github.com/langchain4j/langchain4j/pull/529
https://github.com/langchain4j/langchain4j/pull/443
https://github.com/langchain4j/langchain4j/pull/439
https://github.com/langchain4j/langchain4j/pull/375
https://github.com/langchain4j/langchain4j/pull/372
https://github.com/langchain4j/langchain4j/pull/371
https://github.com/langchain4j/langchain4j/pull/359
https://github.com/langchain4j/langchain4j/pull/356
https://github.com/langchain4j/langchain4j/pull/339
https://github.com/langchain4j/langchain4j/pull/328
https://github.com/langchain4j/langchain4j/pull/183
https://github.com/langchain4j/langchain4j/pull/107

**Comment by LizeRaes** [comment]
@agoncal Azure label is added to those tickets now as well. Thank you for all your contributions!
