### ISSUE TITLE
[FEATURE] Support new Imagen parameters and get ready for Imagen v3

### ISSUE THREAD

**Issue by glaforge** [langchain4j/langchain4j#1367]
Not all of the latest image generation parameters are supported yet for Imagen: for example aspect ratio, watermarking, generation of persons, mime type, etc. Some of these parameters are also specific to Imagen v3, which isn't officially generally available yet.

The goal of this ticket is to add the missing parameters, and also to prepare for the arrival of Imagen v3 and ensure that LangChain4j's support will be ready.

**Comment by langchain4j** [comment]
Implemented in https://github.com/langchain4j/langchain4j/pull/1278
