### ISSUE TITLE
[FEATURE] mark QwenHelper  public 

### ISSUE THREAD

**Issue by utf7** [langchain4j/langchain4j#1368]
[`QwenHelper`](https://github.com/langchain4j/langchain4j/blob/main/langchain4j-dashscope/src/main/java/dev/langchain4j/model/dashscope/QwenHelper.java ) is package visiable ,not public ,we want to use this class.
can be make it class and method public ?

**Comment by langchain4j** [comment]
Hi, why do you want to use it? Making it public will make changing this class very hard for us

**Comment by utf7** [comment]
> Hi, why do you want to use it? Making it public will make changing this class very hard for us

Thanks for reply.

We use llm-proxy rest service which is  rest api to connect with different models        

the url like      

`https://xxxx//ai-proxy/aliyun/qwen`     
` https://xxxx//ai-proxy/openai/gpt-4`        

but langchain4j will be auto added to the url  some like `***/chat/completions`, `***/aigc/text-generation/generation`     

OpenAI model we  create a OpenAiClient modify the url and use java `reflect` modify the OpenAiChatModel      

the the QwenChatModel can't be do that ,any other suggestion for use ?

**Comment by langchain4j** [comment]
@jiangsier-xyz could you please comment on this?

**Comment by jiangsier-xyz** [comment]
> > Hi, why do you want to use it? Making it public will make changing this class very hard for us
> 
> Thanks for reply.
> 
> We use llm-proxy rest service which is rest api to connect with different models
> 
> the url like
> 
> `https://xxxx//ai-proxy/aliyun/qwen` ` https://xxxx//ai-proxy/openai/gpt-4`
> 
> but langchain4j will be auto added to the url some like `***/chat/completions`, `***/aigc/text-generation/generation`
> 
> OpenAI model we create a OpenAiClient modify the url and use java `reflect` modify the OpenAiChatModel
> 
> the the QwenChatModel can't be do that ,any other suggestion for use ?



> > Hi, why do you want to use it? Making it public will make changing this class very hard for us
> 
> Thanks for reply.
> 
> We use llm-proxy rest service which is rest api to connect with different models
> 
> the url like
> 
> `https://xxxx//ai-proxy/aliyun/qwen` ` https://xxxx//ai-proxy/openai/gpt-4`
> 
> but langchain4j will be auto added to the url some like `***/chat/completions`, `***/aigc/text-generation/generation`
> 
> OpenAI model we create a OpenAiClient modify the url and use java `reflect` modify the OpenAiChatModel
> 
> the the QwenChatModel can't be do that ,any other suggestion for use ?

It appears that setting QwenHelper to public does not resolve your issue. Adding paths such as /chat/completions is the internal logic of the DashScope SDK and is not handled within QwenHelper. Here are some suggestions:
- Set up a "proxy" that maps the service paths of DashScope to your own paths, and pass the URL of this proxy as the baseUrl to QwenXxxModel.
- Alternatively, encapsulate a module, such as langchain4j-your-llm-proxy, that implements the LanguageModel/ChatLanguageModel interfaces of langchain4j. Internally, this module should use your own logic to call the specific OpenAiXxxModel or QwenXxxModel.
