### ISSUE TITLE
SSLHandshakeException: PKIX path building failed:

### ISSUE THREAD

**Issue by langchain4j** [langchain4j/langchain4j#1369]
### Discussed in https://github.com/langchain4j/langchain4j/discussions/347

<div type='discussions-op-text'>

<sup>Originally posted by **iamuspace** December 12, 2023</sup>
OpenAiChatModel.generate() error. 
stand alone java application code works fine. 

but, 
error in web application using Glassfish web server of NetBeans IDE

I guess that SSL to api.openai.com cert. 
I added api.openai.com's cert to Zulu-21 OpenJDK  security/cacerts using keytool. 

The same error still occurs.

How can I solve the problem?

java.lang.RuntimeException: java.lang.RuntimeException: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at dev.langchain4j.internal.RetryUtils.withRetry(RetryUtils.java:29)
	at dev.langchain4j.model.openai.OpenAiChatModel.generate(OpenAiChatModel.java:127)
	at dev.langchain4j.model.openai.OpenAiChatModel.generate(OpenAiChatModel.java:91)</div>

**Comment by jawaharbabus** [comment]
@langchain4j I am working on this issue.

**Comment by jawaharbabus** [comment]
This is not necessarily a bug from langchain4j. Basically, SSLHandshakeException occurs when Glassfish's keystore doesn't recognize or trust the certificate authority (CA) that signed the server's SSL certificate, in our case api.openai.com. Glassfish only trusts the certificates in its truststore file  (keystore.jks and cacerts.jks) and tries to keep its truststore to minimum.
I resolved this issue by exporting the root certificate from https://api.openai.com/ and adding it in truststore files (both keystore.jks and cacerts.jks) in my glassfish configuration directory. The solution is to add the root certificate of the CA to Glassfish's keystore. This tells Glassfish to trust certificates signed by this CA.

To resolve this issue, 
- Export the root certificate from https://api.openai.com/ and store it as a pem file.
- Look for "keystore.jks" and "cacerts.jks" files under "glassfish/domains/domain1/config/" directory.
- Add the exported certificate to both the jks file using
 `keytool -import -alias [choose_an_alias] -file [path_to_root_certificate] -keystore [path_to_glassfish_keystore]`
- You will be prompted for keystore password. usually, the keystore password for Glassfish is "changeit".
- repeat the process for both the jks files
- restart the glassfish for the changes to take effect.

Alternatively, you can add all certificates from your jdk to the glassfish truststore. 
This exception is specific to the Glassfish webserver. There is a discussion about this on Glassfish issue tracker: https://github.com/eclipse-ee4j/glassfish/issues/24523
If this is not working, consider switching to Tomcat or any other webserver.

**Comment by langchain4j** [comment]
@jawaharbabus awesome, thank you so much!
Then I guess we can close this issue?
