### ISSUE TITLE
[BUG] Loading SystemMessage or UserMessage fromResource causes a problem (resource not found)

### ISSUE THREAD

**Issue by ilyako87** [langchain4j/langchain4j#1372]
**Describe the bug**

When you use a SystemMessage or UserMessage from a resource (fromResource method), it causes the resource to not be found. The problem is that the classloader is not used to load the resource.

```
    @SystemMessage(fromResource = "system_prompt.txt")
    fun doChat(@MemoryId chatId: String, @UserMessage message: String): String
```

**Log and Stack trace**
```
dev.langchain4j.exception.IllegalConfigurationException: @SystemMessage's resource 'system_prompt.txt' not found
	at dev.langchain4j.exception.IllegalConfigurationException.illegalConfiguration(IllegalConfigurationException.java:16) ~[langchain4j-0.31.0.jar:na]
	at dev.langchain4j.service.DefaultAiServices.getTemplate(DefaultAiServices.java:357) ~[langchain4j-0.31.0.jar:na]
	at dev.langchain4j.service.DefaultAiServices.findSystemMessageTemplate(DefaultAiServices.java:231) ~[langchain4j-0.31.0.jar:na]
	at dev.langchain4j.service.DefaultAiServices.prepareSystemMessage(DefaultAiServices.java:222) ~[langchain4j-0.31.0.jar:na]
	at dev.langchain4j.service.DefaultAiServices.access$100(DefaultAiServices.java:33) ~[langchain4j-0.31.0.jar:na]
	at dev.langchain4j.service.DefaultAiServices$1.invoke(DefaultAiServices.java:94) ~[langchain4j-0.31.0.jar:na]
	at jdk.proxy2/jdk.proxy2.$Proxy94.doChat(Unknown Source) ~[na:na]
```

**To Reproduce**
Put the message file in your resources folder and include its name as a resource in the annotation. When calling a service method, an error will occur. This also won't work if you specify an absolute path in the file system.

**Expected behavior**
The file will be found and read.

**Please complete the following information:**
- LangChain4j version: 0.31.0
- LLM(s) used: Ollama: llama3
- Java version: 17
- Spring Boot version (if applicable): 3.2.5

**Additional context**
Most likely the problem is in the getResourceAsStream(name) method call.
This is[ line 376 of the DefaultAiServices class](https://github.com/langchain4j/langchain4j/blob/9c31319693d3d95dc7ce763f5367f60bddaf40bb/langchain4j/src/main/java/dev/langchain4j/service/DefaultAiServices.java#L376)

**Comment by langchain4j** [comment]
Hi @ilyako87, if `system_prompt.txt` is located in the root of recources, you need to add "/" before the file name like so:

```
    @SystemMessage(fromResource = "/system_prompt.txt")
    fun doChat(@MemoryId chatId: String, @UserMessage message: String): String
```

**Comment by ilyako87** [comment]
Hi @langchain4j, thanks for your prompt response. But I proceed from the fact that if the classloader will be used, then this problem will not appear at all. 
Just rewrite the method:
```
private static String getResourceText(Class<?> clazz, String name) {
        return getText(clazz.getClassLoader().getResourceAsStream(name));
    }
```

**Comment by langchain4j** [comment]
@ilyako87 ah, I see what you mean. This will be a breaking change unfortunately...
For users who have these prompts in the root of `resources` dir, they have a "/" prefix in the `fromResource`.
If we change to `clazz.getClassLoader().getResourceAsStream(name)`, it will fail to find the file for them. We might need to do a fallback to `clazz.getResourceAsStream(name)`, WDYT?

**Comment by langchain4j** [comment]
I forgot that there is an [open PR](https://github.com/langchain4j/langchain4j/pull/781) to help with this issue already

**Comment by ilyako87** [comment]
@langchain4j, thanks for informing. I'm glad to know that the problem has already been resolved.
