### ISSUE TITLE
[BUG]  dev.langchain4j langchain4j-dashscope 0.31.0 pull from maven failed

### ISSUE THREAD

**Issue by wang1589019** [langchain4j/langchain4j#1376]
<dependency>
    <groupId>dev.langchain4j</groupId>
    <artifactId>langchain4j-dashscope</artifactId>
    <version>0.31.0</version>
</dependency>

使用千问模型，在中国区网络下，配置了阿里云的代理，发现拉取失败，请教下这是为什么？
Using the Qianwen model and configuring Alibaba Cloud's proxy in the China network, it was found that the pull failed. May I ask why this is happening?
![Snipaste_2024-06-28_23-01-37](https://github.com/langchain4j/langchain4j/assets/6722749/20f9b0b0-647f-4654-ab2f-176a003e3877)

**Comment by langchain4j** [comment]
@wang1589019 hi, could you please translate the error message from the screenshot?

**Comment by jiangsier-xyz** [comment]
You need to consult the technical support personnel of Aliyun's maven mirror provider. Alternatively, you can download it from the maven central repository: https://central.sonatype.com/artifact/dev.langchain4j/langchain4j-dashscope.
