### ISSUE TITLE
[AzureAiSearch] keep metadata for all kind of search

### ISSUE THREAD

**Issue by fb33** [langchain4j/langchain4j#1383]
The default structure of an azure ai search index is a content ( and content_vector) and metadata with attributes as a map.

When we do a vector search, metadata are retrieved in the Content (via TextSegment). But for others types of search these metadata are lost.

Can we mutualise this code for all the search type ? : 
https://github.com/langchain4j/langchain4j/blob/30bf0aac087d803d9391c7018ba557b735f2b537/langchain4j-azure-ai-search/src/main/java/dev/langchain4j/store/embedding/azure/search/AbstractAzureAiSearchEmbeddingStore.java#L271-L300

**Comment by fb33** [comment]
I'm going to propose a PR

**Comment by yoshioterada** [comment]
Dear @fb33  
It seems that this is similar to the following issue.
 
https://github.com/langchain4j/langchain4j/issues/1098
https://github.com/langchain4j/langchain4j/issues/1263

**Comment by fb33** [comment]
Hi @yoshioterada 

For #1263 is not exactly the same, because the #1263 was about the filter on metadata used to search, and here it's about retrieving metadata in the result contents.

For #1098, you're right, a part of that issue is the same :
> Also, metadata mapping in the AzureAiSearchContentRetriever seems to be limited to pure Vector queries and not implemented for FullText, Hybrid or HybridWithReranking.

But I think the main topic of #1098 is about managing indexes with AzureAiSearchContentRetriever that are not defined with the default (standard ?) structure (ie content, content_vector, metedata with attributes)
