### ISSUE TITLE
[BUG] 0.31.0 azure chatgpt not getting tokenusage

### ISSUE THREAD

**Issue by wzglgo** [langchain4j/langchain4j#1388]
- LangChain4j version: 0.31.0
`        UserMessage userMessage = UserMessage.from(
                TextContent.from("what's it?"),
                ImageContent.from("https://learn.microsoft.com/en-us/media/home-and-directory/featured-documentation_dark.jpg?branch=live")
        );
        msgList.add(userMessage);
        Response<AiMessage> response = azureOpenAiChatModel
                .generate(msgList);
        System.out.println(response.tokenUsage());`

**Comment by langchain4j** [comment]
@wzglgo I am getting the following error:

`INFO: Error generating response, {error={message=Invalid content type. image_url is only supported by certain models., type=invalid_request_error, param=messages.[0].content.[1].type, code=null}}`

Try another model that supports image inputs, like `gpt-4o`

**Comment by wzglgo** [comment]
> @wzglgo I am getting the following error:
> 
> `INFO: Error generating response, {error={message=Invalid content type. image_url is only supported by certain models., type=invalid_request_error, param=messages.[0].content.[1].type, code=null}}`
> 
> Try another model that supports image inputs, like `gpt-4o`

I can get response just only tokenusage get null. My model on azure is gpt4o @langchain4j

**Comment by langchain4j** [comment]
@wzglgo please provide a complete example, I cannot reproduce this issue with the provided code snippets
