### ISSUE TITLE
[FEATURE] Gemini to support function calling mode (AUTO, ANY, NONE)

### ISSUE THREAD

**Issue by glaforge** [langchain4j/langchain4j#1397]
Gemini recently added the definition of [function calling mode](https://cloud.google.com/vertex-ai/generative-ai/docs/multimodal/function-calling#tool-config). By default, it's the `AUTO` mode where Gemini decides or not if a function should be called and which one. `NONE` specifies that no function should be requested. And `ANY` allows the user to select a subset of possible functions among those defined in the tools.

**Comment by langchain4j** [comment]
Implemented in https://github.com/langchain4j/langchain4j/pull/1278
