### ISSUE TITLE
[FEATURE] Gemini should support setting a JSON schema for its JSON output mode

### ISSUE THREAD

**Issue by glaforge** [langchain4j/langchain4j#1399]
Gemini added the ability to specify a response MIME type, like `application/json` to force Gemini to generate pure JSON response. But it also added the ability to [specify a JSON schema](https://cloud.google.com/vertex-ai/generative-ai/docs/multimodal/control-generated-output) to guide the _controlled generation_ of the JSON response. So you describe the output in the form of a JSON schema, so Gemini should return JSON that complies with that schema.

**Comment by langchain4j** [comment]
Implemented in https://github.com/langchain4j/langchain4j/pull/1278
