### ISSUE TITLE
[BUG] System message added multiple times during the lifespan of a chat memory

### ISSUE THREAD

**Issue by mmanco** [langchain4j/langchain4j#140]
System messages are being [added multiple times](https://github.com/langchain4j/langchain4j/blob/main/langchain4j/src/main/java/dev/langchain4j/service/AiServices.java#L386) to the chat memory during its lifespan. This repetitive addition of system messages not only consumes valuable tokens but also leads to the exhaustion of the token limit more quickly. As a result, the available context span for the conversation is reduced, potentially affecting the quality and coherence of the language model's responses.

**To Reproduce**
Any scenario with a system message will lead to the described behavior.

**Expected behavior**
Anchor the system message in the head of the chat memory and manage memory slots within the chat memory type's boundaries (message/token window).

- LangChain4j version: 0.21.0
- Java version: 17
- Spring Boot version: 3.1.2

**Comment by langchain4j** [comment]
Hi @mmanco multiple system messages can be in the memory only if they are different. For example, we have a service with 2 methods annotated with `@SystemMessage`. [New system message is added to the memory only if the last system message is not equals to the new system message](https://github.com/langchain4j/langchain4j/blob/main/langchain4j/src/main/java/dev/langchain4j/service/AiServices.java#L471).

If you have multiple methods with different system messages it means that you have different intents and LLM should respond differently. In this case, to communicate new intent, new system message is required. But if we remove previous system messages, LLM will be confused.

In general it is advisable to avoid adding multiple methods to AI services if you need memory, as it becomes complicated and confusing.

**Comment by mmanco** [comment]
@langchain4j Thank you for the response and pointers. It makes total sense and the setup I had so far is as described. Will separate to multiple services. 

Thank you for this great library!
