### ISSUE TITLE
[BUG] AiServices with tool execution supports response as message or tool execution, but not both

### ISSUE THREAD

**Issue by SteveMartinBIL** [langchain4j/langchain4j#1402]
Hello there

I am implementing LangChain4J in a Spring boot java project, with AI Services.
It's working pretty well, but I have a case where the model answer a text message like "Please wait I am retrieving some information for you" and ask for a tool execution. In this case, le tool execution is ignored (cf https://github.com/langchain4j/langchain4j/blob/abc957a8013ccb857d7a791eaf33119431fce7d3/langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/InternalAzureOpenAiHelper.java#L267)

**Describe the bug**
For me, it should execute the function first, or give the possibility to have the choice.

**To Reproduce**
Create an AI Service with tool execution and ask for something like "retrieve my todo list"

**Expected behavior**
The function should be executed instead of returning the text message from the model.

**Please complete the following information:**
- LangChain4j version: 0.31.0
- LLM(s) used: Azure OpenAI gpt-4o
- Java version: 17
- Spring Boot version (if applicable): 3.1.11

Thank you for your work, this lib is great :)

**Comment by langchain4j** [comment]
@SteveMartinBIL thanks a lot for reporting! Fixing it right now.

cc @agoncal @jdubois
