### ISSUE TITLE
[BUG]  Azure Open AI - finish reason management

### ISSUE THREAD

**Issue by fb33** [langchain4j/langchain4j#1404]
Problem : AzureOpenAi model should use FinishReason.LENGTH in case of token length limit reached.

If we do a request with too many tokens, then Azure Open AI answer with a http status 400 and a json body that contains an error code.
This status 400 causes getChatCompletions of OpenAiClient raises an exception 
`ChatCompletions chatCompletions = client.getChatCompletions(deploymentName, options);`

This exception is handled here : https://github.com/langchain4j/langchain4j/blob/0a706ecb444b114ef079613da3e7b4e1f3e1070a/langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiChatModel.java#L313-L336

And the helper only deals with ContentFilter case.
https://github.com/langchain4j/langchain4j/blob/0a706ecb444b114ef079613da3e7b4e1f3e1070a/langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/InternalAzureOpenAiHelper.java#L337-L359

I think it should also manage Token limit reached, and then the method should certainly be renamed in `exceptionFinishReasonManagement` for example. 

With the current implementation, we got a `FinishReason.OTHER` and we lost the fact that the limit was reached (even if the limit should be correctly managed by the business application ;-) )

**Comment by langchain4j** [comment]
@fb33 I doubt 400 error in this case should be mapped to `FinishReason.LENGTH`.
`FinishReason.LENGTH` means that LLM produced some response, but it did not manage to finish (produce complete response) because **_output_** token limit has been reached (either max token limit of the model or `maxTokens` set by the user).

400 HTTP error means that the request has a problem, in this case **_input_** token limit has been reached.

**Comment by fb33** [comment]
Hi @langchain4j 
Here is the return message retrieve by AzureOpenAiChatModel from com.azure.ai.openai.implementation.OpenAIClientImpl.getChatCompletionsSync(...)  : 
```json
{
  "az.sdk.message": "HTTP response",
  "statusCode": 400,
  "url": "https://xxxxxx.openai.azure.com//openai/deployments/completions/chat/completions?api-version=2024-03-01-preview",
  "durationMs": 106,
  "content-length": 281,
  "Date": "Thu, 04 Jul 2024 09:44:54 GMT",
  "Content-Type": "application/json",
  "x-ms-client-request-id": "0cf9dfba-065d-4024-98db-2ab5164855ed",
  "redactedHeaders": "x-request-id,x-ms-region,apim-request-id,x-ratelimit-remaining-tokens,x-ratelimit-remaining-requests,Strict-Transport-Security,azureml-model-session,access-control-allow-origin,x-content-type-options,x-ms-rai-invoked,ms-azureml-model-error-statuscode,ms-azureml-model-error-reason",
  "Date": "Thu, 04 Jul 2024 09:44:54 GMT",
  "Content-Type": "application/json",
  "x-ms-client-request-id": "0cf9dfba-065d-4024-98db-2ab5164855ed",
  "redactedHeaders": "x-request-id,x-ms-region,apim-request-id,x-ratelimit-remaining-tokens,x-ratelimit-remaining-requests,Strict-Transport-Security,azureml-model-session,access-control-allow-origin,x-content-type-options,x-ms-rai-invoked,ms-azureml-model-error-statuscode,ms-azureml-model-error-reason",
  "content-length": 281,
  "body": {
  "error": {
    "message": "This model's maximum context length is 8192 tokens. However, your messages resulted in 9948 tokens. Please reduce the length of the messages.",
    "type": "invalid_request_error",
    "param": "messages",
    "code": "context_length_exceeded"
  }
}
}
```
So maybe FinishReason.LENGTH is not the right reason to use. But as a FinishReason is computed on a http 400 like here : 
https://github.com/langchain4j/langchain4j/blob/0a706ecb444b114ef079613da3e7b4e1f3e1070a/langchain4j-azure-open-ai/src/main/java/dev/langchain4j/model/azure/AzureOpenAiLanguageModel.java#L233-240
I thought, we can manage also context_length_exceeded.
Maybe, we can introduce a FinishReason.REQUEST_LENGTH ? Or should we use FinishReason only for LLM response and error, and then use another enum to qualify the technical error?

**Comment by langchain4j** [comment]
@fb33 In my understanding `FinishReason` makes sense when the requst to the LLM provider succeeded (with the exception of filtered content).
If the request is problematic (400), then it is a bug which developer should fix. So I would throw a `RuntimeException` in this case. WDYT?

**Comment by fb33** [comment]
Yes, I'm agree.

The question is, should the LanguageModel.generate(...) be implemented in a somewhat functional way (i.e. always return a Response object even if there is a technical error, and this is what it started to do with managing 400 and filtered content) or  be implemented with exceptions ?

**Comment by langchain4j** [comment]
@fb33 we are usually throwing exceptions if there are technical errors, I would follow the same style instead of introducing a new one

**Comment by langchain4j** [comment]
@fb33 what's the status of this issue/PR? Should we close it?
