### ISSUE TITLE
[FEATURE] ApachePdfBoxDocumentParser should return metadata extracted from the PDF

### ISSUE THREAD

**Issue by Samyssmile** [langchain4j/langchain4j#1406]
Try to get metadata from a perfect accessable pdf that contains metadata. 

Here is such a pdf attached
[bookmarklet-einrichten.pdf](https://github.com/user-attachments/files/16090155/bookmarklet-einrichten.pdf)

I expect a Metada Object

```
       ApachePdfBoxDocumentParser parser = new ApachePdfBoxDocumentParser();
        InputStream inputStream = new FileInputStream("bookmarklet-einrichten.pdf");
        Document document = parser.parse(inputStream);
        Metadata metadata = document.metadata();
        System.out.println(metadata.toMap().isEmpty());

```
Above Code prints true, I also debugged alot of PDFs, its always empty. I also investigate the parse Method. As I see you never extract any metadata.

**Expected behavior**
Metadata of parsed pdf.

**Please complete the following information:**
- LangChain4j version: 0.31.0
- LLM(s) used: none
- Java version: 21
- Spring Boot version (if applicable): none

**Comment by zambrinf** [comment]
@Samyssmile check if [1475](https://github.com/langchain4j/langchain4j/pull/1475) works for you, it uses information available in `org.apache.pdfbox.pdmodel.PDDocumentInformation` to get the metadata

**Comment by Samyssmile** [comment]
@zambrinf ok will check it

**Comment by Samyssmile** [comment]
@zambrinf I tested it and did code review. It looks good now.

**Comment by zambrinf** [comment]
> @zambrinf I tested it and did code review. It looks good now.

@Samyssmile you can leave the Issue open, when the PR is merged it closes the issue automatically
