### ISSUE TITLE
[FEATURE] Configure tools dynamically/programmatically

### ISSUE THREAD

**Issue by vcjj** [langchain4j/langchain4j#141]
i want to use tool desc like this, how can i do,thanks

```
class ServiceImpl {
       @Value(${xxx})
       private String desc;

        @Tool(name="tool1", value=desc)
        int add(int a, int b) {
            System.out.println("Called add()");
            return a + b;
        }
}
```

There should be a way to define tools outside of the application (e.g. in a config file or a database) and possibly add/register them in runtime.

**Comment by langchain4j** [comment]
Hi @vcjj, it is not possible at the moment, as @Tool.value should be a constant. We are working now on adding an option to AiServices to define tools without @Tool annotation, so you will be able to do it soon. Will update you once we add this.

**Comment by langchain4j** [comment]
cc @amirkhan-ak-sf

**Comment by langchain4j** [comment]
Implemented in https://github.com/langchain4j/langchain4j/pull/1364

**Comment by d135-1r43** [comment]
Great feature!

> and possibly add/register them in runtime.

That is not yet implemented, right?

**Comment by langchain4j** [comment]
Right, registering tools after the creation of AI Service is not yet implemented

**Comment by langchain4j** [comment]
BTW, please check my comment here: https://github.com/langchain4j/langchain4j/issues/1420#issuecomment-2220019006
