### ISSUE TITLE
Function call feature for locally deployed models

### ISSUE THREAD

**Issue by shaojool** [langchain4j/langchain4j#1415]
For local models like Qwen or Ollama that are less familiar, is there a plan to support the function calling feature?

**Comment by langchain4j** [comment]
@qq1005894049 [Qwen (DashScope)](https://docs.langchain4j.dev/integrations/language-models/dashscope) already supports function calling, and example is [here](https://github.com/langchain4j/langchain4j/blob/bfae3927e6ef73584d03fee7c22da40900b32891/langchain4j-dashscope/src/test/java/dev/langchain4j/model/dashscope/QwenChatModelIT.java#L90).

Ollama does not support function calling natively yet. Once it will support it, we will add it too. Closing this request as there is https://github.com/langchain4j/langchain4j/issues/318 already

**Comment by shaojool** [comment]
Does Qwen (DashScope) only support cloud service calls? Can the locally private deployed Qwen large model support calls as well?

**Comment by langchain4j** [comment]
@jiangsier-xyz could you please comment?

**Comment by jiangsier-xyz** [comment]
> Does Qwen (DashScope) only support cloud service calls? Can the locally private deployed Qwen large model support calls as well?

No, langchain4j-dashscope is a wrapper for the model service provider DashScope (by Aliyun). If we want to use some local runtime framework to run the Qwen2 model and implement the relevant interfaces of langchain4j, we will need to implement it separately.

**Comment by caopengan** [comment]
> @qq1005894049 [Qwen (DashScope)](https://docs.langchain4j.dev/integrations/language-models/dashscope) already supports function calling, and example is [here](https://github.com/langchain4j/langchain4j/blob/bfae3927e6ef73584d03fee7c22da40900b32891/langchain4j-dashscope/src/test/java/dev/langchain4j/model/dashscope/QwenChatModelIT.java#L90).
> 
> Ollama does not support function calling natively yet. Once it will support it, we will add it too. Closing this request as there is #318 already

When do you plan to release it?

**Comment by langchain4j** [comment]
@caopengan do you mean tool support for ollama? Did ther already release it?

**Comment by caopengan** [comment]
> @caopengan do you mean tool support for ollama? Did ther already release it?

No, I'm interested in whether the Qwen model supports tool calls,Because I see that version 0.32.0 is not supported yet.

**Comment by langchain4j** [comment]
Doesn't [this](https://github.com/langchain4j/langchain4j/blob/bfae3927e6ef73584d03fee7c22da40900b32891/langchain4j-dashscope/src/test/java/dev/langchain4j/model/dashscope/QwenChatModelIT.java#L90) work for you?

**Comment by caopengan** [comment]
> Doesn't [this](https://github.com/langchain4j/langchain4j/blob/bfae3927e6ef73584d03fee7c22da40900b32891/langchain4j-dashscope/src/test/java/dev/langchain4j/model/dashscope/QwenChatModelIT.java#L90) work for you?

yeah,I see, but I use a StreamingChatLanguageModel, it is still not back support tools

**Comment by langchain4j** [comment]
@jiangsier-xyz could you please comment?

**Comment by caopengan** [comment]
> @jiangsier-xyz could you please comment?

Okay, I'll do that. Thank you very much, bro
