### ISSUE TITLE
[FEATURE] Distributed Tools

### ISSUE THREAD

**Issue by d135-1r43** [langchain4j/langchain4j#1420]
**Is your feature request related to a problem? Please describe.**

Our bot currently has very many tools, most of them using a different JDBC driver, different APIs (REST, GQL, gRPC). This comes with several downsides:

* Dependency accumulation, too many data sources
* The Bot grows to be an omnipotent monolith
* API lifecycle management needs to be addressed 
* token consumption is high and will grow even further
* customizing the bot for different customers or deployments is not possible

Also, some of our tools are located on the remote servers. It means, that these tools may become unavailable during the work of the service, also some new tools may appear, or some past remote tools can be deleted. Also, we do not know descriptions and parameters of these remote tools in advance, so they cannot be attached to an AIService during the boot time or compile time.

**Describe the solution you'd like**

Tools should be distributed. A Tool can be implemented by a microservice. As soon as that microservice starts, it will register itself at the AIService; if it is unavailable, the tool can be unregistered. It should be possible to run these operations in the runtime.  

**Describe alternatives you've considered**

Right now, to make the LLM know about connected remote tools, we use `RetrievalAugmentor` that returns descriptions of the attached remote tools. Then, LLM can call a special "generic" tool that is attached traditionally as a common tool with an annotation. This tool acts like a dispatcher for all the connected remote tools. This approach is very buggy and non-deterministic and consumes tons of tokens, so it seems more like a workaround rather than a reliable, solid solution.

**Additional context**

We at EXP would be willing to contribute a PR.

**Comment by langchain4j** [comment]
Hi @d135-1r43, if you need the ability to specify which tools should be available to the LLM dynamically (for each AI Service invocation), there is [this issue](https://github.com/langchain4j/langchain4j/issues/637) which can be implemented pretty easily.
So, something like this:
```java
Map<ToolSpecification, ToolExecutor> tools = new ConcurrentHashMap<>();  // you manage this map, adding and removing tools to it as you need

Assistant assistant = AiServices.builder(Assistant.class)
    .chatLanguageModel(...)
    .toolProvider((userMessage, memoryId) -> tools)
    .build();
```

`toolProvider` will be called on every invocation of `Assistant` and you can return all the tools that LLM should have access to for this specific invocation. This way, tools can change over time (you can add/remove new/existing tools in the map). You can also provide different tools for different users or even depending on the current message (e.g. depending on user intent). Would that work for you?

**Comment by MiggiV2** [comment]
Hello @langchain4j. I'm affiliate with @d135-1r43 at EXP and want to propose some enhancements.  
I checked out your implementation of programmatically defined tools, which is great, btw.  

It would be awesome to add tools to an existing Assistant instance, rather than creating a new one.
Right now, we can only set tools, while building one. After building, we can't add / remove tools. 
```` JAVA
Assistant assistant = AiServices.builder(Assistant.class)
    .chatLanguageModel(chatLanguageModel)
    .tools(singletonMap(toolSpecification, toolExecutor))
    .build();
````

## New Wrapper for ToolSpecification & ToolExecutor:
To define a new tool, you will always need a specification and executor.  
This wrapper should be called `ToolRequest` and simplify the registration of new tools.  
The wrapper should have two setter methods
```` JAVA
toolRequest
.setSpecification(toolSpecification);
.setExecutor(toolExecutor);
````
And also a constructor like this:
```
ToolRequest toolRequeset = new ToolRequest(toolSpecification, toolExecutor);
```

## New AiService / Assistant methods
How should the new API look like to register new tools and what methods should the API provide?  
Method to add tools:
```
ToolRequest foobar;
ToolRequest barfoo;
assistant.addTools(foobar, barfoo, ...);
```

Methods to remove tools:  
```
assistant.removeTool(foobar.getName());
assistant.removeTool(foobar);
```

Method to remove all tools:  
```
assistant.removeAllTools();
```
I think when `removeAllTools()` also remove the static tools that have been added by annotations would be the most intuitive behavior.

**Comment by langchain4j** [comment]
Hi @MiggiV2, thanks for the suggestion! I was considering a similar approach, but I am not sure it is flexible enough.
Did you check [this comment](https://github.com/langchain4j/langchain4j/issues/1420#issuecomment-2220019006)? It allows for adding/updating/removing tools after AI Service is created, but also allows to chose which tools to include depending on the user and/or user intent, etc.

**Comment by MiggiV2** [comment]
Your [similar approach](https://github.com/langchain4j/langchain4j/issues/637#issuecomment-1956558379) is even better than our proposal. Selecting the matching tool before and then send it with the user request seams to be very efficient.

This matches our use case very well 🙂

Is it okay for you, if I work on the pull request for this?

**Comment by langchain4j** [comment]
Sure, go ahead!

I propose the following API (draft):

```java
public class ToolProviderRequest {

    private final Object chatMemoryId;
    private final UserMessage userMessage;
}

public class ToolProviderResult {

    private final Map<ToolSpecification, ToolExecutor> tools;
}

public class ToolProvider {

    ToolProviderResult provideTools(ToolProviderRequest request);
}

Assistant assistant = AiServices.builder(Assistant.class)
    .toolProvider(...)
    .build();
```

Either tool provider or (static) tools can be configured during building of AI Service, but not both.

WDYT?

**Comment by MiggiV2** [comment]
I like the draft for the API and your idea that either tool provider or (static) tools can be configured during building.

So `toolProvider(...)` will take an implementation of ToolProvider, right?

**Comment by langchain4j** [comment]
> So toolProvider(...) will take an implementation of ToolProvider, right?

Yes, correct

**Comment by d135-1r43** [comment]
We at EXP are on it. As both @MiggiV2 and I are currently on vacation, the MR will come in ca. 2 weeks.

**Comment by MiggiV2** [comment]
Hi @langchain4j. I've just created the PR #1644.
I also want you to inform, that @d135-1r43 reviewed my code, and we are both excited to hear your feedback.

**Comment by langchain4j** [comment]
Implemented in https://github.com/langchain4j/langchain4j/pull/1644

**Comment by d135-1r43** [comment]
Thanks a lot. Great feature, great work!
