### ISSUE TITLE
[BUG] Spring boot application start issue after upgrading to latest version of langchain starter version of openAI

### ISSUE THREAD

**Issue by hemadrio** [langchain4j/langchain4j#1441]
**Describe the bug**
After upgrading libraries am unable to run spring boot application
And in my project I will create model object on demand not at application start time

My dependencies 
compile 'dev.langchain4j:langchain4j:0.32.0'
	compile 'dev.langchain4j:langchain4j-open-ai-spring-boot-starter:0.32.0'
	compile 'dev.langchain4j:langchain4j-vertex-ai-gemini:0.32.0'
	compile 'dev.langchain4j:langchain4j-embeddings-all-minilm-l6-v2:0.32.0'
	
	
	
Error on application start
java.lang.IllegalArgumentException: Unresolvable class definition for class [dev.langchain4j.openai.spring.Properties]\n\tat org.springframework.util.ClassUtils.resolveClassName(ClassUtils.java:331)\n\tat org.springframework.core.annotation.TypeMappedAnnotation.adapt(TypeMappedAnnotation.java:474)\n\tat org.springframework.core.annotation.TypeMappedAnnotation.getValue(TypeMappedAnnotation.java:397)\n\tat org.springframework.core.annotation.TypeMappedAnnotation.asMap(TypeMappedAnnotation.java:283)\n\tat org.springframework.core.annotation.AbstractMergedAnnotation.asAnnotationAttributes(AbstractMergedAnnotation.java:193)\n\tat org.springframework.core.type.AnnotatedTypeMetadata.getAnnotationAttributes(AnnotatedTypeMetadata.java:106)

but for 0.30.0 application works fine	

**Log and Stack trace**
java.lang.IllegalArgumentException: Unresolvable class definition for class [dev.langchain4j.openai.spring.Properties]\n\tat org.springframework.util.ClassUtils.resolveClassName(ClassUtils.java:331)\n\tat org.springframework.core.annotation.TypeMappedAnnotation.adapt(TypeMappedAnnotation.java:474)\n\tat org.springframework.core.annotation.TypeMappedAnnotation.getValue(TypeMappedAnnotation.java:397)\n\tat org.springframework.core.annotation.TypeMappedAnnotation.asMap(TypeMappedAnnotation.java:283)\n\tat org.springframework.core.annotation.AbstractMergedAnnotation.asAnnotationAttributes(AbstractMergedAnnotation.java:193)\n\tat org.springframework.core.type.AnnotatedTypeMetadata.getAnnotationAttributes(AnnotatedTypeMetadata.java:106)

**To Reproduce**
upgrade dependecies to latest version

**Expected behavior**

**Please complete the following information:**
- LangChain4j version: 0.32.0
- LLM(s) used: openai, gemini
- Java version: 11
- Spring Boot version (if applicable): 2.7

**Additional context**

**Comment by langchain4j** [comment]
@hemadrio thanks a lot for reporting!
Could you please share your code so that I can try to reproduce this issue?
Thanks!

**Comment by ThomasVitale** [comment]
Starting from LangChain4j 0.32.0, the Spring support is baselined on Spring Boot 3.2 and Java 17. The error in the stack trace is probably due to the fact that the application runs on Spring Boot 2.7 and Java 11.

Spring Boot 2.7 reached end-of-life in November 2023, so it's not supported anymore and it's not receiving any security update. Same thing with Spring Boot 3.0 and 3.1. The Java 17 baseline is because Spring Boot 3.x requires that version of Java as a minimum requirement.

More information: https://spring.io/projects/spring-boot#support
