### ISSUE TITLE
[FEATURE] CohereEmbeddingModel: implement batching

### ISSUE THREAD

**Issue by langchain4j** [langchain4j/langchain4j#1442]
`CohereEmbeddingModel` currently sends all `TextSegment` that it receives in `embedAll(List<TextSegment> textSegments)` method to the Cohere API.
When the number of segments is more than 96, Cohere API responds with an error:
`status code: 400; body: {"message":"invalid request: total number of texts must be at most 96 - received 280"}`

We need to add a `maxSegmentsPerBatch` parameter (with default value 96) in the ctor/builder and batch `textSegments`.

**Comment by Apetun** [comment]
Hey i would like to work on this issue. Can you let me know where to get started?

**Comment by langchain4j** [comment]
Hi, you can take a look at `AzureOpenAiEmbeddingModel` as an example

**Comment by Apetun** [comment]
Please check and see if the implementation is right.
