### ISSUE TITLE
[FEATURE/BUG] Application cannot properly shutdown when `langchain4j` is used

### ISSUE THREAD

**Issue by InAnYan** [langchain4j/langchain4j#1454]
**Is your feature request related to a problem? Please describe.**
I've been introducing AI features to an app as a part of my Google Summer of Code 2024 project (it's not like I want to hide it, but I want to make this issue general).

During development we have noticed, that our app cannot close correctly. In fact, the main method is fully evaluated, and the app just hangs on shutdown.

During examination of stack traces and working threads, we have made a hypothesis that there were some threads that were not fully finished or closed.

It turns out, our hypothesis was true. We have found 3 places in `langchain4j` were new threads were introduced and were not closed at the end of the program:
1. `OpenAiChatModel`: situation with this class is a little bit complex, it uses a third-party package for HTTP requests. But the shutdown of the client should be handled properly too, see #1449 for details.
2. `DefaultRetrievalAugmentor`: it creates by default a `Executors.newCachedThreadPool` which doesn't close.
3. `EmbeddingModel`: in-process embedding models also create it's own thread executor, if some other is used, it would use an HTTP client (which in turn also may create a thread pool, etc.).

The problem is: thread pools, which were created in those classes, were not properly shutdown (using a `close()` or `shutdown()` methods). As a result, our app hanged on shutdown.

**Our workaround**
1. `OpenAiChatModel`: we decided to use an external package and write our implementation of `ChatLanguageModel` using [jvm-openai](https://github.com/StefanBratanov/jvm-openai). (It also doesn't provide a `shutdown()` method, so we provided a customized `HttpClient` with customized thread pool, and we managed them externally). We couldn't use `langchain4j` `OpenAiChatModel` because there is no way to supply custom HTTP client and/or `Executor`.
2. `DefaultRetrievalAugmentor`: I didn't expect it created any process. But it was possible to customize `ConversationalRetrievalChain` with `RetrievalAugmentor`. We've supplied custom `Executor` to `DerfaultRetrievalAugmentor` and managed it's lifetime externally.
3. `EmbeddingModel`: also didn't expected it's run in it's own thread. But it was possible to supply a custom `Executor` to `AllMiniLmL6V2EmbeddingModel`.

**Describe the solution you'd like**
I believe this issue is very serious in `langchain4j`. There are several architectural/code -level questions to answer. Solving this issue may introduce breaking changes.

The first thing I propose to do:
```
Add more documentation to langchain4j
```
This includes:
1. Tell which process create their own threads and/or thread pools. For example, I didn't expect that `DefaultRetrievalAugmentor` and `EmbeddingModel` run their own threads. I thought getting an embedding is a blocking call. Or maybe I don't understand well how it works internally.
2. Tell programmers that the classes that have an `Executor` doesn't shutdown them. In real app they must provide their own `Executor`s and manage their lifetime externally.

The second thing I propose to do:
```
Either 1) force programmers to supply their own Executors (no default Executors) or 2) make classes implement AutoClosable
```
Both of these ways introduce breaking changes.

**Comment by InAnYan** [comment]
About `AutoClosable` and `Executors`: it's a little bit complex question because we entering a realm of non-GC programming languages and ownership theory.

If we make `ChatLanguageModel` and/or `EmbeddingModel` to implement `AutoClosable`, there will be a strange issue:
1. If we don't supply custom `Executor`, the object will create a default one and shutdown it in `close()` method. Everything is correct.
2. If we supply a custom `Executor`, then who will be responsible of the lifetime of the `Executor`? If other code will be responsible for this, then `close()` will anyways shutdown it, which we may not expect. If the `ChatLanguageModel` and/or `EmbeddingModel` will manage the lifetime of the `Executor`, then what if I as a programmer don't like that?

That's probably why you haven't require `close()` methods.

Ah, a complex issue. I'm only a beginner programmer

**Comment by langchain4j** [comment]
@InAnYan thanks a lot for raising this issue, I will have a look at it this week.

**Comment by langchain4j** [comment]
Hi @InAnYan

> 1. OpenAiChatModel: situation with this class is a little bit complex, it uses a third-party package for HTTP requests. But the shutdown of the client should be handled properly too, see https://github.com/langchain4j/langchain4j/pull/1449 for details.

Do you experience this problem with `OpenAiChatModel` or `OpenAiStreamingChatModel`?
BTW, `OpenAiStreamingChatModel` shuts down automatically in about 1 minute.

**Comment by InAnYan** [comment]
I had issues with `OpenAiChatModel`, haven't tried streaming one yet.

Still, 1 minute shutdown may be okay from user side,  but architecturally seems not good

**Comment by langchain4j** [comment]
@InAnYan could you share your repo so that I can reproduce the issue with `OpenAiChatModel`?

**Comment by InAnYan** [comment]
@langchain4j here is the branch of the project I work on: https://github.com/JabRef/jabref/tree/ai-pr-1

I would like to provide an MWE, but, who knows, maybe there won't be issues.

In this branch all of the issues I mentioned are resolved.

You can try to comment shutdown of `ExecutorService`s in classes like: `ChatLanguageModel`, `EmbeddingModel`, and (if I remember correctly) `AiChat`.

If you comment code inside `close()`, you will see that the app hangs on shutdown

**Comment by langchain4j** [comment]
Can't launch it, getting this error:

```
Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not resolve one.jpro.platform:jpro-mdfx:0.3.3-SNAPSHOT.
     Required by:
         project :
      > Could not resolve one.jpro.platform:jpro-mdfx:0.3.3-SNAPSHOT.
         > Unable to load Maven meta-data from https://sandec.jfrog.io/artifactory/repo/one/jpro/platform/jpro-mdfx/0.3.3-SNAPSHOT/maven-metadata.xml.
            > Could not HEAD 'https://landing.jfrog.com/reactivate-server/sandec'. Received status code 409 from server: Conflict
   > Could not resolve one.jpro.jproutils:tree-showing:0.2.2.
     Required by:
         project : > com.dlsc.gemsfx:gemsfx:2.32.0
      > Could not resolve one.jpro.jproutils:tree-showing:0.2.2.
         > Could not get resource 'https://sandec.jfrog.io/artifactory/repo/one/jpro/jproutils/tree-showing/0.2.2/tree-showing-0.2.2.pom'.
            > Could not HEAD 'https://landing.jfrog.com/reactivate-server/sandec'. Received status code 409 from server: Conflict

```

Any tips how to fix it? Thanks!

**Comment by InAnYan** [comment]
Ah, sorry, you should begin from the start:
https://devdocs.jabref.org/getting-into-the-code/guidelines-for-setting-up-a-local-workspace/

There are many compile parameters to setup

**Comment by koppor** [comment]
> Ah, sorry, you should begin from the start: [devdocs.jabref.org/getting-into-the-code/guidelines-for-setting-up-a-local-workspace](https://devdocs.jabref.org/getting-into-the-code/guidelines-for-setting-up-a-local-workspace/)
> 
> There are many compile parameters to setup

Only for IntelliJ. Here, the command line is used. - Especially gradle as build tool.

Meaning: `./gradlew compileJava` shoud work out of the box. Our CI pipeline also just runs gradle.

> `Could not resolve one.jpro.platform:jpro-mdfx:0.3.3-SNAPSHOT.`

Fixed. I removed the dependency. It was a left over of some tries some weeks ago.

> `Could not resolve one.jpro.jproutils:tree-showing:0.2.2.`

Oh, maybe https://sandec.jfrog.io/artifactory/repo/ had a hickup. That dependency is only available at that repository.

I hope that a retry solves the issue.

(I tried locally with `gradlew --refresh-dependencies run` and it worked.

**Comment by langchain4j** [comment]
@koppor this helped, I was able to start the app, thank you!
What is the easiest way to trigger LLM/embedding models?

**Comment by InAnYan** [comment]
@langchain4j Just go to Preferences -> AI
And here you need to turn on `Enable chatting with PDF files` and then write you OpenAI API key

**Comment by langchain4j** [comment]
I will check the problem with `OpenAiChatModel` a bit later, but I have addressed problems with `DefaultRetrievalAugmentor` and in-process `EmbeddingModel`s in these PRs, please take a look:
- https://github.com/langchain4j/langchain4j/pull/1479
- https://github.com/langchain4j/langchain4j-embeddings/pull/34

**Comment by InAnYan** [comment]
@langchain4j The PRs seems good! I see they are made without breaking changes.

Though, I've already used the workaround I proposed, so I can't test them.

Also I can't test the embedding generation, because I switched from `ONNX` to `Deep Java Library` because of distribution size.

But I think the workarounds are good.

I believe that this is more architectural problem, because of absence of `close()` methods, but solving this will introduce breaking changes. I think some documentation note should be added :smile:

**Comment by langchain4j** [comment]
@InAnYan thanks for the review!

> I believe that this is more architectural problem, because of absence of close() methods, but solving this will introduce breaking changes.

I am not sure I understand the "architectural" part. The `close()` methods can be added, but why? Those components are now "auto-closeable" by default, I am not sure it is a good idea to force users to call `close()` method. But if one wants to manage `Executors` manualy and call `close()`, it can be done by specifying a custom `Executor`.

> I think some documentation note should be added 😄

Docu was updated in those PRs, is anything else missing?

**Comment by InAnYan** [comment]
Ah, I see, sorry. Documentation is great!
