### ISSUE TITLE
[BUG] NPE when GoogleCustomWebSearchEngine search results is empty

### ISSUE THREAD

**Issue by gpr-indevelopment** [langchain4j/langchain4j#1458]
**Describe the bug**
I have added `GoogleCustomWebSearchEngine` as a `ContentRetriever` in my app (no router). An NPE (null pointer exception) is currently being thrown whenever a user input gets sent to the search engine and the search results are empty. This does not happen if the search engine returns at least one result.

**Log and Stack trace**
`Cannot invoke "java.util.List.stream()" because the return value of "com.google.api.services.customsearch.v1.model.Search.getItems()" is null`

```java
// GoogleCustomWebSearchEngine.java
return WebSearchResults.from(
                searchMetadata,
                WebSearchInformationResult.from(
                        Long.valueOf(getOrDefault(search.getSearchInformation().getTotalResults(), "0")),
                        !isNullOrEmpty(search.getQueries().getRequest())
                                ? calculatePageNumberFromQueries(search.getQueries().getRequest().get(0)) : 1,
                        searchInformationMetadata.isEmpty() ? null : searchInformationMetadata),
                // Error happens here, getItems is null
                search.getItems().stream()
                        .map(result -> WebSearchOrganicResult.from(
                                result.getTitle(),
                                URI.create(result.getLink()),
                                result.getSnippet(),
                                null, 
                                toResultMetadataMap(result, searchTypeImage)
                        )).collect(toList()));
```

**To Reproduce**
Setup a Google search engine API key that can search the entire web, and [configure it as a`ContentRetriever` to the assistant](https://docs.langchain4j.dev/tutorials/rag#web-search-content-retriever). Interact with the assistant using an input that will not generate any search results such as "abasduashduahduasd". It will throw the error.

**Expected behavior**
Empty search results from google search API should not trigger any errors. It should only result in no additional context to the LLM during RAG.

**Please complete the following information:**
- LangChain4j version: 0.32.0
- LLM(s) used: OpenAI gpt-4o
- Java version: 17
- Spring Boot version (if applicable): 3.3.0

**Comment by langchain4j** [comment]
@gpr-indevelopment thanks a lot for reporting!

@czelabueno could you please take a look?

**Comment by czelabueno** [comment]
hey @gpr-indevelopment , thanks to report it. In fact, I'm not expected that someone search results by "abasduashduahduasd" :) but yeah make sense expected behavior. I'll be working these days to fix it.
