### ISSUE TITLE
[FEATURE] Web Search Engine / Tool

### ISSUE THREAD

**Issue by JCASTANO** [langchain4j/langchain4j#146]
Hello good evening, thank you for this project, it's great

I would like to propose the inclusion of the following feature

give internet access with serpapi

It would be great to chain with internet access

https://medium.com/@rubentak/give-openai-models-with-internet-access-using-langchain-7d5849f33e03

**Comment by IrynaLiubarska** [comment]
Hi @JCASTANO, serpapi integration is already in our backlog. We'll give you feedback, as soon as it will be released.

**Comment by iaceiba** [comment]
Hello, any news regarding this topic? @IrynaLiubarska

**Comment by IrynaLiubarska** [comment]
Hi @iaceiba serpapi integration is still in backlog sorry, btw contributions are welcome :)

**Comment by langchain4j** [comment]
Related:
https://github.com/langchain4j/langchain4j/pull/676
https://github.com/langchain4j/langchain4j/pull/642
https://github.com/langchain4j/langchain4j/pull/641

**Comment by langchain4j** [comment]
Google and Tavily web search has been implemented, some other search engines are in progress
