### ISSUE TITLE
[FEATURE] Compatible with switching between different vector dimensions

### ISSUE THREAD

**Issue by yushengliao** [langchain4j/langchain4j#1462]
Caused by: io.milvus.exception.ParamException: Incorrect dimension for field 'vector': the no.0 vector's dimension: 1024 is not equal to field's dimension: 4096

In my application, it is possible to switch between different embedding models.
What solution should be used to handle the different sizes of vector dimensions generated by different embedding models?
Langchain4j doesn't seem to provide such a solution

**Comment by langchain4j** [comment]
Hi @yushengliao, if you change the embedding model, you need to re-create the embedding store index (milvus in this case) and re-embed all the data in it again. I am not sure what solution are you looking for exactly.

**Comment by yushengliao** [comment]
> Hi @yushengliao, if you change the embedding model, you need to re-create the embedding store index (milvus in this case) and re-embed all the data in it again. I am not sure what solution are you looking for exactly.

I am developing an application similar to 'dify', where each knowledge base can use vector models from different dimensions. However, if they are all saved to milvus, the set of milvus seems to only have fields from one dimension. At present, there is no good solution for langchain4j

**Comment by langchain4j** [comment]
@yushengliao you could use a separate collection with specific vector dimension for each knowledge base:

```java
    MilvusEmbeddingStore embeddingStore1 = MilvusEmbeddingStore.builder()
            ...
            .collectionName("collection_1")
            .dimension(1024)
            .build();
            
    MilvusEmbeddingStore embeddingStore2 = MilvusEmbeddingStore.builder()
            ...
            .collectionName("collection_2")
            .dimension(4096)
            .build();
```
