### ISSUE TITLE
[FEATURE] AzureAiSearchEmbeddingStore - "remove" operation

### ISSUE THREAD

**Issue by vprudnikov** [langchain4j/langchain4j#1467]
Hello!

I wonder when `AzureAiSearchEmbeddingStore` is going to implement the `EmbeddingStore#remove` and `EmbeddingStore#removeAll` operations.

Thank you!

**Comment by Devansh-Rastogi** [comment]
@langchain4j Hey, is it up for grab?
If yes, i would like to take it

**Comment by Devansh-Rastogi** [comment]
@langchain4j , how do i test my changes once done??
Any reference would be helpful

**Comment by langchain4j** [comment]
Hi @Devansh-Rastogi, it seems like noone works on it, so feel free to take it!

As for testing, the best would be to have an Azure account and deploy Azure search service.
