### ISSUE TITLE
[BUG] ServiceOutputParser sometimes fails to map JSON output from gpt-4o to a POJO

### ISSUE THREAD

**Issue by dionoid** [langchain4j/langchain4j#1471]
**Describe the bug**
`ServiceOutputParser` sometimes fails to parse the JSON output from gpt-4o when mapping to a POJO. While the `outputFormatInstructions` method clearly states "You must answer strictly in the following JSON format: ...", for some reason gpt-4o sometimes returns the JSON inside a markdown code block. I guess gpt-4o really likes markdown :)

Example response from gpt-4o is this case:

\`\`\`json
{
  "detectedLanguage" : "Dutch"
}
\`\`\`

**Workaround**
A workaround is to add to the prompt: "Only return valid JSON, no markdown.". Together with the instructions added by `ServiceOutputParser.outputFormatInstructions`, this fixes the problem.

**Log and Stack trace**
java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $

**To Reproduce**
Use one of the POJO mapping examples from https://www.sivalabs.in/langchain4j-ai-services-tutorial/

**Expected behavior**
No exception :)

**Please complete the following information:**
- LangChain4j version: 0.32.0
- LLM(s) used: gpt-4o
- Java version: 17
- Spring Boot version (if applicable): 3.3.1

**Comment by langchain4j** [comment]
Hi @dionoid, thank you for reporting!
I will close this issue as there is https://github.com/langchain4j/langchain4j/issues/1446 already.
The fix should be quite easy, would you be up to submit a PR?
Thanks!

**Comment by PrimosK** [comment]
@langchain4j I guess you meant to mention #1446 in your previous comment.

**Comment by langchain4j** [comment]
@PrimosK yep, corrected, thanks!

**Comment by dionoid** [comment]
As @abbas-gadhia mentioned [here](https://github.com/langchain4j/langchain4j/issues/859#issuecomment-2133123587), enabling the JSON-mode of the LLM solves the issue. So maybe this should be added to documentation?

**Comment by langchain4j** [comment]
@dionoid this is already documented: https://docs.langchain4j.dev/tutorials/ai-services#json-mode

**Comment by dionoid** [comment]
@langchain4j you are right; I must have overlooked this. I'm closing this issue now.
