### ISSUE TITLE
[FEATURE] chunkOverlap

### ISSUE THREAD

**Issue by JCASTANO** [langchain4j/langchain4j#148]
thanks for this great project

I would like to propose the inclusion of the chunkOverlap parameter in the document splitters, it is a necessary function to increase the possibility of a better response from the vector store

https://js.langchain.com/docs/modules/data_connection/document_transformers/

**Comment by chcodex** [comment]
+1

**Comment by thanh-p** [comment]
Hi @langchain4j, have you worked on this yet?  If not, I would like to take charge.

**Comment by langchain4j** [comment]
Hi, sorry for the late reply, I am working on this

Am Sa., 16. Sept. 2023 um 12:48 Uhr schrieb Thanh P <
***@***.***>:

**Comment by JCASTANO** [comment]
it was include in the lastest version, thank you so much
