### ISSUE TITLE
[BUG] A list of objects is not serialised correctly 

### ISSUE THREAD

**Issue by G0dC0der** [langchain4j/langchain4j#1480]
In a recent release, tool parameters support POJOs. I am however having problem getting it to work when the POJO is wrapped in a collection.

**Describe the bug**
Here is what happens when a tool param is a collection of POJOS: The contents of data is valid, but the structure is wrong. Meaning, if the param is `java.util.List<MyPojo>`, the actual object is an ArrayList, containing LinkedTreeMap. The contents of the map is correct though(meaning keys match those of MyPojo).

**Log and Stack trace**
n/a

**To Reproduce**
```java
    public record AiVariant(String type, String value) {}

    @Tool
    public void saveVariants(
        List<AiVariant> variants
    ) { }

    @Bean
    public ChatLanguageModel openAiChatModel() {
        return OpenAiChatModel.builder()
            .apiKey(openAiApiKey)
            .responseFormat("json_object")
            .build();
    }

    //The RAG is probably not needed for this example. 
    @Bean
    public AiAssistant aiAssistant(ChatLanguageModel openAiChatModel, ContentRetriever rag, ContentTools contentTools) {
        return AiServices.builder(AiAssistant.class)
            .chatLanguageModel(openAiChatModel)
            .tools(contentTools)
            .chatMemory(MessageWindowChatMemory.withMaxMessages(10))
            .contentRetriever(rag)
            .build();
    }
...

public interface AiAssistant {
    @SystemMessage("Json")
    String chat(String message);
}

...

@Component
public class Test implements CommandLineRunner {
   
    @Autowired private AiAssistant aiAssistant;

    @Override
    public void run(final String... args) throws Exception {
        var chat = aiAssistant.chat("Save variants with type jurisdiction and value EU");

```

**Current vs Expected behavior**
_Current behavior_:
![Screenshot 2024-07-17 at 17 08 42](https://github.com/user-attachments/assets/a89d9d86-01b3-4f2c-8649-9425a6e648ca)

_Expected behavior_: A list of objects of type "AiVariants", and not LinkedTreeMap.

**Please complete the following information:**
- LangChain4j version:
langchain4j, langchain4j-open-ail & langchain4j-easy-rag: 0.32.0
- LLM(s) used: 
Default version
- Java version:
JDK 21 
- Spring Boot version (if applicable): 
3.3.1

**Additional context**

**Comment by langchain4j** [comment]
HI @G0dC0der, thanks for reporting!

@gs-snagaraj would you like to take this one please?

**Comment by gs-snagaraj** [comment]
Hi @langchain4j 

Have fixed it.
please check PR https://github.com/langchain4j/langchain4j/pull/1495

**Comment by G0dC0der** [comment]
There is a workaround though. Wrap the collection around another POJO.
