### ISSUE TITLE
[FEATURE] Support for GROQ

### ISSUE THREAD

**Issue by amirkhan-ak-sf** [langchain4j/langchain4j#1489]
**Is your feature request related to a problem? Please describe.**
Performance related support for Groq (https://groq.com/)

**Describe the solution you'd like**
Add groq support for LangChain4J

**Describe alternatives you've considered**
-
**Additional context**
-

**Comment by langchain4j** [comment]
Hi, groq can be used with `langchain4j-open-ai` module:

```java
ChatLanguageModel model = OpenAiChatModel.builder()
    .baseUrl("https://api.groq.com/openai/v1")
    .apiKey("gsk_...")
    .modelName("llama3-8b-8192")
    .build();
```

**Comment by amirkhan-ak-sf** [comment]
Thank You, will try it out!

**Comment by mbofb** [comment]
to have stated this explcitly: this works for the ChatLanguageModel - not with OpenAiLanguageModel
