### ISSUE TITLE
[FEATURE] PromptTemplate supports multiple templating engines.

### ISSUE THREAD

**Issue by jiangsier-xyz** [langchain4j/langchain4j#149]
I have noticed that PromptTemplate currently uses Mustache directly to generate the final string from a template string. However, in the real world, Python f-strings and Jinja2 are widely used to describe prompt templates. I suggest abstracting an interface for the template engine and integrating it into PromptTemplate to handle different styles of template strings (of course we can have a default handler).

For Mustache, we can use the following maven package:
```
<dependency>
    <groupId>com.github.spullara.mustache.java</groupId>
    <artifactId>compiler</artifactId>
</dependency>
```

For Python f-strings, we can use the following maven package:
```
<dependency>
    <groupId>com.github.squidfunk</groupId>
    <artifactId>python-string-format</artifactId>
</dependency>
```

For Jinja2/Jinjava, we can use the following maven package:
```
<dependency>
    <groupId>com.hubspot.jinjava</groupId>
    <artifactId>jinjava</artifactId>
</dependency>
```
(Since it uses {{...}} style placeholders like Mustache, maybe we don't need to integrate it.)

**Comment by jiangsier-xyz** [comment]
Oops...ChatGPT told me about com.github.squidfunk:python-string-format, but it doesn't exist...
Now I'm using regex ways to resolve f-string templates.

**Comment by langchain4j** [comment]
There is a `PromptTemplateFactory` SPI with default implementation `DefaultPromptTemplateFactory`.

One can implement `PromptTemplateFactory` interface and plug in their own templating engine.
