### ISSUE TITLE
[FEATURE] Change default OpenAI Model to GPT-4o-mini

### ISSUE THREAD

**Issue by zambrinf** [langchain4j/langchain4j#1497]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
From [gpt-3-5-turbo](https://platform.openai.com/docs/models/gpt-3-5-turbo)
> As of July 2024, gpt-4o-mini should be used in place of gpt-3.5-turbo, as it is cheaper, more capable, multimodal, and just as fast.

To [GPT-4o mini](https://platform.openai.com/docs/models/gpt-4o-mini)

**Describe alternatives you've considered**

**Additional context**
I have ran AiServicesIT tests with 4o mini and just one test fails, but the instructions are a bit ambiguous, changing to a clearer instruction make it pass.

**Comment by zambrinf** [comment]
Related: #1102

**Comment by langchain4j** [comment]
Sounds good, the only problem it is a breaking change...

**Comment by zambrinf** [comment]
@langchain4j how should we address this? There are also some deprecations that are failing tests, you can take a look at the PR

**Comment by langchain4j** [comment]
Good question. It seems like having a default value for the model was not the best idea 😅 
Newer and better models will keep releasing... So making a breaking change now and be forced to do the same every year or so is probably not the right thing to do. Perharps we should get rid of the default value and enforce users to set it explicitly. First step would be to update all examples and documentation and set model explicitly everywhere. WDYT?

Deprecations are ok, let's merge them

**Comment by zambrinf** [comment]
@langchain4j I removed the changes to the default model from the PR

**Comment by langchain4j** [comment]
We will get rid of default values for model names in the near future
