### ISSUE TITLE
[FEATURE]  Using tools to return directly

### ISSUE THREAD

**Issue by magi-wang** [langchain4j/langchain4j#150]
Often, it can be desirable to have a tool output returned directly to the user, if it’s called. You can do this easily with LangChain by setting the return_direct flag for a tool to be True.

**Additional context**

https://python.langchain.com/docs/modules/agents/tools/custom_tools#using-tools-to-return-directly

**Comment by langchain4j** [comment]
@doucheng how do you plan to distinguish between response from LLM (if it decided to _not_ execute a tool) and a tool execution result? What are your expectations regarding chat memory? The user->llm->tool->llm->user interaction inside the memory will be unfinished...

**Comment by langchain4j** [comment]
Duplicate of https://github.com/langchain4j/langchain4j/issues/124
