### ISSUE TITLE
OpenAiStreamingChatModel uses the third-party base_url, it does not work

### ISSUE THREAD

**Issue by IMYR666** [langchain4j/langchain4j#1511]
code:

``` java
    public interface Assistant2 {
        TokenStream chat(String chatMessage);
    }
   @Test
    void langChain4jAiServicesStreamTest() {
        String apiKey = "sk-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        StreamingChatLanguageModel openAiChatModel = OpenAiStreamingChatModel.builder()
                .apiKey(apiKey)
                .modelName(OpenAiChatModelName.GPT_4_O)
                .baseUrl("https://api.3rd-party.com/v1/")
                .build();
        Assistant2 assistant = AiServices.create(Assistant2.class, openAiChatModel);
        TokenStream tokenStream = assistant.chat("Tell me a joke");
        tokenStream.onNext(new Consumer<String>() {
                    @Override
                    public void accept(String s) {
                        System.out.println(1123);
                        System.out.println(s);
                    }
                })
                .onComplete(System.out::println)
                .ignoreErrors()
                .start();
    }
```

**Describe the bug**

After running the above code in the test module of SpringBoot3, there is neither an error thrown nor any output information; it appears that the onNext method is not being called. Replacing https://api.3rd-party.com/v1/ with https://baidu.com results in the same phenomenon. Theoretically, a request to https://baidu.com/chat/completions should result in an error, such as indicating that there is no such API or returning a 4XX error code.

The lack of any indication has left me uncertain whether this behavior is due to a bug or a configuration issue on my part.

I am confident that my third-party base_url is accessible, because when I switch to OpenAiChatModel, the content is outputted correctly.

**Log and Stack trace**

**To Reproduce**

**Expected behavior**

**Please complete the following information:**
- LangChain4j version: 0.32.0
- LLM(s) used: openai
- Java version: jdk17
- Spring Boot version (if applicable): 3.1.1

**Additional context**

**Comment by langchain4j** [comment]
Hi @IMYR666, you are calling `.ignoreErrors()`, this might be the reason you don't see any errors. Can you change it to `.onError()` and see if it helps?

You can also activate logs on the model:
```java
OpenAiStreamingChatModel.builder()
                ...
                .logRequests(true)
                .logResponses(true)
                .build();
```

**Comment by IMYR666** [comment]
``` java

@Test
    void langChain4jAiServicesStreamTest() {
         String apiKey = "sk-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        StreamingChatLanguageModel openAiChatModel = OpenAiStreamingChatModel.builder()
                .apiKey(apiKey)
                .logRequests(true)
                .logResponses(true)
                .modelName(OpenAiChatModelName.GPT_4_O)
                .baseUrl("https://api.3rd-party.com/v1/")
                .build();
        Assistant2 assistant = AiServices.create(Assistant2.class, openAiChatModel);
        TokenStream tokenStream = assistant.chat("Tell me a joke");
        tokenStream.onNext(new Consumer<String>() {
                    @Override
                    public void accept(String s) {
                        System.out.println(1123);
                        System.out.println(s);
                    }
                })
                .onComplete(System.out::println)
                .onError(System.out::println)
                .start();
    }
```

thank you for your reply. I tried using onError, logRequests, and logResponses, but the result is still the same: no errors are reported, and no messages are outputted. 

However, when I integrated the code into the SpringBoot production project, messages were returned, which is quite strange.

Initially, I wrote it in the Test module to quickly verify whether LangChain meets the requirements without modifying the business code. Instead, I ended up wasting time due to this unexpected issue🤣.

**Comment by langchain4j** [comment]
When logging is configured correctly, you should at least see the request. If you don't see anything at all, it seems that you do not have any slf4j log backend configured, you can add this and run tests again:

 ```
            <dependency>
                <groupId>org.tinylog</groupId>
                <artifactId>tinylog-impl</artifactId>
                <version>2.6.2</version>
            </dependency>

            <dependency>
                <groupId>org.tinylog</groupId>
                <artifactId>slf4j-tinylog</artifactId>
                <version>2.6.2</version>
            </dependency>
```

Spring Boot comes with logging configured out of the box, this might be the reason why it worked.
