### ISSUE TITLE
[Documentation] - Skeleton for documentation

### ISSUE THREAD

**Issue by clun** [langchain4j/langchain4j#152]
#### Context
After chatting with the owners of the framework, we realized it was a good moment to start providing more documentation. 
As I have set up documentation using MKDocs + Materials previously I wanted to propose a template to start from.
So here it goes.

![Screenshot 2023-08-31 at 14 12 18](https://github.com/langchain4j/langchain4j/assets/726536/c998013a-1530-4159-b520-725889837a27)

#### If you want to see immediately what it looks like 
https://clun.github.io/langchain4j-docs

#### Where is the code ?
https://github.com/clun/langchain4j-docs

#### How can I run it locally ?

- You need to install python.

- Clone the project
```
git clone https://github.com/clun/langchain4j-docs.git
cd langchain4j-docs
```

- Install the dependencies

```
python3 -m pip install --upgrade pip     # install pip
python3 -m pip install mkdocs            # install mkdocs 
python3 -m pip install mkdocs-material   # install material theme
python3 -m pip install mkdocs-git-revision-date-plugin # install git revision date
python3 -m pip install mkdocs-video # install git revision date
python3 -m pip install mkdocs-video # install git revision date
```

- Start locally and see site available at http://localhost:8000

```
mkdocs serve
```

- Any modification in the files is immediately hot reloaded and you see the updates

## How to we deploy ? 

That is the neat part. With a `github action` [here](https://github.com/clun/langchain4j-docs/blob/main/.github/workflows/build-and-publish.yml) on any commit or pull request accepted the webiste is regenerated in the gh-pages !

## How do you get the code in the organization ?

- If you are happy with the skeleton I transfer the ownership to this organization

- it would be nice to add me `CLUN` to keep contributing.

**Comment by langchain4j** [comment]
Hi @clun thank you so much! I will play with it a bit and will start adding content.

**Comment by clun** [comment]
Of course.

- I requested the ownership transfer to this org.

- the page `cheat.md` https://clun.github.io/langchain4j-docs/cheat/ help to know what is doable in the markdown.

**Comment by LizeRaes** [comment]
@clun Thank you so much for starting this website, looking great! We're happy to extend and complete it, getting @Martin7-1 on board here too

After a close look, I see following action items:

- on the 'Getting Started' page ( https://clun.github.io/langchain4j-docs/pages/documentation/introduction/ ) 
   I suggest adding more examples to 'Getting Started', next to HelloWorld, suggestions:
		* Chat
		* Streaming
		* Classifier
		* RAG
		* Using tools / calling functions
		* Image generation
- I would move modules to it's own tab, and add (description, example, tutorial)
		* Image Creation 
		* Tools / function calling
		* AI Services
		* (to be removed?) Agents (I don't think they are supported yet)
- under 'Integrations' ( https://clun.github.io/langchain4j-docs/pages/integrations/ ), include the lists of supported
		* model integrations (language models + image models)
		* document parsers
		* vector/embedding stores
		* embedding models
		* code execution APIs
		* frameworks (GraalVM?, Quarkus, Spring Boot, Azure OpenAI SDK, anything missing?)
		(optionally add examples or tutorials for each)
- change 'Sample Codes' to 'Code Examples'? https://clun.github.io/langchain4j-docs/pages/samples/
	Add more in-depth examples (invite contributors to put their code there, we can curate), also link the examples from https://github.com/langchain4j/langchain4j-examples and optionally turn it into tutorials
- There are a couple of blocks on the start page, we could make them clickable and link to doc/examples
	* Assistant and ChatBot
	* Vector Stores
	* Embeddings Computation
	* Chains
	* (to be added) AI Services
	* (to be added) Image Generation
- ensure the website stays up-to-date: make it update relevant fields/pages automatically with every new release, and keep track of the things that have to be manually reviewed/updated every release
- if we write tutorials, we could publish some on eg. Baeldung, Medium (langchain4j channel: https://medium.com/@langchain4j ), ... so people do find them when searching for things like
	* 'how to connect to gpt4/LLMs with java'
	* 'how to use AI in java/in the backend'
	* 'generate AI images via java'

Note that quite some examples already exist on https://github.com/langchain4j/langchain4j-examples

I'll get started on listing the integrations.

**Comment by langchain4j** [comment]
Hi @clun, could you please update us on the status of the transfer? Mabe it will be simpler to just copy-paste it? Thanks

**Comment by LizeRaes** [comment]
Closing because covered in #429
