### ISSUE TITLE
[FEATURE] Ability to specify dimensions parameter in AzureOpenAiEmbeddingModel

### ISSUE THREAD

**Issue by denistsyplakov** [langchain4j/langchain4j#1528]
Currently Embedding Options has dimensions parameter but I cannot specify it. See code below

```Java

    private Response<List<Embedding>> embedTexts(List<String> texts) {

           // I cannot change dimensions parameter
            EmbeddingsOptions options = new EmbeddingsOptions(batch);
            Embeddings response = client.getEmbeddings(deploymentName, options);
```

Can you please add  ability to specify dimensions. I want to try text-embedding-3-large with pg vector but default vector size for text-embedding-3-large is 3072  but pgvector can have only 2000 dimensions

**Comment by Devansh-Rastogi** [comment]
@denistsyplakov do you want to set dimension as part of EmbeddingsOptions Constructor??
I guess you can use setter to set the dimensions once you create the EmbeddingsOptions object.

**Comment by langchain4j** [comment]
I guess what @denistsyplakov means is that there is no way to specify `dimensions` when creating `AzureOpenAiEmbeddingModel`.

For example, `OpenAiEmbeddingModel` builder has this property which is then propagated to OpenAI.

**Comment by Devansh-Rastogi** [comment]
so, a property is required for AzureOpenAiEmbeddingModel which can be used in embedding options?

**Comment by langchain4j** [comment]
Yes, `AzureOpenAiEmbeddingModel` builders/ctors should allow setting `dimensions` property which should be propagated into `EmbeddingsOptions`

**Comment by Devansh-Rastogi** [comment]
Ok, Got it 
@langchain4j , could you please assign it to me, will work on it

**Comment by Devansh-Rastogi** [comment]
Is it possible to use models other than the one mentioned here..

![image](https://github.com/user-attachments/assets/30521da8-3f7e-4620-bd70-ae517572f7cc)

**Comment by Devansh-Rastogi** [comment]
@langchain4j,  @denistsyplakov I have made the necessary code changes for setting the dimensions in EmbeddingOptions, but unable to test it on my end as I tried Azure OpenAI Service to deploy the models (tried with text-embedding-3-large, text-embedding-3-small and text-embedding-ada-002) and dimensions of these models can't be altered. Also tried deploying the service to US East, Central India, US West, etc, didnt get any embedding model that is not defined in the codebase for embedding..

So, is there a way i can test this for the model whose configuration is not defined in the codebase?

**Comment by langchain4j** [comment]
@Devansh-Rastogi please submit a draft PR and I will try to run tests on my end

**Comment by Devansh-Rastogi** [comment]
submitted the draft PR. I have added an example, but i guess in order to test it you need to change the model
