### ISSUE TITLE
[BUG]  MONGODB Embedding Stores not working correctly

### ISSUE THREAD

**Issue by amirkhan-ak-sf** [langchain4j/langchain4j#1532]
Hi,

I try to build a knowledge store with Pinecone and Mongodb, similar which I did successfully for Chroma, Weaviate, Elastic and Milvus. However with Mongodb I don't get any matches. 

I have 2 scripts. The first one creates embedding in the store. 

```
        TextSegment segment1 = TextSegment.from("I like football.");
        Embedding embedding1 = embeddingModel.embed(segment1).content();
        embeddingStore.add(embedding1, segment1);

        TextSegment segment2 = TextSegment.from("The weather is good today.");
        Embedding embedding2 = embeddingModel.embed(segment2).content();
        embeddingStore.add(embedding2, segment2);  

```

Later on I try to query with a question, but the size of the matching list is empty. 

```
import dev.langchain4j.data.embedding.Embedding;
import dev.langchain4j.data.segment.TextSegment;
import dev.langchain4j.model.embedding.AllMiniLmL6V2EmbeddingModel;
import dev.langchain4j.model.embedding.EmbeddingModel;
import dev.langchain4j.model.openai.OpenAiEmbeddingModel;
import dev.langchain4j.store.embedding.EmbeddingMatch;
import dev.langchain4j.store.embedding.EmbeddingSearchRequest;
import dev.langchain4j.store.embedding.EmbeddingStore;
import dev.langchain4j.store.embedding.chroma.ChromaEmbeddingStore;
import dev.langchain4j.store.embedding.mongodb.IndexMapping;
import dev.langchain4j.store.embedding.mongodb.MongoDbEmbeddingStore;

import com.mongodb.MongoClientSettings;
import com.mongodb.client.MongoClient;
import com.mongodb.client.MongoClients;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.model.Filters;
import java.util.List;

import org.apache.commons.compress.utils.Sets;

import static java.lang.String.format;


public class ChromaEmbeddingStoreExample {
    public static void main(String[] args) {

        MongoClient client;

        String username = "amirkhantest";
        String password = "...";
        String host = "cluster0.frw123123s.mongodb.net";
        String connectionString = format("mongodb+srv://%s:%s@%s/?retryWrites=true&w=majority", username, password, host);
        client = MongoClients.create(connectionString);

        EmbeddingModel embeddingModel = OpenAiEmbeddingModel.builder()
        .apiKey("...")
        .modelName("text-embedding-ada-002")
        .build();

        IndexMapping indexMapping = IndexMapping.builder()
        .dimension(embeddingModel.dimension())
        .metadataFieldNames(Sets.newHashSet("test-key"))
        .build();

        EmbeddingStore<TextSegment> embeddingStore = MongoDbEmbeddingStore.builder()
            .fromClient(client)
            .databaseName("test")
            .collectionName("test")
            .indexName("default")
            .indexMapping(indexMapping)
            .build();



        Embedding queryEmbedding = embeddingModel.embed("What is the capital of Switzerland?").content();
        List<EmbeddingMatch<TextSegment>> relevant = embeddingStore.findRelevant(queryEmbedding, 1, 0);
        List<EmbeddingMatch<TextSegment>> relevant2 = embeddingStore.findRelevant(queryEmbedding,3);


        System.out.println(relevant.size());
        EmbeddingMatch<TextSegment> embeddingMatch = relevant.get(0);
        System.out.println(queryEmbedding); // 0.8144288493114709

        queryEmbedding.normalize();
        System.out.println(queryEmbedding); // 0.8144288493114709

        System.out.println(embeddingMatch.score()); // 0.8144288493114709
        System.out.println(embeddingMatch.embedded().text()); // I like football.

    }
}
```

If there is a working example for Mongodb it would be great. 

Thanks
Amir

**Comment by Heezer** [comment]
@amirkhan-ak-sf Hi Amir, there are two working examples of MongoDB integration which use the local instance via container:
- https://github.com/langchain4j/langchain4j/blob/main/langchain4j-mongodb-atlas/src/test/java/dev/langchain4j/store/embedding/mongodb/MongoDbEmbeddingStoreLocalIT.java
- https://github.com/langchain4j/langchain4j/blob/main/langchain4j-mongodb-atlas/src/test/java/dev/langchain4j/store/embedding/mongodb/MongoDbEmbeddingStoreFilterIT.java

**Comment by langchain4j** [comment]
@amirkhan-ak-sf this seems to be the same "problem" you faced with other embedding stores. Try to wait a bit (e.g. 5 seconds) between adding embeddings to the store and searching.

**Comment by amirkhan-ak-sf** [comment]
I couldn't get it work with MongoDB, I waited 1 minute. However I was able to use it with PGVectors.

**Comment by langchain4j** [comment]
@amirkhan-ak-sf do you get some errors or just empty list?

**Comment by amirkhan-ak-sf** [comment]
relevant.size() = 0 always

**Comment by langchain4j** [comment]
@amirkhan-ak-sf can you see added embeddings in the mongodb atlas console?

![image](https://github.com/user-attachments/assets/559c241e-7863-4fa1-a2e6-751a64032df8)

**Comment by amirkhan-ak-sf** [comment]
yes, embeddings are added and the embedding model is the same. 
<img width="1507" alt="image" src="https://github.com/user-attachments/assets/ffc4178f-d6ec-471a-acb1-9a8f78453c4d">

**Comment by langchain4j** [comment]
It seems that you specified incorrect database name and collection name:

```java 
EmbeddingStore<TextSegment> embeddingStore = MongoDbEmbeddingStore.builder()
            .fromClient(client)
            .databaseName("test") <- should probably be "langchain4j"?
            .collectionName("test") <- should probably be "langchain4j"?
            .indexName("default") <- make sure this is correct as well
            .indexMapping(indexMapping)
            .build();
```

**Comment by amirkhan-ak-sf** [comment]
I just "anonymised" it for the post. I have databaseName langchain4j and also for collection. For index I have default. Where Can I find the index name in Mongo? Maybe that's the issue?

**Comment by amirkhan-ak-sf** [comment]
This is the index I have 
<img width="1031" alt="image" src="https://github.com/user-attachments/assets/59e8698b-e33f-4834-8a18-c472513def60">

I guess default is correct.

**Comment by langchain4j** [comment]
I have the same and it works 🤔 

![image](https://github.com/user-attachments/assets/c9a2b5de-2388-40df-be0a-c48f4154749f)

**Comment by langchain4j** [comment]
Maybe try playing with `maxResultRatio` parameter?

cc @Martin7-1

**Comment by amirkhan-ak-sf** [comment]
Could it be related to the different dimensions of the embedding model? I am using OpenAI Ada 002.

**Comment by langchain4j** [comment]
Should not be. As long as you are using the smae embedding model for adding and searching, it should be fine. Maybe @Martin7-1 can help as he developed this module.

**Comment by Martin7-1** [comment]
@amirkhan-ak-sf Hi! Thank you for reporting bug. I will take a look tomorrow. Based on previous information, I think the problem maybe happen during the creation of `EmbeddingStore`. It seems that your first script has different text content and it does not have metadata. Could you please check the creation of `MongoDbEmbeddingStore` between two scripts?

**Comment by Martin7-1** [comment]
You should create Index on `Atlas Search`.

<img width="1223" alt="image" src="https://github.com/user-attachments/assets/2f3b6e1f-edf2-45b4-a9bc-cc73bd274f65">

Select `Atlas Search` and create index named `default` on your embedding field and metadata field. A example is like below:

<img width="1240" alt="image" src="https://github.com/user-attachments/assets/1f462787-7323-4444-bfa2-f39e2425c794">
