### ISSUE TITLE
[FEATURE] Neo4J Embedding pom for Java 8

### ISSUE THREAD

**Issue by amirkhan-ak-sf** [langchain4j/langchain4j#1536]
Hi

currently when I compile a java program with the neo4j embedding dependency 0.33.0 I get the following error.

```
import dev.langchain4j.store.embedding.neo4j.Neo4jEmbeddingStore;
                                            ^
  bad class file: /Users/user/.m2/repository/dev/langchain4j/langchain4j-neo4j/0.33.0/langchain4j-neo4j-0.33.0.jar(dev/langchain4j/store/embedding/neo4j/Neo4jEmbeddingStore.class)
    class file has wrong version 61.0, should be 52.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
```

Any chance we can make it available for java 8. The other libraries are also supporting java 8.

**Comment by langchain4j** [comment]
@amirkhan-ak-sf java 8 is supported only by Neo4j 3.x which seems to be not supported any more: https://neo4j.com/docs/operations-manual/current/installation/requirements/#deployment-requirements-java

We are using 5.15.0
