### ISSUE TITLE
Neo4j module use private api

### ISSUE THREAD

**Issue by hendrikebbers** [langchain4j/langchain4j#1537]
To be prepared to use Java modules in the future (see https://github.com/langchain4j/langchain4j/issues/1066), langchain4j code must not access code of a module that is not exported by that module. The Neo4J module uses `org.neo4j.driver.internal.value.NodeValue` in the `Neo4jContentRetriever` class today.

**Comment by hendrikebbers** [comment]
Adding @michael-simons since it might be easy for hiom to fix.

**Comment by michael-simons** [comment]
Sure, that's an embarrassing thing todo, especially as the driver is fully module path compatible.

**Comment by michael-simons** [comment]
Sent you a PR.
