### ISSUE TITLE
[FEATURE] Embedding Sources

### ISSUE THREAD

**Issue by amirkhan-ak-sf** [langchain4j/langchain4j#1543]
Hi

I know that using the AI Service I can get the sources presented when doing RAG. I am interested if this is also possible with the Embedding Class and its related objects without going through the AI Service? If not, I would like to request this feature.

**Comment by langchain4j** [comment]
@amirkhan-ak-sf I am not sure I completely understand your request, but it seems that it was answered in [this](https://github.com/langchain4j/langchain4j/issues/1548#event-13726563906) one?

**Comment by amirkhan-ak-sf** [comment]
yes it was answered. Thanks!!
