### ISSUE TITLE
[BUG] `AbstractInProcessEmbeddingModel` never closes its `executor`

### ISSUE THREAD

**Issue by boris-petrov** [langchain4j/langchain4j#1545]
**Describe the bug**
The `executor` that is created in `AbstractInProcessEmbeddingModel` is never closed. And the threads are not daemon ones. Which means that the JVM will never shut down properly.

**Log and Stack trace**
N/A

**To Reproduce**
Just use one of the implementations (say `OnnxEmbeddingModel`) and don't pass an executor so the default is used - the Java process won't finish.

**Expected behavior**
The Java process to finish.

Either there should be a `close` method in there or the thread pool must use daemon threads.

**Please complete the following information:**
- LangChain4j version: 0.33.0
- LLM(s) used: N/A
- Java version: 22
- Spring Boot version (if applicable): N/A

**Comment by langchain4j** [comment]
Hi @boris-petrov in 0.33.0 the default executor in `AbstractInProcessEmbeddingModel` [caches threads for 1 second](https://github.com/langchain4j/langchain4j-embeddings/pull/34), after which they die.

This was a problem in 0.32.0, but should not be in 0.33.0. Could you please check again? Or please provide more details to reproduce.

**Comment by langchain4j** [comment]
Related: https://github.com/langchain4j/langchain4j/issues/1454

**Comment by boris-petrov** [comment]
I believe the issue is [here](https://github.com/langchain4j/langchain4j-embeddings/blob/0.33.0/langchain4j-embeddings/src/main/java/dev/langchain4j/model/embedding/onnx/OnnxEmbeddingModel.java#L34). `Executors.newFixedThreadPool` does not allow core threads to timeout.

**Comment by langchain4j** [comment]
Oh, you are right, I completely overlooked that one. Thanks!
