### ISSUE TITLE
[BUG] Nullpointer in version 33 when using an outputparser

### ISSUE THREAD

**Issue by BlueJoneleth** [langchain4j/langchain4j#1546]
Hi,

I tried upgrading from 32 to 33 but suddenly my code throws a nullpointer:
```java
var userMessage = PromptTemplate.from(promptConfig.getUserMessage()+ ServiceOutputParser.outputFormatInstructions(promptInput.getReturnType()))
                   .apply(promptInput.getParams())
                   .toUserMessage();
```

```
Java.lang.NullPointerException: Cannot invoke "java.lang.Class.isEnum()" because "typeArgumentClass" is null

    at dev.langchain4j.service.output.DefaultOutputParserFactory.get(DefaultOutputParserFactory.java:53)
    at dev.langchain4j.service.output.ServiceOutputParser.outputFormatInstructions(ServiceOutputParser.java:90)
```

This happen in the ServiceOutputParser class: 
ServiceOutputParser.outputFormatInstructions(Class<?>))

In the previous versions it was a static method, it's no longer the case. 

The nullpointer is thrown if you pass a List.class as argument to this method.

**Comment by zambrinf** [comment]
@PrimosK could you take a look? This is related to #725 changes. I could replicate, NPE happens because he does not have a parameterized type when using List.class

**Comment by PrimosK** [comment]
We could align current impl. to match the old behaviour (easily) but given the fact that `AiServices` supports only `List<String>` and `List<Enum>` (and errors out in other cases), I am curious about your specific use case. 

Are you expecting a list of strings? If so, you might be able to use the following approach:
```
Type listOfStringsType = new TypeToken<List<String>>() {}.getType();
String formatInstructions = sut.outputFormatInstructions(listOfStringsType);
```
This code snippet uses `TypeToken` to define the expected type as `List<String>` and then retrieves the format instructions accordingly. Does this align with your requirements?

Given the fact that:
-  it's hard for me to establish whether this is genuine bug 
-  I'll be away for two weeks 
...  I suggest @langchain4j to jump in if needed...

**Comment by langchain4j** [comment]
Hi @BlueJoneleth, in general, `ServiceOutputParser` is an internal class that is used by AI Services and is not supposed to be used directly.

Does @PrimosK's suggestion works for you?

**Comment by PrimosK** [comment]
Given that this class is not being used as intended, I consider this a non-bug.

Due to this and the lack of activity, I suggest closing the issue.
