### ISSUE TITLE
[QUESTION] Is there a way to retrieve sources without using the AIService?

### ISSUE THREAD

**Issue by amirkhan-ak-sf** [langchain4j/langchain4j#1548]
Hi 
I am looking for an approach to receive sources without using the AI Service. 

I tried it with the embedding matches but the meta data is empty:

```
    for (EmbeddingMatch<TextSegment> match : relevantEmbeddings) {
      Metadata matchMetadata = match.embedded().metadata();

      fileName = matchMetadata.getString("file_name");
      absoluteDirectoryPath = matchMetadata.getString("absolute_directory_path");
      textSegment = matchMetadata.getString("textSegment");

.....
```

Any kind of help would be very much appreciated!

**Comment by InAnYan** [comment]
You can retrieve sources without any AIServices or RetrievalChains, but then you should orchestrate the RAG by hand.

You did right, you made a search explicitly, to get search results. Then you will need to supply a prompt template and fill it with user question and sources.

However, it seems strange that you don't have metadata. It surely relates to this:
- Either you haven't provided them.
- Your `EmbeddingStore` implementation doesn't store them properly

**Comment by amirkhan-ak-sf** [comment]
It was the later. It was weaviate which did not provide it, I tested the same code with PGVector and all info is available. Thanks!

**Comment by langchain4j** [comment]
Weaviate supports storing metadata for a few months now: https://docs.langchain4j.dev/integrations/embedding-stores/
