### ISSUE TITLE
[FEATURE] Add support for in-process (ONNX) scoring model

### ISSUE THREAD

**Issue by aseovic** [langchain4j/langchain4j#1553]
**Is your feature request related to a problem? Please describe.**
At the moment the only scoring models provided are Cohere and Jina, both of which are remote models requiring an API key and remote REST calls.

**Describe the solution you'd like**
Ideally, we should be able to perform re-ranking using a local ONNX runtime, the same way we can currently create embeddings using `OnnxEmbeddingModel`. Basically, I'd like the implementation of an `OnnxScoringModel` as well.

**Comment by hzkitty** [comment]
I have written a similar one modeled after OnnxEmbeddingModel, using the local bge reranker large to test normally. If there are any problems, please feel free to correct me. See #1549

**Comment by aseovic** [comment]
Awesome, that looks very much like what I'm looking for, thanks! I'll give it a try 👍 

Do you plan to create a PR for it?

**Comment by langchain4j** [comment]
Closing as a duplicate of https://github.com/langchain4j/langchain4j/issues/1549
