### ISSUE TITLE
[FEATURE] Ollama.EmbeddingRequest  Please support multiple inputs

### ISSUE THREAD

**Issue by yushengliao** [langchain4j/langchain4j#1559]
The current EmbeddingRequest does not support multiple inputs, and the current method indirectly supports multiple inputs through loops, which is very inefficient

![image](https://github.com/user-attachments/assets/dd93ffc3-d02b-4a62-9403-a9cc360fa49f)

![image](https://github.com/user-attachments/assets/36d2c638-070d-4a8d-8e82-f0ab0cdfe606)

**Comment by langchain4j** [comment]
@Martin7-1 would you like to take this one? It also seems that we are using an outdated `api/embeddings`, we should use a new `api/embed`

**Comment by Martin7-1** [comment]
> @Martin7-1 would you like to take this one? It also seems that we are using an outdated `api/embeddings`, we should use a new `api/embed`

@langchain4j No problem. Maybe it will take me 3 days to finish it :)

**Comment by Martin7-1** [comment]
@langchain4j Should we remove the old `api/embeddings` or just add `@Deprecated` on it? In my view I think remove is ok.

**Comment by langchain4j** [comment]
`OllamaApi` is not public, so we can safely remove it
