### ISSUE TITLE
add proxy ip in config of langchain4j-spring-boot-starter

### ISSUE THREAD

**Issue by lizhaowh** [langchain4j/langchain4j#156]
When I use <langchain4j-spring-boot-starter> as a dependency development, I cannot add my own proxy service IP in the configuration

resolve:
so , I hope Expose a configuration item for the IP of a proxy service

**Comment by caopengan** [comment]
I had the same problem

**Comment by langchain4j** [comment]
fixed by https://github.com/langchain4j/langchain4j-spring/pull/1

**Comment by langchain4j** [comment]
in `dev.langchain4j:langchain4j-open-ai-spring-boot-starter:0.25.0` you will be able to define it like this:
```
langchain4j.open-ai.chat-model.proxy.type=HTTP
langchain4j.open-ai.chat-model.proxy.host=host.com
langchain4j.open-ai.chat-model.proxy.port=1234
```
