### ISSUE TITLE
How can the Langchain framework be more flexible in application?

### ISSUE THREAD

**Issue by leleZeng** [langchain4j/langchain4j#1566]
I encountered some obstacles in actual development, such as wanting to notify users of the information about function call execution to let them know the data source, or wanting to notify users of the data source retrieved from the vector database. 

I don't know if it can be implemented with the existing Langchain4j framework. What I hope for is that the current framework can set context for the entire conversation link, such as the current conversation ID or the user ID of the current conversation, so that I can obtain this information from anywhere in the entire conversation link to push the data to the corresponding person.

For example, if there is already custom information(`conversationId`) in the entire conversation link, I can use custom `EmbeddingStore` to inform users of the data.
```
    private List<EmbeddingMatch<TextSegment>> toMatches(SearchResponse<DataSetSegment> response) {
        return response.hits().hits().stream()
                .map(hit -> Optional.ofNullable(hit.source())
                        .map(this::sendEvent)
                        .map(dataSetSegment -> new EmbeddingMatch<>(
                                hit.score(),
                                hit.id(),
                                new Embedding(dataSetSegment.getVector()),
                                dataSetSegment.getText() == null
                                        ? null
                                        : TextSegment.from(dataSetSegment.getText(), new Metadata(dataSetSegment.getMetadata()))
                        )).orElse(null))
                .collect(toList());
    }

    private DataSetSegment sendEvent(DataSetSegment dataSetSegment) {
        SpringContext.getBean(EventBus.class).publish("/llm/conversation/{conversationId}", dataSetSegment).subscribe();
        return dataSetSegment;
    }
```

**Comment by langchain4j** [comment]
Hi, sources can be accessed like [this](https://docs.langchain4j.dev/tutorials/rag#accessing-sources).

Context can be maintained with [memory id](https://docs.langchain4j.dev/tutorials/ai-services#chat-memory).
Information of called tools should be available once [this](https://github.com/langchain4j/langchain4j/pull/1248) is implemented (see latest comments)

**Comment by langchain4j** [comment]
I have created a separate issue for tools: https://github.com/langchain4j/langchain4j/issues/1567

**Comment by leleZeng** [comment]
Thank you for your reply. I followed your tutorial and used `Result<TokenStream>` to build the `Agent`, but found that only the content of the fragment can be obtained from `List<Content>` . I added the fragment to the vector storage library, I added the document number to the vector storage library, and I would prefer to obtain the document information to which this fragment belongs.

If the langchain4j framework allows users to customize parameters to be set within the context of the conversation flow, and each processing chain can send a **Spring event** with the context of the user-defined parameters, this approach would be more flexible for users to listen for themselves.

**Comment by langchain4j** [comment]
Hi,

> I followed your tutorial and used Result<TokenStream>


Unfortunately returning sources when streaming (`TokenStream`) [is not supported yet](https://github.com/langchain4j/langchain4j/issues/660).

> I added the fragment to the vector storage library, I added the document number to the vector storage library, and I would prefer to obtain the document information to which this fragment belongs.

I am not sure I understand, please elaborate.

> If the langchain4j framework allows users to customize parameters to be set within the context of the conversation flow, and each processing chain can send a Spring event with the context of the user-defined parameters, this approach would be more flexible for users to listen for themselves.

This is not clear either, please provide more explanation.

Thanks!

**Comment by leleZeng** [comment]
Thank you very much for your patience. I am a non-native English speaker, and I will try my best to explain things clearly.
﻿
Currently, the context scope of the langchain4j framework is within AiServices. I hope to have a custom parameter context scope for single chat sessions, where the context parameters can be passed in when calling the agent chat function. When a specific processing chain is executed, the processing chain and the context parameters can be sent to a `Spring event`. This way, I can listen for events similar to `ChainEventEntity`, receive the events, and send them in real-time to the user interface through a long connection.

**Comment by langchain4j** [comment]
What such spring event will contain? Can you provide a concrete example? code/pseudocode will be ideal

**Comment by leleZeng** [comment]
```
public interface KnowledgeBaseAgent {

    TokenStream chat(@MemoryId Long memoryId, @UserMessage String userMessage, @UserParam HashMap<String, Object> param);

}
```
Pass in custom parameters when calling the agent

```
hashMap.put("conversationId", "fdac198a5a1e48ebbec6a4881af805c8");
hashMap.put("userId", "1")
knowledgeBaseAgent.chat(memoryId, "What is the working principle of a battery?", hashMap)
```
Send a spring event in the vector retrieval chain of the dialogue call chain
```
class EmbeddeddingEvent extends ApplicationEvent{
	private Map<Object, Object> userParam;
	private List<EmbeddingMatch<Embedded>> matches;
}

public interface EmbeddingStore<Embedded> {

    default EmbeddingSearchResult<Embedded> search(EmbeddingSearchRequest request) {
        List<EmbeddingMatch<Embedded>> matches =
                findRelevant(request.queryEmbedding(), request.maxResults(), request.minScore());
		Map<Object, Object> param = ParamContext.getCurrentChatContext();
		getApplicationContext().publishEvent(EmbeddeddingEvent.build(param, matches))
        return new EmbeddingSearchResult<>(matches);
    }

}
```

**Comment by langchain4j** [comment]
@leleZeng I see, thanks for the detailed explanation! We are already working on [observability](https://github.com/langchain4j/langchain4j/issues/199) and [custom parameters](https://github.com/langchain4j/langchain4j/issues/1122)

**Comment by leleZeng** [comment]
Thank you for your contribution!

**Comment by langchain4j** [comment]
Updates:
https://github.com/langchain4j/langchain4j/issues/1567 and https://github.com/langchain4j/langchain4j/issues/660 are completed.

Closing, please track other issues mentioned above (https://github.com/langchain4j/langchain4j/issues/199 and https://github.com/langchain4j/langchain4j/issues/1122)
