### ISSUE TITLE
[FEATURE] AI Services: provide information about executed tools

### ISSUE THREAD

**Issue by langchain4j** [langchain4j/langchain4j#1567]
- Add new field `List<ToolExecution> toolExecutions` to the `Result<T>` class:
```java
public class ToolExecution {
    ToolExecutionRequest toolExecutionRequest;
    Object toolExecutionResult;
}
```

_Originally posted by @langchain4j in https://github.com/langchain4j/langchain4j/issues/1248#issuecomment-2219830528_

**Comment by hrhrng** [comment]
@langchain4j Hi, I'd like to implement this, and I notice the method `dev.langchain4j.service.tool.ToolExecutor#execute` returns a` String` as the tool execution result. Should we add a new method to return an `Object`, or should we modify `ToolExecution.toolExecutionResult` to be an String instead of a Object?

**Comment by langchain4j** [comment]
@hrhrng great, thank you!

Good question! The idea was that `ToolExecution.toolExecutionResult` will hold the original object returned from the `@Tool` method, be it a `String` or a POJO or something else. This way user can access it without the need to parse it back from JSON. With the current `ToolExecutor` API this is not possible, but I was planning to revise this part soon, so it might change.

But you are right, if it will return `Object`, many users might just invoke `.toString()` on it to get to the `String`. But if in the future we will change `ToolExecutor` to return a POJO, user code will most probably break as it will get a `toString()` of the POJO, not the JSON (as user would expect). It would probably be better in this case to introduce another accessor method to get the original object. So yeah, it makes sense to make `ToolExecution.toolExecutionResult` a `String`. Thank you for pointing this out!
