### ISSUE TITLE
segmentOverlap removed from CharacterSplitter class in version 0.22.0?

### ISSUE THREAD

**Issue by stoneLee81** [langchain4j/langchain4j#157]
Found that the segmentOverlap parameter was removed from the CharacterSplitter class，However, the segmentOverlap variable is very useful for text splitting scenarios and contextual logical association. I don’t know why remove this parameter?

**Comment by langchain4j** [comment]
@stoneLee81 I had to drop this feature to finally release recursive splitter. It is not that simple as it sounds. Going to add it soon.

**Comment by IrynaLiubarska** [comment]
Hi @stoneLee81, new version of LangChain4j 0.23.0 got back segment overlap, check it out. If have any other questions, please let us know. I'll close this issue.
