### ISSUE TITLE
Persist metadata in Neo4j vector store

### ISSUE THREAD

**Issue by msche** [langchain4j/langchain4j#1571]
Dear team,

I would like to persist metadata (like source, creation date, author, etc) together with the vector of the text in the Neo4j vector store. How could I realize this?

**Comment by langchain4j** [comment]
Hi, perharps @jexp or @vga91 could comment?

**Comment by msche** [comment]
I could possibly persist the meta dat in the ID of the vector but I don't think this is a wise decission.

**Comment by langchain4j** [comment]
Pardon, I missed that `Neo4jEmbeddingStore` already supports storing metadata: https://github.com/langchain4j/langchain4j/blob/e3f171944a83b8dd41597df98daae1582489a41a/langchain4j-neo4j/src/test/java/dev/langchain4j/store/embedding/neo4j/Neo4jEmbeddingStoreIT.java#L472

**Comment by jexp** [comment]
And you can extend this to even connect the vector storage in chunks or other entities to a larger graph structure that you then can fetch as relevant context with a retrieval query.

**Comment by ck-amrahd** [comment]
Hi, I have a huge knowledge graph in neo4j, I am using Langchain to embed the node properties:

    vector_index = Neo4jVector.from_existing_graph(...)


 how do I persist this vector db?
