### ISSUE TITLE
Dose not have bge-small-zh-v1.5 for embedding model 

### ISSUE THREAD

**Issue by hgwu4869** [langchain4j/langchain4j#1575]
I find that bge-small-zh-v1.5 is better than bge-small-zh. But this project does not support bge-small-zh-v1.5.
How should I use bge-small-zh-v1.5 as fast as I can? Can I replace the model files by myself? If possible, what should be done?

Here is the link to bge-small-zh-v1.5: https://huggingface.co/BAAI/bge-small-zh-v1.5

**Comment by langchain4j** [comment]
Please check `langchain4j-embeddings-bge-small-zh-v15` and `langchain4j-embeddings-bge-small-zh-v15-q` modules

**Comment by langchain4j** [comment]
You can find all supported models here: https://github.com/langchain4j/langchain4j-embeddings

**Comment by hgwu4869** [comment]
thx! I don't realize it was updated a few weeks ago
