### ISSUE TITLE
[FEATURE] Graph DB QA chain support

### ISSUE THREAD

**Issue by gkorland** [langchain4j/langchain4j#158]
Adding support for Graph QA 

See: https://python.langchain.com/docs/use_cases/more/graph/graph_qa

**Comment by langchain4j** [comment]
@gkorland would you like to contribute this feature? I have too much on my plate right now.

**Comment by gkorland** [comment]
Sure, I'll be glad to, can you share some high level vision? how would you like to see it?

**Comment by langchain4j** [comment]
@gkorland not yet as I don't understand what is the scope and the goal. Could you please provide more details? Do you want to integrate some graph db like neo4j? Or the logic to create the graphs out of unstructured data? Or both?

**Comment by gkorland** [comment]
I want to do both :)

**Comment by theawesomenayak** [comment]
Adding the recommendation from my other issue
```
HI @theawesomenayak this sounds interesting!
But I would implement it not as a chain (old concept which we are deprecating), but as a custom ContentRetriever from https://github.com/langchain4j/langchain4j/pull/538.
Something like Neo4jContentRetriever that will accept an instance of a ChatLanguageModel and Neo4j details about the graph in the constructor/builder and then when the Query comes, it will use that ChatLanguageModel to create a cypher query?
```

@langchain4j this works too. I'll share a PR for this.

**Comment by theawesomenayak** [comment]
Added retrieval support in #741

**Comment by langchain4j** [comment]
Closing as it was implemented in https://github.com/langchain4j/langchain4j/pull/741
