### ISSUE TITLE
[FEATURE] Add Qwen-Audio for langchain4j-dashscope

### ISSUE THREAD

**Issue by TroiiF** [langchain4j/langchain4j#1584]
Is there any schedule for adding qwen-audio model for langchain4j-dashscope? 🙏🏻🙏🏻

The document can be found at: https://help.aliyun.com/zh/dashscope/developer-reference/qwen-audio-chat-api

**Comment by langchain4j** [comment]
cc @jiangsier-xyz

**Comment by jiangsier-xyz** [comment]
I'm on vacation this week, I'll take a look in the next few weeks. Also, feel free to submit PRs.
