### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by QingZzzzzzzzz** [langchain4j/langchain4j#1585]
**Describe the bug**

![image](https://github.com/user-attachments/assets/ea49e0da-d1e6-4751-949d-92aa9c721bbf)

**repro steps：**
```
Return result example(Markdown):
“\n## AA“
”\n“
”### AAA“
```

1、result = "## AA" Jump to handler.onNext(result);
2、result = "\n" Jump to if (Utils.isNullOrBlank(result)) { return;}
3、result = "### AAA" Jump to handler.onNext(result);
Due to the loss of the '\ n' character, This will cause the output format of '### AAA' to display incorrectly
I think using the isNullOrEmpty method is more reasonable

**Please complete the following information:**
- LangChain4j version: 0.33.0
- LLM(s) used: qianfan
- Java version: 17
- Spring Boot version (if applicable): 

**Additional context**

**Comment by langchain4j** [comment]
cc @lane12138
