### ISSUE TITLE
[BUG] SpringBoot scanBasePackages does not take effect

### ISSUE THREAD

**Issue by Saoforest** [langchain4j/langchain4j#1593]
**Describe the bug**
When specifying scanBasePackages, AiServicesAutoConfig cannot correctly scan AiService at the specified path.

**Log and Stack trace**
```text
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [top.xiaolinz.wechat.bot.plugin.chat.GroupChatBotAiService]: Specified class is an interface
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:83)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1331)
	... 67 common frames omitted
```

**Please complete the following information:**
- LangChain4j version: 0.33.0
- LLM(s) used:  openai
- Java version:  21
- Spring Boot version (if applicable):  3.3.2

**Comment by langchain4j** [comment]
Hi @Saoforest, thanks a lot for reporting! Do you have a fix/solution in your mind already?

**Comment by Saoforest** [comment]
> Hi @Saoforest, thanks a lot for reporting! Do you have a fix/solution in your mind already?

@langchain4j 
Can try using the`AutoConfigurationPackages` utility class provided by Spring Boot. You can use the method `AutoConfigurationPackages.get(BeanFactory beanFactory)` to obtain the list of base packages for auto-configuration. This usually includes the package where the `@SpringBootApplication` annotation is located, as well as the packages specified by the `scanBasePackages` attribute

**Comment by langchain4j** [comment]
@Saoforest great, would you like to open a PR?

**Comment by langchain4j** [comment]
Related: https://github.com/langchain4j/langchain4j/issues/1606

**Comment by langchain4j** [comment]
Implemented in https://github.com/langchain4j/langchain4j-spring/pull/36
