### ISSUE TITLE
agent add ollama model

### ISSUE THREAD

**Issue by smileyboy2019** [langchain4j/langchain4j#1595]
At present, the agent API only supports the following models, and the ollama model is the most commonly used local large model. We hope to add an ollama agent. At the same time, we raise questions about why the agent needs to be bound to the model and why it is not separated

**Comment by langchain4j** [comment]
Hi, I am not sure I fully understand your question, but support for Ollama tools has been just merged: https://github.com/langchain4j/langchain4j/pull/1558

**Comment by smileyboy2019** [comment]
When will Ollama agent be released and can be used

**Comment by langchain4j** [comment]
You can already use it in `0.34.0-SNAPSHOT` version. The release will most probably happen next week.

**Comment by smileyboy2019** [comment]
![image](https://github.com/user-attachments/assets/34ce4e0f-d7a5-464a-811d-6c4dd65929e0)
How do other models support agents besides the following models
OpenAiChatModel
AzureOpenAiChatModel
MistralAiChatModel
LocalAiChatModel
QianfanChatModel

**Comment by langchain4j** [comment]
@smileyboy2019 all models that support tools can be seen [here](https://docs.langchain4j.dev/integrations/language-models/) (check "Tools" column)
