### ISSUE TITLE
[FEATURE] Extend extensions list for the TXT DocumentType

### ISSUE THREAD

**Issue by alexisross** [langchain4j/langchain4j#160]
Hello,

Thanks for langchain4j. I want to use It for java ia generative with embeddings and corpus loadings. I'm going to use the FileSystemDocumentLoader.loadDocuments method but the DocumentType is fixed while I want to read ".java" and ".csv" files.

Is it possible to let us define an extension list considerered as "TXT"  ?
Other thing, maybe we can do case insensitive test in th e "of" method.

Here is modest try :
```java
public enum DocumentType
{

   TXT("txt"), //
   PDF("pdf"), //
   HTML("html", "htm", "xhtml"), //
   DOC("doc", "docx"), //
   XLS("xls", "xlsx"), //
   PPT("ppt", "pptx");

   private final List<String> supportedExtensions;

   DocumentType(String... supportedExtensions)
   {
      this.supportedExtensions = new ArrayList<>(Arrays.asList(supportedExtensions));
   }

   public static void addSupportedTxtExtensions(String... exts)
   {
      if (exts != null && exts.length > 0)
      {
         for (String ext : exts)
         {
            if (ext != null && !ext.trim().isEmpty() && !TXT.supportedExtensions.contains(ext.trim()))
            {
               TXT.supportedExtensions.add(ext.trim());
            }
         }
      }
   }

   public static DocumentType of(String fileName)
   {
      for (DocumentType documentType : values())
      {
         for (String supportedExtension : documentType.supportedExtensions)
         {
            if (fileName != null && fileName.toLowerCase().endsWith(supportedExtension))
            {
               return documentType;
            }
         }
      }
      throw new UnsupportedDocumentTypeException(fileName);
   }
}
``` 
Use
```java
   public static void main(String[] args)
   {
      DocumentType.addSupportedTxtExtensions("java", "csv");
      System.out.println(DocumentType.of("MyClass.java")); // ouput: TXT type
      System.out.println(DocumentType.of("MyStats.csv")); // ouput: TXT type
      System.out.println(DocumentType.of("MyStats.DOCX")); // ouput: DOC type
   }
```

**Comment by langchain4j** [comment]
Hi @alexisross is seems that the current design of document loaders is not extensible at all, I will look into it soon to re-design. For the time being I can offer to intoroduce an UNKNOWN document type and fallback to it (will try to load the document the same way as TXT), so that you dont need to specify it yourself. what do you think?

**Comment by alexisross** [comment]
Hi, thanks for the reply. Seems to be a good solution. Thanks :)

**Comment by thanh-p** [comment]
Hi @langchain4j, I think the proposed solution might be confusing.

The purpose of the UnsupportedDocumentTypeException is to tell the user that langchain4j does not support that document type. If langchain4j parses the unsupported document type anyway, the user will think it is a bug because the parsed content can be broken.

If the user wants to use a different type, they can implement their own parser and create a Document directly instead of using FileSystemDocumentLoader.

If we want to support custom parsers, we can add something like FileSystemDocumentLoader.withCustomerParsers(listOfCustomerParsers) and ignore the document type check in the loadDocument functions.

Another problem is that we currently have 3 APIs:
1/ Document loadDocument(Path filePath)
2/ Document loadDocument(Path filePath, DocumentType documentType)
3/ List<Document> loadDocuments(Path directoryPath)
The loadDocument(Path filePath, DocumentType documentType) function should be deprecated since we already support auto-detecting the document type. Additionally, because we cannot create new DocumentType, the function provides no valuable usage.

**Comment by alexisross** [comment]
Hi @thanh-p ,
I understand your point. But it's not an problem of Parser since I want the existing TXT parser. It's just that the extension check is limited to "txt" only.  csv, tsv, js, java (or ext from other languages) are text files. 
If we don't accept those extensions what's the next step for me ? Just rename all my files from xxxx.java to xxxx.txt. It's a bit boring.
That's being said, in addition, give a method to provide CustomParser is a good idea.

**Comment by thanh-p** [comment]
Hi @alexisross, @langchain4j ,
Thank you for providing more details. We already have a function to forcefully load any document type using existing parsers.
You can use the below code to parse .java file using TXT parser:
``` 
Path filePath = Paths.get("/path/to/java/file/Examples.java");
Document document = FileSystemDocumentLoader.loadDocument(filePath, DocumentType.TXT);
System.out.println(document);
```
This case is not mentioned in the Javadoc of the function. It should be updated.

**Comment by nooone** [comment]
@langchain4j Has Apache Tika been considered as a general solution to parse pretty much any file format into text out of the box? It does not rely on file endings, can detect the file format itself and read text from all of the currently implemented DocumentTypes and more.

**Comment by langchain4j** [comment]
@nooone good idea with Apache Tika, need to take a closer look at it and alternatives a bit later.

**Comment by nn200433** [comment]
> @langchain4j Has Apache Tika been considered as a general solution to parse pretty much any file format into text out of the box? It does not rely on file endings, can detect the file format itself and read text from all of the currently implemented DocumentTypes and more.Apache Tika 是否被认为是将几乎任何文件格式解析为开箱即用文本的通用解决方案？它不依赖于文件结尾，可以检测文件格式本身，并从所有当前实现的 DocumentTypes 等中读取文本。

I'm using  Apache Tika, operation is as follows：

1. upload file, use Apache Tika(use PaddleOCR, support Chinese) parse file and then return text content
2. use text content to build new Document Object and then add to embedding store

---

some code:

```java
@Override
public Map<String, TikaUtil.FileInfo> uploadMultiFileMap(HttpServletRequest request) {
    return uploadMultiFile(request).stream()
            // add to embedding store
            .peek(f -> VectorStoreUtil.addText(f.getFileName(), f.getContent()))
            .collect(Collectors.groupingBy(TikaUtil.FileInfo::getFileName, Collectors.collectingAndThen(Collectors.toList(), CollUtil::getFirst)));
}

@Override
public List<TikaUtil.FileInfo> uploadMultiFile(HttpServletRequest request) {
    final List<UploadTempFile> fileList  = saveUploadFileLocal(request);
    final int                  totalFile = fileList.size();
    // submit parse task
    final CompletionService<TikaUtil.FileInfo> threadExecutor = new ExecutorCompletionService<TikaUtil.FileInfo>(taskPool);
    fileList.forEach(f -> threadExecutor.submit(f::parse));
    // get parse result
    List<TikaUtil.FileInfo> fileInfoList = new ArrayList<TikaUtil.FileInfo>(totalFile);
    for (int i = 0; i < totalFile; i++) {
        try {
            final Future<TikaUtil.FileInfo> take = threadExecutor.take();
            fileInfoList.add(take.get(3, TimeUnit.MINUTES));
        } catch (Exception e) {
            log.error("---> file parse error", e);
        }
    }
    return fileInfoList;
}
```

```java
@Slf4j
public class UploadTempFile {

    public TikaUtil.FileInfo parse() {
        final File        tempFile     = getTempFile();
        final String      originalName = getOriginalName();
        final String      extName      = getExtName();
        TikaUtil.FileInfo fileInfo     = new TikaUtil.FileInfo();
        try {
            final String        cleanOriginalFilename = StrUtil.cleanBlank(FileUtil.cleanInvalid(originalName));
            Map<String, Object> varMap                = new HashMap<String, Object>(2);
            varMap.put("fileName", cleanOriginalFilename);
            varMap.put("extName", extName);
            varMap.put("withoutExtName", cleanOriginalFilename.replace(extName, StrUtil.EMPTY));
            ThreadLocalUtil.put(varMap);
            // begin parse
            fileInfo = TikaUtil.parseFile(tempFile, properties.getIsFormatText(), f -> f.setExtract(nlpService.extract(f)))
                    .fileName(originalName);
        } catch (Exception e) {
            log.error("---> file parse error", e);
        } finally {
            if (null != tempFile) {
                tempFile.deleteOnExit();
            }
        }
        return fileInfo;
    }

}
```

```java
public class VectorStoreUtil {

    public static void addText(String fileName, String content) {
        final String extName = StrUtil.DOT + FileUtil.extName(fileName);
        add(Document.from(content, Metadata.from(MapUtil.builder(Document.DOCUMENT_TYPE, extName)
                                                         .put(Document.FILE_NAME, fileName)
                                                         .build())));
     }

    public static void add(Document document) {
        getEmbeddingStore().ingest(document);
    }

}
```

**Comment by langchain4j** [comment]
Closing this as any text (not necessarily only .txt, any file with cleartext content like .html) file can be now loaded using `TextDocumentParser`:
```java
Document document = FileSystemDocumentLoader.loadDocument(path, new TextDocumentParser());
```

Support for Apache Tika will be added this week in scope of https://github.com/langchain4j/langchain4j/pull/686
