### ISSUE TITLE
[FEATURE] Support of filtering by metadata for Qdrant in EmbeddingStore

### ISSUE THREAD

**Issue by holeniev** [langchain4j/langchain4j#1600]
We are implementing the chat platform with multiple users. The code is based on langhcain4j and Qdrant to store and augment the future chats based on historical chats. In order to do this we need to search the previous messages and filter them by user id and some other fields from Qdrant collection. Currently I see the support for vector metadata search for Milvus and Elasticsearch but not Qdrant.

My team needs the possibility to filter the results of vector search with metadata. E.g. call to QdrantEmbeddingStore.search(EmbeddingSearchRequest) with filter added to EmbeddingSearchRequest instance.
The alternatives we consider are the separate collections for distinct user (not scaleable) or switching to Milvius (we chose Qdrant as a result of comparison so it would be easier to stay and implement this feature rather than switching)

My team and me are ready to contribute and implement this feature. 
This was also discussed in #151

**Comment by langchain4j** [comment]
@holeniev please feel free to open a PR with this, thank you!

[Here](https://github.com/langchain4j/langchain4j/pull/1601) is a recent example of the same feature implemented for Pinecone.

**Comment by Anush008** [comment]
Hey. I'll try to implement this.

**Comment by langchain4j** [comment]
@Anush008 great, thank you!

**Comment by holeniev** [comment]
@Anush008 what is needed to close this? Feel free to ask for any assistance from my side

**Comment by Anush008** [comment]
> @Anush008 what is needed to close this? Feel free to ask for any assistance from my side

A review.
