### ISSUE TITLE
Tool Calling - how can we request to the LLM that it re-calls for data after a period of time

### ISSUE THREAD

**Issue by algotechnology** [langchain4j/langchain4j#1602]
In my use case the data changes and the LLM keeps returning and using cached data ....

any ideas or tips to avoid this ?

Thanks

**Comment by InAnYan** [comment]
I've also been thinking about those kinds of problems.

You need to understand, that an LLM is just a `Text -> Text` function. And all other logic ("architecture" of an LLM app) should be managed externally.

If you have a tool call, that LLM uses, then it's the responsibility of the programmer who made the system to handle the tool call.

Not LLM returns output, but a combination of LLM + tools + servers that handle requests.

If your system returns cached output, then look into your caching mechanism. Turn if off, or make the expiry less

**Comment by algotechnology** [comment]
Thanks.  My tool side of things always returns the latest / live data.  The issue is that if the LLM has called it once it often caches the tool result in the LLM so the LLM does not call the tool for every request (which I would like).  Ive tried adding plenty of hints via @Tool which helps a bit but still it caches some data / fails to re-execute the actual tool call (if that makes sense).
