### ISSUE TITLE
[BUG] Expected a SETTINGS frame but was WINDOW_UPDATE

### ISSUE THREAD

**Issue by Blarc** [langchain4j/langchain4j#1619]
**Describe the bug**
When making a request to OpenAI, an IOException is thrown. The error java.lang.RuntimeException: java.io.IOException: Expected a SETTINGS frame but was WINDOW_UPDATE is indicative of a problem that likely arises at the level of the HTTP/2 protocol, within model.generate call.

Supposedly works fine on Windows 10, but not on Ubuntu 22.04 [source](https://github.com/Blarc/ai-commits-intellij-plugin/issues/226#issue-2478169890).

**Log and Stack trace**
[tail_log.txt](https://github.com/user-attachments/files/16697472/tail_log.txt)

**To Reproduce**
I am not sure how to reproduce, since it doesn't always happen. The langchain4j is used as a dependency for IntelliJ plugin.

**Expected behavior**
The request to OpenAI to go through.

**Please complete the following information:**
- LangChain4j version: 0.33.0
- LLM(s) used: OpenAI (gpt-4o)
- Java version: 17

**Additional context**
https://github.com/Blarc/ai-commits-intellij-plugin/issues/226

**Comment by langchain4j** [comment]
@Blarc seems like this issue happens on a much lower level than LC4j, I am not sure what exactly can be fixed here.
I would suggest opening this issue on okhttp github and/or check on OpenAI forum

**Comment by Blarc** [comment]
Alright, thanks for responding.

**Comment by Blarc** [comment]
Hey @langchain4j,

is there a way to force http/1.1 in the OkHttp client? That's the suggested workaround according to https://github.com/square/okhttp/issues/8524.

**Comment by langchain4j** [comment]
@Blarc there is no way to do so right now. Please note that there is a plan to replace okhttp with another http client (jdk11 http client most probably) in the near future. How often does this issue happen? Does automatic retry help?
