### ISSUE TITLE
[BUG] For vector search, we get a higher result score than for native SDK search

### ISSUE THREAD

**Issue by yichen142** [langchain4j/langchain4j#1625]
**Describe the bug**
When using the Milvus vector database, the Embedding<float> object automatically reduces the precision when receiving vector decimal point data (18-19 decimal places), resulting in large query scores

**Log and Stack trace**
Original floating-point value: -0.050223954021930695
java float with reduced precision: -0.0502240

Try changing this:
1. Change the Embedding data obtained through the api to a Double object to receive, and the floating point value can receive the full decimal point.
2. In addition, the official Milvus-SDK-Java 2.3.9 sdk of milvus also has the same problem, which uses float to receive and send embedded data instead of double.

**Please complete the following information:**
- LangChain4j version:3.2
- LLM(s) used: bge-1m
- Java version: 1.8

**Additional context**

**Comment by langchain4j** [comment]
> resulting in large query scores

What do oyu mean by that?

**Comment by yichen142** [comment]
LangChain4j version:3.2
LLM(s) used: bge-1m
milvus data: 1

 Vector databases have only one piece of data,This one down here：
[When using the Milvus vector database, the Embedding object automatically reduces the precision when receiving vector decimal point data (18-19 decimal places), resulting in large query scores]


//Use langchain4j to search for content by vector
          Embedding embedding=EmbeddingTools.getEmbeddingText("resulting in large query scores");
		
		MilvusEmbeddingStore embeStore = MilvusEmbeddingStore.builder()
				.host("192.168.1.161")
				.port(19530)
				.databaseName("test141")
				.collectionName("test")
				.dimension(1024)//bge-1m
				.build();
		
		//langchain4j search
		List<EmbeddingMatch<TextSegment>> findResultList=embeStore.findRelevant( embedding, 5, 0.1);
		for (EmbeddingMatch<TextSegment> match:findResultList) {
			double score= match.score();
			System.out.println("langchain4j ID:"+match.embeddingId());
			System.out.println("langchain4j score:"+score);
		}

**Result output:**
langchain4j ID:72cd2db5-6123-4e52-b330-5bef6abe887f
langchain4j score: 0.8106803596019745


 //Search was performed using the milvus native sdk [milvus-sdk-java 2.3.9]
 String query="resulting in large query scores";
 List<Float> vectorList=getEmbeddingDataList(query);
List<BaseVector> datas= new ArrayList<BaseVector>();
 datas.add(new FloatVec(vectorList));
SearchResp searchR = client.search(SearchReq.builder()
                .collectionName(collectionName)
                .data(datas)
                .topK(10)
                .outputFields(Collections.singletonList("*"))
                .build());
List<List<SearchResp.SearchResult>> searchResults = searchR.getSearchResults();
 for (List<SearchResp.SearchResult> results : searchResults) {
      for (SearchResp.SearchResult result : results) {
           System.out.println("native  ID:"+result.getId());
	   System.out.println("native score:"+result.getScore());
      }
 }

**native Result output:**
native      ID:  72cd2db5-6123-4e52-b330-5bef6abe887f
native score: 0.6213607



Note：
langchain4j score: 0.8106803596019745
native score: 0.6213607

Query results using milvus search page：

![微信截图_20240826145326](https://github.com/user-attachments/assets/055844b5-66c4-454f-8213-37684207dba3)

**Comment by langchain4j** [comment]
`EmbeddingMatch.score()` is a **relevance score** (value between 0 and 1).
Score returned by Milvus is a **cosine similarity** (value between 0 and 2).
`MilvusEmbeddingStore` uses `RelevanceScore.fromCosineSimilarity()` for conversion. If you need the original score, you can convert it back with `CosineSimilarity.fromRelevanceScore()`.
But It does not really matter which one you use, as long as all comparisons are done in the same metric.

> Original floating-point value: -0.050223954021930695
> java float with reduced precision: -0.0502240

The use of floats instead of doubles is fine, the last numbers are noise anyway

**Comment by yichen142** [comment]
Ok, thank you very much
