### ISSUE TITLE
"Cannot resolve symbol OpenAiChatModelName" in IntelliJ

### ISSUE THREAD

**Issue by ppatierno** [langchain4j/langchain4j#1627]
After updating to 0.33.0 I am facing the following issue, just in IntelliJ, in both the langchain4j-examples repo or any other project trying to use langchain4j as dependency.
Taking the `OpenAiFunctionCallingExamples` as an example, IntelliJ reports the "Cannot resolve symbol OpenAiChatModelName" on the following import:

```java
import static dev.langchain4j.model.openai.OpenAiChatModelName.GPT_4_O;
```

The same happens if I try to import any value from the other enums in the picture (i.e. OpenAiEmbeggingModelName, and so on).

![Screenshot from 2024-08-24 15-03-52](https://github.com/user-attachments/assets/06f094b5-88ae-4bc4-9423-dab72a4c36d6)

Of course, the application compiles are run with maven as well as the symbol is recognized when using VSCode for example.
I tried to invalidate the cache, deleting the .idea folder and more.
No luck.
Is there anyone else facing the same problem? It was working fine until 0.32.0 when the above enums weren't there yet I guess.

**Comment by langchain4j** [comment]
This happened to me as well a while ago. I've updated to the latest Intellij and the problem was solved 🤷

**Comment by ppatierno** [comment]
Interesting ... I am on 2022.3 so an old one, I will try the latest and let you know. Thanks!

**Comment by ppatierno** [comment]
Going to close this one. Updating IntelliJ fixed the issue. Thanks!
