### ISSUE TITLE
[FEATURE] Milvus - upgrade to Milvus SDK 2.3.9

### ISSUE THREAD

**Issue by r0x07k** [langchain4j/langchain4j#1629]
Milvus has released SDK 2.3.9, replacing Fastjson with Gson and adding support for MilvusClientV2. It would be beneficial for users to have langchain4j-milvus updated with this new dependency, so they can use both LangChain and MilvusClientV2 in one app where needed.

**Comment by r0x07k** [comment]
Upgrading to MilvusClientV2 would be even better, as it operates significantly faster (at least in my experience). I even skipped langchain4j-milvus for embedding generation and used MilvusClientV2 directly to store embeddings. However, I understand that this upgrade would require more effort.

**Comment by langchain4j** [comment]
@r0x07k would you like to implement this?

**Comment by r0x07k** [comment]
Hi,

It was done.
