### ISSUE TITLE
[FEATURE] Support more Agent and Chain like langchain python edition

### ISSUE THREAD

**Issue by Jashinck** [langchain4j/langchain4j#163]
as we know, the langchain official python edition, has many types of AgentType and ChainType, which can provide multi choice for users

**Comment by langchain4j** [comment]
@Jashinck please be more specific and provide a prioritized list of agents/chains, thanks

**Comment by Jashinck** [comment]
High priority: 
Common Chains: LLMChain、SequentialChain、RouterChain
Agent Type:  zero-shot-react-description, conversational-react-description, structured-chat-zero-shot-react-description

**Comment by kevin-wu-os** [comment]
Python Official document - https://python.langchain.com/docs/modules/chains/foundational/sequential_chains

Given the definition there, I think the current chain definition needs to be changed.

Per `SequentialChain: A more general form of sequential chains, allowing for multiple inputs/outputs.`

The current Chain interface is 

```java
public interface Chain<Input, Output> {

    Output execute(Input input);
}
```

v.s In Python abstract class is used with an abstract method to return one or multiple keys.

https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/chains/base.py#L183

**Comment by langchain4j** [comment]
- LLMChain: there are many ways to do it already: `PromptTemplate` + `ChatLanguageModel`, `AiServices`, etc
- SequentialChain: I doubt there sohuld be a separate abstraction for that, you can simply call multiple components in a row
- RouterChain: good idea, I have created a separate issue for this: https://github.com/langchain4j/langchain4j/issues/952
- Agents: there is another issue for this, please track it there: https://github.com/langchain4j/langchain4j/issues/193
