### ISSUE TITLE
[FEATURE] EmbeddingModelTextClassifier to support Map<String, List<String>>

### ISSUE THREAD

**Issue by fmx0717** [langchain4j/langchain4j#1665]
I would like the EmbeddingModelTextClassifier to support Map<String, List<String>> as input, rather than only Map<Enum, List<String>>, and to provide the similarity score for each output result.

**Comment by zzutligang** [comment]
I also need this demand

**Comment by Martin7-1** [comment]
@langchain4j Hi, Could you please assign this issue to me? I think we could make two changes:

1. Change `TextClassifier<E extends Enum<E>>` and `EmbeddingModelTextClassifier<E extends Enum<E>>` to `TextClassifier<E>` and `EmbeddingModelTextClassifier<E>`. (I think this change will not break current implementation and test)
2. Make `LabelWithScore` class public, and add a new method in `TextClassfiler`:

```java
List<LabelWithScore> classifyWithScore(String text);
```

WDYT?

**Comment by langchain4j** [comment]
@Martin7-1 Sure! Hard to say right now, need to see the end result...
