### ISSUE TITLE
[FEATURE] divide the Module into more Detail

### ISSUE THREAD

**Issue by Martin7-1** [langchain4j/langchain4j#168]
Currently the module is at the same level. But I think it will cause conflict at some time.

Suppose that we have `Redis` for `EmbeddingStore` And `Memory`. How to name both of them?

I suggest that we can move current module into submodule, such as `langchain4j-model`(contains `langchain4j-vertex-ai` and `langchain4j-dashscope`) and `langchain4j-embeddding-store`(contains `langchain4j-milvus`, `langchain4j-pinecone`, `langchain4j-weaviate` and `langchain4j-elasticsearch`).

In the future we may need `langchain4j-memory-store` and `langchain4j-agents`.

One question is that if we add prefix to current module(eg. langchain4j-elasticsearch to langchain4j-embedding-store-elasticsearch). It may not be compatible. if we do not add prefix, how to avoid conflict(such as `langchain4j-embedding-store-redis` and `langchain4j-memory-store-redis`)?

demo see [PR](https://github.com/Martin7-1/langchain4j/pull/2)

**Comment by Martin7-1** [comment]
One question is that if we add prefix to current module(eg. `langchain4j-elasticsearch` to `langchain4j-embedding-store-elasticsearch`). It may not be compatible. if we do not add prefix, how to avoid conflict?

**Comment by Martin7-1** [comment]
demo see [PR](https://github.com/Martin7-1/langchain4j/pull/2)

**Comment by langchain4j** [comment]
@Martin7-1 good question. I guess at some point we will probably need to rename modules to include prefix as you suggested. Or maybe we will just put all related implemnetations (embedding store, memory store) in the same module to keep things simple. If person already uses redis to store embeddings, there is a big chance he will use redis to store memory.

**Comment by Martin7-1** [comment]
> @Martin7-1 good question. I guess at some point we will probably need to rename modules to include prefix as you suggested. Or maybe we will just put all related implemnetations (embedding store, memory store) in the same module to keep things simple. If person already uses redis to store embeddings, there is a big chance he will use redis to store memory.

@langchain4j You are right. Now if we don't get any feedback we probably don't need to think about that for a while.
