### ISSUE TITLE
PgVector: migrate from Gson to Jackson

### ISSUE THREAD

**Issue by langchain4j** [langchain4j/langchain4j#1684]
Migrate `langchain4j-pgvector` module from Gson to Jackson.
Currently `JSONMetadataHandler` uses `Json.fromJson()` and `Json.toJson()` methods that use Gson under the hood.

**Comment by langchain4j** [comment]
cc @humcqc

**Comment by humcqc** [comment]
@langchain4j , I don't see a Jackson implementation of JsonCodec, do you want me to add one or I will use directly ObjectMapper like in other modules ?

**Comment by langchain4j** [comment]
Please use `ObjectMapper` directly
