### ISSUE TITLE
Ollama: migrate from Gson to Jackson

### ISSUE THREAD

**Issue by langchain4j** [langchain4j/langchain4j#1688]
Apart from Gson being used in `OllamaApiIT`, `OllamaMessagesUtils` uses `Json.toJson()` method that use Gson under the hood

**Comment by langchain4j** [comment]
cc @Martin7-1

**Comment by Martin7-1** [comment]
@langchain4j Hi! For the class which uses `Json.toJosn()`, should we change `langchain4j-core` and implement `JacksonJsonCodec` to replace current `GsonJsonCodec`? We can make `GsonJsonCodec` deprecated and change `loadCodec` like this:

```java
    private static JsonCodec loadCodec() {
        for (JsonCodecFactory factory : loadFactories(JsonCodecFactory.class)) {
            return factory.create();
        }
        return new JacksonJsonCodec();
    }
```

In this way, we don't need to mannually change the usage of `Json.toJson()`

**Comment by langchain4j** [comment]
@Martin7-1 I feel like it was a bad idea to have `Json.xxx()` in the `langchain4j-core` module and use it everywhere, there are a few problems with it:
- it forces `langchain4j-core` to depend on some json library which is not ideal as this modele is used transitively in all other modules (whether they need json or not)
- it means that serialization logic should be the same across all modules, but some modules require special logic

So I was considering moving `Json` class into `langchain4j` module and using it only to serialize/deserialize tools and structured outputs. WDYT?

**Comment by Martin7-1** [comment]
@langchain4j Sounds good. I will change the implementation in `OllamaMessageUtils` asap.
