### ISSUE TITLE
It is strongly recommended to add an optional tokenizer parameter to the ElasticsearchEmbeddingStore constructor

### ISSUE THREAD

**Issue by zzutligang** [langchain4j/langchain4j#1700]
It is strongly recommended to add an optional tokenizer parameter to the ElasticsearchEmbeddingStore constructor, and then specify a tokenizer for the [text] field when creating an index based on whether the tokenizer parameter is passed in the creatIndexIfNotExist method. This way, in case the vector retrieval document is not ideal, the document can be retrieved through keywords and handed over to LLM for generation.

**Comment by langchain4j** [comment]
@zzutligang it is not clear, please elaborate

**Comment by dadoonet** [comment]
From 0.34, there's no more the `creatIndexIfNotExist` method. It's highly recommended to define yourself the mapping/settings you want to use and IMO using index templates is the way to go.
So I think this is not needed.

My 2 cents

**Comment by langchain4j** [comment]
@zzutligang feel free to reopen if needed
