### ISSUE TITLE
I suggest that chat supports Chains

### ISSUE THREAD

**Issue by smileyboy2019** [langchain4j/langchain4j#1701]
I suggest that chat supports Chains. The benefits of Chains are that I can execute the chat in order.
For example, openAiChatModel. generate (userMessage 1). generate (userMessage 2)
Among them, userMessage 1 converts DDL statements into SQL, outputs SQL, and passes a userMessage 2. The role of userMessage 2 is to execute SQL in the database, return JSON data, and let the big model infer the data.

**Comment by langchain4j** [comment]
Hi, you might want to look into https://github.com/langchain4j/langchain4j-examples/blob/main/rag-examples/src/main/java/_3_advanced/_10_Advanced_RAG_SQL_Database_Retreiver_Example.java
