### ISSUE TITLE
[FEATURE] AiServices supports  Result<TokenStream>

### ISSUE THREAD

**Issue by fmx0717** [langchain4j/langchain4j#1703]
When using RAG (Retrieval-Augmented Generation) in AiServices and returning results via a stream, only TokenStream is being returned. I need it to return Result<TokenStream> instead, so that I can access the sources within the Result for referencing the original text.

**Comment by langchain4j** [comment]
Hi, this has been implemented in #1527 and will be released in 0.34.0 this week
