### ISSUE TITLE
[FEATURE] Add timeout support for Amazon Bedrock Anthropic API

### ISSUE THREAD

**Issue by JSON-OBJECT** [langchain4j/langchain4j#1704]
**Is your feature request related to a problem? Please describe.**
The **BedrockAnthropicMessageChatModel** in LangChain4j currently lacks a **timeout()** method, which is available in other model implementations like **AzureOpenAiChatModel**. This inconsistency makes it difficult to set timeouts for API calls when using the Amazon Bedrock Anthropic API, potentially leading to long-running requests that could impact application performance.

**Describe the solution you'd like**
I propose adding a **timeout()** method to the **BedrockAnthropicMessageChatModel** builder, similar to the one available in **AzureOpenAiChatModel**. This would allow users to set a timeout duration for API calls, enhancing control over request handling. The implementation should be consistent with other LangChain4j model implementations. For example:

```java
BedrockAnthropicMessageChatModel.builder()
    .region(Region.US_EAST_1)
    .model("anthropic.claude-3-5-sonnet-20240620-v1:0")
    .temperature(0.3)
    .topP(0.3f)
    .timeout(Duration.ofSeconds(60))  // New timeout method
    .build()
```

**Describe alternatives you've considered**
1. Using the AWS SDK v2 directly, which provides timeout functionality through the **ApacheHttpClient** configuration. However, this approach requires more boilerplate code and deviates from the simplified LangChain4j API.

2. Implementing a wrapper class around **BedrockAnthropicMessageChatModel** to add timeout functionality. This solution, while feasible, would not be as clean or consistent with other LangChain4j implementations.

**Additional context**
The AWS CLI and SDK v2 both support setting timeouts for Bedrock API calls. Implementing this feature in LangChain4j would bring the library's functionality in line with these official AWS tools, providing a more consistent developer experience across the ecosystem.

For reference, here's how timeouts are set in the AWS CLI:

```bash
aws bedrock-runtime invoke-model \
    --model-id anthropic.claude-3-5-sonnet-20240620-v1:0 \
    --region us-east-1 \
    --body "$(echo '{
        "anthropic_version": "bedrock-2023-05-31",
        "max_tokens": 200000,
        "messages": [
            {
                "role": "user",
                "content": "Hello!"
            }
        ],
        "temperature": 0.3,
        "top_p": 0.3
    }' | base64 -w 0)" \
    --content-type "application/json" \
    --cli-read-timeout 60 \
    --cli-connect-timeout 60 \
    output.json
```

And in the AWS SDK v2:

```java
Region region = Region.US_EAST_1;
String modelId = "anthropic.claude-3-5-sonnet-20240620-v1:0";
ApacheHttpClient httpClient = ApacheHttpClient.builder()
        .connectionTimeout(Duration.ofSeconds(60))
        .socketTimeout(Duration.ofSeconds(60))
        .build();

BedrockRuntimeClient bedrockRuntimeClient = BedrockRuntimeClient.builder()
        .region(region)
        .credentialsProvider(DefaultCredentialsProvider.create())
        .httpClient(httpClient)
        .build();

Map<String, Object> requestBody = new HashMap<>();
requestBody.put("anthropic_version", "bedrock-2023-05-31");
requestBody.put("max_tokens", 200000);

List<Map<String, String>> messages = new ArrayList<>();
Map<String, String> message = new HashMap<>();
message.put("role", "user");
message.put("content", "Hello!");
messages.add(message);
requestBody.put("messages", messages);
requestBody.put("temperature", 0.3);
requestBody.put("top_p", 0.3);

ObjectMapper objectMapper = new ObjectMapper();
String jsonBody = "";
try {
    jsonBody = objectMapper.writeValueAsString(requestBody);
} catch (Exception e) {
    System.out.println("Error serializing request body: " + e.getMessage());
    return;
}

InvokeModelRequest request = InvokeModelRequest.builder()
        .modelId(modelId)
        .contentType("application/json")
        .accept("application/json")
        .body(SdkBytes.fromUtf8String(jsonBody))
        .build();

String responseBody = null;
try {
    InvokeModelResponse response = bedrockRuntimeClient.invokeModel(request);
    responseBody = response.body().asUtf8String();
} catch (Exception e) {
    System.out.println("Error invoking Bedrock model: " + e.getMessage());
} finally {
    bedrockRuntimeClient.close();
}
```

Adding this feature would significantly improve the usability and flexibility of the **BedrockAnthropicMessageChatModel** in LangChain4j. :)

**Comment by n3kh3l** [comment]
I've started working on it. please assign it to me
