### ISSUE TITLE
[BUG] Ollama - generate without tool list throws not supported

### ISSUE THREAD

**Issue by MiggiV2** [langchain4j/langchain4j#1713]
**Describe the bug**
Using generate with a List works, but as singe object, it throws an IllegalArgumentException.

This would work:
```JAVA
 List<ToolSpecification> toolSpecifications = singletonList(weatherToolSpecification);
```

A single object, does not work.
```JAVA
// given
ToolSpecification toolSpecifications = weatherToolSpecification;

 // when
List<ChatMessage> chatMessages = asList(
        systemMessage("Use tools only if needed"),
        userMessage("Tell a joke")
);
Response<AiMessage> response = ollamaChatModel.generate(chatMessages, toolSpecifications);
```

**Log and Stack trace**
```
java.lang.IllegalArgumentException: Tools are currently not supported by this model

	at dev.langchain4j.model.chat.ChatLanguageModel.generate(ChatLanguageModel.java:86)
	at dev.langchain4j.model.ollama.OllamaToolChatModelIT.should_not_throw_unsupported(OllamaToolChatModelIT.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
```

**To Reproduce**
I will fix this and add a green test.

**Expected behavior**
Successful response.

**Please complete the following information:**
- LangChain4j version: 0.34.0
- LLM(s) used: mistral, mistral-nemo (works best for me), llama3.1
- Java version: 21
- Ollama version: 0.3.9

**Comment by MiggiV2** [comment]
Should be fixed by #1714

**Comment by langchain4j** [comment]
Hi @MiggiV2, this is not a bug.

The method with a single tool spec is supposed to **_force_** the LLM to use that tool. Since Ollama does not support this feature, it throws an exception. Perharps exception text can be adapted to make it more clear

> /**
>      * Generates a response from the model based on a list of messages and a single tool specification.
>      * **_The model is forced to execute the specified tool._**

**Comment by MiggiV2** [comment]
@langchain4j I see. Thanks for clearing this up.
I will close this issue and my PR then.
