### ISSUE TITLE
[FEATURE] Azure OpenAI: Structured Outputs

### ISSUE THREAD

**Issue by langchain4j** [langchain4j/langchain4j#1715]
Same as https://github.com/langchain4j/langchain4j/pull/1590 but for Azure OpenAI

**Comment by langchain4j** [comment]
Azure OpenAI SDK feature request: https://github.com/Azure/azure-sdk-for-java/issues/41655

**Comment by langchain4j** [comment]
Structured Outputs are available in [1.0.0-beta.12](https://repo1.maven.org/maven2/com/azure/azure-ai-openai/1.0.0-beta.12/) now!

Hi @jdubois, @agoncal, any chance you could add this to Azure OpenAI before the next release (most probably mid/end next week)? 🙏

**Comment by langchain4j** [comment]
BTW, there is already a reference implementation in `OpenAiChatModel` and a set of tests, just need to extend `AiServicesWithJsonSchemaIT`, you can see `OpenAiAiServicesWithJsonSchemaIT` as an example.

**Comment by jdubois** [comment]
I've started the work on #1982 but there's a lot to do, and I won't be able to work at all on this next week. Happy to have others contribute if that's urgent!

**Comment by langchain4j** [comment]
Implemented in https://github.com/langchain4j/langchain4j/pull/1982
