### ISSUE TITLE
OpenAI embedding  store Milvus  Error

### ISSUE THREAD

**Issue by caopengan** [langchain4j/langchain4j#172]
When I use the embedding api of openai to store the embedding to milvus, there will always be an error. I suspect it is caused by the size of data transfer. However, I have looked at the grpc setting and it should be called Problem.
![image](https://github.com/langchain4j/langchain4j/assets/12568699/7622cfa3-2a4e-4227-bf8c-efaaf9b4594e)

rpc setting：

![image](https://github.com/langchain4j/langchain4j/assets/12568699/8bfe1810-8fe4-4db1-8c1f-7f2be96f5ea5)

But I did not transfer objects that exceeded this limit

**Comment by langchain4j** [comment]
Hi @caopengan
> I suspect it is caused by the size of data transfer.

Did you try persisting only a single small embedding to test this theory?

Does it happen on adding embedding or on search as well?
Might be a configuration issue.

**Comment by caopengan** [comment]
> Hi @caopengan
> 
> > I suspect it is caused by the size of data transfer.
> 
> Did you try persisting only a single small embedding to test this theory?
> 
> Does it happen on adding embedding or on search as well? Might be a configuration issue.

Sorry, I have already fixed this issue, because the local debugging uses the proxy server reason, I will close this issue
