### ISSUE TITLE
[FEATURE] Allow us to override METADATA_TEXT_SEGMENT in the WeaviateEmbeddingStoreExample

### ISSUE THREAD

**Issue by Jaland** [langchain4j/langchain4j#1722]
**Is your feature request related to a problem? Please describe.**
We have loaded data into a Weaviate DB but we have loaded it with the key `page_content`. When we used the python libraries we were able to specify that key with the following code:

```
WeaviateRetrieverWithScoreThreshold(
      client=WeaviateClient(self.config).client,
      index_name=index_name,
      # TODO: Should we make this data driven? For different data types?
      text_key="page_content",
      embedding_function=self.embeddings,
      k=4, # can we make this dynamic?
    )
```
But when using the WeaviateEmbeddingStoreExample it seems like it default to `text` and there is no way to change that

**Describe the solution you'd like**
I believe this is based on the `METADATA_TEXT_SEGMENT` that seems to be hard coded (linked below). 

It would just be nice if this was a value we were able to override.

**Additional context**
Here is the code I am referencing:
https://github.com/langchain4j/langchain4j/blob/main/langchain4j-weaviate/src/main/java/dev/langchain4j/store/embedding/weaviate/WeaviateEmbeddingStore.java#L42C33-L42C54

**Comment by Jaland** [comment]
Created a PR:
https://github.com/langchain4j/langchain4j/pull/1723

**Comment by Jaland** [comment]
I have also noticed that any meta data is assumed to be under `_metadata` so it seems like it may not be possible to retrieve fields directly under properties.

So inside of my vector DB we have something like:

```
{
	"class": "ClassName",
	"creationTimeUnix": 1718292601895,
	"id": "00cd5667-623e-471f-996c-5f68f585bd15",
	"lastUpdateTimeUnix": 1718292601895,
	"properties": {
		"header1": "Example Header 1",
		"header2": "Example Header 2",
		"language": "en-US",
		"page_content": "CONTENT YADA YADA YADA.......................................",
		"source": "https://my-example-documentation.com",
		"title": "Getting started...",
		"version": "1.1"
	},
	"vectorWeights": null
}
```

And I would want to be able to capture version/source as part of the metadata I care about

**Comment by langchain4j** [comment]
Hi @Jaland, `WeaviateEmbeddingStore` was not specifically designed to be compatible with python's version. Feel free to make changes to make it more configurable though
