### ISSUE TITLE
java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by SamuelSoo1508** [langchain4j/langchain4j#173]
I trying out in pojo java with java version 8. I had reference the jar file below for my project:

        - langchain4j-0.22.0.jar
        - langchain4j-core-0.22.0.jar
        - openai4j-0.9.0.jar
        - okhttp-4.9.3.jar
        - okhttp-sse-4.9.3.jar
        - okio-2.8.0.jar
        - retrofit-2.9.0.jar
        - converter-gson-2.9.0.jar
        - gson-2.9.1.jar
        - log4j-api-2.17.2.jar
        - log4j-to-slf4j-2.17.2.jar
        - commons-chain-1.2.jar

Sample code as below:

		String apiKey = "demo";
		 // Create an instance of a model
		ChatLanguageModel chatLanguageModel = OpenAiChatModel.withApiKey(apiKey );

I am getting the error below:
java.lang.ExceptionInInitializerError
        at dev.langchain4j.model.openai.OpenAiChatModel.<init>(OpenAiChatModel.java:68)
        at dev.langchain4j.model.openai.OpenAiChatModel$OpenAiChatModelBuilder.build(OpenAiChatModel.java:44)
        at dev.langchain4j.model.openai.OpenAiChatModel.withApiKey(OpenAiChatModel.java:137)
        at com.applied.hr.OpenAI.service.OpenAIService.showchat(OpenAIService.java:37)

Any idea? what are all the jar file needed in order for langchain4j to run?

**Comment by langchain4j** [comment]
@SamuelSoo1508 could you please provide the complete log? Java version and pom.xml contents would be helpful as well.

To run the code sample you provided you only need:
```xml
<dependency>
    <groupId>dev.langchain4j</groupId>
    <artifactId>langchain4j</artifactId>
    <version>0.22.0</version>
</dependency>
```

**Comment by langchain4j** [comment]
Closing as you did not provide details. Feel free to reopen if needed.
