### ISSUE TITLE
[FEATURE] TokenStream.onRetrieved, please return the score

### ISSUE THREAD

**Issue by yushengliao** [langchain4j/langchain4j#1733]
Knowing the score is important, as contentAggregator, embeddingRetriever, and customRetriever do not have a score in the returned List<Content>. This is crucial for displaying to users during both development and production phases.
And each Retriever's score can be determined to be the best

**Comment by langchain4j** [comment]
@yushengliao we could add a `score` to the `Content` class, but it will only work for `Content`s retuned by `EmbeddingStoreContentRetriever`, other retrievers (including custom ones) won't have it

**Comment by fmx0717** [comment]
@langchain4j 
Could we consider returning the `embedding_id` within the `Content`, so that, in conjunction with the returned `score` and the existing `metadata` and `text`, it would provide more flexibility for handling various business scenarios?

**Comment by langchain4j** [comment]
@fmx0717 we probably could. You can also store the ID in the metadata of `TextSegment` though.

I guess we can add a `Map<String, Object> metadata` field to `dev.langchain4j.rag.content.Content` and store score and embedding id there. WDYT?

**Comment by fmx0717** [comment]
@langchain4j 
Of course, it's a great idea.

**Comment by langchain4j** [comment]
@fmx0717 would you like to open a PR?

**Comment by fmx0717** [comment]
@langchain4j 
Thank you for your trust and the opportunity. I'm very interested in the project and will definitely consider contributing in the future when I have more time. However, I am currently quite busy with other commitments. Thanks again for understanding!

**Comment by yushengliao** [comment]
@langchain4j 

Perhaps I would like to complete this PR. Could you please advise on how to implement it effectively?

1.Add EmbeddingScore and ReRankScore member variables in the `Content` class?
2.Or add key-value pairs for these scores in `Content.TextSegment.Metadata`?

**Comment by langchain4j** [comment]
@yushengliao I would probably introduce a `Map<String, Object> metadata` field in the `dev.langchain4j.rag.content.Content` and store score(s) and other things (e.g. embedding id) there. WDYT?

We also need to make sure that `ContentAggregator` works properly after these changes and does not take this metadata map into account when comparing two `Content`s (e.g., for RRF)

**Comment by emredmrcan** [comment]
> @yushengliao I would probably introduce a `Map<String, Object> metadata` field in the `dev.langchain4j.rag.content.Content` and store score(s) and other things (e.g. embedding id) there. WDYT?
> 
> We also need to make sure that `ContentAggregator` works properly after these changes and does not take this metadata map into account when comparing two `Content`s (e.g., for RRF)

@langchain4j I noticed that there is no assignee for this issue yet. I’d be happy to create a PR for this following your guidance. Let me know if that works!

**Comment by langchain4j** [comment]
@emredmrcan thanks a lot in advance! 🙏

**Comment by emredmrcan** [comment]
> @emredmrcan thanks a lot in advance! 🙏

@langchain4j It's an absolute pleasure to contribute to this project! Please let me know in the PR if anything is missing or if there’s room for improvement. 🙏

**Comment by yushengliao** [comment]
@langchain4j  @emredmrcan    TokenStream.onRetrieved  It can now return scores, but only the scores of the reranker are returned. In the case of mixed search, the scores of the embeddings are not returned

**Comment by langchain4j** [comment]
@emredmrcan could you please take a look? 🙏

**Comment by emredmrcan** [comment]
> @emredmrcan could you please take a look? 🙏

After the holidays, things have been quite busy, but I’ll look at this as soon as possible.
