### ISSUE TITLE
[FEATURE] Anthropic streaming with Tools

### ISSUE THREAD

**Issue by leduckhc** [langchain4j/langchain4j#1738]
**Is your feature request related to a problem? Please describe.**

Anthropic now supports streaming mode with tools declaration https://docs.anthropic.com/en/api/messages-streaming and we should too

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by langchain4j** [comment]
Hi @leduckhc, would you like to take over this?

**Comment by leduckhc** [comment]
@langchain4j I will work on that next week

**Comment by leduckhc** [comment]
@langchain4j, I drafted implementation and will welcome any comments and suggestions
