### ISSUE TITLE
[BUG] Milvus query result metadata data accuracy loss

### ISSUE THREAD

**Issue by yushengliao** [langchain4j/langchain4j#1747]
I used Milvus to query, and in the returned result, metadata={id: xxxxx} The ID value I saved in the database is a number with a length of 19, but the query result seems to get a Scientific notation? And the accuracy is lost. Is this a problem with the Milvus database?

![image](https://github.com/user-attachments/assets/4310888f-5639-44ec-88ff-16f41bdade6e)

**Comment by langchain4j** [comment]
Hi @yushengliao 

> And the accuracy is lost.

Do you mean that the number you get back from the metadata (`Metadata.getLong("id")`) is different from what you've stored?

> Is this a problem with the Milvus database?
It is the problem in our implementation, it uses Gson that automatically treats every number as `Double`.

**Comment by yushengliao** [comment]
> Do you mean that the number you get back from the metadata (`Metadata.getLong("id")`) is different from what you've stored?

yes

**Comment by langchain4j** [comment]
@yushengliao could you please provide the number so that I can reproduce?

**Comment by yushengliao** [comment]
@langchain4j 

1746714878034235396
1746714878034235397
1746803573369675778
1746803573373870081
1746803573373870082
1746803573373870083
1746803573378064385

These are all IDs generated by the snowflake algorithm

**Comment by langchain4j** [comment]
@yushengliao thank you for the clarification! https://github.com/langchain4j/langchain4j/pull/1949 should fix this problem
