### ISSUE TITLE
[FEATURE] Add custom headers on Azure OpenAI model builders

### ISSUE THREAD

**Issue by afrancescon** [langchain4j/langchain4j#1751]
**Is your feature request related to a problem? Please describe.**
I need to add a custom header to underlined HTTP request.

**Describe the solution you'd like**
All Azure OpenAI model builders should have a `customHeader(Map<String, String> customHeaders)` method.

**Describe alternatives you've considered**
None

**Additional context**
Use same approach used, for ex., on OpenAI models.

See pull request #1752

**Comment by jdubois** [comment]
What's the use case for this? The requests are all sent to Azure OpenAI, and we won't do anything on our side with some extra headers, so I don't understand why this would be useful. Are the requests going through a proxy on your side?

**Comment by afrancescon** [comment]
I'm working on a project that require to add an header named `X-Use-Case` to be used for accounting reason.

**Comment by jdubois** [comment]
Oh maybe you have a load balancer in front of Azure OpenAI, something like Azure API Management, that uses this header? OK, I get the use case, that's interesting.
