### ISSUE TITLE
Anthropic: add ChatModelListener support

### ISSUE THREAD

**Issue by langchain4j** [langchain4j/langchain4j#1757]
Add `ChatModelListener` support to `AnthropicChatModel` and `AnthropicStreamingChatModel`.
See `OpenAiChatModel` and `OpenAiStreamingChatModel` as an example.

**Comment by langchain4j** [comment]
Tests are already in place, one should just extend `ChatModelListenerIT` and `StreamingChatModelListenerIT`, see `OpenAiChatModelListenerIT` `OpenAiStreamingChatModelListenerIT` as an example.

**Comment by markort147** [comment]
@langchain4j I need some clarifications about this issue:
- Is it fine to extend the tests using any Claud version?
- Which branch should I fork the repo from?

**Comment by langchain4j** [comment]
@markort147 

> Is it fine to extend the tests using any Claud version?

Yes, which version do oyu have in mind?

> Which branch should I fork the repo from?

main


Please note that there is [this PR](https://github.com/langchain4j/langchain4j/pull/1791) already from @Claudio-code

**Comment by markort147** [comment]
@langchain4j 
Uh, ok. I'm still diving into the codebase looking for another opportunity to contribute.
