### ISSUE TITLE
Do you have any good suggestions for Chinese word segmentation

### ISSUE THREAD

**Issue by caopengan** [langchain4j/langchain4j#176]
I feel that the semantic understanding of Chinese is much more complicated than that of English

**Comment by langchain4j** [comment]
@caopengan what do you mean by segmentation? Can you show an example?

**Comment by caopengan** [comment]
> @caopengan what do you mean by segmentation? Can you show an example?

Excuse me... Maybe my expression is not very clear, I found that using Chinese vector query, the similarity is not too high, is there any good solution to this? Is it related to word segmentation? Any good suggestions?

**Comment by langchain4j** [comment]
@caopengan which model are you using? Do you see a bad quality of search or just a low score number? Score should not be considered in isolation, only in relationship with other results. Some models naturally return low scores, some other models can return very high scores...

**Comment by caopengan** [comment]
I did use BGE_SMALL_ZH, but when using Chinese word segmentation, the result is always not satisfactory

**Comment by caopengan** [comment]
> @caopengan which model are you using? Do you see a bad quality of search or just a low score number? Score should not be considered in isolation, only in relationship with other results. Some models naturally return low scores, some other models can return very high scores...

I did use BGE_SMALL_ZH, but when using Chinese word segmentation, the result is always not satisfactory

**Comment by langchain4j** [comment]
I am afraid there is nothing we can fix here, try using better chinese embedding models

**Comment by caopengan** [comment]
> I am afraid there is nothing we can fix here, try using better chinese embedding models

ok,Thank you for your efforts
