### ISSUE TITLE
[FEATURE] Add read timeout to Gemini

### ISSUE THREAD

**Issue by itxsvv** [langchain4j/langchain4j#1770]
**Is your feature request related to a problem? Please describe.**
Some requests take alot of time - like 1 min (default timeout of OkHttpClient is 10sec only)

**Describe the solution you'd like**
Add availability to set read timeout for httpRequest

**Describe alternatives you've considered**

**Additional context**

**Comment by glaforge** [comment]
Great idea!
I'll add a configurable timeout:

I'll update the client as follows:
```java
            OkHttpClient okHttpClient = new OkHttpClient.Builder()
                .addInterceptor(logging)
                .callTimeout(this.timeout)
                .build();
```

And then, when using the model builder, you'll have a new method:
```java
        GoogleAiGeminiChatModel gemini = GoogleAiGeminiChatModel.builder()
            .apiKey(GOOGLE_AI_GEMINI_API_KEY)
            .modelName("gemini-1.5-flash")
            .timeout(Duration.ofSeconds(60))
            .build();
```

I'll make the default to be 60s.

**Comment by langchain4j** [comment]
Implemented in https://github.com/glaforge/langchain4j/commit/7b9968b7338c00df21b5f6581f58fc7a5324d38b
