### ISSUE TITLE
[BUG] When use function calls  , it might result in the function being called multiple times in a loop.

### ISSUE THREAD

**Issue by sakoojiang** [langchain4j/langchain4j#1777]
**Describe the bug**

When use function calls  , it might result in the function being called multiple times in a loop.

**To Reproduce**
```
   ChatLanguageModel model = OllamaChatModel.builder()
            .baseUrl("http://localhost:11434")
            .modelName("qwen2:7b")
            .maxRetries(1)
            .build();
    static class Tools {
        @Tool
        int add(int a, int b) {
            log.info("{} + {} is {}",a,b,a+b);
            return a + b;
        }

    }
    @Test
    public void test1(){
        ToolTest.Assistant assistant = AiServices.builder(ToolTest.Assistant.class)
                .chatLanguageModel(model)
                .tools(new ToolTest.Tools())
                .build();
        System.out.println(assistant.chat("What is  3+4?"));
    }

```
  log export:
  10:29:27.883 [main] INFO com.ai.test.ToolTest -- 3 + 4 is 7
  10:29:29.557 [main] INFO com.ai.test.ToolTest -- 3 + 4 is 7
  10:29:31.230 [main] INFO com.ai.test.ToolTest -- 3 + 4 is 7
  10:29:32.935 [main] INFO com.ai.test.ToolTest -- 3 + 4 is 7
  The result of adding 3 and 4 is 7.

**Expected behavior**
Tools.add called  once

**Please complete the following information:**
- LangChain4j version:  0.3.4
- LLM(s) used:    ollama [qwen2:7b]
- Java version:   21
- Spring Boot version (if applicable): 

**fix  suggest **
modify OllamaMessagesUtils.otherMessages as bellow(qwen2 test only):

    private static Message otherMessages(ChatMessage chatMessage) {
        if(chatMessage instanceof AiMessage aiMessage){
            if(aiMessage.hasToolExecutionRequests()){
                List<ToolCall> toolCalls =aiMessage.toolExecutionRequests()
                        .stream().map(req->{
                            FunctionCall functionCall = FunctionCall.builder()
                                    .name(req.name())
                                    .arguments(Json.fromJson(req.arguments(), HashMap.class))
                                    .build();
                            return  ToolCall.builder()
                                    .function(functionCall).build();
                        }) .toList();
                return Message.builder()
                        .role(Role.ASSISTANT)
                        .toolCalls(toolCalls)
                        .build();
            }
        }
        return Message.builder()
                .role(toOllamaRole(chatMessage.type()))
                .content(chatMessage.text())
                .build();
    }

**Comment by Martin7-1** [comment]
@sakoojiang Thank you! Looks like it's a problem only related to `langchain4j-ollama` right? Will take a look and fix it asap.

BTW, could you please add `logRequests(true)` and `logResponses(true)` in `OllamaChatModel` and show it completely?

**Additions:**

It looks like `Ollama` REST API `chat` has two fields about tools:

1. `tool_calls` in message(optional): a list of tools the model wants to use
2. `tools`: tools for the model to use if supported. Requires stream to be set to false

In `Ollama` [REST API document](https://github.com/ollama/ollama/blob/main/docs/api.md#generate-a-chat-completion), looks like `tool_calls` filed is used in ChatResponse, And `tools` field is used in ChatRequest.

I am confused about your fix suggest, Could you please explain it in detail? Looks like you add message `tool_calls` field when request ollama, but it seems not required.

**Comment by Martin7-1** [comment]
Hmmm...After reproducing you use case, I think the problem is that the history does not carry the correct messages:

The original messages:

```json
{
    "model": "qwen2:7b-instruct-q2_K",
    "messages": [
        {
            "role": "user",
            "content": "What is  3+4?"
        },
        {
            "role": "assistant"
        },
        {
            "role": "tool",
            "content": "7"
        }
    ],
    "options": {},
    "stream": false,
    "tools": [
        {
            "type": "function",
            "function": {
                "name": "add",
                "description": "",
                "parameters": {
                    "properties": {
                        "arg1": {
                            "type": "integer"
                        },
                        "arg0": {
                            "type": "integer"
                        }
                    },
                    "required": [
                        "arg0",
                        "arg1"
                    ]
                }
            }
        }
    ]
}
```

After the fix you suggest:

```json
{
  "model" : "qwen2:7b-instruct-q2_K",
  "messages" : [ {
    "role" : "user",
    "content" : "What is  3+4?"
  }, {
    "role" : "assistant",
    "tool_calls" : [ {
      "function" : {
        "name" : "add",
        "arguments" : {
          "arg1" : 4,
          "arg0" : 3
        }
      }
    } ]
  }, {
    "role" : "tool",
    "content" : "7"
  } ],
  "options" : { },
  "stream" : false,
  "tools" : [ {
    "type" : "function",
    "function" : {
      "name" : "add",
      "description" : "",
      "parameters" : {
        "type" : "object",
        "properties" : {
          "arg1" : {
            "type" : "integer"
          },
          "arg0" : {
            "type" : "integer"
          }
        },
        "required" : [ "arg0", "arg1" ]
      }
    }
  } ]
}
```

Maybe the model try to call the tool many times is due to the lack of `tool_calls`.
