### ISSUE TITLE
[FEATURE] Google AI Gemini — Implement a Tokenizer

### ISSUE THREAD

**Issue by glaforge** [langchain4j/langchain4j#1790]
To benefit from the tokenization support offered by our document splitters, the idea is to implement a Tokenizer for the Gemini models.

**Comment by langchain4j** [comment]
Implemented in https://github.com/glaforge/langchain4j/commit/6b7dcab7d5edbab7ef2c490c16d88fae24cac378#diff-c8be04ead99b6c91ad0fb6e9c2b5195193b5b21e2f3b8b5875b4b0e3be9f20e8
