### ISSUE TITLE
[FEATURE] SystemMessage sometimes not sent to gpt

### ISSUE THREAD

**Issue by vcjj** [langchain4j/langchain4j#180]
when I use service and ChatMemory,  i set memory window to 3, and set @SystemMessage annotation，as the oldest message removed , the system message promot disappear, does it right? Is that a bug?
![image](https://github.com/langchain4j/langchain4j/assets/26586739/fad60f0d-fc01-48e0-a3d1-cefa73df0c09)

**Comment by langchain4j** [comment]
@vcjj this is a bug, thank you for pointing it out!

**Comment by kuraleta** [comment]
hi, @vcjj please check the new version 0.23.0. there is a bug fix. We will close this issue as completed. If you need any help or have other concerns feel free to reopen the issue.
