### ISSUE TITLE
Voyage AI: Implement Embedding Model

### ISSUE THREAD

**Issue by langchain4j** [langchain4j/langchain4j#1813]
Implement `VoyageAiEmbeddingModel`.

Documentation: https://docs.voyageai.com/docs/embeddings

See `CohereEmbeddingModel` as an example.

**Comment by Martin7-1** [comment]
@langchain4j Hi! Could you please assign this issue to me?

**Comment by langchain4j** [comment]
Implemented in https://github.com/langchain4j/langchain4j/pull/1816
