### ISSUE TITLE
[BUG] OllamaDateDeserializer parse 2024-06-15T05:18:13.974383393-07:00 Method threw 'java.lang.StringIndexOutOfBoundsException' exception.

### ISSUE THREAD

**Issue by beiliubei** [langchain4j/langchain4j#1824]
**Describe the bug**

**Log and Stack trace**

**To Reproduce**

**Expected behavior**

**Please complete the following information:**
- LangChain4j version: 0.34.0
- LLM(s) used: 
- Java version: 
- Spring Boot version (if applicable): 

**Additional context**

**Comment by langchain4j** [comment]
cc @bidek
