### ISSUE TITLE
[BUG] Pipelines java_build failure

### ISSUE THREAD

**Issue by Claudio-code** [langchain4j/langchain4j#1835]
**Describe the bug**

When pipeline is running Java Build on all versions fails with same errors on OpenIA tests
![Screenshot from 2024-09-25 19-20-47](https://github.com/user-attachments/assets/33734413-f9c9-466a-bb09-42c0539e6637)

https://github.com/langchain4j/langchain4j/actions/runs/11041955007/job/30673342561?pr=1826

**Log and Stack trace**

**To Reproduce**

**Expected behavior**

**Please complete the following information:**
- LangChain4j version:
- LLM(s) used: 
- Java version: 
- Spring Boot version (if applicable): 

**Additional context**

**Comment by kpavlov** [comment]
It is a limitation of GitHub, it does not inject secrets for fork builds. You may open PR against main branch in YOUR repository (like [here](https://github.com/kpavlov/langchain4j/pulls?q=is%3Apr+)) and it will run all unti tests and skip integration tests. You may run integration tests locally using your own credentials. That was changed in #1913
