### ISSUE TITLE
[BUG] Tools doesnt work when AiServices using TokenStream

### ISSUE THREAD

**Issue by chenhaoqiang** [langchain4j/langchain4j#184]
when return type is TokenStream, Tools doesnt work. Is that a bug?
![image](https://github.com/langchain4j/langchain4j/assets/20062034/25270fd5-b5e1-4d13-a290-4ed447f80135)

**Comment by langchain4j** [comment]
@chenhaoqiang do you have a concrete example of when tools are not working? Tools are still supposed to work even when return type is TokenStream. See [`StreamingAiServicesIT.should_execute_tool_then_stream_answer()` test](https://github.com/langchain4j/langchain4j/blob/271fdd61e2f2949125fc560ff978843d00a3437a/langchain4j/src/test/java/dev/langchain4j/service/StreamingAiServicesIT.java#L126)

**Comment by chenhaoqiang** [comment]
> @chenhaoqiang do you have a concrete example of when tools are not working? Tools are still supposed to work even when return type is TokenStream. See [`StreamingAiServicesIT.should_execute_tool_then_stream_answer()` test](https://github.com/langchain4j/langchain4j/blob/271fdd61e2f2949125fc560ff978843d00a3437a/langchain4j/src/test/java/dev/langchain4j/service/StreamingAiServicesIT.java#L126)

I will try. Thx!

**Comment by chenhaoqiang** [comment]
> @chenhaoqiang do you have a concrete example of when tools are not working? Tools are still supposed to work even when return type is TokenStream. See [`StreamingAiServicesIT.should_execute_tool_then_stream_answer()` test](https://github.com/langchain4j/langchain4j/blob/271fdd61e2f2949125fc560ff978843d00a3437a/langchain4j/src/test/java/dev/langchain4j/service/StreamingAiServicesIT.java#L126)

Sorry, I made a mistake. I tried this and it worked. Sorry for causing you trouble.

**Comment by langchain4j** [comment]
@chenhaoqiang no worries!
