### ISSUE TITLE
[FEATURE] Milvus: configurable field names

### ISSUE THREAD

**Issue by timspannzilliz** [langchain4j/langchain4j#1842]
**Is your feature request related to a problem? Please describe.**

https://github.com/langchain4j/langchain4j/blob/11855157dd71eb52d603c981a4e3ac561a336107/langchain4j-milvus/src/main/java/dev/langchain4j/store/embedding/milvus/MilvusEmbeddingStore.java

        //static final String ID_FIELD_NAME = "id";
        //static final String TEXT_FIELD_NAME = "text";
        //static final String METADATA_FIELD_NAME = "metadata";
        //static final String VECTOR_FIELD_NAME = "vector";

These are hardcoded, if I want to reuse an existing collection it can have different names for these.   I may also have multiple field names.

**Describe the solution you'd like**

Make these changeable via set, parameter on create or builder

**Describe alternatives you've considered**

Make these changeable via set, parameter on create or builder

Or at least make them properties in a app resources file

**Additional context**
LangChain supports this in Python.

As a Milvus user I usually have different field names and multiple vectors in my collection

**Comment by hrhrng** [comment]
@timspannzilliz Do you have a plan to implement this? I can also help.
