### ISSUE TITLE
[BUG] OllamaModelsBuilder methods are package private

### ISSUE THREAD

**Issue by Blarc** [langchain4j/langchain4j#1849]
**Describe the bug**

After upgrading from 0.34.0 to 0.35.0, my code doesn't compile, because OllamaModelsBuilder methods are now package private.

![image](https://github.com/user-attachments/assets/7238eb48-365b-4f49-a2f6-af176a6b2e57)

**Log and Stack trace**

```
Cannot access 'fun timeout(p0: Duration!): OllamaModels.OllamaModelsBuilder!': it is package-private in 'dev/langchain4j/model/ollama/OllamaModels.OllamaModelsBuilder'.
```

**Expected behavior**

Methods should've stayed public?

**Please complete the following information:**
- LangChain4j version: 0.35.0
- LLM(s) used: Ollama
- Java version: 21

**Additional context**

This was changed by the following MR: https://github.com/langchain4j/langchain4j/pull/1658.

**Comment by Martin7-1** [comment]
Looks like it's solved in #1843
