### ISSUE TITLE
[BUG] `EmbeddingMatch` result from `EmbeddingStore.findRelevant` returns `null` for associated embedding

### ISSUE THREAD

**Issue by ff137** [langchain4j/langchain4j#185]
Good day.

I have set up some code where we add many embeddings (about ~100) to an EmbeddingStore, and then use `findRelevant` to retrieve the most relevant embedding based on some query.

I'm running my project in Scala.

Here's a summary of the code that I've written, with comments to help read it:

```scala
// define model
  private val embeddingModel: EmbeddingModel = HuggingFaceEmbeddingModel
    .builder()
    .accessToken(sys.env("HF_API_KEY"))
    .modelId("sentence-transformers/all-MiniLM-L6-v2")
    .waitForModel(true)
    .timeout(Duration.ofSeconds(60))
    .build()

// define store
  private val embeddingStore: EmbeddingStore[TextSegment] =
    new InMemoryEmbeddingStore[TextSegment]()

// helper methods
  def embedAll(inputList: java.util.List[TextSegment]): java.util.List[Embedding] = {
    embeddingModel.embedAll(inputList)
  }

  def storeAllEmbeddings(embeddings: java.util.List[Embedding]): Unit = {
    embeddingStore.addAll(embeddings)
  }

// Function to take a list of "Opportunity" case classes as input. 
// From the list, we define text segments, then call embedAll and storeAll
  def getAndStoreAll(opportunities: List[Opportunity]): Unit = {
    val textSegments: List[TextSegment] = opportunities.map { opportunity =>
      val metadata = Metadata() // all of the following are strings:
        .add("id", opportunity.id)
        .add("title", opportunity.title)
        .add("organisationName", opportunity.organisationName)

      TextSegment.from(opportunity.description.take(256), metadata)
    } 

// the above gives us a list of TextSegments (with input text + metadata). Now embed and store:

    val embeddings: java.util.List[Embedding] = embedAll(textSegments.asJava)
    storeAllEmbeddings(embeddings)
  }

// Then our function to retrieve the most relevant opportunity, based on some input query:
  def findMostRelevantFromQuery(
      queryText: String,
      maxResults: Int = 1
  ): EmbeddingMatch[TextSegment] = {
    val queryEmbedding: Embedding = embeddingModel.embed(queryText.take(256))

    val relevant: List[EmbeddingMatch[TextSegment]] =
      embeddingStore.findRelevant(queryEmbedding, maxResults).asScala.toList

    val embeddingMatch = relevant.headOption
    embeddingMatch match
      case None        =>
        // handle no result
      case Some(value) =>
        scribe.info(s"Got embedding match with: $value")
        value
  }
```

Now, the above code works. We can successfully create and store all the embeddings, and then the `findRelevant` result does indeed give us a match when we test with a sample query:
```
Got embedding match with: EmbeddingMatch { score = 0.7731258459290872, embedded = null, embeddingId = 80bcb216-7d33-4813-800e-e7e10d19c440, embedding = Embedding { vector = [0.016193626, ... ] } }
```

However, the problem is that I was hoping for `embedded` to contain the TextSegment that has been matched with. Instead, we get null.

There also doesn't seem to be a way to use the `embeddingId` to retrieve the TextSegment from the embedding store.
So, all I can see is that we got a match with a score, but we can't return the data that has been matched with.

Does anyone know how we might move forward to debugging this? Or how we can use the embeddingId to fetch the associated TextSegment from the store? Any help will be appreciated!

Thanks for your time!

**Please complete the following information:**
- LangChain4j version: 0.22.0
- Java version: 20
- Spring Boot version: n/a

**Comment by Martin7-1** [comment]
>   def storeAllEmbeddings(embeddings: java.util.List[Embedding]): Unit = {
>    embeddingStore.addAll(embeddings)
>  }

`Embedding` class doesn't contains `TextSegment`, so actually you should use `addAll(List<Embedding>, List<TextSegment>)` method instead of `addAll(List<Embedding>)`? I'm not very good at scala, but I hope this answer helps you

**Comment by ff137** [comment]
> `Embedding` class doesn't contains `TextSegment`, so actually you should use `addAll(List<Embedding>, List<TextSegment>)` method instead of `addAll(List<Embedding>)`? I'm not very good at scala, but I hope this answer helps you

@Martin7-1 that's absolutely right! Thank you. That was my oversight - I missed that EmbeddingStore has two methods for `addAll`, and that `Embedding` alone doesn't contain original metadata.

At the least I wanted to suggest that the EmbeddingStore needs a way to fetch with the embeddingId, because that functionality seems missing. But that's not necessary now that we get the metadata with the match. Thanks again!
