### ISSUE TITLE
[BUG] Tool function with parameter List<Integer> incorrectly parsed as List<Double>

### ISSUE THREAD

**Issue by rwankar** [langchain4j/langchain4j#1858]
I've defined a tool with a function like this.

```
        @Tool("Finds books based on filters. Returns a json array of books with different attributes. At least one parameter is required.")
        String findBooks(
            @P(value = "A filter to find/search books by their name.", required = false) String match,
            @P(value = "A JSON array of authors (or user) IDs to filter by authors.", required = false) List<Integer> authors,
        {
        }

```
The LLM made a call to the tool as below.

```
{
    "role" : "assistant",
    "tool_calls" : [ {
      "id" : "call_8yxDdgTdIN4Ljzo7jXIsoW3B",
      "type" : "function",
      "function" : {
        "name" : "findBooks",
        "arguments" : "{\"arg1\":[123]}"
      }
    } ]
  }

```

As you can see the LLM returned an array of Integer, but in the function I get the value 123.0. Looks like an issue with parsing.

**Comment by glaforge** [comment]
Hi, which model do you use?
Out of curiosity, what happens if you use an `int[]` array instead?

**Comment by langchain4j** [comment]
@rwankar thank you!

This is a known bug: https://github.com/langchain4j/langchain4j/blob/23bfad5c9e6565caa33d4390414aec239982c355/langchain4j/src/test/java/dev/langchain4j/service/AiServicesWithToolsIT.java#L474
