### ISSUE TITLE
[BUG] OpenAiStreamingChatModel - Okhttp3 exception - java.lang.ClassNotFoundException: okhttp3.internal.Util

### ISSUE THREAD

**Issue by phankhanhngan** [langchain4j/langchain4j#1860]
There is an okhttp exception raised when I tried to integrate with `OpenAiStreamingChatModel`.  

**Describe the bug**
There is no streaming response return but this Exception `Caused by: java.lang.ClassNotFoundException: okhttp3.internal.Util`

**Log and Stack trace**
```
Exception in thread "OkHttp Dispatcher" java.lang.NoClassDefFoundError: okhttp3/internal/Util
	at okhttp3.internal.sse.RealEventSource.processResponse(RealEventSource.kt:69)
	at okhttp3.internal.sse.RealEventSource.onResponse(RealEventSource.kt:46)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:539)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.ClassNotFoundException: okhttp3.internal.Util
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 6 more
Caused by: java.lang.ClassNotFoundException: okhttp3.internal.Util
```

**To Reproduce**
This is the code snippet I got from you at https://github.com/langchain4j/langchain4j/issues/433#issuecomment-1884695337 and I was trying to run them
```
fun test() {
    val store: ChatMemoryStore = object : ChatMemoryStore {
      var messages: List<ChatMessage> = ArrayList()

      override fun getMessages(memoryId: Any): List<ChatMessage> {
        return messages
      }

      override fun updateMessages(memoryId: Any, messages: List<ChatMessage>) {
        this.messages = messages
        println("updateMessages: $messages")
      }

      override fun deleteMessages(memoryId: Any) {
      }
    }

    val chatMemoryProvider = ChatMemoryProvider { memoryId: Any? ->
      MessageWindowChatMemory.builder()
        .id(memoryId)
        .maxMessages(10)
        .chatMemoryStore(store)
        .build()
    }

    val model = OpenAiStreamingChatModel.builder()
      .apiKey(apiKey)
      .modelName("gpt-4o")
      .timeout(Duration.ofSeconds(30))
      .build()

    val assistant: Assistant = AiServices.builder(Assistant::class.java)
      .streamingChatLanguageModel(model)
      .chatMemoryProvider(chatMemoryProvider)
      .build()

    assistant.chat("Tell me a joke")
        ?.onNext {
          token -> println("onNext: $token")
        }
      ?.onComplete(System.out::println)
      ?.onError { error -> error.printStackTrace() }
      ?.start()
  }

  interface Assistant {
    fun chat(userMessage: String?): TokenStream?
  }
```

**Expected behavior**
- According to your response, the expected result should be:
```
updateMessages: [UserMessage { name = null text = "Tell me a joke" }]

Sure
,
 here
's
 a
 joke
 for
 you
:


Why
 don
't
 scientists
 trust
 atoms
?


Because
 they
 make
 up
 everything
!
updateMessages: [UserMessage { name = null text = "Tell me a joke" }, AiMessage { text = "Sure, here's a joke for you:

Why don't scientists trust atoms?

Because they make up everything!" toolExecutionRequests = null }]
Response { content = AiMessage { text = "Sure, here's a joke for you:

Why don't scientists trust atoms?

Because they make up everything!" toolExecutionRequests = null }, tokenUsage = TokenUsage { inputTokenCount = 11, outputTokenCount = 22, totalTokenCount = 33 }, finishReason = STOP }
```

**Please complete the following information:**
- LangChain4j version: 0.35.0
- LLM(s) used: OpenAI (GPT 4o)
- Java version: 17
- Spring Boot version (if applicable): I am using Micronaut 3.7.1

**Comment by langchain4j** [comment]
Hi @phankhanhngan, this error usually happens when you have cnflicting versions of the library in classpath.

Please provide the output of `mvn dependency:tree -Dverbose`

**Comment by langchain4j** [comment]
[Answer by hieudoraemon](https://discord.com/channels/1156626270772269217/1292338064009597020/1292911108000321678) from discord:

> Hi @LangChain4j Since our project used Gradle, not POM, so here's the result for ./gradlew dependencies --configuration compileClasspath
> compileClasspath - Compile classpath for null/main.
> --- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.20
>      +--- org.jetbrains.kotlin:kotlin-stdlib:1.8.20
>      |    +--- org.jetbrains.kotlin:kotlin-stdlib-common:1.8.20
>      |    --- org.jetbrains:annotations:13.0
>      --- org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.8.20
>           --- org.jetbrains.kotlin:kotlin-stdlib:1.8.20 (*)
> We suspect if there's something wrong with our okhttp3 version since our used 4.9.3, and yours are using something different

**Comment by phankhanhngan** [comment]
It is a library conflict. I have resolved this.

The OkHttp version conflict is from AWS SDK for Kotlin. Currently, they have no plans to downgrade OkHttp. However, they’ve released a new HTTP engine based on OkHttp3 4.x to address this issue.

Follow their configuration below to resolve the conflict:
```
dependencies {
    implementation("aws.sdk.kotlin:s3:$SDK_VERSION") // and other AWS SDK clients...
    implementation("aws.smithy.kotlin:http-client-engine-okhttp4:$SMITHY_KOTLIN_VERSION") // use OkHttp4Engine
}
```
```
configurations.all {
    resolutionStrategy {
        // Force resolution to OkHttp 4.x
        force("com.squareup.okhttp3:okhttp:4.12.0") // or the version you are using...
    }
    exclude(group = "com.squareup.okhttp3", module = "okhttp-coroutines") // Exclude okhttp-coroutines dependency, introduced in 5.0.0-alpha.X
}
```

Related issues: https://github.com/awslabs/aws-sdk-kotlin/issues/765
Related solution: https://github.com/smithy-lang/smithy-kotlin/tree/main/runtime/protocol/http-client-engines/http-client-engine-okhttp4#configuration
