### ISSUE TITLE
[BUG] langchain4j-openai-spring-boot-starter and langchain4j-azure-openai-spring-boot-starter cannot be used together

### ISSUE THREAD

**Issue by myrosia** [langchain4j/langchain4j#1867]
**Describe the bug**

It's impossible to include "dev.langchain4j:langchain4j-open-ai-spring-boot-starter" and "dev.langchain4j:langchain4j-azure-open-ai-spring-boot-starter" together in the same project.

We have an app where we would like to use either ChatGPT on Azure or openai API directly depending on the profile, and be able to configure it in the application.yml

The system works fine if I include "dev.langchain4j:langchain4j-open-ai-spring-boot-starter" and a corresponding configuration in application.yml. It also works if I use "dev.langchain4j:langchain4j-azure-open-ai-spring-boot-starter" and an azure-specific configuration.

But if I include both dependencies, the system fails to start up with the following message: The bean 'openAiTokenizer', defined in class path resource [dev/langchain4j/openai/spring/AutoConfig.class], could not be registered. A bean with that name has already been defined in class path resource [dev/langchain4j/azure/openai/spring/AutoConfig.class] and overriding is disabled.

**Log and Stack trace**
```
2024-10-03 17:38:44 [main] WARN  o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.support.BeanDefinitionOverrideException: Invalid bean definition with name 'openAiTokenizer' defined in class path resource [dev/langchain4j/openai/spring/AutoConfig.class]: Cannot register bean definition [Root bean: class [null]; scope=; abstract=false; lazyInit=null; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=dev.langchain4j.openai.spring.AutoConfig; factoryMethodName=openAiTokenizer; initMethodNames=null; destroyMethodNames=[(inferred)]; defined in class path resource [dev/langchain4j/openai/spring/AutoConfig.class]] for bean 'openAiTokenizer' since there is already [Root bean: class [null]; scope=; abstract=false; lazyInit=null; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=dev.langchain4j.azure.openai.spring.AutoConfig; factoryMethodName=openAiTokenizer; initMethodNames=null; destroyMethodNames=[(inferred)]; defined in class path resource [dev/langchain4j/azure/openai/spring/AutoConfig.class]] bound. 

***************************
APPLICATION FAILED TO START
***************************

Description:

The bean 'openAiTokenizer', defined in class path resource [dev/langchain4j/openai/spring/AutoConfig.class], could not be registered. A bean with that name has already been defined in class path resource [dev/langchain4j/azure/openai/spring/AutoConfig.class] and overriding is disabled.

Action:

Consider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true

Process finished with exit code 1
```

**To Reproduce**

lib.versions.toml
```
[versions]
langchain4j = "0.34.0"

[libraries]

langchain4j = { module = "dev.langchain4j:langchain4j", version.ref = "langchain4j" }
langchain4j-openai = { module = "dev.langchain4j:langchain4j-open-ai", version.ref = "langchain4j" }
langchain4j-openai-spring-boot-starter = { module = "dev.langchain4j:langchain4j-open-ai-spring-boot-starter", version.ref = "langchain4j" }
langchain4j-azure-openai = { module = "dev.langchain4j:langchain4j-azure-open-ai", version.ref = "langchain4j" }
langchain4j-azure-openai-spring-boot-starter = { module = "dev.langchain4j:langchain4j-azure-open-ai-spring-boot-starter", version.ref = "langchain4j" }
langchain4j-spring-boot-starter = { module = "dev.langchain4j:langchain4j-spring-boot-starter", version.ref = "langchain4j" }
```

build.gradle.kts
```
    // LangChain4j
    implementation(libs.langchain4j)
    implementation(libs.langchain4j.spring.boot.starter)
    implementation(libs.langchain4j.openai)
    implementation(libs.langchain4j.openai.spring.boot.starter)
    implementation(libs.langchain4j.azure.openai)
    implementation(libs.langchain4j.azure.openai.spring.boot.starter)
```

application.yml
```
langchain4j:
  azure-open-ai:
    chat-model:
      deployment-name: local-test-model-gpt-4o-2024-05-13
      log-requests-and-responses: true
      endpoint: https://<ourresource>.openai.azure.com
      api-key: ${AZURE_API_KEY:dummy_key_to_satisfy_langchain4j_factory}
      temperature: 0
```

Code:
```
@AiService
fun interface LlmIntentRecognitionService {
    @SystemMessage(SYSTEM_MESSAGE)
    fun chat(text: String): String
```

**Expected behavior**

An application starts up. I can call `LlmIntentRecognitionService.chat("Some prompt")` and receive a response from Azure

I can change my `application.yml` to contain a set of `langchain4j.open-ai.chat-model` properties instead of the configuration above and receive a response from OpenAi

**Please complete the following information:**
- LangChain4j version: 0.34
- LLM(s) used:  azure-open-ai (gpt-4o), open-ai (gpt-4o)
- Java version: Coretto-21 JDK
- Spring Boot version (if applicable): 3.3.4

**Additional context**

I cannot simply enable bean overriding in Spring because it may initialize the wrong tokenizer to go with the model, seeing as these are order dependent. Looking at the source code, it seems that definitions of `openAiTokenizer` in `AutoConfig` in both classes are the only one not marked as "conditionalOnProperty" and have identical names, but I don't know enough about the auto-configuration mechanism to know what would fix it.

**Comment by jdubois** [comment]
Thanks, I'm doing a PR on the LangChain4J-Spring project, and will link it here

**Comment by jdubois** [comment]
PR is at https://github.com/langchain4j/langchain4j-spring/pull/45

**Comment by CanEkinci** [comment]
Hello @jdubois. 

I have discovered the same error in version 0.35.0. The bug has already been fixed, but when can we expect a release? 

Many thanks in advance

**Comment by langchain4j** [comment]
@CanEkinci I am doing a release right now, should be available in a few hours. Could you please link the fix of the bug here? Thanks!

**Comment by CanEkinci** [comment]
@langchain4j: @jdubois has already done this in https://github.com/langchain4j/langchain4j-spring/pull/45
