### ISSUE TITLE
[BUG] Tool calls skip description of properties and required for json objects when they are part of a list

### ISSUE THREAD

**Issue by ashishs** [langchain4j/langchain4j#1881]
Tool calls skip description of properties and required for json objects when they are part of a list.

For example consider the tool definition.

    class MyTool {

    @Tool("get today's temperature for a city")
    fun getTemperature(@P("city, both city name and airport code are required", required = true) city: City): Double {
        return 0.0
    }

    class City(@Description("name of the city") var name: String,
               @Description("airport code of the city") var airportCode: String)
    }
    }

`
{
  "function": {
    "name": "getTemperature",
    "description": "get today's temperature for a city",
    "parameters": {
      "type": "object",
      "properties": {
        "city": {
          "description": "city, both city name and airport code are required",
          "type": "object",
          "properties": {
            "name": {
              "type": "string",
              "description": "name of the city"
            },
            "airportCode": {
              "type": "string",
              "description": "airport code of the city"
            }
          },
          // This is missing  "required": ["name", "airportCode"] // This is missing 
        }
      },
      "required": [
        "city"
      ]
    }
  },
  "type": "function"
}
`

**Expected behavior**
The required for the property "name" and "airportCode" are missing.

**Please complete the following information:**
- LangChain4j version: 0.35.0
- LLM(s) used: OpenAI
- Java version: 17
- Spring Boot version (if applicable): 3.3.0

**Additional context**
The same can be manually constructed programmatically using ToolSpecification builder, but does not work when tools are defined in code.

**Comment by langchain4j** [comment]
@ashishs thanks a lot for reporting!
