### ISSUE TITLE
[BUG] Missing required property KnnQuery.k for ElasticsearchEmbeddingStore

### ISSUE THREAD

**Issue by leduckhc** [langchain4j/langchain4j#1885]
**Describe the bug**

Embedding search does not work for Elasticsearch (client v 8.14.3), it is missing the required parameter `KnnQuery.k`.

**Log and Stack trace**

```
co.elastic.clients.util.MissingRequiredPropertyException: Missing required property 'KnnQuery.k'
	at co.elastic.clients.util.ApiTypeHelper.requireNonNull(ApiTypeHelper.java:76)
	at co.elastic.clients.elasticsearch._types.KnnQuery.<init>(KnnQuery.java:78)
	at co.elastic.clients.elasticsearch._types.KnnQuery.<init>(KnnQuery.java:54)
	at co.elastic.clients.elasticsearch._types.KnnQuery$Builder.build(KnnQuery.java:373)
	at dev.langchain4j.store.embedding.elasticsearch.ElasticsearchConfigurationKnn.internalSearch(ElasticsearchConfigurationKnn.java:68)
	at dev.langchain4j.store.embedding.elasticsearch.ElasticsearchEmbeddingStore.search(ElasticsearchEmbeddingStore.java:297)
```
**To Reproduce**

**Expected behavior**

**Please complete the following information:**
- LangChain4j version: 0.35.0
- LLM(s) used:  ElasticsearchEmbeddingStore
- Java version: 
- Spring Boot version (if applicable): 

**Additional context**

**Comment by langchain4j** [comment]
@leduckhc `langchain4j-elasticsearch` 0.35.0 is compatible with Elasticsearch 8.14.3, so I am not sure this is a bug. I guess we have to update to the latest version of Elasticsearch client in the next release though.

**Comment by leduckhc** [comment]
@langchain4j , IMHO, update to the latest version of ES client is necessary. Should I open PR and contribute an update?

I would like to also point out that integration tests that LC4J have with testcontainers was not able to catch this exception (error). 🤷

**Comment by langchain4j** [comment]
> I would like to also point out that integration tests that LC4J have with testcontainers was not able to catch this exception (error). 🤷

Because it runs agains 8.14.3 (which we support) and it works with that version.

We do not advertise anywhere that we support 8.15+ version.

**Comment by leduckhc** [comment]
@langchain4j  Don"t get me wrong, vector search **does not** work with implementation of ES client 8.14.3 that comes with LC4J v0.35.0. I will update the issue description to reflect that.

Especially it throws exception when using real ES database instance (not testcontainer)

**Comment by dadoonet** [comment]
I'm looking into this. There are some other things which are breaking with 8.15.2, like the range queries, and the script query.

I'm going to create a PR for this.
And while I'm at it, I'm going to check this specific issue.

**Comment by dadoonet** [comment]
@leduckhc I don't think I'm able to reproduce your issue.

Here's what I'm running:

* Elasticsearch 8.15.2 
* Langchain4j 0.34.0 which uses Elasticsearch client 8.14.3 behind the scene

The following code works for me:

```java
        EmbeddingStore<TextSegment> embeddingStore =
                ElasticsearchEmbeddingStore.builder()
                        .indexName("games")
                        .restClient(client)
                        .build();
        embeddingStore.removeAll();
        embeddingStore.add(response1.content(), game1);
        embeddingStore.add(response2.content(), game2);

        client.performRequest(new Request("POST", "/games/_refresh"));

        String question = "I want to pilot a car";
        Embedding questionAsVector = model.embed(question).content();
        EmbeddingSearchResult<TextSegment> result = embeddingStore.search(EmbeddingSearchRequest.builder()
                .queryEmbedding(questionAsVector)
                .build());
        result.matches().forEach(m -> Logger.info("{} - score [{}]",
                m.embedded().metadata().getString("gameName"), m.score()));
```

So the knn search is working in my case.

Could you tell me exactly what is your setup and how you are running all that? The Java code I mean.

**Comment by langchain4j** [comment]
@dadoonet BTW did you look into hybrid (full-text + vector) search already and [how it would be possible to implement it](https://github.com/langchain4j/langchain4j/issues/1324) in `ElasticsearchEmbeddingStore`?

**Comment by leduckhc** [comment]
@dadoonet sure,

versions: 
- java: tested on both 17 and 20
- langchain4j: 0.35.0 (from tag)
- elasticsearch java client: 8.14.3
- elasticsearch-image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3

```
EmbeddingStore<TextSegment> embeddingStore = ElasticsearchEmbeddingStore
        .builder()
       // .configuration(ElasticsearchConfigurationKnn.builder().numCandidates(1000).build()) // adding this line, does nothing
        .serverUrl(address)
        .userName(userName)
        .password(password)
        .indexName("games")
        .build();
String text = "I like dungeons and dragons";
Embedding vector = model.embed(text).content();
// String id = embeddingStore.add(vector, TextSegment.from(text));

EmbeddingSearchRequest request = EmbeddingSearchRequest.builder()
        .queryEmbedding(vector)
        .maxResults(5)
        .build();
EmbeddingSearchResult<TextSegment> result = embeddingStore.search(request); // This throws exception.
log.info("Search result: {}", result.matches());
```

---

and for 
- langchain4j: 0.35.0 (from tag)
- elasticsearchclient  8.15.2

It does not work out of the box, I had to tweak (aka update the code with new Elasticsearch client) the InlineScript part and RangeQuery parts

**Comment by dadoonet** [comment]
You need to upgrade Elasticsearch cluster to 8.15.2.
