### ISSUE TITLE
[FEATURE] Support FewShotPromptTemplate

### ISSUE THREAD

**Issue by lordofthejars** [langchain4j/langchain4j#1886]
**Describe the solution you'd like**

Implement `FewShotPromptTemplate` class  (https://www.educative.io/answers/what-is-a-fewshotprompttemplate-in-langchain) similar as langchain.

**Describe alternatives you've considered**

You can always use `PromptTemplate` which is already supported in LangChain4j, but the Java version could also provide this integration. 

**Additional context**

I can provide a PR with an initial implementation if you think it has sense.

**Comment by langchain4j** [comment]
Hi @lordofthejars!

We have a similar [feature request](https://github.com/langchain4j/langchain4j/issues/908), could you please check if it will be enough?

(I started developing it already BTW)

**Comment by lordofthejars** [comment]
oh yes it is the same

**Comment by langchain4j** [comment]
@lordofthejars ok, then I will close this as duplicate
