### ISSUE TITLE
[BUG] how to solve a multi step problem by langchain4j tools? Why my response seems can use just one tool instead of two ?

### ISSUE THREAD

**Issue by flatLying** [langchain4j/langchain4j#1894]
![image](https://github.com/user-attachments/assets/46e3d3b7-ffb5-47d5-a81f-0c1297bee1de)
![image](https://github.com/user-attachments/assets/9c5c8729-42e7-4bd2-ae43-9442e981a1c6)
![image](https://github.com/user-attachments/assets/82614c2e-cb3e-4465-9017-0997e528eab4)

As we can see, the final answer is not given. why the second tool was't used?
Thanks so much for help!!!!

**Comment by flatLying** [comment]
After trying different model， I seems to know the reason.
The process works just fine if I use gpt-4.
This kind of problem occures when I use GLM4-flash.

So I wonder if this problem is caused by model ability ? 
Or I use the langchain4j in a wrong way? Thanks

**Comment by langchain4j** [comment]
Hi @flatLying 

> So I wonder if this problem is caused by model ability ?

Seems so, different LLMs cave different abilities with tools.


I would probably merge these 2 tools together to have a "get file content by file id" tool. This should work much more reliable and avoid having an extra round trip to the LLM
