### ISSUE TITLE
[FEATURE] Test base modules without using real providers

### ISSUE THREAD

**Issue by kpavlov** [langchain4j/langchain4j#1899]
**Is your feature request related to a problem? Please describe.**

As a developer, I want the project to be fast and reliable. Currently, cloning and building the project without providing cloud provider credentials does not work, as the tests require a connection to real providers. This makes local testing impossible without using real accounts and is also slow due to internet I/O. Additionally, it complicates testing failure I/O scenarios.

**Describe the solution you'd like**

I propose implementing a test suite that runs locally against mock HTTP/gRPC servers. The advantages of this approach include:
- **Speed**: This will be faster than calling the real LLMs.
- **Determinism**: Tests can control the LLM's responses.
- **Negative Scenario Testing**: It will allow for testing different errors and timeouts.
- **Regression Testing**: We can verify provider clients against expected provider response payloads.

To implement this:
- The current (integration) test suite should remain in place.
- A new set of test suites or Spring test profiles should be created for each provider, allowing for independent testing of various tasks.
- I want to use [Wiremock](https://wiremock.org/) for implementing mock providers, create test DSL for easy describing mock behavior in the tests and also write it in Kotlin, because it is concise and readable, which is very important for tests. Kotlin code can coexists with java code easily.

**Describe alternatives you've considered**

- Adding credentials for each provider, similar to the [CI environment](https://github.com/langchain4j/langchain4j/blob/main/.github/workflows/main.yaml#L61-L94) — this approach is slow and expensive for developers.
- Using only Mockito for mocking and excluding I/O tests from local runs — this raises concerns about verifying regressions.

**Additional context**

To run the project, I used the command:  
```bash
mvn verify
```
and got the errors like:
```
-- Time elapsed: 0 s <<< ERROR!
java.lang.IllegalArgumentException: openAiApiKey cannot be null or empty. API keys can be generated here: https://platform.openai.com/account/api-keys
 ```

**Comment by langchain4j** [comment]
@kpavlov I am all for using mock HTTP servers for testing some specific error scenarios, but for regular tests I would like to keep using actual LLM providers as in this fast-moving time LLM APIs evolve pretty fast, so we need to test agains the real thing.
Existing tests are running on CI every night (I have most of the keys). I am not convinced that you need to run tests locally if you did not do any changes to the specific module. If you are doing changes to a specific module, then you 100% need an API key to ensure that your changes work against the real thing. I am also afraid of maintaining tonnes of mock responses that will become outdated pretty fast.

**Comment by langchain4j** [comment]
There is another approach that might be of interest: for OpenAI, I am hosting a proxy server that caches requests to OpenAI for 24 hours. So if I run the same test multiple times, it will return the same payload much faster and without the need to spend tokens. Right now it requires an API key, but I can imagine injecting my API key on the proxy side and scaling this apporach to other LLM providers. I think this approach provides a good balance. At least once per day we hit the real thing and make sure it works as expected. WDYT?

**Comment by kpavlov** [comment]
@langchain4j, I totally agree, that testing against real LLMs is highly important.

What if such tests live in the LLM-specific modules, while the `langchain4j-core` and `langchain4j` modules are tested against mock providers? The core and main modules do not have to depend on specific LLM implementations. The [following dependencies](https://github.com/langchain4j/langchain4j/blob/11855157dd71eb52d603c981a4e3ac561a336107/langchain4j/pom.xml#L41-L74) appear to be cyclic dependencies to me.

What if, in these modules, `ChatModelMock` is used [instead of OpenAI Chat Model](https://github.com/langchain4j/langchain4j/blob/cc7121a016ffc7da2e0932b279e883003df3a753/langchain4j/src/test/java/dev/langchain4j/rag/query/transformer/ExpandingQueryTransformerIT.java#L41)?

We may want to run parameterized tests against different LLMs, I suggest creating a separate integration-test module and move integraiton tests there or creating an abstract integration test class in the main or another base module, and then creating concrete integration tests that extend that base integration test in LLM-specific modules.

I would love to test with an API proxy, but this approach does not scale outside the contributors' group because proxy credentials/URLs have to become public.

**Comment by langchain4j** [comment]
Sounds good, we are slowly moving in this direction (e.g. `AiServicesWithJsonSchemaIT`), https://github.com/langchain4j/langchain4j/pull/1668 introduces `AiServicesWithNewToolsIT`. I will try to move the rest soon too.

**Comment by kpavlov** [comment]
@langchain4j, actually, the problem is with mixing unit and integration tests. If we define _unit tests_ as tests that can run  without real providers and _integration tests_ as tests, requiring real providers, then we can enforce unit tests to run on every build and integration tests - only on langchain4j/langchain4j PR. 

This can be achieved with changes like [this](https://github.com/kpavlov/langchain4j/pull/3/files#diff-71cabc4177e41ea8f15a89eb65398fa8187739f68a2762706d84885cd8b2ddc3). CI pipeline [run](https://github.com/kpavlov/langchain4j/actions/runs/11317423486/job/31470851860?pr=3).
Other changes required was renaming GoogleAiGeminiTokenizerTest (cc: @glaforge), upgrading graalvm and Oracle image. [Commit history](https://github.com/kpavlov/langchain4j/pull/3/commits) includes also changes from the previous [PR](https://github.com/langchain4j/langchain4j/pull/1908)

I think it is very important to get tests to the green state before doing other changes

**Comment by kpavlov** [comment]
If #1913 seems too big it might be splitted...

**Comment by langchain4j** [comment]
> If we define unit tests as tests that can run without real providers and integration tests as tests, requiring real providers

This is how it is currently (or at least should be)

> then we can enforce unit tests to run on every build and integration tests - only on langchain4j/langchain4j PR.

Is there a reason you want [to run all unit tests](https://github.com/langchain4j/langchain4j/pull/1913/files#diff-71cabc4177e41ea8f15a89eb65398fa8187739f68a2762706d84885cd8b2ddc3R59) instead of those residing in affected modules? (We are using GIB)

**Comment by kpavlov** [comment]
> This is how it is currently (or at least should be)

This is how it should be. #1913 fixes it. Currently, some unit tests require access to external models, e.g. [Gemini](https://github.com/langchain4j/langchain4j/pull/1913/commits/7537677692207999836ec74e1d3033f121bd680c).

> Is there a reason you want to run all unit tests

I want to ensure the code compiles and to avoid regressions. Excluded modules aren’t compiled under JDKs < 21, despite targeting JDK 1.8, which may lead to issues later. 

Unit tests are fast, and catching failures early saves time and money compared to testing against real providers, which should happen later.

I also faced challenges running tests locally due to a lack of clear guidance (`mvn verify` fails).

Also, it is currently not possible to verify my PR if I am not a contributor. With [this](https://github.com/langchain4j/langchain4j/pull/1913/files#diff-71cabc4177e41ea8f15a89eb65398fa8187739f68a2762706d84885cd8b2ddc3R63) change I can open PR against my fork's main branch and run unit tests. Other validations, like spotless and spotbugs, should be added to this build phase in the future (separate PRs)

**Comment by langchain4j** [comment]
> This is how it should be. https://github.com/langchain4j/langchain4j/pull/1913 fixes it. Currently, some unit tests require access to external models, e.g. [Gemini](https://github.com/langchain4j/langchain4j/pull/1913/commits/7537677692207999836ec74e1d3033f121bd680c).

So there is a single test that does not follow Test/IT convention? Good catch!

> I want to ensure the code compiles and to avoid regressions. Excluded modules aren’t compiled under JDKs < 21, despite targeting JDK 1.8, which may lead to issues later.

What do you mean? Most of the modules are built with integration tests on jdk 8 and up (so they are compiled)

> Unit tests are fast, and catching failures early saves time and money compared to testing against real providers, which should happen later.

Agreed. But what I meant is that we are using GIB to figure out which modules has changed in the PR and which are affected and should be built. So perharps it makes no sense to (unit test) modules that were not affected. For example, if only OpenAI module has changed, there is no need to test e.g. Pinecone.

**Comment by langchain4j** [comment]
> I also faced challenges running tests locally due to a lack of clear guidance (mvn verify fails).

I see, good point! Since you've just went through this path, could you please add a docu on onboarding new contributors?
