### ISSUE TITLE
Google AI Gemini: implement streaming model

### ISSUE THREAD

**Issue by langchain4j** [langchain4j/langchain4j#1903]
### Discussed in https://github.com/langchain4j/langchain4j/discussions/1902

<div type='discussions-op-text'>

<sup>Originally posted by **Bjarne-Kinkel** October 11, 2024</sup>
Is there allready an efford to implement a GoogleAiGeminiStreamingChatModel as mentioned [here](https://docs.langchain4j.dev/integrations/language-models/google-ai-gemini#googleaigeministreamingchatmodel)? Or at least a feature request?</div>

**Comment by glaforge** [comment]
I haven't succeeded yet with Retrofit/OkHttp to implement a streaming variant, but I'd definitely want to have it!
Would you want to try to implement this yourself?

**Comment by langchain4j** [comment]
BTW next week we will start migrating to java 17, so no need in retrofit/okhttp any more, let's use jdk 11 http client by default

**Comment by Bjarne-Kinkel** [comment]
I'll take a look at it, though I'm not sure if I'll be able to pull it off. Is there already any code for this @glaforge?

**Comment by glaforge** [comment]
@Bjarne-Kinkel I had started with Retrofit/OkHttp but never got it to work, and anyway, we need to move to JDK 11 HttpClient, so we have to start from scratch (and we'll have to migrate the current non-streaming model to also use HttpClient instead).

There are 2 streaming modes for the Gemini API: 
* HTTP/2: which sends a big JSON array that contains response fragments
* SSE: a server-sent-event mode that is classical SSE, but you have to alter the endpoint URL by appending `?alt=sse`.

I'm not sure what's the easiest to implement with HttpClient, to be honest.

It's worth trying with cURL first, to get a good idea of what is exchanged exactly.

Don't hesitate to ping me here or on the Discord channel to further discuss it as you progress along. Happy to help!

**Comment by Bjarne-Kinkel** [comment]
@glaforge Okay, I will take a closer look at it next week. So far, I have only found information about streaming with SSE. Where can I find information about the option with HTTP/2?

**Comment by glaforge** [comment]
@Bjarne-Kinkel good question! I didn't really find any page that documents how streaming really works.
The best way for me was to just to try with curl to better understand what was flying through the wire.

For example on [this page](https://ai.google.dev/gemini-api/docs/text-generation?lang=rest#generate-a-text-stream) they show an example of streaming with SSE:
```
curl "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:streamGenerateContent?alt=sse&key=${GOOGLE_API_KEY}" \
        -H 'Content-Type: application/json' \
        --no-buffer \
        -d '{ "contents":[{"parts":[{"text": "Write a story about a magic backpack."}]}]}'
```

Notice the `alt=sse` added as query parameter.

It returns something like this:

```http
HTTP/2 200 
content-type: text/event-stream
content-disposition: attachment
vary: Origin
vary: X-Origin
vary: Referer
date: Sat, 12 Oct 2024 17:06:05 GMT
server: scaffolding on HTTPServer2
x-xss-protection: 0
x-frame-options: SAMEORIGIN
x-content-type-options: nosniff
server-timing: gfet4t7; dur=299
alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
 
data: {"candidates": [{"content": {"parts": [{"text": "The backpack"}],"role": "model"},"finishReason": "STOP","index": 0}],"usageMetadata": {"promptTokenCount": 8,"candidatesTokenCount": 2,"totalTokenCount": 10}}

data: {"candidates": [{"content": {"parts": [{"text": " was ordinary, except for the tarnished silver buckle that pulsed faintly whenever Maya touched it."}],"role": "model"},"finishReason": "STOP","index": 0,"safetyRatings": [{"category": "HARM_CATEGORY_SEXUALLY_EXPLICIT","probability": "NEGLIGIBLE"},{"category": "HARM_CATEGORY_HATE_SPEECH","probability": "NEGLIGIBLE"},{"category": "HARM_CATEGORY_HARASSMENT","probability": "NEGLIGIBLE"},{"category": "HARM_CATEGORY_DANGEROUS_CONTENT","probability": "NEGLIGIBLE"}]}],"usageMetadata": {"promptTokenCount": 8,"candidatesTokenCount": 20,"totalTokenCount": 28}}
...
```

It seems to be SSE over HTTP/2.

For non-SSE, you'll see that each candidate object ends up inside an array, and are thus all separated with commas:

```
curl "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:streamGenerateContent?ke=${GOOGLE_API_KEY}" \
        -H 'Content-Type: application/json'  \
        --http2 \
        --no-buffer \
        -d '{ "contents":[{"parts":[{"text": "Write a story about a magic backpack."}]}]}'
```

And the output gives:
```http
HTTP/2 200 
content-type: application/json; charset=UTF-8
vary: X-Origin
vary: Referer
vary: Origin,Accept-Encoding
date: Sat, 12 Oct 2024 17:08:39 GMT
server: scaffolding on HTTPServer2
cache-control: private
x-xss-protection: 0
x-frame-options: SAMEORIGIN
x-content-type-options: nosniff
server-timing: gfet4t7; dur=789
alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
accept-ranges: none

[{
  "candidates": [
    {
      "content": {
        "parts": [
          {
            "text": "The"
          }
        ],
        "role": "model"
      },
      "finishReason": "STOP",
      "index": 0
    }
  ],
  "usageMetadata": {
    "promptTokenCount": 8,
    "candidatesTokenCount": 1,
    "totalTokenCount": 9
  }
}
,
{
  "candidates": [
    {
      "content": {
        "parts": [
          {
            "text": " old, worn leather backpack had been in the attic for years, collecting dust alongside"
          }
        ],
        "role": "model"
      },
      "finishReason": "STOP",
      "index": 0,
      "safetyRatings": [
        {
          "category": "HARM_CATEGORY_SEXUALLY_EXPLICIT",
          "probability": "NEGLIGIBLE"
        },
        {
          "category": "HARM_CATEGORY_HATE_SPEECH",
          "probability": "NEGLIGIBLE"
        },
        {
          "category": "HARM_CATEGORY_HARASSMENT",
          "probability": "NEGLIGIBLE"
        },
        {
          "category": "HARM_CATEGORY_DANGEROUS_CONTENT",
          "probability": "NEGLIGIBLE"
        }
      ]
    }
  ],
  "usageMetadata": {
    "promptTokenCount": 8,
    "candidatesTokenCount": 17,
    "totalTokenCount": 25
  }
}
,
...
]
```

**Comment by langchain4j** [comment]
I would go with SSE, as it is used by all other LLM providers, so it will be easier to fit into the [abstracted HTTP client](https://github.com/langchain4j/langchain4j/pull/1103/files#diff-2e378f55aa7c64e82d1c10eef416067adf61a6109bf4488c15ccf6f642cc80c7) which I hope to finalize soon

**Comment by Bjarne-Kinkel** [comment]
@langchain4j The idea was to migrate the existing functions to the HttpClient (Java 11) before implementing the StreamingChatModel anyway. However, wouldn’t it make more sense to use your new abstracted client instead of creating a custom implementation with the HttpClient? 
Therefore, the new plan would be to first migrate the existing functions to the new abstracted client and then implement streaming. 
How usable is the abstracted client at this point?

**Comment by langchain4j** [comment]
@Bjarne-Kinkel that PR is a draft of a concept, it is far from being ready. I do not have clear timelines, it can easily be 2-3 months. So I would suggest implementing streaming using JDK 11 http client using SSE. Once this abstracted clients will be ready, it should be pretty easy to migrate.

**Comment by Bjarne-Kinkel** [comment]
Quick update: 
I have now completed both tasks:
(1) the migration of the GeminiService to the HttpClient
(2) the GeminiAiStreamingChatModel
After initial testing, both seem to be working. I’ll try to create a PR in the coming days. I'll make two separate ones, marking them as drafts, correct? The PR for the streaming will then depend on the HttpClient PR. Is there anything else I should keep in mind @langchain4j?

**Comment by langchain4j** [comment]
@Bjarne-Kinkel great! Yes, 2 smaller is better than 1 big one :) Thank you!

**Comment by glaforge** [comment]
@Bjarne-Kinkel Wonderful! I'm looking forward to reviewing the PRs!

**Comment by Bjarne-Kinkel** [comment]
I've created two drafts. @glaforge, feel free to take an initial look if you'd like. I haven't had time to run all the tests or implement new ones yet—I've only done some basic testing with my own small application. I'll take care of the testing next week. 

I'm not entirely sure if the error handling and logging are done correctly. It's a bit different from the previous version but similar to the implementation in other modules.
