### ISSUE TITLE
[BUG] OpenAI chat completions are not complete

### ISSUE THREAD

**Issue by ice09** [langchain4j/langchain4j#191]
I am using version 0.22.0, it works as expected, but like when using GPT manually, the output often is incomplete.

For the example below about 10 question/answer pairs instead of 30 or more are returned and the result is then cut at some point.

Is there a possibility to force a complete answer?

```
OpenAiChatModel assistant = OpenAiChatModel.builder().apiKey("sk").timeout(Duration.ofMinutes(5)).build();

SystemMessage sysMsg = new SystemMessage("""
                Create questions and answers in FAQ-style for the user provided text.
                Format the questions and answers as jsonl format which can be used to fine-tune GPT: for each pair create a new list with key 'messages', the questions with role 'user' and the answers with role 'assistant'.
                """);

List<ChatMessage> messages = List.of(sysMsg, new UserMessage(
                "Create 30 questions and answers for this text: ###" + postContent.substring(0, 16384) + "###"));
return assistant.sendMessages(messages).text();
```

**Comment by ice09** [comment]
I also tried the streaming approach, but with same result, after less than 30 questions the stream is completed.

```
assistant.chat("Create 30 questions and answers for this text: ###" + postContent.substring(0, 16384) + "###")
                .onNext(answerBuilder::append)
                .onComplete(() -> {
                    futureAnswer.complete(answerBuilder.toString());
                })
                .onError(futureAnswer::completeExceptionally)
                .start();

        return futureAnswer.get(360, TimeUnit.SECONDS);
```

**Comment by langchain4j** [comment]
@ice09 this is due to a context size of the model. You can try another model with a bigger context size (e.g. gpt-3.5-turbo-16k), but this might provide poorer results and be more expensive. You can also try to split your task into sub-tasks that fit into the context window. For example, first ask gpt to identify main topics for the text, then for each topic do a separate call and ask to provide a list of questions for that specific topic.

**Comment by ice09** [comment]
Thanks for the quick reply! 
This sounds very logical to me, however when trying this with the 16k model, there is still no difference, the answers are complete (by syntax) now, but there are still way less questions generated than I instructed.
However, this bug can be closed, I will investigate further (also by varying `maxTokens` parameter), thanks again.
