### ISSUE TITLE
Problems with MilvusEmbeddingStore

### ISSUE THREAD

**Issue by Nsatyar** [langchain4j/langchain4j#192]
Hello, can provide MilvusEmbeddingStore related examples, I don't know what parameters are needed to create this store, hope to have an example as a reference

**Comment by langchain4j** [comment]
@Nsatyar should be available till the end of the week, will keep you posted.

**Comment by kuraleta** [comment]
hi @Nsatyar new version 0.23.0  includes a fix for milvus. Here is an example: https://github.com/langchain4j/langchain4j-examples/blob/main/milvus-example/src/main/java/MilvusEmbeddingStoreExample.java
