### ISSUE TITLE
[BUG] Excessive logging in tests

### ISSUE THREAD

**Issue by kpavlov** [langchain4j/langchain4j#1929]
**Describe the bug**

Testcontainers are downloading images and spamming trace logs to console. This might cause builds to be slow (too much IO).

[e.g.](https://github.com/langchain4j/langchain4j/actions/runs/11349343735/job/31565219265):
```
2024-10-15 15:33:59 [docker-java-stream--399605824] com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.impl.Wire.wire()
DEBUG: http-outgoing-3 << "pulling 17b7e63fbe77... 100% [0xffffffe2][0xffffff96][0xffffff95][0xffffffe2][0xffffff96][0xffffff88][0xffffffe2][0xffffff96][0xffffff88][0xffffffe2][0xffffff96][0xffffff88][0xffffffe2][0xffffff96][0xffffff88][0xffffffe2][0xffffff96][0xffffff88][0xffffffe2][0xffffff96][0xffffff88][0xffffffe2][0xffffff96][0xffffff88][0xffffffe2][0xffffff96][0xffffff88][0xffffffe2][0xffffff96][0xffffff88][0xffffffe2][0xffffff96][0xffffff88][0xffffffe2][0xffffff96][0xffffff88][0xffffffe2][0xffffff96][0xffffff88][0xffffffe2][0xffffff96][0xffffff88][0xffffffe2][0xffffff96][0xffffff88][0xffffffe2][0xffffff96][0xffffff88][0xffffffe2][0xffffff96][0xffffff88][0xffffffe2][0xffffff96][0xffffff8f]   51 B                         [\n]"
```

**Log and Stack trace**
https://github.com/langchain4j/langchain4j/actions/runs/11349343735/job/31565219265

**To Reproduce**
Run build

**Expected behavior**
No trace/debug information from the testcontainers is printed in the log

The issue is probably caused by missing `src/main/resources/tinylog-test.properties` file with:
```properties
level = info
writingthread = true
```
Default severity level is [TRACE](https://tinylog.org/v2/configuration/#severity-level)

Proposed solution: add `tinylog-test.properties` to all modules.

**Question:** Is there a specific reason or benefit of using tinylog in tests? Should we switch to slf4j-simple?

**Please complete the following information:**
- LangChain4j version: 0.36.0-SNAPSHOT
- LLM(s) used: ollama
- Java version: 17 & 21

**Additional context**

https://github.com/langchain4j/langchain4j/actions/runs/11349343735/job/31565219265

**Comment by Martin7-1** [comment]
Actually it has no specific reason for using tinylog...

**Comment by kpavlov** [comment]
Moving to simple slf4j-simple then? @langchain4j , what do you think?

**Comment by Martin7-1** [comment]
@kpavlov 

> Moving to simple slf4j-simple then? @langchain4j , what do you think?

I think what `slf4j` implementation to use does not matter? Currently it looks good and has no side effect. Is there any reason?

> The issue is probably caused by missing src/main/resources/tinylog-test.properties file with:
> 
> ```
> level = info
> writingthread = true
> ```
> 
> Default severity level is [TRACE](https://tinylog.org/v2/configuration/#severity-level)

Sounds reasonable, but actually modules do not really depend on `tinylog`, should the file be added in `src/test/resources` rather than `src/main/resources`?

**Comment by langchain4j** [comment]
In general, I would keep tinylog if there is no objective downside. It seems that it can be configured via system properties: `java -jar -Dtinylog.writer.level=debug application.jar`, so I would try use this instead of adding config files for every module. WDYT?

If slf4j-simple allows to solve this simpler, let's go for it, I do not have a strong preference.

**Comment by kpavlov** [comment]
Let me try system properties with maven.config

**Comment by kpavlov** [comment]
@langchain4j , let's reopen it for a while.

it seems like `-Dtinylog.writer.level=info` did not help, still see the [debug output in the log](https://github.com/langchain4j/langchain4j/actions/runs/11381435393/job/31662818093?pr=1939) and it is huge.

Should I proceed with switching to slf4j-simple? It's default logging level is [INFO](https://www.slf4j.org/api/org/slf4j/simple/SimpleLogger.html)
> org.slf4j.simpleLogger.defaultLogLevel - Default log level for all instances of SimpleLogger. Must be one of ("trace", "debug", "info", "warn", "error" or "off"). If not specified, defaults to "info".

**Comment by langchain4j** [comment]
Maybe `jvm.config` is not picked up by the build? Perharps try passing `-Dtinylog.writer.level=info` directly in the build command?

Feel free to migrate to `slf4j-simple` thiough
