### ISSUE TITLE
[FEATURE] Configuring ReRankingContentAggregator to Return Top Results

### ISSUE THREAD

**Issue by fmx0717** [langchain4j/langchain4j#1944]
Does ReRankingContentAggregator support parameter configuration to return the maximum number of results with the highest scores? For example:
ContentAggregator contentAggregator = ReRankingContentAggregator.builder()
    .scoringModel(scoringModel)
    .minScore(reranking_min_score)
    .maxResults(5)
    .build();
Because ContentRetriever has already set maxResults in EmbeddingStoreContentRetriever, for example, if I want to recall 5 pieces of data, EmbeddingStoreContentRetriever also returns 5 results. If ReRankingContentAggregator filters the results based on minScore and only returns 3 results, the final output will have only 3 results, which does not match my expected result.

To address this, I want to increase the number of results recalled by EmbeddingStoreContentRetriever so that ReRankingContentAggregator can determine the final number of results. For example, I might set maxResults in EmbeddingStoreContentRetriever to a higher value, such as 10, to ensure that ReRankingContentAggregator has enough candidates to select from and can still return the desired number of top results.

// Example configuration for EmbeddingStoreContentRetriever
ContentRetriever contentRetriever = EmbeddingStoreContentRetriever.builder()
    .maxResults(10)  // Increase the number of results to recall
    .build();

// Example configuration for ReRankingContentAggregator
ContentAggregator contentAggregator = ReRankingContentAggregator.builder()
    .contentRetriever(contentRetriever)
    .scoringModel(scoringModel)
    .minScore(reranking_min_score)
    .maxResults(5)  // Desired number of final results
    .build();

**Comment by langchain4j** [comment]
Hi @fmx0717, this is not supported yet, but should be very easy to implement. Would you like to open a PR please?
