### ISSUE TITLE
[Question] - Open a discord room ?

### ISSUE THREAD

**Issue by clun** [langchain4j/langchain4j#195]
Hello,

Would you be OK to open a discord room where people can ask question and interact with the team ?

For instance as of now the project is not compiling for me 
`EmbeddingModelTextClassifierTest` required `AllMiniLmL6V2QuantizedEmbeddingModel` not found anywhere and as such my PR is marked as failling.

Thank you for all your work !

**Comment by nooone** [comment]
@clun Did you close this because there is something like that? If so... where?

**Comment by clun** [comment]
MIssed the notification. It does not exist anywhere no. 

I would let the core team decide about it, to create one

+ I got the `AllMiniLmL6V2QuantizedEmbeddingModel` fixed : it was an error more on less on my ends with the second repo containing embeddings and `onn` file to be installed separately.

**Comment by langchain4j** [comment]
Ok let's try discord: https://discord.gg/V5qHrWNVf
