### ISSUE TITLE
[BUG] `langchain4j-embeddings` has conflict dependency with `langchain4j`

### ISSUE THREAD

**Issue by Martin7-1** [langchain4j/langchain4j#1952]
**Describe the bug**

When I want to build `langchain4j-embeddings` 0.36.0-SNAPSHOT using `mvn clean install -DskipTests -DskipITs`, the build failed.

**Log and Stack trace**

```
[ERROR] Rule 0: org.apache.maven.enforcer.rules.dependency.DependencyConvergence failed with message:
[ERROR] Failed while enforcing releasability.
[ERROR] 
[ERROR] Dependency convergence error for com.google.code.gson:gson:jar:2.10.1 paths to dependency are:
[ERROR] +-dev.langchain4j:langchain4j-embeddings:jar:0.36.0-SNAPSHOT
[ERROR]   +-dev.langchain4j:langchain4j-core:jar:0.36.0-SNAPSHOT:compile
[ERROR]     +-com.google.code.gson:gson:jar:2.10.1:compile
[ERROR] and
[ERROR] +-dev.langchain4j:langchain4j-embeddings:jar:0.36.0-SNAPSHOT
[ERROR]   +-ai.djl:api:jar:0.30.0:compile
[ERROR]     +-com.google.code.gson:gson:jar:2.11.0:compile
```

**To Reproduce**

Just run `mvn clean install` in `langchain4j-embeddings` main repo.

**Expected behavior**

Build successfully.

**Please complete the following information:**
- LangChain4j version: 0.36.0-SNAPSHOT
- LLM(s) used: null
- Java version: 17
- Spring Boot version (if applicable): null

**Additional context**

Should we update gson version in `langchain4j` main repo?

**Comment by langchain4j** [comment]
@Martin7-1 thank you for reporting!
