### ISSUE TITLE
[FEATURE] Ollama: support tools in streaming mode

### ISSUE THREAD

**Issue by langchain4j** [langchain4j/langchain4j#1971]
Tool support has been implemented for `OllamaChatModel` in #1558.

We need to implement the same for `OllamaStreamingChatModel`.

Implementation in `OpenAiStreamingChatModel` and `OpenAiStreamingResponseBuilder` can be taken as an example.

**Comment by langchain4j** [comment]
@bidek could you consider implementing this please?

**Comment by sheiy** [comment]
@langchain4j https://github.com/ollama/ollama/issues/5796  it looks like ollama not support streaming tools call for now.

**Comment by langchain4j** [comment]
@sheiy oh, thanks for the heads up!

**Comment by sheiy** [comment]
by my test `OpenAiStreamingChatModel` works good with tools

**Comment by langchain4j** [comment]
Sorry I meant `OllamaStreamingChatModel`. And my comment makes no sense now.

**Comment by sakoojiang** [comment]
At present, it seems that ollama does not support function call in streaming mode.
However, I simply processed it in a non-mainstream way, allowing him to support the logic of single function calls in some simple scenarios.

**Comment by langchain4j** [comment]
@sakoojiang 

> At present, it seems that ollama does not support function call in streaming mode.
> However, I simply processed it in a non-mainstream way, allowing him to support the logic of single function calls in some simple scenarios.

What do you mean?

**Comment by ParthSareen** [comment]
Hey everyone - just rolled out streaming tool calls https://github.com/ollama/ollama/releases/tag/v0.4.6

**Comment by langchain4j** [comment]
@sheiy would you like to implement this? 🙏

**Comment by sheiy** [comment]
@langchain4j I’ve been a bit busy lately, but if I find the time, I can work on implementing this feature.
