### ISSUE TITLE
[BUG] test_backwards_compatibility_with_0_27_1 broken in InMemoryEmbeddingStoreTest

### ISSUE THREAD

**Issue by omarmahamid** [langchain4j/langchain4j#1992]
**Describe the bug**

test_backwards_compatibility_with_0_27_1 broken in InMemoryEmbeddingStoreTest

**Comment by kpavlov** [comment]
+1

**Comment by langchain4j** [comment]
What's wrong with it?
All tests in `InMemoryEmbeddingStoreTest` are green on main branch

**Comment by omarmahamid** [comment]
@langchain4j 
what I'm missing ?

![image](https://github.com/user-attachments/assets/cc24047d-be7f-45b8-bb2e-ff55fe296d92)

**Comment by langchain4j** [comment]
Hmm, it seems that `AllMiniLmL6V2QuantizedEmbeddingModel` generates embeddings with a bit lower precision on your environment. Which OS do you use?

I think we can remove this test, 0.27-1 was released a long time ago

**Comment by omarmahamid** [comment]
I will deep dive into it and remove if needed

**Comment by omarmahamid** [comment]
@langchain4j 

I removed the test, I think it's not relevant to precision on env

I'm using macOS M2 and JDK17.0.9
