### ISSUE TITLE
[FEATURE] Add custom-headers to the Azure Open AI Spring Boot Starter

### ISSUE THREAD

**Issue by arey** [langchain4j/langchain4j#2038]
**Is your feature request related to a problem? Please describe.**

In a Spring Boot application using the Azure Open AI starter, I need to pass a special HTTP header to access the OpenAI instance provided by my company.
The `dev.langchain4j.azure.openai.spring.ChatModelProperties` doest not provide a `customHeaders` property.

**Describe the solution you'd like**
In the `dev.langchain4j.azure.openai.spring.ChatModelProperties` class, add a `customHeaders` property:
```
    private Map<String, String> customHeaders = new HashMap();
```
then bind it in the `AutoConfig`class.

**Describe alternatives you've considered**

In the meantime, I've declared a `ChatLanguageModel` bean and comment all the `langchain4j.azure-open-ai.*` properties:

```
	@Bean
	ChatLanguageModel chatLanguageModel() {
		return AzureOpenAiChatModel.builder()
			.deploymentName("gpt-4o")
			.endpoint(System.getenv("AZURE_OPENAI_ENDPOINT"))
			.apiKey(System.getenv("AZURE_OPENAI_KEY"))
			.customHeaders(Map.of("custom-key", System.getenv("CUSTOM_AZURE_KEY")))
			.logRequestsAndResponses(true)
			.build();
	}
```

**Additional context**

I can contribute on this feature if you want.

**Comment by langchain4j** [comment]
@arey it would be great if you could contribute this, thank you!

**Comment by arey** [comment]
Hi @langchain4j I submit this PR: https://github.com/langchain4j/langchain4j-spring/pull/50
Once merged, I could work on the lombok removal for the Azure OpenAI starter like I've done https://github.com/langchain4j/langchain4j-spring/pull/49

**Comment by agoncal** [comment]
@langchain4j  as the PR https://github.com/langchain4j/langchain4j-spring/pull/50 has been merged, can this issue be closed ?

**Comment by langchain4j** [comment]
@agoncal right, thanks!
