### ISSUE TITLE
[FEATURE] anthropic claude models

### ISSUE THREAD

**Issue by JCASTANO** [langchain4j/langchain4j#204]
thanks for this great project

I would like to propose the inclusion of the anthropic claude models, it is a necessary function to do solutions with this kind of models

https://js.langchain.com/docs/modules/model_io/models/chat/integrations/anthropic
https://docs.anthropic.com/claude/reference/complete_post

**Comment by kuraleta** [comment]
hi, @JCASTANO if you have access to Claude, we can try to implement it, but then we will need your help to test it, as our contributors still don't have access to it.

**Comment by pascalconfluent** [comment]
@JCASTANO Claude support was added via AWS Bedrock support. Not sure if it is good enough for your use case.

**Comment by langchain4j** [comment]
@JCASTANO feel free to reopen if still needed
