### ISSUE TITLE
[FEATURE] Use MemoryId in @Tool ?

### ISSUE THREAD

**Issue by AbdullahGheith** [langchain4j/langchain4j#206]
How am i supposed to do this? this doesnt work

	@Tool("Saves phonenumber")
	void savePhonenumber(@MemoryId String sessionId, String phonenumber) {
		System.out.println(sessionId + " @ Saving phone number to db: "+phonenumber);
	}
	
My user is chatting through this:
	String chat(@MemoryId String memoryId, @UserMessage String userMessage);

chat.chat(userId, prompt.toUserMessage().text());

and i want to retreive that userid, how do i do it?

**Comment by langchain4j** [comment]
@AbdullahGheith Good question, we do not support this yet, but probably should. Will take a look at this feature...

**Comment by AbdullahGheith** [comment]
If multiple people are chatting with the bot, how am I supposed to differentiate between the users? Any suggestion until it gets fixed?

**Comment by langchain4j** [comment]
In theory you could try to inform LLM about userId (e.g. in the system prompt) and make one of Tool parameters to be userId (annotated with `@P("userId")`), but there is no guarantee LLM will not hallucinate it. So use it on your own risk

**Comment by lukasstanek** [comment]
We create an AiServices / Tools instance for each session and hold it inside of a hashmap to work around this currently. But I agree this feature would be very helpful!

We also tried the approach with adding the sessionid to the prompt and it generally worked, but we had the feeling that we don't want to burden the ai with unnecessary tasks.

**Comment by benedictstrube** [comment]
Also highly interested in that feature! Could be implemented the same we way we pass a `@MemoryId` to the prompting interface methods, wdyt?

**Comment by benedictstrube** [comment]
@langchain4j You can close this, I think :)
