### ISSUE TITLE
[FEATURE] JsonSchema - anyOf

### ISSUE THREAD

**Issue by mareksvatos** [langchain4j/langchain4j#2081]
**Is your feature request related to a problem? Please describe.**
I am using JsonSchema and cannot find a way to use the anyOf specification. It would be great if langchain4j supported it since openai does. 

- https://platform.openai.com/docs/guides/structured-outputs#supported-types
- https://platform.openai.com/docs/guides/structured-outputs#for-anyof-the-nested-schemas-must-each-be-a-valid-json-schema-per-this-subset

**Describe the solution you'd like**
Add another implementation of `JsonSchemaElement` e.g. `JsonAnyOfSchema`.

**Comment by langchain4j** [comment]
Hi @MarekSvatos! Do you plan to use `ChatLanguageModel` API for this or AI Services? For Structured Outputs or tools?
Could you please provide an example/use case of how do you plan to use it (what do you plan to extract)?
Thanks!

**Comment by mareksvatos** [comment]
I would like to use it for Structured Outputs. Right now I mostly use `ChatLanguageModel` since the data in my application is dynamic, so I build the `JsonSchema` dynamically as well. But I think AI Services could take advantage of anyOf spec too.

My current use case for anyOf is extracting logical conditions from a description. If there is a simpler way to achieve this, please let me know. Thank you.

Here is a simplified example:
Description: A person whose name is John and is older than 18 years old.
JsonSchema:
```
{
 {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "operator": {
      "type": "string",
      "enum": [
        "AND",
        "OR"
      ]
    },
    "conditions": {
      "type": "array",
      "items": {
        "anyOf": [
          {
            "type": "object",
            "description": "Condition for string properties",
            "properties": {
              "type": {
                "type": "string",
                "const": "string"
              },
              "operator": {
                "type": "string",
                "enum": [
                  "CONTAINS",
                  "DOES_NOT_CONTAIN",
                  "IS",
                  "IS_NOT",
                  "IS_EMPTY",
                  "IS_NOT_EMPTY"
                ]
              },
              "property": {
                "type": "string",
                "enum": [
                  "name",
                  "address"
                ]
              },
              "value": {
                "type": "string"
              }
            },
            "required": ["type", "operator", "property", "value"]
          },
          {
            "type": "object",
            "description": "Condition for number properties",
            "properties": {
              "type": {
                "type": "string",
                "const": "number"
              },
              "operator": {
                "type": "string",
                "enum": [
                  "IS_EQUAL",
                  "IS_NOT_EQUAL",
                  "IS_GREATER_THAN_OR_EQUAL",
                  "IS_GREATER_THAN",
                  "IS_LESS_THAN_OR_EQUAL",
                  "IS_LESS_THAN"
                ]
              },
              "property": {
                "type": "string",
                "enum": [
                  "age",
                  "height"
                ]
              },
              "value": {
                "type": "number",
                "format": "double"
              }
            },
            "required": ["type", "operator", "property", "value"]
          }
        ]
      }
    }
  }
}
```
Expected Output:
```
{
  "operator": "AND",
  "conditions": [
    {
      "type" : "string",
      "operator": "IS",
      "property": "name",
      "value": "John"
    },
    {
      "type" :"number",
      "operator": "IS_GREATER_THAN",
      "property": "age",
      "value": 18
    }
  ]
}
``` 

Output would be deserialized into something like this:

```
public record ConditionSet(Operator operator,
                           List<Condition> conditions) {
}
```
```
public record NumberCondition(NumberProperty property,
                              NumberOperator operator,
                              double value) implements Condition {
}
```
```
public record StringCondition(StringProperty property,
                              StringOperator operator,
                              String value) {
}
```

**Comment by langchain4j** [comment]
@MarekSvatos that's interesting, it would indeed help a lot!
I guess this can be "emulated" now by merging `NumberCondition` and `StringCondition` into a single object, but I agree that this is ugly.
Would you like to contribute this feature please? 🙏

**Comment by langchain4j** [comment]
@MarekSvatos BTW how do you find working with `JsonSchema`? Or would you prefer to generate schema yourself?

**Comment by mareksvatos** [comment]
Working with `JsonSchema` is great, but it’s important to keep up with the different supported specifications. Right now, I need to be able to provide the schema as a string to take advantage of the `anyOf` specification. Therefore, it might be viable to support both approaches.

For the solution, I propose creating two new implementations of `JsonSchemaElement`:

- `JsonAnyOfSchema`: https://json-schema.org/understanding-json-schema/reference/combining#anyOf
- `JsonConstSchema`: https://json-schema.org/understanding-json-schema/reference/const

`JsonConstSchema`, used as an optional feature in combination with `anyOf`, would be helpful for deserialization of different types that `anyOf` can return. For example, in my previous use case, I provided const values such as `"string"` and `"number"`. Based on these values, I can deserialize them into corresponding types like `StringCondition` or `NumberCondition`.

I looked into the current implementation, and these are the additions I believe are required:

1. Add `JsonAnyOfSchema` and `JsonConstSchema` to https://github.com/ai-for-java/openai4j.
2. Add `JsonAnyOfSchema` and `JsonConstSchema` to https://github.com/langchain4j/langchain4j.
3. Add a mapping function in `InternalOpenAiHelper`.

If this represents the full scope of the feature, I can implement it. If there are additional requirements, please let me know. Thank you!

**Comment by langchain4j** [comment]
@MarekSvatos that makes sense! Although I am not sure I fully understand the need for `JsonConstSchema`, I will have a bit more time next week to look into it deeper. If you are sure about it, please go ahead :)
