### ISSUE TITLE
Ollama: update documentation and examples

### ISSUE THREAD

**Issue by langchain4j** [langchain4j/langchain4j#2100]
Ollama [documentation](https://docs.langchain4j.dev/integrations/language-models/ollama) and [examples](https://github.com/langchain4j/langchain4j-examples/blob/main/ollama-examples/src/main/java/OllamaChatModelTest.java) still use
`langchain4j/ollama-...` images that are not supported any more.

Update docu and examples and describe 2 ways of running Ollama:
- when Ollama runs locally
- when Ollama runs in testcontainers

**Comment by soul2zimate** [comment]
Hi @langchain4j I'd like to take this one, Can you assign this to me ?

**Comment by langchain4j** [comment]
@soul2zimate thanks a lot in advance!
