### ISSUE TITLE
[BUG] Enable and enforce Codacy or other code analysis tool

### ISSUE THREAD

**Issue by kpavlov** [langchain4j/langchain4j#2108]
**Describe the bug**
Code quality in the repo is poor. Static analysis tool must be enabled and enforced for all new PRs

**Log and Stack trace**

**To Reproduce**

**Expected behavior**

**Please complete the following information:**
- LangChain4j version: 0.36.0
- LLM(s) used: any
- Java version: any
- Spring Boot version (if applicable): any

**Additional context**

**Comment by langchain4j** [comment]
Thank you for your feedback.
Could you please elaborate? Does "poor" apply to all the code in this repo, or are there specific areas that should be improved first? It would also help if you could specify concere criteria by which you asses.

BTW I have already enabled codacy and openrewrite checks on each PR.

**Comment by kpavlov** [comment]
@langchain4j Sorry for too being too expressive and harsh. I noticed some amount of duplication, cyclomatic complexity and a room for optimization. I prefer detach myself as a human from the code analysis and delegate it to automated tools. It will prevent tension and ensure that each PR makes the code better.
Since project has many contributors and PR rate is high, automated checks could help to avoid reviewing PRs, that not meed expected code quality and style.
Thank you, for your efforts in general and for enabling static analysis back.

**Comment by langchain4j** [comment]
@kpavlov all good ❤️ 
I am not agains tooling in general, but I was too busy recently with other stuff, so I did not have enough time to look into every tool you proposed and commit to using it, hence the delay. Now that they are enabled, I hope they will help indeed.
