### ISSUE TITLE
[FEATURE] Runtime interception of tool methods (input and output parameters, execution time)

### ISSUE THREAD

**Issue by catofdestruction** [langchain4j/langchain4j#2113]
I want to intercept all tool methods marked with @Tool at runtime.

By doing this, I can track the execution flow of the entire application at runtime, such as the input and output of each invoked tool and their execution time.

Currently, I have successfully intercepted methods related to @AiService and obtained runtime information.

However, when I use AOP to intercept methods related to @Tool, the framework doesn’t seem to work properly. 
The tool cannot be properly invoked by the framework.

Is there a good way to achieve this? Thank you very much.

Will our framework consider incorporating observability-related features in the future? I think it’s a very important feature, similar to LangSmith."

**Comment by langchain4j** [comment]
Hi @catofdestruction, could you please provide more details? How do you currently intercept? 
Yes, we plan to add more observability features in the future, including tool calls.

In the meantime, please consider using this https://docs.langchain4j.dev/tutorials/tools#accessing-executed-tools

**Comment by catofdestruction** [comment]
> Hi @catofdestruction, could you please provide more details? How do you currently intercept? Yes, we plan to add more observability features in the future, including tool calls.
> 
> In the meantime, please consider using this https://docs.langchain4j.dev/tutorials/tools#accessing-executed-tools




Thanks! I immediately upgraded to version 0.36.0, and the onToolExecuted method is now working properly.

Currently, I am using @Aspect in a very straightforward manner to intercept method calls.

for AiService:  (this work now for me)

```
public class MyAspect {

      @Around("execution(!void *(..)) && @within(dev.langchain4j.service.spring.AiService)")
      public Object interceptAiServiceMethods(ProceedingJoinPoint joinPoint) throws Throwable {
          var signature = (MethodSignature) joinPoint.getSignature();
          var method = signature.getMethod();
          var targetClass = method.getDeclaringClass();
          var aiService = targetClass.getAnnotation(AiService.class);
          // logic with input & output of method, execution time，etc
          return joinPoint.proceed();
      }
}
```


for Tool  (when using @MyInterceptorAnnotation, toolA won`t be called  :( )


```
@Component
public class MyTools {

    @Tool("aaa")
    @MyInterceptorAnnotation
    public String toolA(@P("aaa") Long a) {
        //
        return "aaa";
    }
}
```

**Comment by langchain4j** [comment]
@catofdestruction hmm, do you know if such a tool is registered [here](https://github.com/langchain4j/langchain4j-spring/blob/c6c183b1d18b6e9e6b88b9443aca3eab6c108a3c/langchain4j-spring-boot-starter/src/main/java/dev/langchain4j/service/spring/AiServicesAutoConfig.java#L54) at all? I suspect that it is not registered as the bean is wrapped into a proxy and the `@Tool` annotation is lost?

**Comment by catofdestruction** [comment]
> @catofdestruction hmm, do you know if such a tool is registered [here](https://github.com/langchain4j/langchain4j-spring/blob/c6c183b1d18b6e9e6b88b9443aca3eab6c108a3c/langchain4j-spring-boot-starter/src/main/java/dev/langchain4j/service/spring/AiServicesAutoConfig.java#L54) at all? I suspect that it is not registered as the bean is wrapped into a proxy and the `@Tool` annotation is lost?

Well, I don’t think my approach is very reasonable. If I find out why the tool isn’t working properly, I will reply here promptly.

**Comment by catofdestruction** [comment]
> @catofdestruction hmm, do you know if such a tool is registered [here](https://github.com/langchain4j/langchain4j-spring/blob/c6c183b1d18b6e9e6b88b9443aca3eab6c108a3c/langchain4j-spring-boot-starter/src/main/java/dev/langchain4j/service/spring/AiServicesAutoConfig.java#L54) at all? I suspect that it is not registered as the bean is wrapped into a proxy and the `@Tool` annotation is lost?



> @catofdestruction hmm, do you know if such a tool is registered [here](https://github.com/langchain4j/langchain4j-spring/blob/c6c183b1d18b6e9e6b88b9443aca3eab6c108a3c/langchain4j-spring-boot-starter/src/main/java/dev/langchain4j/service/spring/AiServicesAutoConfig.java#L54) at all? I suspect that it is not registered as the bean is wrapped into a proxy and the `@Tool` annotation is lost?

I found the answer!

At that time, when a custom annotation (for example, @MyInterceptorAnnotation) was added to the @Tool method and the Spring @Aspect was used to intercept method calls, the current framework code caused AiServices to be unable to properly construct toolSpecifications and toolExecutors.

The reason is that the list of objectsWithTools already consists entirely of objects enhanced by Spring AOP, making it impossible to access the methods in the original class, and thus unable to retrieve the methods related to @Tool.
I believe that other developers using our framework may encounter this issue as well.

Currently, I have thought of a solution: 
before making the determination, add a check to see if the objectsWithTool are AOP-enhanced objects.
If they are, use AopProxyUtils to obtain the original object. This way, the framework will be able to correctly construct the toolSpecifications and toolExecutors. 

However, this solution requires including the spring-aop dependency because we need to use AopUtils and AopProxyUtils.

The code is shown in the screenshot below：

<img width="1197" alt="image" src="https://github.com/user-attachments/assets/58a2813e-7f13-453e-8c87-160b6cbfcfe7">

 my solution:

<img width="1186" alt="image" src="https://github.com/user-attachments/assets/96dbcb6e-ebdb-4407-abe3-5cea1f101a0c">

<img width="518" alt="image" src="https://github.com/user-attachments/assets/be8ae299-d8b4-4d5e-8ee1-ac8560351378">

**Comment by langchain4j** [comment]
@catofdestruction good catch, thank you for digging into it!

Isn't `spring-aop` already transitively imported by `spring-boot-starter`?

**Comment by catofdestruction** [comment]
> @catofdestruction good catch, thank you for digging into it!
> 
> Isn't `spring-aop` already transitively imported by `spring-boot-starter`?

Yes, you can directly depend on spring-boot-starter to use spring-aop, but currently the parent POM of langchain4j does not include a dependency on spring-boot-starter or langchain4j-spring-boot-starter; 

it only includes langchain4j-spring-boot-starter in the BOM.”

**Comment by langchain4j** [comment]
`langchain4j-spring-boot-starter` module (where I guess we should do changes) has a `spring-boot-starter` dependency, so `spring-aop` is already there. We should not bring in any spring-specific dependencies into the `langchain4j-core` or `langchain4j` modules.

**Comment by catofdestruction** [comment]
> `langchain4j-spring-boot-starter` module (where I guess we should do changes) has a `spring-boot-starter` dependency, so `spring-aop` is already there. We should not bring in any spring-specific dependencies into the `langchain4j-core` or `langchain4j` modules.

Got it. I can implement the logic to retrieve the original object from the AOP object in the getObject method of AiServiceFactory. Do I need to add a new feature and submit it? I can create a branch with a name like aop-tools-support :)

**Comment by langchain4j** [comment]
@catofdestruction yes, it would be great if you could submit a PR 🙏
For this, pelase fork the `langchain4j-spring` repo, do the changes in your fork and then you will be able to submit a PR from your fork to the main branch of `langchain4j-spring` repo.

Regarding hte implementaiton, I think extracting an original object is a good idea, it will allow to read all the tool metadata with reflection.
But we need to make sure that when the `ToolExecutor` calls the tool method, we call the **_proxy_**, not the original object. This way all the AOP stuff will work as expected.

**Comment by catofdestruction** [comment]
> @catofdestruction yes, it would be great if you could submit a PR 🙏 For this, pelase fork the `langchain4j-spring` repo, do the changes in your fork and then you will be able to submit a PR from your fork to the main branch of `langchain4j-spring` repo.
> 
> Regarding hte implementaiton, I think extracting an original object is a good idea, it will allow to read all the tool metadata with reflection. But we need to make sure that when the `ToolExecutor` calls the tool method, we call the **_proxy_**, not the original object. This way all the AOP stuff will work as expected.

I surrender.

I tried to restore the enhanced part of List<Object> tools in AiServiceFactory, and the tools can be called correctly. 

However, since the framework internally uses JDK dynamic proxies and reflection for method calls, the AOP interceptors do not work properly for the intercepted methods.

As it stands, there doesn’t seem to be a good solution to monitor the start and end of tool method execution, including method parameters, return values, and execution duration.

It might be a better approach to encapsulate this information into ToolExecution :)

**Comment by langchain4j** [comment]
> However, since the framework internally uses JDK dynamic proxies and reflection for method calls, the AOP interceptors do not work properly for the intercepted methods.

In `AiServices`, there is an option to configure tools this way: `tools(Map<ToolSpecification, ToolExecutor> tools)`, which should help here.

In `AiServicesAutoConfig`, when you have an object (with a `@Tool`-annotated methods) which is wrapped into a Spring proxy, you can use AOP utils to get the original object, right? So we can create a `ToolSpecification`(s) from this **original** object. But we can make `ToolExecutor` to execute calls on the **wrapped** proxy, right? `DefaultToolExecutor` can be created from the wrapped object.

**Comment by catofdestruction** [comment]
> > However, since the framework internally uses JDK dynamic proxies and reflection for method calls, the AOP interceptors do not work properly for the intercepted methods.
> 
> In `AiServices`, there is an option to configure tools this way: `tools(Map<ToolSpecification, ToolExecutor> tools)`, which should help here.
> 
> In `AiServicesAutoConfig`, when you have an object (with a `@Tool`-annotated methods) which is wrapped into a Spring proxy, you can use AOP utils to get the original object, right? So we can create a `ToolSpecification`(s) from this **original** object. But we can make `ToolExecutor` to execute calls on the **wrapped** proxy, right? `DefaultToolExecutor` can be created from the wrapped object.

If DefaultToolExecutor is constructed using the wrapped object and wrapped method, can the aspect be triggered normally during the actual reflection call? This might need to be verified. 

Additionally, I found many methods in the enhancement class, and among them, there should be two enhanced tool methods. Which one should be used to construct DefaultToolExecutor?

<img width="1214" alt="image" src="https://github.com/user-attachments/assets/a39d485f-9f80-4789-b49b-bddcf2ab1567">

original method is here:

<img width="1142" alt="image" src="https://github.com/user-attachments/assets/cb560b7a-2dc4-49d7-8511-e9e8f91dd445">

Finally, if we want to achieve this without introducing Spring dependencies in langchain4j-core, then the implementation of the tools construction method in AiServices might also need to be modified, as shown in the figure below:

<img width="1109" alt="image" src="https://github.com/user-attachments/assets/b02c2f9b-bba6-4f96-93d5-7f31a1436167">

**Comment by langchain4j** [comment]
> If DefaultToolExecutor is constructed using the wrapped object and wrapped method, can the aspect be triggered normally during the actual reflection call? This might need to be verified.

I would expect it to work, but ofc better to verify.

> Additionally, I found many methods in the enhancement class, and among them, there should be two enhanced tool methods. Which one should be used to construct DefaultToolExecutor?

I have no idea, never worked with AOP this close...

> Finally, if we want to achieve this without introducing Spring dependencies in langchain4j-core, then the implementation of the tools construction method in AiServices might also need to be modified, as shown in the figure below:

We can adjust implementation in `AiServices` if required, but I had an impression that we can already use `tools(Map<ToolSpecification, ToolExecutor> tools)` as-is?

**Comment by catofdestruction** [comment]
> > If DefaultToolExecutor is constructed using the wrapped object and wrapped method, can the aspect be triggered normally during the actual reflection call? This might need to be verified.
> 
> I would expect it to work, but ofc better to verify.
> 
> > Additionally, I found many methods in the enhancement class, and among them, there should be two enhanced tool methods. Which one should be used to construct DefaultToolExecutor?
> 
> I have no idea, never worked with AOP this close...
> 
> > Finally, if we want to achieve this without introducing Spring dependencies in langchain4j-core, then the implementation of the tools construction method in AiServices might also need to be modified, as shown in the figure below:
> 
> We can adjust implementation in `AiServices` if required, but I had an impression that we can already use `tools(Map<ToolSpecification, ToolExecutor> tools)` as-is?

I’ll try it out again when I have the chance :)

**Comment by catofdestruction** [comment]
> > If DefaultToolExecutor is constructed using the wrapped object and wrapped method, can the aspect be triggered normally during the actual reflection call? This might need to be verified.
> 
> I would expect it to work, but ofc better to verify.
> 
> > Additionally, I found many methods in the enhancement class, and among them, there should be two enhanced tool methods. Which one should be used to construct DefaultToolExecutor?
> 
> I have no idea, never worked with AOP this close...
> 
> > Finally, if we want to achieve this without introducing Spring dependencies in langchain4j-core, then the implementation of the tools construction method in AiServices might also need to be modified, as shown in the figure below:
> 
> We can adjust implementation in `AiServices` if required, but I had an impression that we can already use `tools(Map<ToolSpecification, ToolExecutor> tools)` as-is?

Good News! It works :) 
& I just submit a PR to the main branch (with IT passed)    
https://github.com/langchain4j/langchain4j-spring/pull/80

**Comment by langchain4j** [comment]
@catofdestruction thanks a lot! I will review it ASAP

**Comment by langchain4j** [comment]
Implemented in https://github.com/langchain4j/langchain4j-spring/pull/80

Good job @catofdestruction, thank you!
