### ISSUE TITLE
Jlama: support tools/functions in streaming mode

### ISSUE THREAD

**Issue by langchain4j** [langchain4j/langchain4j#2115]
Tools/functions should be supported in streaming mode. Currently, they work only in sync mode.

**Comment by langchain4j** [comment]
Hi @tjake, does Jlama supports tools in streaming mode?

**Comment by tjake** [comment]
No, but I'm going to add it see https://github.com/tjake/Jlama/issues/94

I need to look at how localai does it since you don't want to stream the actual json call inputs

**Comment by langchain4j** [comment]
@tjake great, thanks for info!
FWIW, most LLM backends stream tool call JSON token by token...
