### ISSUE TITLE
Missing JSON Schema When Using Tools with Structured Outputs in LangChain4j

### ISSUE THREAD

**Issue by Gikicio** [langchain4j/langchain4j#2120]
**Bug Report: Missing JSON Schema When Using Tools with Structured Outputs in LangChain4j**

**Description:** When using structured outputs together with tools in LangChain4j, the JSON schema is not included in the requests during tool execution (The issue is not with structured outputs specifically, but rather that for normal responses, when tools are involved, the `generate` method is called without including the schema information.) . This causes the assistant to respond without the expected structured JSON format, leading to parsing failures.

**Steps to Reproduce:**

1. **Set Up Structured Outputs:**

   - Define an AI service method that returns a structured type (e.g., a custom POJO).
   - The schema is deduced automatically based on the output type and not directly provided by the user.

2. **Configure Tools:**

   - Implement tools by annotating methods with `@Tool` and add these tools to your AI service configuration.

3. **Invoke the AI Service Method:**

   - Call the method that uses both structured outputs and tools.

**Expected Behavior:**

- The assistant should include the deduced JSON schema in all requests, ensuring responses adhere to the expected structured format.

**Actual Behavior:**

- **Without Tools:** When structured outputs are used alone, the request properly flows through the `chat` method (dev.langchain4j.model.openai.OpenAiChatModel#chat), where the JSON schema is included:

  ```java
  Response<AiMessage> response = generate(
      request.messages(),
      request.toolSpecifications(),
      null,
      getOrDefault(toOpenAiResponseFormat(request.responseFormat(), strictJsonSchema), this.responseFormat)
  );
  ```

  This ensures that the response format includes the deduced schema.

- **With Tools:** When tools are used, the flow is different. The `generate` (dev.langchain4j.model.openai.OpenAiChatModel#generate(java.util.List\<dev.langchain4j.data.message.ChatMessage>, java.util.List\<dev.langchain4j.agent.tool.ToolSpecification>))\
  method is called without the response format being explicitly passed:

  ```java
  @Override
  public Response<AiMessage> generate(List<ChatMessage> messages, List<ToolSpecification> toolSpecifications) {
      return generate(messages, toolSpecifications, null, this.responseFormat);
  }
  ```

  Here, `this.responseFormat` does not retain the JSON schema, resulting in a missing schema in the request sent to the model.

**Impact:**

- Users are unable to reliably use structured outputs in combination with tools.
- The assistant's response cannot be parsed into the desired structured type.

**Please complete the following information:**
- LangChain4j version: 0.36
- LLM(s) used: OpenAI GPT_4_O_MINI
- Java version: 21

**Comment by langchain4j** [comment]
@Gikicio thanks a lot for reporting! I will address it asap!
