### ISSUE TITLE
Content Aggregator Aggregate Method Question

### ISSUE THREAD

**Issue by stevenli87** [langchain4j/langchain4j#2131]
I'm having trouble getting the aggregate method of the content aggregator to work as it's returning zero results. I have a variable called contents which is of type List of Content , studentSummary represents a String, and contentRetriever.retrieve(Query.from(studentSummary)) is a List<Content>.

        contents = contentAggregator.aggregate(
                    Collections.singletonMap(
                        Query.from(studentSummary),
                        Collections.singletonList(contentRetriever.retrieve(Query.from(studentSummary)))
                    )
                );

What am I doing wrong here? Thanks

**Comment by langchain4j** [comment]
Hi @stevenli87 please share a bit more code, it is not clear from this piece of code what is happening.
Did you implement your own content aggregator or are you using the default one?

**Comment by stevenli87** [comment]
hi @langchain4j i am using the default content aggregator. First I created a content retriever using the default interface and add a cohere reranker model:

         Filter filter = metadataKey("id").isIn(courseIds);

        contentRetriever = EmbeddingStoreContentRetriever.builder()
            .minScore(0.5)
            .embeddingStore(embeddingStore)
            .embeddingModel(embeddingModel)
            .filter(filter)
            .maxResults(15)
            .build();
          
       ScoringModel scoringModel = CohereScoringModel.builder().apiKey(cohereApiKey).modelName("rerank-english- 
       v3.0").build();
        ContentAggregator contentAggregator = 
        ReRankingContentAggregator.builder().scoringModel(scoringModel).minScore(0.8).build();

        contents = contentAggregator.aggregate(
            Collections.singletonMap(
                Query.from(studentSummary),
                Collections.singletonList(contentRetriever.retrieve(Query.from(studentSummary)))
            )
        );
        
        
I tried lowering the minScore in the ReRankingContentAggregator builder to almost 0 but it still didn't return any results.

**Comment by langchain4j** [comment]
@stevenli87 does `contentRetriever.retrieve(Query.from(studentSummary))` return any result? If yes, perharps remove `minScore` setting?

**Comment by stevenli87** [comment]
@langchain4j removing the `minScore` setting from the reranking content aggregator worked for me since `contentRetriever.retrieve(Query.from(studentSummary))` returned results. Thanks.
