### ISSUE TITLE
[BUG] Failed to load Huggingface native library.

### ISSUE THREAD

**Issue by stardyun** [langchain4j/langchain4j#2144]
**Describe the bug**

`EmbeddingModel embeddingModel = new BgeSmallZhV15EmbeddingModel();`
An error occurs when executing the above code

**Log and Stack trace**
```
11:14:42.733 [main] INFO ai.djl.util.Platform -- Found matching platform from: jar:file:/Users/jackie/.m2/repository/ai/djl/huggingface/tokenizers/0.30.0/tokenizers-0.30.0.jar!/native/lib/tokenizers.properties
11:14:42.740 [main] INFO ai.djl.huggingface.tokenizers.jni.LibUtils -- library not found in classpath: native/lib/osx-x86_64/cpu/libtokenizers.dylib
Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.jiuwei.tcmsp.thridapi.digitalhuman.service.impl.handler.InputEmbeddingHandler.main(InputEmbeddingHandler.java:108)
Caused by: java.lang.RuntimeException: ai.djl.engine.EngineException: Failed to load Huggingface native library.
	at dev.langchain4j.model.embedding.onnx.OnnxBertBiEncoder.<init>(OnnxBertBiEncoder.java:41)
	at dev.langchain4j.model.embedding.onnx.AbstractInProcessEmbeddingModel.loadFromJar(AbstractInProcessEmbeddingModel.java:48)
	at dev.langchain4j.model.embedding.onnx.bgesmallzhv15.BgeSmallZhV15EmbeddingModel.<clinit>(BgeSmallZhV15EmbeddingModel.java:31)
	... 1 more
Caused by: ai.djl.engine.EngineException: Failed to load Huggingface native library.
	at ai.djl.huggingface.tokenizers.jni.LibUtils.<clinit>(LibUtils.java:56)
	at ai.djl.huggingface.tokenizers.HuggingFaceTokenizer.newInstance(HuggingFaceTokenizer.java:185)
	at dev.langchain4j.model.embedding.onnx.OnnxBertBiEncoder.<init>(OnnxBertBiEncoder.java:38)
	... 3 more
Caused by: ai.djl.engine.EngineException: Unexpected flavor: cpu
	at ai.djl.huggingface.tokenizers.jni.LibUtils.copyJniLibrary(LibUtils.java:195)
	at ai.djl.huggingface.tokenizers.jni.LibUtils.loadLibrary(LibUtils.java:82)
	at ai.djl.huggingface.tokenizers.jni.LibUtils.<clinit>(LibUtils.java:54)
	... 5 more
```
**To Reproduce**

```
public static void main(String[] args) {

        EmbeddingStore<TextSegment> embeddingStore = new InMemoryEmbeddingStore<>();
        EmbeddingModel embeddingModel = new BgeSmallZhV15EmbeddingModel();

        // refresh(embeddingModel, embeddingStore);

        Embedding queryEmbedding = embeddingModel.embed("hello").content();
        EmbeddingSearchResult<TextSegment> relevant = embeddingStore.search(
                EmbeddingSearchRequest.builder()
                        .queryEmbedding(queryEmbedding)
                        .maxResults(10)
                        .build());
        EmbeddingMatch<TextSegment> embeddingMatch = relevant.matches().get(0);

        System.out.println(embeddingMatch.score()); // 0.8138435
        System.out.println(embeddingMatch.embedded().text()); // I like football.
    }
```
**Expected behavior**

**Please complete the following information:**
- LangChain4j version: 0.36.0
- LLM(s) used: BgeSmallZhV15EmbeddingModel
- Java version: 17
- Spring Boot version (if applicable): 3.2.3

**Additional context**

**Comment by annam002** [comment]
Same problem here. Works fine with version 0.34.0.

**Comment by langchain4j** [comment]
Thanks for reporting!
I would really appreciate any help with this issue (investigation/fixing).
Could someone please take care of it? 🙏

**Comment by omarmahamid** [comment]
@langchain4j I will take a look

**Comment by stardyun** [comment]
It seems that this version of the package doesn't have this directory.
`ai/djl/huggingface/tokenizers/0.30.0/tokenizers-0.30.0.jar!/native/lib/osx-x86_64`
```
<dependency>
      <groupId>ai.djl.huggingface</groupId>
      <artifactId>tokenizers</artifactId>
      <version>${ai.djl.version}</version>
  </dependency>
```
Is it not supported? @langchain4j @omarmahamid

**Comment by MonalisaClaimer** [comment]
Same problem here, had to downgrade the LangChain4j version

**Comment by omarmahamid** [comment]
@stardyun 

I assume u are mac user with intel processor ?

I can see that djl change the build between the versions


can you add this in your dependency and make sure every thing will work fine ?

````
        <dependency>
            <groupId>ai.djl.huggingface</groupId>
            <artifactId>tokenizers</artifactId>
            <version>0.28.0</version>
        </dependency>
````


@langchain4j 

upgrading to 0.30 djl tokenizer can block the mac intel users

https://github.com/langchain4j/langchain4j-embeddings/commit/88de236910d7584939115cc24f2fbd3e0300d56d


so I will try seeing why they block this , and may open an issue for them

**Comment by omarmahamid** [comment]
@stardyun 

From djl maintainer

https://github.com/deepjavalibrary/djl/issues/3488

macos intel is no longer supported from djl version 0.29.0

**Comment by omarmahamid** [comment]
djl commit removing support of mac intel.


https://github.com/deepjavalibrary/djl/commit/d2b854ed12cfe06a9c33f8e76c72781208782f12


@langchain4j this should be a release note to langchain4j-embedding versions

**Comment by misselvexu** [comment]
> @stardyun
> 
> From djl maintainer
> 
> [deepjavalibrary/djl#3488](https://github.com/deepjavalibrary/djl/issues/3488)
> 
> macos intel is no longer supported from djl version 0.29.0

If so, is that the only option to downgrade the version? Or will compatibility processing be considered at the LC4J framework level ?

**Comment by langchain4j** [comment]
@misselvexu unfortunately we do not have capacity to support this on our side

**Comment by stardyun** [comment]
> djl commit removing support of mac intel.
> 
> [deepjavalibrary/djl@d2b854e](https://github.com/deepjavalibrary/djl/commit/d2b854ed12cfe06a9c33f8e76c72781208782f12)
> 
> @langchain4j this should be a release note to langchain4j-embedding versions

OK, Thank U

**Comment by stardyun** [comment]
maven Management djl version 0.28.0 is supported
```
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>ai.djl.huggingface</groupId>
            <artifactId>tokenizers</artifactId>
            <version>0.28.0</version>
        </dependency>
    </dependencies>
</dependencyManagement>
```
