### ISSUE TITLE
[FEATURE] Opensearch, but not hosted on AWS

### ISSUE THREAD

**Issue by rems** [langchain4j/langchain4j#215]
The [`OpensearchEmbeddingStore`](https://github.com/langchain4j/langchain4j/blob/43917ee474a504ec4c02cf17729a967d2ab7ac01/langchain4j-opensearch/src/main/java/dev/langchain4j/store/embedding/opensearch/OpenSearchEmbeddingStore.java#L121) seems currently tied to AWS.

I'm using opensearch, but hosted elsewhere.

It could be useful to separate to two things: the store technology, and the hosting solution.

Ideally, there would be no dependencies to the [shadded aws jars](https://github.com/langchain4j/langchain4j/blob/43917ee474a504ec4c02cf17729a967d2ab7ac01/langchain4j-opensearch/src/main/java/dev/langchain4j/store/embedding/opensearch/OpenSearchEmbeddingStore.java#L37)

Thanks a lot for this project!

**Comment by mzhu-ai** [comment]
I think this issue can be closed since OpensearchEmbeddingStore builder method allows you to inject your own custom openSearchClient, it is not tied to aws sdk

**Comment by langchain4j** [comment]
@rems I will close this for now (see @mzhu-ai's comment). Feel free to reopen if needed.
