### ISSUE TITLE
Milvus support

### ISSUE THREAD

**Issue by liyf1** [langchain4j/langchain4j#22]
Can you support Milvus, please

**Comment by langchain4j** [comment]
@liyf1 yes, we plan to add it asap. Would you like to help with that? Thanks!

**Comment by maxiao124** [comment]
> @liyf1 yes, we plan to add it asap. Would you like to help with that? Thanks!

If there is no response, I am ready to proceed with this matter @langchain4j

**Comment by langchain4j** [comment]
@liyf1 so far I was not able to start with this. Please feel free to implement milvus integration. You can check how it is done for Pinecone (separate module). Thank you!

**Comment by langchain4j** [comment]
@liyf1 @maxiao124 supported in 0.23.0: https://github.com/langchain4j/langchain4j-examples/blob/main/milvus-example/src/main/java/MilvusEmbeddingStoreExample.java
