### ISSUE TITLE
[FEATURE] Which module in langchain4j replaces the Agent module in Langchain?

### ISSUE THREAD

**Issue by mylzj** [langchain4j/langchain4j#220]
Which module in langchain4j replaces the Agent module in Langchain?

**Comment by langchain4j** [comment]
@mylzj at the moment there are no real agents implemented, but AI Service with Tools is kind of "light agent". ReAct and similar algorithms are yet to be implemented.

**Comment by CharleyXu** [comment]
> @mylzj at the moment there are no real agents implemented, but AI Service with Tools is kind of "light agent". ReAct and similar algorithms are yet to be implemented.

How to use tools to implement a ReAct-based Agent？Are there any plans to implement it in the near future?

**Comment by langchain4j** [comment]
@CharleyXu although not exactly ReAct, this is an example of an agentic behaviour that can be implemented with Tools in LangChain4j: https://github.com/langchain4j/langchain4j-examples/blob/main/spring-boot-example/src/test/java/dev/example/CustomerSupportApplicationTest.java

**Comment by langchain4j** [comment]
Duplicate of https://github.com/langchain4j/langchain4j/issues/193

**Comment by zk020106** [comment]
> [@CharleyXu](https://github.com/CharleyXu) although not exactly ReAct, this is an example of an agentic behaviour that can be implemented with Tools in LangChain4j: https://github.com/langchain4j/langchain4j-examples/blob/main/spring-boot-example/src/test/java/dev/example/CustomerSupportApplicationTest.java虽然不完全是 ReAct，但这是可以使用 LangChain4j 中的工具实现的代理行为示例：https://github.com/langchain4j/langchain4j-examples/blob/main/spring-boot-example/src/test/java/dev/example/CustomerSupportApplicationTest.java

I want to view this clip, but it has now been deleted.
