### ISSUE TITLE
[FEATURE] How to connect to my local LLM

### ISSUE THREAD

**Issue by mylzj** [langchain4j/langchain4j#222]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by langchain4j** [comment]
@mylzj you can run local LLMs using LocalAI or oobabooga (or any other tool that has OpenAI-compatible API) and use `langchain4j-local-ai` dependency to connect to it
