### ISSUE TITLE
[FEATURE] Add httpClient to bedrock runtime client builder

### ISSUE THREAD

**Issue by rndtavares** [langchain4j/langchain4j#2238]
I need to use AWS Bedrock runtime client with a proxy setted on the httpClient, it is not possible right now because the BedrockRuntimeClient creation is in a private method, as a workaround and I am extending it on my company's project to add this httpClient. 

**Describe the solution you'd like**
A greater thing can be a possibility to pass the BedrockRuntimeClient itself to AbstractBedrockChatModel, without this, every time that I need to set a new property that is not on the AbstractSharedBedrockChatModel fields, I will need a new PR on langchain4j, by doing this if on some new version AWS put a new property it will automatically be ready for use on langchain4j, but I am not sure how can I pass a BedrockRuntimeClient.

Extending AbstractSharedBedrockChatModel to add a httpClient
<img width="824" alt="image" src="https://github.com/user-attachments/assets/b66b83e0-c9cb-4863-a607-b8c563354434">

So I can use it when creating a BedrockAnthropicMessageChatModel 
<img width="914" alt="image" src="https://github.com/user-attachments/assets/901ec8c8-5399-4c82-a8fd-824cf8e0ad8c">

**Comment by langchain4j** [comment]
@rndtavares thank you, good point!

Would you like to implement this? I can't advise right now with technicalities though.
BTW, there is a work in progress to integrate newer Converse API [here](https://github.com/langchain4j/langchain4j/pull/2132). Perharps the same should be done there?

**Comment by rndtavares** [comment]
Thanks @langchain4j, I will talk to my friend @herbert-beckman
