### ISSUE TITLE
[FEATURE] Make PDF and MS office parsed as optional modules. 

### ISSUE THREAD

**Issue by me0106** [langchain4j/langchain4j#224]
### Moving the module load to another module may be better. 

Many times when using Langchain, the document parsing function of PDF and MS office is not used.
```
 langchain4j
    └── document-loader
        ├── loader-ms-office
        └── loader-pdf
```

-------
### The following are optional. Perhaps a separate issue should be created.
`dev.langchain4j.data.document.DocumentLoaderUtils`  can use SPI to load and parse custom parsers.( OPTIONAL CHANGES )

#### BREAKING CHAINGE (DRAFT)
`DocumentParser 'interface changed to
```java
public interface DocumentParser {

      boolean support(DocumentSource source);
      
      Document parse(DocumentSource source)
}
```
usage: 
```java

class DocumentLoaderUtils {
    static Document load(DocumentSource source) {
        var parsers =   ServiceLoader.load(dev.langchain4j.data.document.DocumentParser.class);
        for (DocumentParser documentParser : parsers) {
            if (documentParser.support(source)) {
                return documentParser.parse(source);
            }
        }
        throw new RuntimeException("Failed to load document,No suitable parser found");
    }
}
```

**Comment by me0106** [comment]
@langchain4j Is this destructive modification allowed in the current situation ?

**Comment by Heezer** [comment]
from my side it makes sense! @langchain4j  what do you think? otherwise I would say @me0106 feel free to create PR for this

**Comment by me0106** [comment]
@langchain4j 
Are there any latest updates?

**Comment by Heezer** [comment]
@me0106 sorry for delay, simply create your PR

**Comment by langchain4j** [comment]
@me0106 sorry for the delay. I decided to go with a simple approach, without SPI and auto-recognition magic. Now one has to provide a `DocumentParser` when loading a document, see [here](https://github.com/langchain4j/langchain4j/pull/354/files#diff-19036fa2540cec947278d5d36cdd71410c398bf696feac64aee6ad4265849fa7). This way there is no limiting `DocumentType` enum and user can provide whatever parser he wants, also a custom one

**Comment by me0106** [comment]
nice work! :)
