### ISSUE TITLE
[BUG] AllMiniLmL6V2EmbeddingModel doesn't work with linux/amd64 openjdk:14-alpine 

### ISSUE THREAD

**Issue by stephanj** [langchain4j/langchain4j#225]
Please provide as much details as possible, this will help us to deliver a fix as soon as possible.
Thank you!

**Describe the bug**
Deploying a Java 14 Spring Boot 2.2.7 application to Google Cloud Kubernetes using an embedded LLM AllMiniLmL6V2EmbeddingModel.  Runs perfect locally on my Mac but when deploying the GCP I get the following error.

The docker file uses FROM --platform=linux/amd64 openjdk:14-alpine 

**Log and Stack trace**

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'presentationSearchService' defined in URL [jar:file:/app.war!/WEB-INF/classes!/com/devoxx/devoxxians/service/PresentationSearchService.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'semanticSearchService' defined in URL [jar:file:/app.war!/WEB-INF/classes!/com/devoxx/devoxxians/service/SemanticSearchService.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'embeddingModel' defined in class path resource [com/devoxx/devoxxians/config/Langchain4JConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [dev.langchain4j.model.embedding.EmbeddingModel]: Factory method 'embeddingModel' threw exception; nested exception is java.lang.UnsatisfiedLinkError: /tmp/onnxruntime-java13369089796432798736/libonnxruntime.so: Error loading shared library libstdc++.so.6: No such file or directory (needed by /tmp/onnxruntime-java13369089796432798736/libonnxruntime.so) at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:798) at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:228) at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1358) at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1204) at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557) at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226) at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:895) at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878) at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550) at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) at com.devoxx.devoxxians.DevoxxiansApp.main(DevoxxiansApp.java:65) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.base/java.lang.reflect.Method.invoke(Method.java:564) at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) at org.springframework.boot.loader.Launcher.launch(Launcher.java:51) at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:58) Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'semanticSearchService' defined in URL [jar:file:/app.war!/WEB-INF/classes!/com/devoxx/devoxxians/service/SemanticSearchService.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'embeddingModel' defined in class path resource [com/devoxx/devoxxians/config/Langchain4JConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [dev.langchain4j.model.embedding.EmbeddingModel]: Factory method 'embeddingModel' threw exception; nested exception is java.lang.UnsatisfiedLinkError: /tmp/onnxruntime-java13369089796432798736/libonnxruntime.so: Error loading shared library libstdc++.so.6: No such file or directory (needed by /tmp/onnxruntime-java13369089796432798736/libonnxruntime.so) at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:798) at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:228) at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1358) at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1204) at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557) at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226) at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1306) at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1226) at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:885) at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:789) ... 25 common frames omitted Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'embeddingModel' defined in class path resource [com/devoxx/devoxxians/config/Langchain4JConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [dev.langchain4j.model.embedding.EmbeddingModel]: Factory method 'embeddingModel' threw exception; nested exception is java.lang.UnsatisfiedLinkError: /tmp/onnxruntime-java13369089796432798736/libonnxruntime.so: Error loading shared library libstdc++.so.6: No such file or directory (needed by /tmp/onnxruntime-java13369089796432798736/libonnxruntime.so) at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:656) at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:484) at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1338) at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177) at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557) at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226) at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1306) at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1226) at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:885) at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:789) ... 39 common frames omitted Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [dev.langchain4j.model.embedding.EmbeddingModel]: Factory method 'embeddingModel' threw exception; nested exception is java.lang.UnsatisfiedLinkError: /tmp/onnxruntime-java13369089796432798736/libonnxruntime.so: Error loading shared library libstdc++.so.6: No such file or directory (needed by /tmp/onnxruntime-java13369089796432798736/libonnxruntime.so) at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:651) ... 53 common frames omitted Caused by: java.lang.UnsatisfiedLinkError: /tmp/onnxruntime-java13369089796432798736/libonnxruntime.so: Error loading shared library libstdc++.so.6: No such file or directory (needed by /tmp/onnxruntime-java13369089796432798736/libonnxruntime.so) at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method) at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2452) at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2508) at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2704) at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2637) at java.base/java.lang.Runtime.load0(Runtime.java:745) at java.base/java.lang.System.load(System.java:1871) at ai.onnxruntime.OnnxRuntime.load(OnnxRuntime.java:369) at ai.onnxruntime.OnnxRuntime.init(OnnxRuntime.java:160) at ai.onnxruntime.OrtEnvironment.<clinit>(OrtEnvironment.java:31) at dev.langchain4j.model.embedding.OnnxBertBiEncoder.<init>(OnnxBertBiEncoder.java:38) at dev.langchain4j.model.embedding.AbstractInProcessEmbeddingModel.loadFromJar(AbstractInProcessEmbeddingModel.java:21) at dev.langchain4j.model.embedding.AllMiniLmL6V2EmbeddingModel.<clinit>(AllMiniLmL6V2EmbeddingModel.java:18) at com.devoxx.devoxxians.config.Langchain4JConfiguration.embeddingModel(Langchain4JConfiguration.java:13) at com.devoxx.devoxxians.config.Langchain4JConfiguration$$EnhancerBySpringCGLIB$$d739cf84.CGLIB$embeddingModel$0(<generated>) at com.devoxx.devoxxians.config.Langchain4JConfiguration$$EnhancerBySpringCGLIB$$d739cf84$$FastClassBySpringCGLIB$$8dc60ee8.invoke(<generated>) at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) at com.devoxx.devoxxians.config.Langchain4JConfiguration$$EnhancerBySpringCGLIB$$d739cf84.embeddingModel(<generated>) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.base/java.lang.reflect.Method.invoke(Method.java:564) at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ... 54 common frames omitted

**To Reproduce**

Dockerfile

FROM --platform=linux/amd64 openjdk:14-alpine

**Expected behavior**
Had expected to work but probably needs a different OS?

**Please complete the following information:**
- LangChain4j version: 0.23.0
- Java version: 14
- Spring Boot version (if applicable): 2.2.7

**Comment by langchain4j** [comment]
Hi @stephanj, ChatGPT helped me here 😆:

The error you're experiencing originates from libonnxruntime.so not finding its dependency libstdc++.so.6:

```bash
java.lang.UnsatisfiedLinkError: /tmp/onnxruntime-java13369089796432798736/libonnxruntime.so: 
Error loading shared library libstdc++.so.6: No such file or directory (needed by /tmp/onnxruntime-java13369089796432798736/libonnxruntime.so)
```

This issue often occurs when you're using an Alpine-based image because Alpine uses musl instead of glibc and often doesn't have the standard C++ library installed by default.

Here are some suggestions to fix this:

**Option 1: Use a glibc-based image**
Switch to a glibc-based Java image instead of Alpine, as libstdc++.so.6 is usually pre-installed.

```Dockerfile
FROM --platform=linux/amd64 openjdk:14
```

**Option 2: Install the required libraries on the Alpine image**
If you still want to use the Alpine image, try installing the missing C++ standard library.

```Dockerfile
FROM --platform=linux/amd64 openjdk:14-alpine
RUN apk add --no-cache libstdc++
```

**Option 3: Use a multi-stage build**
In a multi-stage Docker build, you can copy only necessary executables and libraries from a fuller image to your Alpine image.

```Dockerfile
# First stage: Build the app and fetch dependencies
FROM --platform=linux/amd64 openjdk:14 AS builder
# ... your build steps here ...

# Second stage: Copy only what's needed
FROM --platform=linux/amd64 openjdk:14-alpine
COPY --from=builder /path/to/app /app
RUN apk add --no-cache libstdc++
```
