### ISSUE TITLE
[FEATURE] Support queries on DB's e.g. SQLite and MySQL among others like https://python.langchain.com/docs/use_cases/qa_structured/sql

### ISSUE THREAD

**Issue by jnahansen** [langchain4j/langchain4j#232]
**Is your feature request related to a problem? Please describe.**
I want to query SQLite and MySQL databases using an AI Chatbot but don't want to integrate with Python

**Describe the solution you'd like**
Desire something like the mechanisms provided by https://python.langchain.com/docs/use_cases/qa_structured/sql

**Describe alternatives you've considered**
Python integration with LangChain

**Comment by dylankolson** [comment]
+1 would love to see this feature - any roadmap on this?

**Comment by langchain4j** [comment]
Can be introduced as a custom implementation of `ContentRetriever`, similar to `Neo4jContentRetriever`

**Comment by langchain4j** [comment]
Implemented in https://github.com/langchain4j/langchain4j/pull/1056
