### ISSUE TITLE
[BUG] Error reported when calling QwenChatModel

### ISSUE THREAD

**Issue by cv-msan** [langchain4j/langchain4j#2335]
**Describe the bug**

Calling reports an error and returns an error message {"statusCode":404,"message":"Not Found","code":"response_error","isJson":false}
**Log and Stack trace**

**To Reproduce**

**Expected behavior**

```
public interface ChatModelFactory {
    /**
     * 创建模型实例
     * 
     * @param aiModel 从数据库中查询到的 AiModel 对象，包含动态参数
     * @return ChatLanguageModel 模型对象
     */
    ChatLanguageModel createModel(AiModel aiModel);
}
public class DashScopeChatModelFactory implements ChatModelFactory {
    @Override
    public ChatLanguageModel createModel(AiModel aiModel) {
        // 从 AiModel 对象中动态获取参数
        String apiKey = xxxx;
        String modelName = "qwen-max-latest";
        String baseUrl ="https://dashscope.aliyuncs.com/compatible-mode/v1";
        // 模型实例
        return QwenChatModel
                .builder()
                .baseUrl(baseUrl)
                .apiKey(apiKey)
                .modelName(modelName)
                .build();
    }
}
public ChatAssistant appAssistant(AppMessageVo message) {
                    return AiServices.builder(ChatAssistant.class)
                            .chatMemoryProvider(buildMemoryProvider()) // 设置历史对话窗口
                            .chatLanguageModel(languageModel) // 配置语言模型
                            .build();
              
 }
ChatAssistant chatAssistant = chatService.appAssistant(messageVo);

Result<String> resultChat = chatAssistant.chat(sessionId, messageVo.getMessage());
When calling this chat method, it returns  {"statusCode":404,"message":"Not Found","code":"response_error","isJson":false}
Zhipu and others are like this, only OpenAi does not report errors
When building OpenAI, the following steps are taken:
public class OpenAiChatModelFactory implements ChatModelFactory {
    @Override
    public ChatLanguageModel createModel(AiModel aiModel) {
        // 从 AiModel 对象中动态获取参数
        String apiKey = aiModel.getApiKey();
        String modelName = aiModel.getModelName();
        String baseUrl = aiModel.getBaseUrl();
        // 返回 OpenAI 模型实例
        return OpenAiChatModel
                .builder()
                .baseUrl(baseUrl)
                .apiKey(apiKey)
                .modelName(modelName)
                .build();
    }
}
```
**Please complete the following information:**
- LangChain4j version:1.0
- LLM(s) used: QwenChatModel，ZhipuAiChatModel
- Java version: 17
- Spring Boot version (if applicable): 3

**Additional context**

**Comment by cv-msan** [comment]
And the example code in the official documentation of langchain4j has been removed
![image](https://github.com/user-attachments/assets/261ae63f-cca9-4081-b451-068b1ed3ed9d)
![image](https://github.com/user-attachments/assets/c56acdcb-569b-49e4-b9a2-29a8b6ba7a37)

**Comment by Martin7-1** [comment]
@cv-msan Hi! Thank you for reporting.

Sorry about the broken link of docs, it's because `langchain4j-dashscope` has been migrated to [community repo](https://github.com/langchain4j/langchain4j-community). So could you please re-open this issue in [community repo](https://github.com/langchain4j/langchain4j-community)?

/cc @jiangsier-xyz

**Comment by Martin7-1** [comment]
And, I think it's a problem related to the `baseUrl`, what about removing it and just using:

```java
return QwenChatModel.builder()
            .apiKey(apiKey)
            .modelName("qwen-max-latest")
            .build();
```

**Comment by cv-msan** [comment]
> @cv-msan您好！感谢您报告。
> 
> 很抱歉文档链接已损坏，这是因为 `langchain4j-dashscope` 已迁移到 [社区仓库](https://github.com/langchain4j/langchain4j-community)。所以您能否请在此 [社区仓库](https://github.com/langchain4j/langchain4j-community) 中重新打开此问题？
> 
>   / cc@jiangsier-xyz

ok I will go to the community warehouse to resubmit the issue

**Comment by cv-msan** [comment]
> 并且，我认为这是一个与`baseUrl`相关的问题，关于移除它并只使用：
> 
> ```java
> return QwenChatModel.builder()
>             .apiKey(apiKey)
>             .modelName("qwen-max-latest")
>             .build();
> ```
Thank you very much for removing the baseURL. It does work, but Zhipu encountered other errors. I will submit them to the community repository
