### ISSUE TITLE
[BUG] ServiceOutputParser.outputFormatInstructions() does not crawl the custom field objects

### ISSUE THREAD

**Issue by konstantin-kostadinov** [langchain4j/langchain4j#234]
When determining outputFormatInstructions, only the first level of fields are described. 
Expected behavior: Recursively check if a field is not a primitive type (or already described) and write the whole json schema not just the 1st level. 
This results in JsonSyntaxException gson expects an object, but gets a string.

- LangChain4j version: 0.23.0
- Java version: 1.8

```
private static String jsonStructure(Class<?> structured) {
        StringBuilder jsonSchema = new StringBuilder();
        jsonSchema.append("{\n");
        for (Field field : structured.getDeclaredFields()) {
            jsonSchema.append(format("\"%s\": (%s),\n", field.getName(), descriptionFor(field)));
        }
        jsonSchema.append("}");
        return jsonSchema.toString();
    }

```

**Comment by langchain4j** [comment]
@konstantin-kostadinov thanks for reporting!

**Comment by konstantin-kostadinov** [comment]
jackson-module-jsonSchema is a good option for schema generation. It also supports jackson annotations, which is perfect for providing additional descriptions to the llm using @JsonPropertyDescription.

**Comment by langchain4j** [comment]
Should be fixed by https://github.com/langchain4j/langchain4j/pull/513

**Comment by langchain4j** [comment]
This is now supported in version 0.28.0
