### ISSUE TITLE
ToolExecutionRequest has a problem when parse argument to map

### ISSUE THREAD

**Issue by breezexiao** [langchain4j/langchain4j#24]
ToolExecutionRequest argumentsAsMap has a problem when parse argument to map, for example, default gson convert number to double, then cause java.lang.IllegalArgumentException: argument type mismatch when toolExecutor.execute beause my tool function parameter is integer

**Comment by langchain4j** [comment]
@breezexiao thank you for reporting! Could you please provide your tool method and the exception you are getting? Logs of execution would be very helpful as well. Thank you!

**Comment by langchain4j** [comment]
@breezexiao the issue has been fixed.
Please check 0.13.0 release and let me know if you have any problems.
Thanks

**Comment by breezexiao** [comment]
> @breezexiao the issue has been fixed. Please check 0.13.0 release and let me know if you have any problems. Thanks

@langchain4j Cool , my problem has been solved, thanks
