### ISSUE TITLE
Adding Neo4j/Cypher support for vector search and knowledge graph integration

### ISSUE THREAD

**Issue by jexp** [langchain4j/langchain4j#241]
**Is your feature request related to a problem? Please describe.**

Knowledge Graphs are widely seen as an important part for GenAI applications.
So integrating them into orchestration frameworks is a great way of giving users this capability.

Neo4j has added integrations to langchain and llamaindex for vector search, GraphQAChain for query generation, RAG and RAG with sources, where people can use their existing graph as part of their applications or generate new graphs from unstructured data.

**Describe the solution you'd like**
We would like to propose and also happy to implement Neo4j support in langchain4j similiar to how we did it in LangChain.

https://python.langchain.com/docs/integrations/providers/neo4j

* Vector Store
* GraphQAChain
* RetrieverChain
* GraphTransformer 

**Describe alternatives you've considered**
Not implementing the support, which would leave users without a valuable option. :)

**Additional context**

* [Neo4j GenAI](https://neo4j.com/generativeai)
* [Neo4j Vector Store](https://neo4j.com/docs/cypher-manual/current/indexes-for-vector-search/)
* [Docker+Neo4j GenAI Stack](https://github.com/docker/genai-stack)
* [LangChain Docs](https://python.langchain.com/docs/integrations/providers/neo4j)
* [LlamaIndex Docs](https://gpt-index.readthedocs.io/en/latest/examples/index_structs/knowledge_graph/Neo4jKGIndexDemo.html)

Happy to answer any questions in comments.

**Comment by langchain4j** [comment]
Hi @jexp sounds awesome! Seems like a lot of work, which feature would you like to start with? Looking forward to your contribution!

**Comment by jexp** [comment]
The vector index would be the first and easiest.
