### ISSUE TITLE
[FEATURE] Ollama Support

### ISSUE THREAD

**Issue by fxrobin** [langchain4j/langchain4j#244]
Simply adding Ollama support to langchain4j.

**Comment by Martin7-1** [comment]
@langchain4j Hi! Could you please assign it to me? I'm not familiar with Ollama, But Maybe I will complete it in one week.

After checking [Ollama's doc](https://github.com/jmorganca/ollama/blob/main/docs/api.md), looks like we should use REST API to interact with Ollama.

**Comment by langchain4j** [comment]
Was added in https://github.com/langchain4j/langchain4j/releases/tag/0.24.0
