### ISSUE TITLE
[FEATURE] Terminate a running streaming model

### ISSUE THREAD

**Issue by stoneLee81** [langchain4j/langchain4j#245]
If it is running streamModel, how to terminate the runnnng model and obtain the execution token？

**Comment by langchain4j** [comment]
@stoneLee81 could you please elaborate? what do you mean by "execution token" ?

**Comment by stoneLee81** [comment]
A callback can be provided to stop a running steam mode chat and return how many tokens have been executed when stopping

**Comment by zzutligang** [comment]
I also have this requirement

**Comment by langchain4j** [comment]
@stoneLee81 does LLM providers provide token usage when streaming is cancelled?

**Comment by stoneLee81** [comment]
> @stoneLee81 does LLM providers provide token usage when streaming is cancelled?

I am currently using ByteDance's Doubao model, which has a terminate callback in its SDK that provides token consumption details after termination.

**Comment by langchain4j** [comment]
Oh that's nice! AFAIK no other LLM provider does this?

**Comment by stoneLee81** [comment]
> Oh that's nice! AFAIK no other LLM provider does this?

Other LLM providers should work similarly. ByteDance's Doubao model, in stream mode, will stop generating tokens when the code execution is throw exception and terminated. This has been confirmed after consulting their technical team.

**Comment by stoneLee81** [comment]
> Oh that's nice! AFAIK no other LLM provider does this?

My current method for handling the logic of successfully interrupting a stream execution is as follows: after receiving the chat UUID, I compare it with the conversation UUID. If they match, I throw an exception inside the stream's `subscribe` block. At the same time, I calculate the token count of the current prompt as input tokens and the token count of the model's output at the moment of interruption as output tokens. This approach addresses the situation where a conversation is interrupted.

At present, this seems to be the only solution, as I have consulted ByteDance's technical team, and they confirmed that in cases of conversation interruption exceptions, they do not return the executed tokens. Most likely, this is the same with other model providers as well.
