### ISSUE TITLE
[FEATURE] Support for Amazon Bedrock

### ISSUE THREAD

**Issue by quadrrem** [langchain4j/langchain4j#247]
**Is your feature request related to a problem? Please describe.**
I would like to use langchain4j to access models provided by [Amazon Bedrock](https://aws.amazon.com/bedrock/)

**Describe the solution you'd like**
Provide an  integration that works with Amazon Bedrock (using the [AWS SDK](https://docs.aws.amazon.com/bedrock/latest/userguide/api-setup.html))

**Describe alternatives you've considered**
-

**Additional context**
Integrations were already requested for [langchain-js](https://github.com/langchain-ai/langchainjs) and [langchain](https://github.com/langchain-ai/langchain):
- https://github.com/langchain-ai/langchainjs/issues/775
- https://github.com/langchain-ai/langchain/issues/2828

**Comment by pascalconfluent** [comment]
Hello!

I implemented support for Bedrock (Claude, AI21, Titan) and also Embedding for Titan.
Will be happy to share the code.

**Comment by pascalconfluent** [comment]
This feature request should be closed. Implemented since version 0.24.0
