### ISSUE TITLE
SystemMessage annotation Should fit parameters

### ISSUE THREAD

**Issue by caopengan** [langchain4j/langchain4j#258]
There are some business scenarios that require dynamic SystemMessages, but don't want to consume the token every time.

If you can understand what I mean.

**Comment by langchain4j** [comment]
@caopengan could you please elaborate? I am not sure what you mean.

**Comment by langchain4j** [comment]
`@SystemMessage` supports variables, you can do it like this:
```
@SystemMessage("You are a professional translator into {{language}}")
@UserMessage("Translate the following text: {{text}}")
String translate(@V("text") String text, @V("language") String language);
```

**Comment by langchain4j** [comment]
@caopengan I am closing this because there is no answer. Please feel free to reopen.
