### ISSUE TITLE
[BUG] Pinecone java uses Apache 2.0 license

### ISSUE THREAD

**Issue by rohanshah18** [langchain4j/langchain4j#261]
Please provide as much details as possible, this will help us to deliver a fix as soon as possible.
Thank you!

**Describe the bug**
Pinecone-java has updated license to Apache 2.0 recently, so please update the pom.xml's description for pinecone integration repo.
Pom.xml: https://github.com/langchain4j/langchain4j/blob/main/langchain4j-pinecone/pom.xml#L18
Pinecone-java license: https://github.com/pinecone-io/pinecone-java-client/blob/main/LICENSE

**Log and Stack trace**
NA

**To Reproduce**
NA

**Expected behavior**
Should say Apache 2.0 license

**Please complete the following information:**
NA

**Additional context**
NA

**Comment by langchain4j** [comment]
@rohanshah18 thanks for reporting! fixed in https://github.com/langchain4j/langchain4j/pull/409
