### ISSUE TITLE
[BUG] content for function call response is empty, not null, result in failure in function calling

### ISSUE THREAD

**Issue by CoderYellow** [langchain4j/langchain4j#264]
this [example](https://github.com/langchain4j/langchain4j-examples/blob/main/other-examples/src/main/java/ServiceWithToolsExample.java) is not working, cuz i got this response from openai:
```json
{
  "id": "chatcmpl-psapACakPhkyDCMJwQpwISLWiPNGn",
  "object": "chat.completion",
  "created": 1699257338,
  "model": "gpt-3.5-turbo",
  "choices": [
    {
      "index": 0,
      "message": {
        "role": "assistant",
        "content": "",
        "function_call": {
          "name": "stringLength",
          "arguments": "{\n\"arg0\": \"hello\"\n}"
        }
      },
      "finish_reason": "function_call"
    }
  ],
  "usage": {
    "prompt_tokens": 122,
    "completion_tokens": 15,
    "total_tokens": 137
  }
}
```
as you can see, the content here is empty string, not null.
so this [code](https://github.com/langchain4j/langchain4j/blob/dbc141a10f698ef29ebd50724ee13f6a4478a7e7/langchain4j-open-ai/src/main/java/dev/langchain4j/model/openai/InternalOpenAiHelper.java#L107) here is not working as expected :
```java

    public static AiMessage aiMessageFrom(ChatCompletionResponse response) {
        if (response.content() != null) {
            return aiMessage(response.content());
        } else {
            FunctionCall functionCall = response.choices().get(0).message().functionCall();

            ToolExecutionRequest toolExecutionRequest = ToolExecutionRequest.builder()
                    .name(functionCall.name())
                    .arguments(functionCall.arguments())
                    .build();

            return aiMessage(toolExecutionRequest);
        }
    }
```
may be we should use some thing like `StringUtils.isEmpty()`

**Comment by CoderYellow** [comment]
may i know are there any quick ways for me to change the json deserialization behavior, i don't have time for this to be fixed

**Comment by CoderYellow** [comment]
new findings, even  there is a response in the content, there could be a function call too

**Comment by langchain4j** [comment]
Fixed in https://github.com/langchain4j/langchain4j/pull/414
