### ISSUE TITLE
[FEATURE]  support for chatglm

### ISSUE THREAD

**Issue by fullofinspiration** [langchain4j/langchain4j#267]
**Is your feature request related to a problem? Please describe.**
want to chatglm 

**Describe the solution you'd like**
support for chatglm

**Comment by Martin7-1** [comment]
Hi @fullofinspiration , Could you please describe it more detailed? It seems that `chatglm` has many version and should we support it all?

btw, different `chatglm` version seems have different API definition, some are compatible with the OpenAI API. Can these models use `langchain4j-open-ai` directly?

**Comment by langchain4j** [comment]
released in 0.25.0
