### ISSUE TITLE
Support `response_format` parameter

### ISSUE THREAD

**Issue by benedictstrube** [langchain4j/langchain4j#270]
Please support the [`response_format`](https://platform.openai.com/docs/api-reference/chat/create#chat-create-response_format) parameter to allow for a guaranteed JSON response. A solution could be to automatically set the parameter in case of a non-String return type in the provided chat completion method interface.

**Comment by sweakpl** [comment]
Additionally the new [`seed`](https://platform.openai.com/docs/api-reference/chat/create#chat-create-seed) parameter could be added in one go with the `response_format` parameter.

**Comment by mozhou-tech** [comment]
Waiting for this feature.

**Comment by mozhou-tech** [comment]
> Waiting for this feature.

In my scenario,  gpt response as restful api response.

**Comment by langchain4j** [comment]
Added this in https://github.com/langchain4j/langchain4j/pull/374 (without automagic for now, will think about it for the next release)
