### ISSUE TITLE
[BUG] AzureOpenAi*Model/Builder classes missing params "n" & "stop"

### ISSUE THREAD

**Issue by nileshpa** [langchain4j/langchain4j#273]
AzureOpenAi*Model/Builder classes are missing params "n" & "stop"

Although the underline request classes like ChatCompletionRequest, and CompletionRequest do have those members to pass it to LLM.

The AzureOpenAi*Model/Builder can be updated to include missing params "n" & "stop" which can be set in the CompletionRequest.

- LangChain4j version: 0.23.0

**Comment by langchain4j** [comment]
@nileshpa `n` (multiple generations at once) is not supported by current LangChain4j API and I am not sure will be (as it will complicate the API and all other features). You can get multiple responses/generations by calling `AzureOpenAi*Model` multiple times sequentially or in parallel if needed. Regarding `stop`, good point. @jdubois would you be able to add this please while I am still waiting for API keys?
