### ISSUE TITLE
[BUG] cant load local embedding model with my local vocabulary file

### ISSUE THREAD

**Issue by KonngExplorer** [langchain4j/langchain4j#277]
cant load local embedding model with local vocabulary file，because PoolingMode class is not public
![image](https://github.com/langchain4j/langchain4j/assets/22168681/097ba17a-1c0f-4c6a-92b2-6b9d7dc9242e)

- LangChain4j version: 0.23.0
- Java version: 17
- Spring Boot version (if applicable): 3.2.0

**Comment by langchain4j** [comment]
was fixed
