### ISSUE TITLE
[BUG] PG Vector Index creation statement incorrect

### ISSUE THREAD

**Issue by lukasstanek** [langchain4j/langchain4j#283]
Please provide as much details as possible, this will help us to deliver a fix as soon as possible.
Thank you!

**Describe the bug**
In the new PgVectorEmbeddingStore there's an option to create the ivfflat index for the vector column automatically. This statement seems to be incorrect as I couldn't execute it in my Tests. 

The statement does not include the "name" of the index as described here: https://www.postgresql.org/docs/current/sql-createindex.html

The statement used is this 
`"CREATE INDEX IF NOT EXISTS ON %s " +
                                "USING ivfflat (embedding vector_cosine_ops) " +
                                "WITH (lists = %s)"`

The correct statement should look something like this: 
`"CREATE INDEX IF NOT EXISTS %s ON %s USING ivfflat (embedding vector_cosine_ops) WITH (lists = %s)"`

**Log and Stack trace**
`java.lang.RuntimeException: org.postgresql.util.PSQLException: ERROR: syntax error at or near "ON"
  Position: 28
	at dev.langchain4j.store.embedding.pgvector.PgVectorEmbeddingStore.<init>(PgVectorEmbeddingStore.java:107)`

**To Reproduce**
just use the pgvector embedding store with the useIndex true option (and createdTable to true)

**Expected behavior**
Should create the table and the respective index on the column

**Please complete the following information:**
- LangChain4j version: 0.24.0

**Additional context**

**Comment by pascalconfluent** [comment]
Fixed.

Here is the PR associated to this issue:
https://github.com/langchain4j/langchain4j/pull/302

**Comment by kevin-wu-os** [comment]
quote from the article [linked](https://www.postgresql.org/docs/current/sql-createindex.html)

```
 If the name is omitted, PostgreSQL chooses a suitable name based on the parent table's name and the indexed column name(s).
 ```
 
Can you select your Postgres Version with `SELECT version();`?

Here is my output
`PostgreSQL 15.3 on aarch64-unknown-linux-gnu, compiled by aarch64-unknown-linux-gnu-gcc (GCC) 9.5.0, 64-bit`

I am using 15.3 without any problem with index autogeneration with suffix `xxx_embedding_idx`

**Comment by lukasstanek** [comment]
It's weird i'm using
Version: PostgreSQL 15.3 (Debian 15.3-1.pgdg110+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit 
docker image: ankane/pgvector:v0.4.4

And it's failing for me.

**Comment by kevin-wu-os** [comment]
In the initial implementation, see local test I use `ankane/pgvector:v0.5.1`
I just spin it up again and tried the following.

```
CREATE TABLE
  public.items (
    vector_id uuid NOT NULL,
    embedding vector(384) NULL,
    text text NULL,
    metadata json NULL
  );

ALTER TABLE
  public.items
ADD
  CONSTRAINT items_pkey PRIMARY KEY (vector_id);

CREATE INDEX ON public.items USING ivfflat (embedding vector_cosine_ops) WITH (lists='100');

SELECT *
FROM pg_indexes
WHERE indexname LIKE '%embedding_idx';
```

<img width="1142" alt="Screen Shot 2023-11-23 at 11 22 48 AM" src="https://github.com/langchain4j/langchain4j/assets/106975698/c77ab84e-e4a3-4613-afbb-3e771352fc52">
<img width="1585" alt="Screen Shot 2023-11-23 at 11 22 58 AM" src="https://github.com/langchain4j/langchain4j/assets/106975698/a80dbba3-ec79-455b-8c3d-7a17e60eb0b0">


Info:
Version query
`PostgreSQL 15.4 (Debian 15.4-2.pgdg120+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit`

**Comment by lukasstanek** [comment]
You're using create index without the "IF NOT EXISTS" clause. For the latter you need an index name because how else would they check if they index does already exist.

**Comment by kevin-wu-os** [comment]
Good catch - 
https://www.postgresql.org/docs/current/sql-createindex.html#:~:text=index%20name%20is%20required%20when%20if%20not%20exists%20is%20specified.
