### ISSUE TITLE
[FEATURE] add support for xunfei spark llm

### ISSUE THREAD

**Issue by naliazheli** [langchain4j/langchain4j#284]
Is your feature request related to a problem? Please describe.

The current repository only supports English language models like GPT-3. There is no support for Chinese language models, limiting the usefulness of the repository for Chinese users.

Describe the solution you'd like

I would like to see support added for the Xunfei Spark Chinese language model. This would allow Chinese users to build applications with a large Chinese language model through the repository.

Describe alternatives you've considered

The only alternative is to use English models like GPT-3, but they lack capabilities for Chinese content. Xunfei Spark is currently the leading Chinese language model.

Additional context

Adding support for Xunfei Spark will significantly increase the accessibility of the repository for Chinese developers. Spark has strong capabilities for generating Chinese text, answering questions, and more. Supporting this model alongside English models like GPT-3 will make the repository useful to a wider global audience.

**Comment by naliazheli** [comment]
generated by claude....

**Comment by Martin7-1** [comment]
Sounds great for Chinese Developers. Maybe I will PR for it in 3-4 weeks

**Comment by langchain4j** [comment]
@naliazheli please note that we already have support for ChatGLM, DashScope and Ollama/LocalAI where you can use chinese LLMs

**Comment by Darmian1998** [comment]
I have submitted a PR for Sparkdesk. If you are interested, could you help me review it @naliazheli @langchain4j @Martin7-1
