### ISSUE TITLE
make it module friendly [BUG] 

### ISSUE THREAD

**Issue by siddhsql** [langchain4j/langchain4j#285]
Please provide as much details as possible, this will help us to deliver a fix as soon as possible.
Thank you!

**Describe the bug**

https://stackoverflow.com/questions/77267416/the-unnamed-module-reads-package-dev-langchain4j-store-embedding-from-both-langc 

```
the unnamed module reads package dev.langchain4j.store.embedding from both langchain4j and langchain4j.core
```

**To Reproduce**

try to use langchain4j as a Java module. complete example to reproduce the bug: https://github.com/siddhsql/jpms-sample/tree/main

**Expected behavior**
should work

**Please complete the following information:**
- LangChain4j version: e.g. 0.22.0
- Java version: e.g. 20
- Spring Boot version (if applicable): NA

**Additional context**
the fix for this bug is that each module should use a unique namespace i.e., don't declare classes that are contained within the same namespace but spread across multiple packages.

**Comment by langchain4j** [comment]
@siddhsql this should be fixed by https://github.com/langchain4j/langchain4j/commit/3882133f6e8f070f4db768c296b9e89df35ed20e in 0.25.0
