### ISSUE TITLE
[BUG] DefaultAiServices should not include outputFormatInstructions to retrieve relevant TextSegments

### ISSUE THREAD

**Issue by Fritsii** [langchain4j/langchain4j#294]
**Describe the bug**
On line 99 in DefaultAiServices, the full prepared UserMessage is used to get relevant TextSegments. This UserMessage can contain instructions for formatting (like a description of a json format). This can cause irrelevant TextSegments to be retrieved.

**Expected behavior**
The output format instructions should be stripped or excluded for retrieving relevant TextSegments.

**Please complete the following information:**
- LangChain4j version: e.g. 0.24.0
- Java version: any
- Spring Boot version (if applicable): any

**Comment by langchain4j** [comment]
Hi @Fritsii, this is now fixed in 0.26.1!
