### ISSUE TITLE
[BUG] NoSuchMethodError: com.knuddels.jtokkit.Encodings.newLazyEncodingRegistry()

### ISSUE THREAD

**Issue by cian666** [langchain4j/langchain4j#304]
java.lang.NoSuchMethodError: com.knuddels.jtokkit.Encodings.newLazyEncodingRegistry()。
在OpenAiTokenizer构造器中，this.encoding = Encodings.newLazyEncodingRegistry().getEncodingForModel(modelName);
但实际Encodings没有newLazyEncodingRegistry方法。

**Comment by Martin7-1** [comment]
@cian666 Hi! Can you show more details about your project such as `pom.xml`? This error could be because you import a different version of `jtokkit` elsewhere in `pom.xml`.

**Comment by langchain4j** [comment]
Hi @cian666, I am closing this issue as we did not hear from you. I hope that the comment @Martin7-1 helped you. Feel free to reopen if needed.

**Comment by PainSix** [comment]
@cian666 The version of the com.knuddels.jtokkit package in the project was too low (0.2.0). I deleted the jar package and re-imported the 0.6.1 version, and then it was fixed.
