### ISSUE TITLE
The 'chain' in langchain4j is too rigidly implemented, requiring more integration for custom processes, and there isn't a solution provided.[FEATURE] 

### ISSUE THREAD

**Issue by leojames** [langchain4j/langchain4j#305]
**Is your feature request related to a problem? Please describe.**
when i use langchain4j, i want to deal with some user message before do findRelevant but the func `    @Override
    public List<TextSegment> findRelevant(String text) {

        Embedding embeddedText = embeddingModel.embed(text).content();

        List<EmbeddingMatch<TextSegment>> relevant;
        if (minScore == null) {
            relevant = embeddingStore.findRelevant(embeddedText, maxResults);
        } else {
            relevant = embeddingStore.findRelevant(embeddedText, maxResults, minScore);
        }

        return relevant.stream()
                .map(EmbeddingMatch::embedded)
                .collect(toList());
    }`

**Describe the solution you'd like**
please add the origin text of user message to the func paramters ,just like 
`    @Override
    public List<TextSegment> findRelevant(String text) {

        Embedding embeddedText = embeddingModel.embed(text).content();

        List<EmbeddingMatch<TextSegment>> relevant;
        if (minScore == null) {
            relevant = embeddingStore.findRelevant(originText,embeddedText, maxResults);
        } else {
            relevant = embeddingStore.findRelevant(originText,embeddedText, maxResults, minScore);
        }

        return relevant.stream()
                .map(EmbeddingMatch::embedded)
                .collect(toList());
    }`

**Describe alternatives you've considered**
when i want to fix some user message or translate to anther question ,i can do everythin just i like to do .

**Comment by igerdy** [comment]
I also encountered such a problem in my business, and my solution was to reimplement the interface.

**Comment by langchain4j** [comment]
Working on improving this right now, next release should include it.

**Comment by leojames** [comment]
> I also encountered such a problem in my business, and my solution was to reimplement the interface.

yes  i apply the pr to next version

**Comment by langchain4j** [comment]
@leojames this is now supported in this PR: https://github.com/langchain4j/langchain4j/pull/538.
There are now many extension points where you could plug in your custom behaviour.
Feel free to reopen this issue if there is something missing.
