### ISSUE TITLE
AzureOpenAIChatModel not working and not able to pass llm model

### ISSUE THREAD

**Issue by fafafifi123** [langchain4j/langchain4j#307]
How can i pass llm model when initializing AzureOpenAiChatModel?

i hit 404 resource not found when use the AzureOpenAIChatModel
```
Caused by: dev.ai4j.openai4j.OpenAiHttpException: {"error":{"code":"404","message": "Resource not found"}}
	at dev.ai4j.openai4j.Utils.toException(Utils.java:8)
	at dev.ai4j.openai4j.SyncRequestExecutor.execute(SyncRequestExecutor.java:28)
	at dev.ai4j.openai4j.RequestExecutor.execute(RequestExecutor.java:59)
```

Sample code to reproduce
```
 AzureOpenAiChatModel model= AzureOpenAiChatModel.builder()
                .apiKey(token).baseUrl(baseUrl)
                .logRequests(true).temperature(0.0).apiVersion("<proper_version>").build();
        ChatMessage message = new UserMessage("Hello, How are you?");
        StopWatch stopWatch = new StopWatch();
        //execute and get the response
        stopWatch.start();
        Response< AiMessage> response = model.generate(message);
        stopWatch.stop();
```

- LangChain4j version: 0.24.0
- Java version: 17

**Comment by langchain4j** [comment]
Hi @willyhalim how does your `baseUrl` look like?
Here is a proper format of it: `https://{resource}.openai.azure.com/openai/deployments/{deployment}`, you need to input a correct `resource` and `deployment`

**Comment by fafafifi123** [comment]
Hi , is there any plan to make it similar like langchain python ? the reason is my baseUrl will be specific to my company. This is how i made it work in python

```
def setup_openai(key):
    openai.api_key = key
    openai.api_type = "azure"
    openai.api_base = "https://mycompany.com/azure/"
    openai.api_version = "2023-07-01"

 setup_openai(mykey)
        print(f"openai.api_base={openai.api_base}")
        print(f"openai.api_type={openai.api_type}")
        print(f"openai.api_key={openai.api_key}")
        print(f"openai.temperature={temperature}")
        model = ChatOpenAI(model=llm_model, temperature=temperature, openai_api_key=openai.api_key,
                         openai_api_base=openai.api_base,
                         request_timeout=480, streaming=True,
                         deployment_id=llm_model, callbacks=callbacks)
```

**Comment by langchain4j** [comment]
@willyhalim do you need `Azure OpenAI` or `OpenAI`?

**Comment by langchain4j** [comment]
@jdubois could you please comment on this? Will new Azure SDK support this use case? Thanks

**Comment by jdubois** [comment]
This looks a lot like what we do in our tests at https://github.com/langchain4j/langchain4j/blob/0c4d33ad9390c76a319602d6f66e574de42bd9aa/langchain4j-azure-open-ai/src/test/java/dev/langchain4j/model/azure/AzureOpenAiChatModelIT.java#L25 and yes, the `endpoint` is the URL where you deploy your models (for me it's something like `https://judubois-xxxxx.openai.azure.com/`), and then you can have as many deployments as you want on it (like `gpt-35-turbo` and `dall-e-3`)

**Comment by jdubois** [comment]
As tomorrow there should be a new release with the new Azure OpenAI SDK instead, @willyhalim will you be able to check the new version? It's a full rewrite, and hopefully that will solve your issue.

**Comment by langchain4j** [comment]
@willyhalim 0.25.0 is available, please check if you still face the issue

**Comment by DenisVoloshin** [comment]
Hello @jdubois, do you have any roadmap for incorporating support to connect to the organization Azure AI proxy endpoint from  langchain4j? This would involve utilizing a Bearer token and the organization proxy endpoint.
Thanks

**Comment by jdubois** [comment]
Hi @DenisVoloshin with the latest release, that included a full re-rewrite with the migration to the Azure OpenAI SDK, this should work.
Otherwise please send more details, and if that’s not possible publicly you can reach me directly.

**Comment by langchain4j** [comment]
This issue seems solved, I am closing it now. Feel free to reopen if needed.
