### ISSUE TITLE
[FEATURE] add support to pass OpenSearchClient to OpenSearchEmbeddingStore

### ISSUE THREAD

**Issue by sboeckelmann** [langchain4j/langchain4j#308]
**Is your feature request related to a problem? Please describe.**
Some CDI based frameworks provide an externally configured OpenSearchClient. Currently there's no way of reusing a properly configured client.

**Describe the solution you'd like**
be able to pass OpenSearchClient to the constructor, similar to what was provided for Elasticsearch in https://github.com/langchain4j/langchain4j/issues/290

**Describe alternatives you've considered**
create an own implementation of EmbeddingStore<TextSegment> for OpenSearch

**Additional context**
I came across this when thinking about adding support for OpenSearch using
https://github.com/quarkiverse/quarkus-opensearch
in 
https://github.com/quarkiverse/quarkus-langchain4j

Other EmbeddingStore are also missing a way to pass client or datasource directly.
Making similar adjustments may be beneficial for other EmbeddingStores as well. What's the project's view on this?

**Comment by langchain4j** [comment]
Hi @sboeckelmann sounds like a good idea, I don't have anything against it. Do you see any cons with this approach? Thanks
