### ISSUE TITLE
[BUG] Null pointer exception due to null finish_reason while testing local LLMS

### ISSUE THREAD

**Issue by ericblue** [langchain4j/langchain4j#316]
I'm in the process of evaluating a number of local LLMS.  I'm levering a project called LiteLLM (https://litellm.ai/) as a proxy, which essentially adds OpenAI API compliance for a large number of LLMs and services.  In my case, I am testing out LiteLLM with Ollama .

This setup has no issues, and works with a number of chat clients and direct with Curl requests.  E.g.

curl --location 'http://0.0.0.0:8000/chat/completions'     --header 'Content-Type: application/json'     --data ' {
    "model": "ollama-custom",
    "messages": [
        {
        "role": "user",
        "content": "what llm are you"
        }
    ]
    }' | jq .

I noticed that by default, it seems that the value for finish_reason is null.  I'm not certain if there are cases where this is legit, but it is causing a null pointer exception.

Here is another example with the request/response:

![image](https://github.com/langchain4j/langchain4j/assets/319455/efd49654-6330-4172-9dad-665419a96770)

Given the following code:

 ChatLanguageModel chatLanguageModel =OpenAiChatModel.builder()
                .apiKey("na")
                .modelName("ollama-custom")
                .baseUrl("http://localhost:8000/")
                .timeout(ofSeconds(60))
                .proxy(new Proxy(Proxy.Type.HTTP, new InetSocketAddress("127.0.0.1", 8888)))
                .logRequests(true)
                .logResponses((true))
                .build();

        Assistant assistant = AiServices.create(Assistant.class, chatLanguageModel);
        
        String answer = assistant.chat("What is the capital of France?");
        System.out.println(answer);

I'm getting the following exception:

![image](https://github.com/langchain4j/langchain4j/assets/319455/59b98968-c2bb-4ab1-88ff-1ed035b8d0a8)

Is there an issue with the code here (e.g. some missing option and not streaming?) or should this case be handled?  Essentially, in OpenAIChatModel

  return Response.from(
                aiMessageFrom(response),
                tokenUsageFrom(response.usage()),
                finishReasonFrom(response.choices().get(0).finishReason())
        );

finishReasonFrom is null and causing the exception.

**Comment by ghost** [comment]
this was a [litellm](https://github.com/BerriAI/litellm) bug that's now fixed @ericblue let me know if the issue persists for you.

**Comment by ericblue** [comment]
Thanks @krrishdholakia!  I just checked out the latest litellm code and verified that the issue is now resolved.
