### ISSUE TITLE
[FEATURE] Ollama to support Tools/Functions

### ISSUE THREAD

**Issue by goafabric** [langchain4j/langchain4j#318]
Langchain4j is at it's current state already an awesome product.
And the recent Ollama integration, makes it possible to have a powerfull LLM running locally, for chat requests.

What it is unfortunately missing, is an implementation of the ChatLanguageModel,
that can be used together with Functions and Tools.
To melt local code with an LLM
For OpenAI we have OpenAiChatModel + AIServices.

For Ollama, thats not yet there.
Outside the Java Ecosystem i found this one:
https://js.langchain.com/docs/integrations/chat/ollama_functions

Would it be possible to get an Ollama Integration similar to the OpenAI one ?

**Comment by langchain4j** [comment]
HI @goafabric yes, this is one of the higher priorities right now. Not sure about Ollama (will check a bit later), but [LocalAI](https://localai.io/) supports [function calling](https://localai.io/features/openai-functions/). Of course it depends a lot on the underlying model... If you have a possibility to run it somewhere (there is a docker image), you can try `AiServices` + `LocalAiChatModel` (from `langchain4j-local-ai` module) with some llamacpp model fine-tuned for function calling.

**Comment by goafabric** [comment]
thx 4 letting me know .. i shied away from localai .. because of the rather complex build options
but i now found there is a simple "localai.app" that can even run on apple silicon .. i might eventually give that a spin
until function support is there for ollama

thx again

**Comment by langchain4j** [comment]
@goafabric Ollama has `format="json"` which can help with function calling, I have added support for this in https://github.com/langchain4j/langchain4j/pull/373

**Comment by bidek** [comment]
I made some experiments, trying to convince model to respond in specific manner if he want to execute tool.

If model respond with string `TOOL-EXECUTION-REQUEST - currentDate` i capture this and respond with `ToolExecutionRequest` to be compatible with current tool execution flow from `DefaultAiServices`.

For now, it only support tools without parameters, capturing and parsing execution request is very fragile but it works.

I tested it on `mistral` model from standard ollama model repository

Its based on work of @fintanmm , maybe @fintanmm could comment on how he sees ollama langchain tool support

[fork-with-ollama-tool-support](https://github.com/bidek/langchain4j/tree/features/ollama-tools-support)
[example-tool-usage](https://github.com/bidek/ollamaToolUsage/blob/master/src/main/java/Main.java)

**Comment by fintanmm** [comment]
I haven't thought that far ahead @bidek. I was working on getting familiar with the code and seeing where I could contribute.

**Comment by langchain4j** [comment]
How it is done in python: https://github.com/langchain-ai/langchain/blob/9b3962fc2521ec0d6ef2ea7c0a40b9c32977671a/libs/experimental/langchain_experimental/llms/ollama_functions.py

**Comment by morki** [comment]
This would be huge, will help testing this when it becomes available.

**Comment by rh-id** [comment]
Hi, is there any progress for this? Would like to help as this is going to be big i think.

I can read python and java, as for code structure and test class files could you help where should I look?

**Comment by fintanmm** [comment]
Hey @rh-id, I have this partially working, but it needs to pass all the tests. I get the following output when using the calculator as a function. 
```json
ChatResponse(model=phi, createdAt=2024-03-05T15:57:06.007907723Z, message=Message(role=null, content={
  "tool": {
    "name": "Calculator",
    "input_type": "number",
    "output_type": "number"
  },
  "tool_input": [485906798473894056],
  "tool_output": 6.9283912098
}
, images=null), done=true, promptEvalCount=153, evalCount=82)
```
I'll make my fork available later tonight, and you'll be able to have a look. My fork does need a bit of cleaning before it would be ready. It would be nice to use the OpenAI API, but the compatibility for using functions is still a work in progress.

**Comment by rh-id** [comment]
Hi @fintanmm @langchain4j ,

I'm running `OllamaChatModelIT` without any modification and it seemed there had existing issues:

![Screenshot from 2024-03-06 12-46-29](https://github.com/langchain4j/langchain4j/assets/58564005/8a76a266-af2d-450b-839f-4bbf61559714)


`should_respect_numPredict()` is this test supposed to return blank " " text?
```
Response { content = AiMessage { text = " Berlin" toolExecutionRequests = null }, tokenUsage = TokenUsage { inputTokenCount = null, outputTokenCount = 1, totalTokenCount = 1 }, finishReason = null }

java.lang.AssertionError: 
Expecting actual:
  " Berlin"
not to contain:
  "Berlin"

	at dev.langchain4j.model.ollama.OllamaChatModelIT.should_respect_numPredict(OllamaChatModelIT.java:69)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
```

`should_respect_system_message()` it seemed Ollama return blank message, `phi` model doesn't support German, is this test supposed to work on `phi` model in the first place?
```
java.lang.IllegalArgumentException: text cannot be null or blank

	at dev.langchain4j.internal.Exceptions.illegalArgument(Exceptions.java:19)
	at dev.langchain4j.internal.ValidationUtils.ensureNotBlank(ValidationUtils.java:98)
	at dev.langchain4j.data.message.AiMessage.<init>(AiMessage.java:30)
	at dev.langchain4j.data.message.AiMessage.from(AiMessage.java:100)
	at dev.langchain4j.model.ollama.OllamaChatModel.generate(OllamaChatModel.java:81)
	at dev.langchain4j.model.chat.ChatLanguageModel.generate(ChatLanguageModel.java:39)
	at dev.langchain4j.model.ollama.OllamaChatModelIT.should_respect_system_message(OllamaChatModelIT.java:81)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
```

Update on this, both tests seemed to pass when model is switched to "mistral"

**Comment by rh-id** [comment]
I had tried using SystemMessage and it seemed to work on `mistral` model but not on `phi` model.

**Comment by rh-id** [comment]
It seemed an endpoint will be added to support tools:

https://github.com/ollama/ollama/issues/2417

**Comment by langchain4j** [comment]
@rh-id `OllamaChatModelIT` is just a bad test, I will improve it

**Comment by meletis** [comment]
Is this PR related to this issue?

> https://github.com/ollama/ollama/pull/5284

**Comment by langchain4j** [comment]
Seems so
