### ISSUE TITLE
[FEATURE] Use Azure OpenAI SDK to connect to Azure OpenAI

### ISSUE THREAD

**Issue by jdubois** [langchain4j/langchain4j#325]
Azure OpenAI support was added in https://github.com/langchain4j/langchain4j/pull/107 by @kuraleta and uses the https://github.com/ai-for-java/ai4j API to connect.

There is an official Azure OpenAI SDK at https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/openai/azure-ai-openai which is official and should be better maintained, so my proposal is to migrate Azure OpenAI support to this SDK.

Then, I believe this was used because you have both an Azure OpenAI and an OpenAI support, and they are both using the same https://github.com/ai-for-java/ai4j API. I'm not sure why you separated them, so once this first migration is done, I'd love to have a look at unifying your Azure OpenAI and your OpenAI support.

**Comment by langchain4j** [comment]
Hi @jdubois, seems like a good idea to use official Azure SDK for Azure OpenAI support (granted it is updated shortly after new features are evailable in the API).
At the moment we do not have access to the Azure OpenAI API, so it is hard to change and test it.
https://aka.ms/oai/access is asking for a company data which we don't have. Is there any way for us to get a key? Thanks!

**Comment by jdubois** [comment]
Oh I have access (I work there...) so I can at least code and test.
As there's an agreement between LangChain and Microsoft, can't you use this? Is LangChain4J totally separated from LangChain?

**Comment by langchain4j** [comment]
Yes, LangChain4J is not related to LangChain. It would be great to have access, could you please help with that?

**Comment by jdubois** [comment]
- You should check with the LangChain project, as you're using their name/branding that's going to cause you some trouble in the future. And they should have everything to test on Azure, so that would be the easiest solution.
- As a company, you can opt in for Microsoft for Startups at https://www.microsoft.com/startups - that would give you credits and access to OpenAI. That would the second best solution, and I might be able as I work with them regularly.
- As an individual you can try https://azure.microsoft.com/en-us/products/ai-services/openai-service but it's limited currently as there's a huge demand, and you'll need to pay for it.
- Last but not least, I can test by myself, but it will be complicated to automate as obviously I can't share my Azure credentials.

**Comment by langchain4j** [comment]
@jdubois thank you for detailed suggestions! I will check what would be the best option.

**Comment by jdubois** [comment]
I created #328 as a draft PR, as I migrated the first class `AzureOpenAiChatModel` to the Azure OpenAI SDK.

- The migration will take some time, but there shouldn't be any blocker
- I will add unit tests and integration tests before putting this PR as ready
