### ISSUE TITLE
Langchain4j to connect to a custom API 

### ISSUE THREAD

**Issue by escuelatech** [langchain4j/langchain4j#330]
We have a corporate network for open AI . Currently all langchain API requests are forwarded open AI . How can I connect to custom endpoint . For eg : http://escuela.openai.com/.

Can add this through a system property ?

**Comment by langchain4j** [comment]
Hi @escuelatech, you can set a `baseUrl` property when creating `OpenAi*Model`:
```
OpenAiChatModel.builder()
                .apiKey(...)
                .baseUrl("http://escuela.openai.com/v1/")
                .build();
```

The default `baseUrl` is `https://api.openai.com/v1/`.
Depending on the model type, a path suffix will be appended to it. For `OpenAiChatModel`, it will become `baseUrl` + "chat/completions", for `OpenAiEmbeddingModel`: `baseUrl` + "embeddings", etc.

Hope this helps. Feel free to reopen if needed.
