### ISSUE TITLE
How chat completion to openai with parameters

### ISSUE THREAD

**Issue by leecho** [langchain4j/langchain4j#34]
The method OpenAiStreamingChatModel.sendUserMessage only include temperature. how to support  other parameters, eg : presencePenalty, maxTokens。

**Comment by langchain4j** [comment]
@leecho good point. Please list all parameters you need, I will add them asap. Thanks.

**Comment by leecho** [comment]
thanks，I'm already see  parameters are be added in code。pls deploy to the maven.

**Comment by langchain4j** [comment]
@leecho just released 0.16.0, please check
