### ISSUE TITLE
Support multiple embedding stores

### ISSUE THREAD

**Issue by breezexiao** [langchain4j/langchain4j#35]
Can AiServices supported multiple Retriever? maybe from multiple different Embedding Store

**Comment by langchain4j** [comment]
@breezexiao yes, but I need to understand use case better.
Let's say you have 2 embedding stores.
Do you want to have 2 independent retrievers and retrieve N most relevant segments from each store, then combine them (2xN) and send to LLM?
Or you want to combine two embedding stores under one retriever and retrieve 1xN most relevant segments (does not matter from which store they are retrieved, as long as they are most relevant)?
Thanks

**Comment by langchain4j** [comment]
@breezexiao just noticed that the title says "Support multiple **documents** chat".
Just in case and to avoid confusion, you already can load and store **multiple** documents in a single embedding store.

**Comment by breezexiao** [comment]
> 



> @breezexiao yes, but I need to understand use case better. Let's say you have 2 embedding stores. Do you want to have 2 independent retrievers and retrieve N most relevant segments from each store, then combine them (2xN) and send to LLM? Or you want to combine two embedding stores under one retriever and retrieve 1xN most relevant segments (does not matter from which store they are retrieved, as long as they are most relevant)? Thanks
@langchain4j yes, that's what it means, Thanks

**Comment by breezexiao** [comment]
> @breezexiao yes, but I need to understand use case better. Let's say you have 2 embedding stores. Do you want to have 2 independent retrievers and retrieve N most relevant segments from each store, then combine them (2xN) and send to LLM? Or you want to combine two embedding stores under one retriever and retrieve 1xN most relevant segments (does not matter from which store they are retrieved, as long as they are most relevant)? Thanks
@breezexiao Yes, that's what it means, I hope it's the second，Thanks

**Comment by breezexiao** [comment]
> @breezexiao yes, but I need to understand use case better. Let's say you have 2 embedding stores. Do you want to have 2 independent retrievers and retrieve N most relevant segments from each store, then combine them (2xN) and send to LLM? Or you want to combine two embedding stores under one retriever and retrieve 1xN most relevant segments (does not matter from which store they are retrieved, as long as they are most relevant)? Thanks

@langchain4j Yes, that's what it means, I hope it's the second one

**Comment by langchain4j** [comment]
@breezexiao technically this is possible.
I am just trying to understand how this should work.
It is hard to desing a good thing without understanding the use case first.

For this setup (2 embedding stores) to work well:
- they should contain embeddings in the same format (e.g. same embedding model was used to embed segments)
- they should have similar knowledgebases (by topic)
In this case I am just wandering, if these 2 embeddings stores are so similar, why are they separated?

Could you please describe your use case in details? I am very interested to hear what you are building.
Thank you!

**Comment by breezexiao** [comment]
> @breezexiao technically this is possible. I am just trying to understand how this should work. It is hard to desing a good thing without understanding the use case first.
> 
> For this setup (2 embedding stores) to work well:
> 
> * they should contain embeddings in the same format (e.g. same embedding model was used to embed segments)
> * they should have similar knowledgebases (by topic)
>   In this case I am just wandering, if these 2 embeddings stores are so similar, why are they separated?
> 
> Could you please describe your use case in details? I am very interested to hear what you are building. Thank you!

@langchain4j Our current scenario is related to the knowledge base. For example, each user can have multiple document libraries. We hope that users can search the contents of multiple document libraries at the same time. The current PineconeEmbeddingStore(String apiKey, String environment, String projectName, String index , String nameSpace) can only specify one namespace, and Pinecone does not seem to support multiple namespaces. Thanks

**Comment by langchain4j** [comment]
@breezexiao if all the libraries of all the users combined are not huge (e.g. < 100K segments), it might make sense to keep all segments in the same embedding store and add a custom metadata for each segment (e.g. userName, libraryName, etc). This way you could add a filter during search/retrieval (search only by documents related to the specific user and/or specific library). I guess this will be easier than maintaining a separate embedding store for each user. What do you think? Metadata filtering is not yet implemented in LangChain4j, but this is something pretty easy/fast to do.

**Comment by langchain4j** [comment]
@breezexiao BTW since you have opened 2 issues and I would love to work on them during this week, do you have a preference for priorities? Streaming support first or this one (retrieval)?

**Comment by breezexiao** [comment]
> @breezexiao BTW since you have opened 2 issues and I would love to work on them during this week, do you have a preference for priorities? Streaming support first or this one (retrieval)?

@langchain4j Priorities are about the same for me, just arrange at your own pace，Thanks

**Comment by langchain4j** [comment]
@breezexiao Does this sound good to you?

> @breezexiao if all the libraries of all the users combined are not huge (e.g. < 100K segments), it might make sense to keep all segments in the same embedding store and add a custom metadata for each segment (e.g. userName, libraryName, etc). This way you could add a filter during search/retrieval (search only by documents related to the specific user and/or specific library). I guess this will be easier than maintaining a separate embedding store for each user. What do you think? Metadata filtering is not yet implemented in LangChain4j, but this is something pretty easy/fast to do.

**Comment by langchain4j** [comment]
Hi @breezexiao, this is now supported: https://github.com/langchain4j/langchain4j/pull/538
Please check `DefaultRetrievalAugmentor` and `QueryRouter` and in version 0.26.1.
I am closing this issue, but feel free to reopen if needed.
Cheers!
