### ISSUE TITLE
[BUG] Unable to use custom ONNX model with Chinese

### ISSUE THREAD

**Issue by yushengliao** [langchain4j/langchain4j#352]
I Downloaded the model from https://huggingface.co/xenova/bge-large-zh/blob/main/onnx/model.onnx 

        EmbeddingModel embeddingModel = new OnnxEmbeddingModel("C:\\Users\\Administrator\\Downloads\\model.onnx");
        EmbeddingStore<TextSegment> embeddingStore = new InMemoryEmbeddingStore<>();
        if (CollectionUtil.isNotEmpty(segments)) {
            List<Embedding> embeddings = embeddingModel.embedAll(segments).content();
            embeddingStore.addAll(embeddings, segments);
        }
        

It seems that there is an error when embedding large sections of Chinese. Some simple Chinese texts are normal, but I haven't found any patterns
Exception Log：

ai.onnxruntime.OrtException: Error code - ORT_INVALID_ARGUMENT - message: Non-zero status code returned while running Gather node. Name:'/embeddings/word_embeddings/Gather' Status Message: indices element out of data bounds, idx=30375 must be within the inclusive range [-21128,21127]

- LangChain4j version:  0.24.0
- Java version:  17
- Spring Boot version: 3.1.3

Additionally, I would like OnnxEmbeddingModel to add a method to pass in its own vocabularyFile and PoolingMode

**Comment by langchain4j** [comment]
Hi @yushengliao how long is the text you are trying to embed? According to [this](https://huggingface.co/BAAI/bge-large-zh/blob/main/sentence_bert_config.json) bge-large-zh can embed maximum 512 tokens. IT seems that you are providing a very long text, which will give you a very poor performance. If you are giving a longer text than 512 tokens, `OnnxEmbeddingModel` is doing some trick under the hood, but this is not advisable. This behavior will be reworked soon.

**Comment by langchain4j** [comment]
@yushengliao can you please provide the document you are having issues with? So that I can reproduce this bug. Thanks

**Comment by langchain4j** [comment]
Implemented in https://github.com/langchain4j/langchain4j-embeddings/pull/13
