### ISSUE TITLE
How to prevent gpt from compiling a content and giving it to my tool as a parameter?

### ISSUE THREAD

**Issue by CatMaiV** [langchain4j/langchain4j#353]
For example, I want GPT to get the username before logging some information, and throw an exception if there is no username. Then GPT will make up a name for me, which is not what I want.

Sometimes GPT will even give me the name I gave GPT in the system prompt as a username.

The following is my pseudo code：

```

@Tool(name = "recordUsername")
public void setUserName(String userName){
    this.toolUser.setUserName(userName);
    //... recorded to db
}

@Tool(name = "getUserName")
public String getUserName(){
   if (StringUtils.isEmpty(toolUser.getUserName())){
       throw new InformationMissingException("Please ask user for their valid email address.");
    }
   return this.toolUser.getUserName();
}

@Tool(name = "createTask")
public String createTask(String taskType,String information) {
    //....some operations
   Tasks taks = new Tasks();
   if (StringUtils.isNotEmpty(this.toolUser.getUserName())){
        tasks.setUserName(this.toolUser.getUserName());
    }else{
        throw new InformationMissingException("Please ask for user's name.");
    }
    SpringUtils.getBean(ITasksService.class).insertTasks(tasks);

    //.....some operations
    return ...;
}
```

ps.  toolUser is used to save the user information of this session

The current effect is that when the user mentions their nickname, recordUsername will be called, or when gpt needs to know the user's name, getUserName will be called. But if the username has not been recorded, but the task is recorded directly, then GPT will compile a username for me, which is not true.

Any suggestions on this?    T.T

Or, in the tool, what kind of exception will better let GPT understand what happened?

**Comment by langchain4j** [comment]
Hi @CatMaiV which model are you using? gpt-3.5 hallucinates a lot, maybe try gpt-4? Also, is there a way to check if provided username valid? like lookup in the DB?

**Comment by CatMaiV** [comment]
> Hi @CatMaiV which model are you using? gpt-3.5 hallucinates a lot, maybe try gpt-4? Also, is there a way to check if provided username valid? like lookup in the DB?

OK, thanks for your reply. I will try GPT4, my expectation is to collect some user provided information through GPT username is just an example and cannot be verified from the DB

**Comment by CatMaiV** [comment]
I tried GPT4 and it made a noticeable difference. Now it meets my expectations, thank you for your suggestion. @langchain4j

**Comment by langchain4j** [comment]
@CatMaiV beware that gpt-4 costs 10-30x of gpt3.5, so you might also want to check other options. One of the option that comes to my mind is taking all user messages in a conversation, concatenating them and sending them to the model (in a fresh chat session, so that the model is not biased by it's previous replies) and asking the model if user provided his name in one of those messages (yes/no answer).
