### ISSUE TITLE
[BUG] when tools function parameter use enum, call tool_function will throw exception.

### ISSUE THREAD

**Issue by showeriszero** [langchain4j/langchain4j#365]
**Describe the bug**
please check follow tools code:

public class DemoTools {
     
    @Tool(value = "use web search to search something", name = "Web search")
    public String webSearch(String search_query, @P("口味") TASTE_ENUM taste) {
        log.debug("search query: {}", search_query);
        log.debug("taste : {}", taste);

        return  search_query + taste;
    }
}

public enum TASTE_ENUM {
    @SerializedName("清淡")
    weak("清淡"),
    @SerializedName("辣")
    spicy("辣"),
    @SerializedName("不辣")
    not_spicy("不辣");
    private final String stringValue;

    TASTE_ENUM(String stringValue) {
        this.stringValue = stringValue;
    }

    @Override
    public String toString() {
        return stringValue;
    }

    public static TASTE_ENUM from(String stringValue) {
        for (TASTE_ENUM taste : TASTE_ENUM.values()) {
            if (taste.stringValue.equals(stringValue)) {
                return taste;
            }
        }
        throw new IllegalArgumentException("Unknown taste: '" + stringValue + "'");
    }
}

first llm return about function_call
"functions": [
    {
      "name": "Web search",
      "description": "use web search to search something",
      "parameters": {
        "type": "object",
        "properties": {
          "taste": {
            "description": "口味",
            "type": "string",
            "enum": [
              "清淡",
              "辣",
              "不辣"
            ]
          },
          "search_query": {
            "type": "string"
          }
        }

but, when run follow code will throw exception
DefaultToolExecutor.execute((Object[] arguments) throws IllegalAccessException, InvocationTargetException {
        Object result = this.method.invoke(this.object, arguments);
        return this.method.getReturnType() == Void.TYPE ? "Success" : Json.toJson(result);
}

**Log and Stack trace**
2023-12-19 11:15:05.592 ERROR 5681 --- [nio-8080-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.IllegalArgumentException: argument type mismatch] with root cause

java.lang.IllegalArgumentException: argument type mismatch
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_392]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_392]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_392]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_392]

- LangChain4j version: e.g. 0.24.0
- Java version: 1.8
- Spring Boot version (if applicable): 2.7.14

please help me, how to do, thx.

**Comment by langchain4j** [comment]
Hi @showeriszero which model are you using? I tried your code with OpenAI/gpt-3.5-turbo and getting this error:
```
  "error": {
    "message": "'Web search' does not match '^[a-zA-Z0-9_-]{1,64}$' - 'functions.0.name'",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
```

**Comment by showeriszero** [comment]
> Hi @showeriszero which model are you using? I tried your code with OpenAI/gpt-3.5-turbo and getting this error:
> 
> ```
>   "error": {
>     "message": "'Web search' does not match '^[a-zA-Z0-9_-]{1,64}$' - 'functions.0.name'",
>     "type": "invalid_request_error",
>     "param": null,
>     "code": null
>   }
> ```

sorry about that, model is our company own, It has not been released to the public. please make a tools function by enum parameters with OpenAI ? thx.

**Comment by langchain4j** [comment]
@showeriszero this is a bug on our side, thank you for reporting!

**Comment by showeriszero** [comment]
> @showeriszero this is a bug on our side, thank you for reporting!

Is there a temporary solution? please...

**Comment by langchain4j** [comment]
@showeriszero you can try using `String` instead of `TASTE_ENUM` as an argument of your `@Tool` and parse the string into enum yourself. This worked well with OpenAI/gpt-3.5-turbo:
```
        @Tool("use web search to search something")
        public String webSearch(String searchQuery, @P("one of: [清淡, 辣, 不辣]") String taste) {
            TASTE_ENUM tasteEnum = TASTE_ENUM.from(taste);
            System.out.println(tasteEnum);
            return searchQuery + taste;
        }
```
