### ISSUE TITLE
chroma support [FEATURE] 

### ISSUE THREAD

**Issue by ab0uts** [langchain4j/langchain4j#39]
do we have a plan to support chroma ? thanks

**Comment by langchain4j** [comment]
Hi @ab0uts, yes, it's in the plan. But we have too few contributors and too big backlog. It would help us a lot if you could help with that. Thank you!

**Comment by Heezer** [comment]
there is no Java client for chroma for the moment unfortunately 😥 so yes, committers for chroma java client & langchain4j are welcome 😄

**Comment by langchain4j** [comment]
We are already working on Chroma support, should be available soon.

**Comment by langchain4j** [comment]
@ab0uts Chroma is now supported in 0.21.0. See example [here](https://github.com/langchain4j/langchain4j-examples/blob/main/other-examples/src/main/java/embedding/store/ChromaEmbeddingStoreExample.java).
