### ISSUE TITLE
[FEATURE] Add support for image input

### ISSUE THREAD

**Issue by oujingzhou** [langchain4j/langchain4j#400]
It would be amazing if langchain4j adds supports for image inputs. Images are made available to the model in two main ways: by passing a **link to the image** or by passing the **base64 encoded image** directly in the request. Images can be passed in the user, system and assistant messages. And also supports **multiple image inputs**.

Check out the GPT-4 with Vision API: https://platform.openai.com/docs/guides/vision

Also other multimodal inputs such as speech, video.

**Comment by langchain4j** [comment]
@King-Chau we already work on this

**Comment by bidek** [comment]
The current codebase supporting ollama makes it easy to add this functionality. Unfortunately the changes spoil the current abstraction.

ollama now supports images at the API request level `dev.langchain4j.model.ollama.CompletionRequest` and at the message
level `dev.langchain4j.model.ollama.Message`

https://github.com/jmorganca/ollama/blob/main/docs/api.md#generate-a-completion

https://github.com/jmorganca/ollama/blob/main/docs/api.md#generate-a-chat-completion

Below are the changes in the `CompletionRequest` and `OllamaLanguageModel` classes:

New field `images` in `CompletionRequest`, list of base64 encoded images

```
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
class CompletionRequest {

    private String model;
    private String system;
    private String prompt;
    private Options options;
    private String format;
    private Boolean stream;
    private List<String> images;
}
```

New method in `OllamaLanguageModel`

```
public class OllamaLanguageModel implements LanguageModel {
 
    public Response<String> generate(String prompt, List<String> images) {
        CompletionRequest request = CompletionRequest.builder()
                .model(modelName)
                .prompt(prompt)
                .options(options)
                .format(format)
                .images(images)
                .stream(false)
                .build();

        CompletionResponse response = withRetry(() -> client.completion(request), maxRetries);

        return Response.from(
                response.getResponse(),
                new TokenUsage(response.getPromptEvalCount(), response.getEvalCount())
        );
    }
    
    
}
```

And usage with output:

```
class MainImages {
    public static void main(String[] args) throws IOException {

        var model = OllamaLanguageModel.builder()
                .baseUrl("http://localhost:11434")
                .modelName("bakllava")
                .temperature(1.0)
                .build();

        var image = Files.readString(Path.of("./beach-jpeg.encoded.base64"));

        Response<String> generate = model.generate("Describe picture", List.of(image));
        System.out.println(generate.content());
        
        /* OUTPUT:
        
         The image depicts a serene and beautiful beach scene. A lone tree branch protrudes from the sand, creating a unique focal point in the landscape. Behind it, an island can be seen in the distance. 
In addition to the picturesque view, several clouds are scattered across the sky, adding to the tranquil ambiance. Moreover, there is a person visible near the center of the image, possibly enjoying the beach environment.

         */
        
    }

}
```

**Comment by bidek** [comment]
I don't know if I should open PR for open PR, but here it is.

https://github.com/langchain4j/langchain4j/pull/430

**Comment by langchain4j** [comment]
Done in https://github.com/langchain4j/langchain4j/pull/428 and https://github.com/langchain4j/langchain4j/pull/462
