### ISSUE TITLE
[FEATURE] Results retrieved should be accompanied by a citation of the document.

### ISSUE THREAD

**Issue by nn200433** [langchain4j/langchain4j#404]
Results retrieved should be accompanied by a citation of the document.

conversation content:

```text
[user]: Robbery What is the sentence?
[chat]: bala bala bala .........。 —— [quote document 《criminal law》]
```

Solutions I can think of at the moment:
```java
public class SimpleTextSegmentTransformerServiceImpl implements TextSegmentTransformer {

    @Override
    public TextSegment transform(TextSegment segment) {
        final String text = StrUtil.format("以下片段摘抄至《{}》。\n{}", segment.metadata(Document.FILE_NAME), segment.text());
        return TextSegment.from(text, segment.metadata());
    }

}
```

**Comment by langchain4j** [comment]
Hi @nn200433, this is now supported in https://github.com/langchain4j/langchain4j/pull/538.
You can include metadata fields along with the segment contents using `DefaultContentInjector`.
Here is an [example](https://github.com/langchain4j/langchain4j-examples/blob/main/rag-examples/src/main/java/_05_Advanced_RAG_with_Metadata.java).
I guess you do not need `TextSegmentTransformer` now.
Feel free to reopen if anything is still missing.

**Comment by nn200433** [comment]
> 你好@nn200433，现在#538支持这一点。 您可以使用元数据字段和片段内容一起包含`DefaultContentInjector`。 这是一个[示例](https://github.com/langchain4j/langchain4j-examples/blob/main/rag-examples/src/main/java/_05_Advanced_RAG_with_Metadata.java?rgh-link-date=2024-01-31T08%3A44%3A16Z)。 我想您现在不需要`TextSegmentTransformer`。 如果仍然缺少任何内容，请随时重新打开。

thank you for your reply.
