### ISSUE TITLE
Add support for non-cloud embedding store (like Weaviate and Chrome) 

### ISSUE THREAD

**Issue by dudu-upstream** [langchain4j/langchain4j#42]
**Describe the solution you'd like**
Can you please support more vectorstores besides Pincone? I want to use the Self-querying feature with some local stores.

**Comment by langchain4j** [comment]
Hi @dudu-upstream we are working now on adding Milvus and plan to add support for weaviate, chroma and vespa in the near future. Will keep you updated.

**Comment by dudu-upstream** [comment]
is Milvus support self-querying? from what I can see in LangChain docs, Milvus not supporting that feature (generate queries over the metadata from prompt)
https://js.langchain.com/docs/modules/data_connection/retrievers/how_to/self_query/weaviate-self-query

**Comment by langchain4j** [comment]
@dudu-upstream AFAIK SelfQueryRetriever is EmbeddingStore-agnostic. Milvus has a support of metadata filtering, so there should be no problem to implement this. BTW, we are now working on Weaviate integration as well. Will keep you updated.

**Comment by Heezer** [comment]
Weaviate support will be merged soon: #57

**Comment by langchain4j** [comment]
@dudu-upstream Weaviate is now supported in 0.19.0 thanks to @Heezer!
Please see example [here](https://github.com/langchain4j/langchain4j-examples/blob/main/other-examples/src/main/java/embedding/store/WeaviateEmbeddingStoreExample.java).
