### ISSUE TITLE
[FEATURE] official website for documents and tutorials

### ISSUE THREAD

**Issue by Martin7-1** [langchain4j/langchain4j#420]
Hi! I would like to ask when we can have an official website to put all the documents and tutorials, so that users can quickly get started and find relevant informations? It seems that new users will only be able to read a few examples through `langchain4j-examples`. An official website will help new users to start quickly.

I think we could just use [github pages](https://pages.github.com/) to build the official website.

**Comment by LizeRaes** [comment]
Hi Martin, great idea, I'm on board to help provide content, examples and tutorials

**Comment by jmgang** [comment]
Hello Martin, I believe there's already an existing issue [#152](https://github.com/langchain4j/langchain4j/issues/152) for a starting documentation site, though it hasn't been updated yet since August.

**Comment by LizeRaes** [comment]
@jmgang thanks for refering! @Martin7-1 that page already looks really good, shall we extend and complete it in that ticket?

**Comment by Martin7-1** [comment]
> @jmgang thanks for refering! @Martin7-1 that page already looks really good, shall we extend and complete it in that ticket?

I'm sorry I didn't notice the issue. @LizeRaes That page looks very nice and I think it's great to extend and complete on it.
