### ISSUE TITLE
[BUG] AiService.class not found

### ISSUE THREAD

**Issue by leon-77** [langchain4j/langchain4j#424]
i import package through maven,but dictionary dev.langchain4j.service is missing and cant't use AiService to create an agent

`<dependency>
            <groupId>dev.langchain4j</groupId>
            <artifactId>langchain4j-open-ai</artifactId>
            <version>0.25.0</version>
        </dependency>`
![image](https://github.com/langchain4j/langchain4j/assets/61659102/9167add3-55ea-45e1-b376-0293d3ab8070)

**Comment by langchain4j** [comment]
Hi @leon-77 `AiServices` is inside `langchain4j` dependency, not `langchain4j-core` or `langchain4j-open-ai`
