### ISSUE TITLE
[FEATURE] When can Langchain4j support vearch？

### ISSUE THREAD

**Issue by imoxu** [langchain4j/langchain4j#425]
When can Langchain4j support vearch？What are the plans, or what other ways can I use vearch

**Comment by imoxu** [comment]
1

**Comment by imoxu** [comment]
1

**Comment by Martin7-1** [comment]
Hi @imoxu , I'm tring my best to contribute, maybe in 1-2 weeks I will PR for it.

**Comment by Martin7-1** [comment]
Hi @imoxu , I'm tring my best to contribute, maybe in 1-2 weeks I will PR for it.

**Comment by langchain4j** [comment]
Was added in 0.27.0
