### ISSUE TITLE
[BUG] Unable to set Hugging Face client parameter returnFullText to null.

### ISSUE THREAD

**Issue by cwensel** [langchain4j/langchain4j#427]
**Describe the bug**
When using the Hugging Face model `facebook/bart-large-cnn`, the following error is returned.

```
java.lang.RuntimeException: status code: 400; body: {"error":"The following `model_kwargs` are not used by the model: ['return_full_text'] (note: typos in the generate arguments will also show up in this list)","warnings":["There was an inference error: The following `model_kwargs` are not used by the model: ['return_full_text'] (note: typos in the generate arguments will also show up in this list)"]}
```

This happens because the value of `false` is passed in the api call, even if the builder value is set to `null`.

Gson will not serialize null fields, allowing the value to be null would disable the parameter preventing the error.

**Log and Stack trace**

```
 at dev.langchain4j.model.huggingface.DefaultHuggingFaceClient.toException(DefaultHuggingFaceClient.java:100)
        at dev.langchain4j.model.huggingface.DefaultHuggingFaceClient.generate(DefaultHuggingFaceClient.java:64)
        at dev.langchain4j.model.huggingface.DefaultHuggingFaceClient.chat(DefaultHuggingFaceClient.java:52)
        at dev.langchain4j.model.huggingface.HuggingFaceChatModel.generate(HuggingFaceChatModel.java:86)
        at dev.langchain4j.model.chat.ChatLanguageModel.generate(ChatLanguageModel.java:39)
        at dev.langchain4j.model.chat.ChatLanguageModel.generate(ChatLanguageModel.java:27)
```

**To Reproduce**

Note that the `"parameters"` object is added in the following example.

```
curl https://api-inference.huggingface.co/models/facebook/bart-large-cnn \
	-X POST \
	-d '{"inputs": "The tower is 324 metres (1,063 ft) tall, about the same height as an 81-storey building, and the tallest structure in Paris. Its base is square, measuring 125 metres (410 ft) on each side. During its construction, the Eiffel Tower surpassed the Washington Monument to become the tallest man-made structure in the world, a title it held for 41 years until the Chrysler Building in New York City was finished in 1930. It was the first structure to reach a height of 300 metres. Due to the addition of a broadcasting aerial at the top of the tower in 1957, it is now taller than the Chrysler Building by 5.2 metres (17 ft). Excluding transmitters, the Eiffel Tower is the second tallest free-standing structure in France after the Millau Viaduct.", "parameters": { "returnFullText": true } }' \
	-H 'Content-Type: application/json' \
	-H "Authorization: Bearer {token}"
```

**Expected behavior**
It looks like the gson serializer will ignore null java properties/fields. but the `HuggingFaceChatModel.builder` tests if the parameter value for `#returnFullText` is null, and if so, keeps the value `false`.

```
HuggingFaceChatModel.builder().returnFullText(null).build(); // keeps false value
```

Here is where the code checks for null: https://github.com/langchain4j/langchain4j/blob/f98c04028a37ccd695978fedb3940c7fd3fe2b4d/langchain4j-hugging-face/src/main/java/dev/langchain4j/model/huggingface/HuggingFaceChatModel.java#L134

**Please complete the following information:**
- LangChain4j version: e.g. 0.25.0
- Java version: e.g. 11

**Additional context**

**Comment by langchain4j** [comment]
Hi @cwensel, `facebook/bart-large-cnn` is `Summarization` model, not `Text Generation`:
![image](https://github.com/langchain4j/langchain4j/assets/132277850/b3ef8e0b-11de-4cbf-a655-134cc0bf2a48)
As per https://huggingface.co/docs/api-inference/detailed_parameters, summarization uses different API (different parameters are expected on inputs and outputs). "Fixing" `return_full_text` will not really help, as the result is returned in a different field (`summary_text` instead of `generated_text`).

I would like to avoid mixing different APIs in the same class. In theory we can add another class (e.g. `HuggingFaceSummarizationModel`) that will implement summarization API. Please let me know if you really need this.

**Comment by cwensel** [comment]
Hey, thanks for the quick reply and explanation. Makes sense.
