### ISSUE TITLE
Add support for connection to Azure OpenAI

### ISSUE THREAD

**Issue by dudu-upstream** [langchain4j/langchain4j#43]
I would like to connect my LangChain app to Azure OpenAI, is it possible?

**Comment by langchain4j** [comment]
@dudu-upstream yes, should be easy to add. Will keep you updated.

**Comment by dudu-upstream** [comment]
Thanks! I will try to do it myself if it shouldn't be that hard

**Comment by stormrise** [comment]
```
<dependency>
    <groupId>com.azure</groupId>
    <artifactId>azure-ai-openai</artifactId>
    <version>1.0.0-beta.2</version>
</dependency>
```

I have seen ms release azure openai java client beta, maybe we can try.

**Comment by langchain4j** [comment]
@stormrise AFAIK Azure has the same API as OpenAI, so it would be nice to re-use [existing OpenAI client](https://github.com/ai-for-java/openai4j) that we use instead of bringing in a new dependency.

**Comment by langchain4j** [comment]
@dudu-upstream did you manage to add it yourself? Do you still need this? Thanks

**Comment by kaltindas** [comment]
> @dudu-upstream did you manage to add it yourself? Do you still need this? Thanks

we need it, could you pls add it ?

**Comment by langchain4j** [comment]
We're adding it. Should be available soon.

**Comment by langchain4j** [comment]
@dudu-upstream @stormrise @kaltindas we've added integration with Azure OpenAI in 0.21.0 (see `AzureOpenAi*Model` classes). Unfortunately we don't have access to it, so we've developed it blindly by docs without ability to test. Please check and provide your feedback, thank you!

**Comment by kaltindas** [comment]
> @dudu-upstream @stormrise @kaltindas we've added integration with Azure OpenAI in 0.21.0 (see `AzureOpenAi*Model` classes). Unfortunately we don't have access to it, so we've developed it blindly by docs without ability to test. Please check and provide your feedback, thank you!

Unfortunately there is an Issue but it should be easy to fix. 

It should be also possible to pass modelId/deploymentId ... https://learn.microsoft.com/en-us/azure/ai-services/openai/reference

Otherwise we get "WARN: Exception was thrown on attempt 1 of 3: dev.ai4j.openai4j.OpenAiHttpException: {"error":{"code":"404","message": "Resource not found"}}" Failure ...  

Because in Azure you can have multiple deployments ...

**Comment by kaltindas** [comment]
Hi, unfortunately there is an Issue ...


`EmbeddingModel embeddingModel = AzureOpenAiEmbeddingModel.builder()
                    .apiKey("azure_key")
                    .baseUrl("https://my-resource.openai.azure.com/")
                    .build();`

Here it should be possible to pass the model-id/deployment-id ... Because in Azure you can have multiple deployments/models in same resource ...

Otherwise we get `{"error":{"code":"404","message": "Resource not found"}}` wenn we call ' ingestor.ingest(document);'

`            EmbeddingStoreIngestor ingestor = EmbeddingStoreIngestor.builder()
                    .splitter(new ParagraphSplitter())
                    .embeddingModel(embeddingModel)
                    .embeddingStore(embeddingStore)
                    .build();
            ingestor.ingest(document);`   
            
          
you can check the docu here: https://learn.microsoft.com/en-us/azure/ai-services/openai/reference#embeddings

**Comment by langchain4j** [comment]
Hi @kaltindas did you try to define baseUrl as "https://{your-resource-name}.openai.azure.com/openai/deployments/{deployment-id}"? Also, it seems you need to specify apiVersion. If it does not work, please provide logs. Thanks!

**Comment by kaltindas** [comment]
You're right, after specifying the api-version and using the modelName in the basePath, the code worked. The following code is functioning:

`
EmbeddingModel embeddingModel = AzureOpenAiEmbeddingModel.builder()
    .apiKey("key")
    .apiVersion("2023-05-15")
    .baseUrl("https://my-resource.openai.azure.com/openai/deployments/text-embedding-ada-002")
    .build();
`

Additionally, if the number of elements inside the segments array exceeds 16 when using the embeddingModel.embedAll() method, it throws an "InvalidRequestError: Too many inputs. The max number of inputs is 16." error. I've managed to handle this by  using a for loop with 16 iterations steps :) . You can also use multithreading of course...

 Add this information to the documentation if you want.

https://learn.microsoft.com/en-us/azure/ai-services/openai/faq#i-am-trying-to-use-embeddings-and-received-the-error--invalidrequesterror--too-many-inputs--the-max-number-of-inputs-is-1---how-do-i-fix-this-

**Comment by langchain4j** [comment]
@kaltindas thanks, goog to know. I will add this iteration logic inside the lib so that users don't need to do it manually.

**Comment by langchain4j** [comment]
@kaltindas may I ask you to test other Azure classes? Much appreciated!

```
AzureOpenAiChatModel model = AzureOpenAiChatModel.builder()
                .apiKey("key")
                .apiVersion("2023-05-15")
                .baseUrl("https://my-resource.openai.azure.com/openai/deployments/gpt-3.5-turbo")
                .build();
        AiMessage answer = model.sendUserMessage("hello");
        System.out.println(answer);
```

```
AzureOpenAiLanguageModel model = AzureOpenAiLanguageModel.builder()
                .apiKey("key")
                .apiVersion("2023-05-15")
                .baseUrl("https://my-resource.openai.azure.com/openai/deployments/text-davinci-003")
                .build();
        String answer = model.process("hello");
        System.out.println(answer);
```

```
AzureOpenAiStreamingChatModel model = AzureOpenAiStreamingChatModel.builder()
                .apiKey("key")
                .apiVersion("2023-05-15")
                .baseUrl("https://my-resource.openai.azure.com/openai/deployments/gpt-3.5-turbo")
                .build();
        model.sendUserMessage("hello", new StreamingResponseHandler() {

            @Override
            public void onNext(String token) {
                System.out.print(token);
            }

            @Override
            public void onComplete() {
                System.out.println();
                System.out.println("completed");
            }

            @Override
            public void onError(Throwable error) {
                error.printStackTrace();
            }
        });
```

```
AzureOpenAiStreamingLanguageModel model = AzureOpenAiStreamingLanguageModel.builder()
                .apiKey("key")
                .apiVersion("2023-05-15")
                .baseUrl("https://my-resource.openai.azure.com/openai/deployments/text-davinci-003")
                .build();
        model.process("hello", new StreamingResponseHandler() {

            @Override
            public void onNext(String token) {
                System.out.print(token);
            }

            @Override
            public void onComplete() {
                System.out.println();
                System.out.println("completed");
            }

            @Override
            public void onError(Throwable error) {
                error.printStackTrace();
            }
        });
```

Thank you!

**Comment by kaltindas** [comment]
> AzureOpenAiStreamingLanguageModel model = AzureOpenAiStreamingLanguageModel.builder()
>                 .apiKey("key")
>                 .apiVersion("2023-05-15")
>                 .baseUrl("https://my-resource.openai.azure.com/openai/deployments/text-davinci-003")
>                 .build();
>         model.process("hello", new StreamingResponseHandler() {
> 
>             @Override
>             public void onNext(String token) {
>                 System.out.print(token);
>             }
> 
>             @Override
>             public void onComplete() {
>                 System.out.println();
>                 System.out.println("completed");
>             }
> 
>             @Override
>             public void onError(Throwable error) {
>                 error.printStackTrace();
>             }
>         });

I tried all 4 code snippets you provided, and they all work flawlessly. The responses are coming through! Everything is in order.

**Comment by kaltindas** [comment]
You've done a great job with a blind implementation. You are awesome :)

**Comment by langchain4j** [comment]
@kaltindas 😊 Thank you for your help with testing!

**Comment by langchain4j** [comment]
@kaltindas sorry for disturbing, but I need your help since I dont have access to Azure OpenAI :( Do you have the same problem as described [here](https://github.com/langchain4j/langchain4j/issues/127)? Thanks!
