### ISSUE TITLE
[BUG] When using a StreamingChatLanguageModel with self ChatMemoryStore, the AiServiceStreamingResponseHandler.onComplete method only give the last token to ChatMemoryStore.

### ISSUE THREAD

**Issue by DarkDance** [langchain4j/langchain4j#433]
Please provide as much details as possible, this will help us to deliver a fix as soon as possible.
Thank you!

**Describe the bug**
When using a StreamingChatLanguageModel with self ChatMemoryStore, the  AiServiceStreamingResponseHandler.onComplete method only give the last token to ChatMemoryStore.
使用StreamingChatLanguageModel的AI时，并自定义了ChatMemoryStore，在AI流信息返回的时候，AiServiceStreamingResponseHandler.onComplete方法给到ChatMemoryStore的数据只有最后一个token数据

**Log and Stack trace**
None.
没有

**To Reproduce**
You can see ServiceWithMemoryForEachUserExample, and use self ChatMemoryStore to print the updateMessages's last message info.
可以使用ServiceWithMemoryForEachUserExample来修改代码，增加一个自定义的ChatMemoryStore，updateMessages方法里面打印信息就可以发现数据缺失

**Expected behavior**
In self ChatMemoryStore, the message token  must bu full.
在自定义的ChatMemoryStore里面接收到的消息应该是完整的

**Please complete the following information:**
- LangChain4j version: e.g. 0.25.0
- Java version: e.g. 17
- Spring Boot version (if applicable): e.g. 3.1.1

**Additional context**
in class AiServiceStreamingResponseHandler，you can amend below methods:
@Override
    public void onNext(String token) {
        answerBuilder.append(token);
        tokenHandler.accept(token);
    }
    
@Override
    public void onComplete(Response<AiMessage> response) {

        AiMessage aiMessage = response.content();

        if (context.hasChatMemory()) {
            if(aiMessage.hasToolExecutionRequests()){
                context.chatMemory(memoryId).add(aiMessage);
            }else{
                AiMessage memoryMessage = AiMessage.aiMessage(answerBuilder.toString());
                context.chatMemory(memoryId).add(memoryMessage);
            }
        }
      ......
}

**Comment by langchain4j** [comment]
Hi @DarkDance thank you for reporting.
Which model are you using? I see no problems with `OpenAiStreamingChatModel`:

```java
    interface Assistant {

        TokenStream chat(String userMessage);
    }

    public static void main(String[] args) {

        ChatMemoryStore store = new ChatMemoryStore() {

            List<ChatMessage> messages = new ArrayList<>();

            @Override
            public List<ChatMessage> getMessages(Object memoryId) {
                return messages;
            }

            @Override
            public void updateMessages(Object memoryId, List<ChatMessage> messages) {
                this.messages = messages;
                System.out.println("updateMessages: " + messages);
            }

            @Override
            public void deleteMessages(Object memoryId) {

            }
        };

        ChatMemoryProvider chatMemoryProvider = memoryId -> MessageWindowChatMemory.builder()
                .id(memoryId)
                .maxMessages(10)
                .chatMemoryStore(store)
                .build();

        OpenAiStreamingChatModel model = OpenAiStreamingChatModel.withApiKey(ApiKeys.OPENAI_API_KEY);

        Assistant assistant = AiServices.builder(Assistant.class)
                .streamingChatLanguageModel(model)
                .chatMemoryProvider(chatMemoryProvider)
                .build();

        assistant.chat("Tell me a joke")
                .onNext(System.out::println)
                .onComplete(System.out::println)
                .onError(Throwable::printStackTrace)
                .start();
    }
```

Log:
```
updateMessages: [UserMessage { name = null text = "Tell me a joke" }]

Sure
,
 here
's
 a
 joke
 for
 you
:


Why
 don
't
 scientists
 trust
 atoms
?


Because
 they
 make
 up
 everything
!
updateMessages: [UserMessage { name = null text = "Tell me a joke" }, AiMessage { text = "Sure, here's a joke for you:

Why don't scientists trust atoms?

Because they make up everything!" toolExecutionRequests = null }]
Response { content = AiMessage { text = "Sure, here's a joke for you:

Why don't scientists trust atoms?

Because they make up everything!" toolExecutionRequests = null }, tokenUsage = TokenUsage { inputTokenCount = 11, outputTokenCount = 22, totalTokenCount = 33 }, finishReason = STOP }
```

As you can see, messages are full when `ChatMemoryStore.updateMessages()` is called.

**Comment by DarkDance** [comment]
Thanks for your response, I use the chinese llm and without sdk, so make the mistake. 
I found the append action in the OpenAiStreamingChatModel source: OpenAiStreamingResponseBuilder, so, it's not a bug, I will change my code. Thanks again
