### ISSUE TITLE
[FEATURE] The user can customize his tool and initialize it using AiServices, but not only use @Tool

### ISSUE THREAD

**Issue by DarkDance** [langchain4j/langchain4j#434]
**Is your feature request related to a problem? Please describe.**
when use a spring bean object as a tool, I can't use the AiServices.tools method, because it always relied to @Tool

**Describe the solution you'd like**
In class AiServices， add a new method to let user defind tools without @Tool method, just like bellow:

 public AiServices<T> tools(Map<String, ToolSpecification> toolSpecifications, Map<String, ToolExecutor> toolExecutors)

**Describe alternatives you've considered**
No, I need the spring bean and inject many object.

**Additional context**
I just try to add a method:

    public AiServices<T> tools(Map<String, ToolSpecification> toolSpecifications, Map<String, ToolExecutor> toolExecutors) {
        context.toolSpecifications = new ArrayList<>();
        context.toolExecutors = new HashMap<>();

        for (Map.Entry<String, ToolSpecification> entry: toolSpecifications.entrySet()) {
            context.toolSpecifications.add(entry.getValue());
            context.toolExecutors.put(entry.getKey(), toolExecutors.get(entry.getKey()));
        }
        return this;
    }

**Comment by langchain4j** [comment]
Hi @DarkDance is it still required?

**Comment by DarkDance** [comment]
No, use the @tool is ok, thanks

**Comment by DarkDance** [comment]
define a class:
```
public abstract class AiMethodTool {
    //none, just mark as a method tool
}
```


extends the class:
```
@Component
public class AiTools extends AiMethodTool {
     @Tool
    public Bar someMethod1(@P Foo foo) {
       // some logic
    }
     @Tool
    public Bar someMethod2(@P Foo foo) {
       // some logic
    }
}
```

then use spring methon to inject and use the AiServices.tools(aiTools.toArray()) 
```
@Resource
private List<AiMethodTool> aiTools;
```
