### ISSUE TITLE
[FEATURE] Pinecone should support storing metadata

### ISSUE THREAD

**Issue by nsadeh** [langchain4j/langchain4j#435]
Please provide as much details as possible, this will help us to deliver a fix as soon as possible.
Thank you!

**Describe the bug**

`PineconeEmbeddingStore`, the Pinecone implementation of `Embedding` store, is a `TextSegment` embeddings store. Since the latter has a `Metadata` attribute, it stands to reason that if a client called the `add` method using TextSegments with metadata, that the metadata would be uploaded to Pinecone. The actual behavior is that the Metadata gets dropped.

**Log and Stack trace**
Please provide a log and a stack trace (with exception), if applicable.

N/A

**To Reproduce**
Please provide a relevant code snippets to reproduce this bug.

1. Instantiate a Pinecone Client, index, and an embedding model
2. Create a TextSegment with non-trivial metadata, for example

(excuse my Java, I am a Clojure programmer)

```java
Metadata m = new Metadata(Map.of(
    "a", "b",
    "c", "d"
));

TextSegment t = TextSegment.from("I Am a text segment, m)
```
3. Create embeddings for this text (although you can actually pass in a random vector for this repro) and invoke .add with the segment to upload to Pinecone
4. The metadata will not make it to Pinecone

**Expected behavior**
Expecting the metadata to appear in the Pinecone console/be retrieved with Query requests

**Please complete the following information:**
- LangChain4j version: e.g. 0.24.0
- Java version:o openjdk version "21.0.1" 2023-10-17
- Spring Boot version (if applicable): e.g. 2.7.14

**Additional context**
This appears to be just omitted from the interaction with Pinecone: https://github.com/langchain4j/langchain4j/blob/e2ba2201f5243e854e1afc9e0706479b5f917c3e/langchain4j-pinecone/src/main/java/dev/langchain4j/store/embedding/pinecone/PineconeEmbeddingStore.java#L135

I may try to make a pull request. In the meantime I will have to write my own Pinecone integration with their SDK.

**Comment by nsadeh** [comment]
See https://github.com/langchain4j/langchain4j/pull/437 for a fix suggestion

**Comment by rgrebski** [comment]
Created PR https://github.com/langchain4j/langchain4j/pull/955 for that issue. 
Please check my comments in the PR itself :pray: 

Btw - If we manage to get this merged soon - I have already done the upgrade from pinecone-client 0.6.0 to 1.0.0.
I will create separate PR once this one gets merged

**Comment by langchain4j** [comment]
Has been implemented in https://github.com/langchain4j/langchain4j/pull/1400
