### ISSUE TITLE
[FEATURE] Are there any plans to add "update" and "delete" methods to the EmbeddingStore interface?

### ISSUE THREAD

**Issue by coderyjr** [langchain4j/langchain4j#436]
The current top-level interface for vector storage, the EmbeddingStore interface, only has methods for adding (add/addAll) and querying (findRelevant). Are there any plans to expand this interface in the future to include "update" and "delete" methods to accommodate more scenarios?

**Comment by langchain4j** [comment]
Hi @coderyjr yes, this is planned, but I am not sure when exactly it will be implemented. Any help would be much appreciated!

**Comment by langchain4j** [comment]
Duplicate of https://github.com/langchain4j/langchain4j/issues/301
