### ISSUE TITLE
[BUG] Azure Open AI produces incorrect json for tools without parameters

### ISSUE THREAD

**Issue by kumlien** [langchain4j/langchain4j#442]
Please provide as much details as possible, this will help us to deliver a fix as soon as possible.
Thank you!

**Describe the bug**
The Azure OpenAI lib doesn't produce correct json for functions/tools without parameters. Current implementation (in InternalAzureOpenAiHelper) sets the parameter field to `{}` but it should be `{
"type": "object", 
"properties": {}
}`

**Log and Stack trace**
`Caused by: com.azure.core.exception.HttpResponseException: Status code 400, 
"{
  "error": {
    "message": "'{}' is not of type 'object' - 'functions.2.parameters'",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}`

**To Reproduce**
Use a tool without parameters

**Expected behavior**
No exception should be thrown.

**Please complete the following information:**
- LangChain4j version: e.g. 0.25.0
- Java version: e.g. 21
- Spring Boot version (if applicable): e.g. 3.2.1

**Additional context**
functions soon to be replace by tools in the api but the schema for the parameters property seem to be the same so I guess it still makes sense to fix it.

**Comment by langchain4j** [comment]
@kumlien thanks a lot for reporting! @jdubois could you please take a look?

**Comment by kumlien** [comment]
I have a PR for it if you want to take a look.

**Comment by langchain4j** [comment]
@kumlien sure!

**Comment by kumlien** [comment]
https://github.com/langchain4j/langchain4j/pull/443

Added a static map close to the function where it's used instead of at the top of the class. Not sure what the code standard here says about that.

**Comment by jdubois** [comment]
Thanks @langchain4j  and @kumlien ! I've just ran the integration tests (as I'm the one with the access!) and I confirm they pass.
