### ISSUE TITLE
llama2 Support

### ISSUE THREAD

**Issue by gongjianfeng** [langchain4j/langchain4j#46]
Is there a plan to support the llama2 model, or what are the best practices for extending the llama2 model on your own?

**Comment by langchain4j** [comment]
Hi @gongjianfeng we are going to release integration with LocalAI today/tomorrow. With LocalAI you can run lots of local models, including Llama2. Will keep you posted.

**Comment by langchain4j** [comment]
@gongjianfeng LocalAI is now supported in 0.18.0, you can run Llama2 and other models with it.
