### ISSUE TITLE
[FEATURE] 

### ISSUE THREAD

**Issue by GuoouGcn** [langchain4j/langchain4j#505]
In China, Baidu's Wenxin Yiyuan is also very popular. I hope to support Wenxin Yiyuan. The link to Wenxin is as follows: https://yiyan.baidu.com/

**Comment by langchain4j** [comment]
Hi, is this what you are looking for? https://github.com/langchain4j/langchain4j/pull/499

**Comment by langchain4j** [comment]
Has been released in 0.26.1.
Feel free to reopen this issue if needed.
