### ISSUE TITLE
[BUG] Unable to build Message

### ISSUE THREAD

**Issue by showeriszero** [langchain4j/langchain4j#516]
**Describe the bug**
The following error occurred after the once runnable code was updated to 0.25.0:
Method 'dev.ai4j.openai4j.chat.Message$Builder dev.ai4j.openai4j.chat.Message.builder()' must be InterfaceMethodref constant

Please help to provide the solution, thank you.

**Log and Stack trace**
Method 'dev.ai4j.openai4j.chat.Message$Builder dev.ai4j.openai4j.chat.Message.builder()' must be InterfaceMethodref constant

pom.xml  include follow:
<dependency>
            <groupId>dev.langchain4j</groupId>
            <artifactId>langchain4j</artifactId>
            <version>0.25.0</version>
            <exclusions>
                <exclusion>
                    <artifactId>slf4j-api</artifactId>
                    <groupId>org.slf4j</groupId>
                </exclusion>
            </exclusions>
        </dependency>

- LangChain4j version: e.g. 0.25.0
- Java version: 17
- Spring Boot version (if applicable):  2.7.14

**Comment by langchain4j** [comment]
@showeriszero that you a lot for reporting!
Could you please provide more details? When exactly does this happen?

From the error message it seems like you are still using an old version of `dev.ai4j:openai4j`, it might have been cached somewhere. Make sure you are using version `0.12.2`.
Could you please do `mvn dependency:tree -Dverbose` in the root of your project and paste an output here?
Thank you!

**Comment by showeriszero** [comment]
thx, It's a version problem， i cleaned maven cached， redownload new version, it was worked.
