### ISSUE TITLE
[FEATURE] Azure OpenAI: use tools instead of deprecated functions

### ISSUE THREAD

**Issue by langchain4j** [langchain4j/langchain4j#521]
![image](https://github.com/langchain4j/langchain4j/assets/132277850/ae255be4-fe54-488f-9f4e-6e8a6d9d9575)
![image](https://github.com/langchain4j/langchain4j/assets/132277850/1c8701aa-257c-442e-bd6d-e4242e9a6d27)
https://learn.microsoft.com/en-au/azure/ai-services/openai/how-to/function-calling?tabs=python#using-function-in-the-chat-completions-api-deprecated

**Comment by langchain4j** [comment]
@jdubois could you please take a look? I am still waiting for an API key 😞
Thank you!

**Comment by xermaor** [comment]
Azure/azure-sdk-for-java#38115

**Comment by jdubois** [comment]
Thanks @langchain4j ! Working on this issue.
