### ISSUE TITLE
[BUG] Provide a way to log (or even more preferably retrieve the generated prompt for later use)

### ISSUE THREAD

**Issue by czp13** [langchain4j/langchain4j#522]
## Describe the Bug
It might even be a feature request; I couldn't decide in the end :).

The issue is that, currently, other than running your application in development mode and debugging some internal classes, you can see the generated prompt (where templating and other magic can happen along the way):

Somewhere here is a good point for debugging and fetching the final/replaced/enhanced prompt:
```
                        Response<AiMessage> response = context.toolSpecifications == null
                                ? context.chatModel.generate(messages)
                                : context.chatModel.generate(messages, context.toolSpecifications);
                        TokenUsage tokenUsageAccumulator = response.tokenUsage();
 ```

Here:
- https://github.com/langchain4j/langchain4j/blob/main/langchain4j/src/main/java/dev/langchain4j/service/DefaultAiServices.java#L137

To my knowledge, the original LangChain4j libraries (Python, NodeJS) provide a way to achieve this.

This poses a significant problem for robust, scalable applications as your application, in the end, is not observable from the application level, and some serious parts/methods are hidden.

## Log and Stack Trace
There are no logs or information about the generated end-result prompt, and that's the problem.

## To Reproduce
Simply add some templating or a JSON response type, or another response type both:
- Templating
- Both response types are like this

For example, for response types, this will be added:
```
You must answer strictly in the following JSON format: {
"modifications": (This is the map of the files modified where the key is the filename and the value is the content of the file; type: java.util.Map<java.lang.String, java.lang.String>),
}
```

So, your initial prompt will be modified.

## Expected Behavior
There should be a way to inspect and potentially even store the end-result prompt. This is extremely important for real-life applications and is almost a deal-breaker at this moment.

## Please Complete the Following Information:
- LangChain4j version: 0.25.0 (but applies to all versions)
- Java version: 17 (but applicable to all)

**Comment by langchain4j** [comment]
Hi @czp13 at the moment you can enable logging on the model level like this:
```
OpenAiChatModel.builder()
...
.logRequests()
.logResponses()
...
```
And you will see the final prompt right before sending to the LLM.

I will look into observability quite soon, this is one of the high priorities.
Can you please expand on "storing prompt" part? You want this for auditing purposes or something else?
Thanks.

**Comment by czp13** [comment]
Hey @langchain4j,

Thank you so much! This is exactly what I need ❤️. I will check out the logging method you provided. I hadn't seen or found it before, which could be due to a lack of documentation or perhaps my own reading skills. 😄

Regarding observability, we are definitely on the same page. Let's brainstorm or something similar, because it would be fantastic to gather data like the amount of time spent in each part of the AI flow.

As for storing data, I agree once again. It's important for auditing purposes, statistics gathering, or even for later training. The prompts used by customers should indeed be stored. As you mentioned, the 'final prompt' as well could also be saved and, potentially later based on these audit logs we could fine-tune the model or just improve the prompts/instructions to the AI model.

Currently, this aspect of the langchain4j framework seems rather obscure."

**Comment by langchain4j** [comment]
Thank you for the detailed feedback! Planning to add observability (at least basic one) in the february release 0.27.0.

**Comment by langchain4j** [comment]
I will close this bug as there are already other feature requests for observability. Feel free to reopen if needed.

**Comment by czp13** [comment]
Thank you very much, I look forward to see and use it!  Sure, feel free to close this one.
And btw good job with this library ;)! Keep up please!
