### ISSUE TITLE
[BUG] Cannot find how to specify weaviate port. Looks like it is hard coded to 80 

### ISSUE THREAD

**Issue by skanga** [langchain4j/langchain4j#532]
I run weaviate locally (without docker) and it listens on port 8080. I can successfully connect to weaviate from python like this:

```
# pip install weaviate-client
import weaviate
client = weaviate.Client("http://127.0.0.1:8080")
client.schema.get()  # Get the schema to test connection
```

How to connect from langchain4j?

**Comment by mzhu-ai** [comment]
I believe it is in the example for weaviate, you can define the host as `http://127.0.0.1:8080` 
`        EmbeddingStore<TextSegment> embeddingStore = WeaviateEmbeddingStore.builder()
                // Find it under "Show API keys" of your Weaviate cluster.
                .apiKey(System.getenv("WEAVIATE_API_KEY"))
                // The scheme, e.g. "https" of cluster URL. Find in under Details of your Weaviate cluster.
                .scheme("https")
                // The host, e.g. "test-o1gvgnp4.weaviate.network" of cluster URL.
                // Find in under Details of your Weaviate cluster.
                .host("test3-bwsieg9y.weaviate.network")`

Here is how to config weaviateclient in java: https://weaviate.io/developers/weaviate/client-libraries/java

**Comment by langchain4j** [comment]
@skanga thank you for reporting, this is indeed confusing! I have added optional `port` parameter in the `WeaviateEmbeddingStore` ctor/builder in https://github.com/langchain4j/langchain4j/commit/bcc80e2cb7861c6785af91faf74780aba818bf09

**Comment by skanga** [comment]
> @skanga thank you for reporting, this is indeed confusing! I have added optional `port` parameter in the `WeaviateEmbeddingStore` ctor/builder in [bcc80e2](https://github.com/langchain4j/langchain4j/commit/bcc80e2cb7861c6785af91faf74780aba818bf09)

Thank you
