### ISSUE TITLE
[FEATURE] Summary table of the capabilities of the integrations implemented so far

### ISSUE THREAD

**Issue by czelabueno** [langchain4j/langchain4j#565]
**Is your feature request related to a problem? Please describe.**
Improve the overview of the capabilities supported so far and the capabilities that remain to be enabled. Shortcut to official documentation.

**Describe the solution you'd like**
Add in the `README.md` file a summarized table like most popular python projects.

**Describe alternatives you've considered**
Add a similar table below of the samples in the `README.md` file something like that:

## Supported LLM Integrations ([Docs](https://langchain4j.github.io/langchain4j/docs/category/integrations))
| Provider      | Native Image     | [Completion](https://langchain4j.github.io/langchain4j/docs/category/language-models) | [Streaming](https://langchain4j.github.io/langchain4j/docs/integrations/language-models/response-streaming)  | [Async Completion](https://langchain4j.github.io/langchain4j/docs/category/language-models)  | [Async Streaming](https://langchain4j.github.io/langchain4j/docs/integrations/language-models/response-streaming)  | [Embedding](https://langchain4j.github.io/langchain4j/docs/category/embedding-models)  | [Async Image Generation](https://langchain4j.github.io/langchain4j/docs/category/image-models)  |  ....
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |----------|
| [OpenAI](https://langchain4j.github.io/langchain4j/docs/integrations/language-models/openai)  | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ |
| [AzureOpenAI](https://langchain4j.github.io/langchain4j/docs/integrations/language-models/azure-openai)  |  | ✅ | ✅ | ✅ | ✅ | ✅ |  |
| [HuggingFace](https://langchain4j.github.io/langchain4j/docs/integrations/language-models/huggingface)  |  | ✅ |  | ✅ |  |
| ....  |  |  |  |  |  |  |

**Additional context**
I think this would not only give quick visibility to users of the features they can use now but also to contributors of what remains to be implemented.

PD: I mentioned it to Dmytro and he told me to talk to you @LizeRaes about it :) . If you want me send a PR I can do that.

**Comment by LizeRaes** [comment]
Love the idea, both to have it right on our `README.md` and in the docs. In the documentation, we could make an overview page in the [integration folder](https://langchain4j.github.io/langchain4j/docs/category/integrations/) of the docs, similar to this one we have for [tutorials](https://langchain4j.github.io/langchain4j/docs/tutorials): 
source file for tutorials looks like this: https://github.com/langchain4j/langchain4j/blob/main/docs/docs/tutorials/index.mdx

If you find time, we would be really happy with a PR, even it the list is incomplete. We will then take care of extending it. Would be very much appreciated!

**Comment by czelabueno** [comment]
alright, I'll work on this in the next days. Thanks!
