### ISSUE TITLE
[FEATURE] Update and remove methods should be added to `EmbeddingStore`

### ISSUE THREAD

**Issue by boris-petrov** [langchain4j/langchain4j#583]
**Is your feature request related to a problem? Please describe.**
Currently there are only `add` methods. People also want to update/remove embeddings from the store. Methods to do that would be nice.

Not sure how the filtering will work, though. That's very specific to the particular store.

**Describe the solution you'd like**
Update and remove methods to be added to `EmbeddingStore`.

**Describe alternatives you've considered**
None.

**Additional context**
None.

P.S. Somewhat related to #151. [This](https://github.com/langchain4j/langchain4j/issues/151#issuecomment-1703682675) comment notes a possible "workaround".

**Comment by langchain4j** [comment]
Duplicate of https://github.com/langchain4j/langchain4j/issues/301
