### ISSUE TITLE
[FEATURE] Ollama Authentication Header injection

### ISSUE THREAD

**Issue by sraeuchle** [langchain4j/langchain4j#586]
Hey there, 

I have run a Ollama Instance behind a Authentication Proxy so i need to send a Authentication Header for every Ollama Request.
In your current OllamaClient implementation I can't handle that in any way. See: https://github.com/langchain4j/langchain4j/blob/057730bc7b2f50e0bca3614bbb28b477a24e2f61/langchain4j-ollama/src/main/java/dev/langchain4j/model/ollama/OllamaClient.java#L33

please add a OKHttpClient on your builder as optional so I am able to do an inject like so:
```
OkHttpClient client = new OkHttpClient.Builder().addInterceptor(new Interceptor() {
      @Override
      public Response intercept(Chain chain) throws IOException {
        Request newRequest  = chain.request().newBuilder()
            .addHeader("Authorization", "Bearer " + token)
            .build();
        return chain.proceed(newRequest);
      }
    }).build();

OllamaChatModel.builder()
    .client(client)
    ....
```

Thanks a lot!

**Comment by mnnayeck** [comment]
total blocker :(

**Comment by langchain4j** [comment]
Implemented in https://github.com/langchain4j/langchain4j-spring/pull/21
