### ISSUE TITLE
[FEATURE] Add responseFormat to AzureOpenAiChatModel and AzureOpenAiStreamingChatModel

### ISSUE THREAD

**Issue by langchain4j** [langchain4j/langchain4j#597]
Currently there is no way to enable [json mode](https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/json-mode?tabs=python) in Azure OpenAI, as well as many other parameters are missing.
`AzureOpenAiChatModel` and `AzureOpenAiStreamingChatModel` should support the same parameters `OpenAiChatModel` supports, or even more (all supported parameters).

**Comment by langchain4j** [comment]
@jdubois FYI https://github.com/quarkiverse/quarkus-langchain4j/pull/266

**Comment by jdubois** [comment]
Thanks @langchain4j ! Can you check #573 as I would like to have this merged first? I'll start working on this.

**Comment by jdubois** [comment]
@langchain4j PR is ready at #605

**Comment by jdubois** [comment]
Sorry I forgot to automatically close this issue with #605 - @langchain4j can you close this?
