### ISSUE TITLE
Do you have a roadmap?[FEATURE] 

### ISSUE THREAD

**Issue by wysstartgo** [langchain4j/langchain4j#60]
Do you have a roadmap? I would like to make some contributions.

**Comment by langchain4j** [comment]
Hi @wysstartgo thank you for your interest! Right now the priority is to expand our integrations for embedding stores (we need Elastic, Qdrant, PGVector and Vespa) and LLM providers (we need Anthropic and Cohere). Please let me know if you are interested in implementing some of abovementioned integrations or want to work on something else. Thank you.

**Comment by wysstartgo** [comment]
ok,I will try to do something @langchain4j

**Comment by langchain4j** [comment]
@wysstartgo awesome, thanks! Please note that Docx parser has been already implemented.

**Comment by wysstartgo** [comment]
> @wysstartgo awesome, thanks! Please note that Docx parser has been already implemented.

okay

**Comment by wysstartgo** [comment]
@langchain4j The Java client for qdrant comes in both gRPC and HTTP versions, and it's built on Java 17. I noticed that langchain4j is based on Java 8. Could you provide some suggestions on how to integrate them?

**Comment by sfitts** [comment]
> @langchain4j The Java client for qdrant comes in both gRPC and HTTP versions, and it's built on Java 17. I noticed that langchain4j is based on Java 8. Could you provide some suggestions on how to integrate them?

FWIW, assuming this is the [metaloom](https://github.com/metaloom/qdrant-java-client) implementation, we had a similar issue (we're on Java 11). Turns out that the only Java 17 feature used is in the tests (at least as of the current version), the main code compiles/runs fine on earlier versions.  

We are very interested in this project, but would definitely need Qdrant support.  Is that being actively worked on?

**Comment by langchain4j** [comment]
Hi @sfitts, it seems that there is an official java client for Qdrant: https://github.com/qdrant/java-client with a minimum java 8 requirement.

TBH integrating Qdrant into LangChain4j is not my priority at the moment, as we already support a lot of other vector stores and we have lots of core features missing which are higher prio right now.
It seems to be easy to integrate, you can take other integrations as an example.

Of course we would appreciate a lot if someone could contribute this integration 🤗

**Comment by sfitts** [comment]
Understood and thanks for the pointer to the new library.

**Comment by tenpigs267** [comment]
Hi @langchain4j, as you say, adding a minimal QDrantEmbeddingStore with qdrant official java client is not so much effort but I have issues with the IT. The ninth digit in Vectors values is sometime cropped/rounded. I'm not enough familiar with it to understand why, do you have a hint? 
I opened an issue in java qdrant client repo but have no answers at the moment.
Thanks.

**Comment by tenpigs267** [comment]
Maybe replacing assertions like
  assertThat(match.embedding()).isEqulaTo(embedding)
with something like : 
  assertThat(CosineSimilarity.between(match.embedding(), embedding)).isCloseTo(1d, Percentage.withPercentage(0.00001d));
can be a way to leave VectorStores room for optimizations (quantization) ?

**Comment by langchain4j** [comment]
@tenpigs267 sorry for the late response!
Please note that https://github.com/langchain4j/langchain4j/pull/542 was been merged yesterday. Sorry, I did not know that there was a parallel effort from your side, I have read your message just today. We used your idea with assertions, so thanks for that!

**Comment by tenpigs267** [comment]
No pb, it's nice to see qdrant merged. I'll surely find another feature or else to contribute, it's really cool library !
Just for reference if anyone from QDrant answer one day : https://github.com/qdrant/java-client/issues/19
