### ISSUE TITLE
[FEATURE] RPC Support

### ISSUE THREAD

**Issue by ningpengtao-coder** [langchain4j/langchain4j#600]
I found that langchain4j mainly supports client side and has no server side support.

Consider a scenario where multiple personal devices act as server and client.

1. Write a java program to use langchain4j to provide llm services and support rpc calls(server side with PC nvidia 4090 etc).
2. Use rpc to request the llm service produced by langchain4j(client side with android device or ios device etc).

**Comment by langchain4j** [comment]
@ningpengtao-coder I am afraid this is out of scope of this project
