### ISSUE TITLE
[FEATURE] ChatMemory supports separate memory for different users

### ISSUE THREAD

**Issue by chenhaoqiang** [langchain4j/langchain4j#61]
I want to develop a chatbot that supports group chat and single chat, and needs to have a separate MemoryChat for each user. I hope to support this feature, thanks!

**Comment by langchain4j** [comment]
@chenhaoqiang this is definitely possible. We will add this in the coming days.

**Comment by chenhaoqiang** [comment]
> @chenhaoqiang this is definitely possible. We will add this in the coming days.

thank you so much! But I ran into another problem，Please help me! #62

**Comment by langchain4j** [comment]
@chenhaoqiang support for a separate `ChatMemory` for each user was added in 0.19.0, please see example [here](https://github.com/langchain4j/langchain4j-examples/blob/main/other-examples/src/main/java/ServiceWithMemoryForEachUserExample.java).

**Comment by chenhaoqiang** [comment]
> @chenhaoqiang support for a separate `ChatMemory` for each user was added in 0.19.0, please see example [here](https://github.com/langchain4j/langchain4j-examples/blob/main/other-examples/src/main/java/ServiceWithMemoryForEachUserExample.java).

thanks!
