### ISSUE TITLE
[FEATURE]: Ollama to support Tools

### ISSUE THREAD

**Issue by ivanicksantos** [langchain4j/langchain4j#612]
I was trying to use Tools, but using OllamaChatModel and it give an erro "java.lang.IllegalArgumentException: Tools are currently not supported by this model"

**Comment by langchain4j** [comment]
Hi @ivanicksantos this is not a bug, Ollama does not support function calling. But we can probably add a wrapper on our side and use json mode.

**Comment by langchain4j** [comment]
Like this https://js.langchain.com/docs/integrations/chat/ollama_functions

**Comment by ivanicksantos** [comment]
there is an example in java?

**Comment by langchain4j** [comment]
@ivanicksantos here is an example of json output: https://github.com/langchain4j/langchain4j-examples/blob/b64efcb6aafdc3b763295c740ae37546a0b475aa/ollama-examples/src/main/java/OllamaChatModelTest.java#L44

**Comment by ivanicksantos** [comment]
Thank you very much. Just to make it clear, is it not possible to use ServiceWithTools in OllamaChatModel? like this : 

public class ToolsDemo {
	
	static String baseUrl() {
		return String.format("http://%s:%d", "localhost", 11434);
	}
	
	static class Calculadora {

        @Tool("Calculates the length of a string")
        int stringLength(String s) {
            System.out.println("Called stringLength with s='" + s + "'");
            return s.length();
        }

        @Tool("Calculates the sum of two numbers")
        int add(int a, int b) {
            System.out.println("Called add with a=" + a + ", b=" + b);
            return a + b;
        }

        @Tool("Calculates the square root of a number")
        double sqrt(int x) {
            System.out.println("Called sqrt with x=" + x);
            return Math.sqrt(x);
        }
    }

    interface Assistant {

        String chat(String userMessage);
    }
    
   
	public static void main(String[] args) {
		// TODO Auto-generated method stub

	String LLAMA2_MODEL_NAME = "fllama2";
		
		//load model
		 ChatLanguageModel model = OllamaChatModel.builder()
	        		.baseUrl(baseUrl())
	        		.temperature(0.1)
	        		.timeout(Duration.ofMinutes(5))
					.modelName(LLAMA2_MODEL_NAME)
					.build();
		 
		 
		 
		 Assistant assistant = AiServices.builder(Assistant.class)
	                .chatLanguageModel(model)
	                .tools(new Calculadora())
	                .chatMemory(MessageWindowChatMemory.withMaxMessages(10))
	                .build();

	        String question = "What is the square root of the sum of the numbers of letters in the words \"hello\" and \"world\"?";

	        String answer = assistant.chat(question);

	        System.out.println(answer);
	}

}

**Comment by ruizrube** [comment]
This feature would be very useful

**Comment by langchain4j** [comment]
Waiting untill [Ollama supports tools](https://github.com/ollama/ollama/issues/2417)

**Comment by langchain4j** [comment]
Duplicate of https://github.com/langchain4j/langchain4j/issues/318
