### ISSUE TITLE
[FEATURE] Add withApiKey and withEndpoint shortcut methods to Azure models

### ISSUE THREAD

**Issue by agoncal** [langchain4j/langchain4j#614]
Today all the models have Builders so you can build a valid model and then invoke it. Some models (`MistralAiChatModel`, `NomicEmbeddingModel`, `OpenAiChatModel`, etc.) also have shortcut methods allowing to set the minimum required attributes instead of using the builder:

```java
// Using shortcut methods
ChatLanguageModel model = OpenAiChatModel.withApiKey(ApiKeys.OPENAI_API_KEY);

// Using the builder
ChatLanguageModel model = OpenAiChatModel.builder()
        .apiKey(ApiKeys.OPENAI_API_KEY))
        .modelName(GPT_4_VISION_PREVIEW)
        .maxTokens(50)
        .build();
```

It would be nice to have the same shortcuts (`apiKey` and `endpoint`) in the Azure models (`AzureOpenAiChatModel`, `AzureOpenAiLanguageModel`, `AzureOpenAiStreamingLanguageModel`, etc.)

```java
AzureOpenAiChatModel model = AzureOpenAiChatModel.withApiKey(apiKey).withEndpoint(endpoint);
```

This way you can easily have an Azure model in one line.... and use the Builder if you need more control.

**Comment by SandraAhlgrimm** [comment]
As a developer who uses langchain4j, I would want the same shortcuts for all models.

**Comment by yeshadoo** [comment]
i wanna try this, pls assign me thanks.

**Comment by langchain4j** [comment]
@yeshadoo go ahead, thanks!

**Comment by agoncal** [comment]
Hey @yeshadoo, any progress on that? Do you need any help?

**Comment by yeshadoo** [comment]
I apologize for being a bit busy recently, so I have to temporarily cancel
the task assignment.

**Comment by agoncal** [comment]
@yeshadoo No problem, that's fine. It happens to all of us. I'll take care of it.

@langchain4j can you assign this one to me please

**Comment by agoncal** [comment]
Closing this as `withApiKey` methods are being removed (see https://github.com/langchain4j/langchain4j/commit/ef2f1ec470d1a470e9682146b62a8947f4e7d09e)
