### ISSUE TITLE
Citations and document removal

### ISSUE THREAD

**Issue by 22mariocalus** [langchain4j/langchain4j#618]
Hello!
 It would be really helpful to reference the documents the application uses to respond to questions. From my research I didn't find anything related to this in langchain4j only in langchain.
Also, something else that I find helpful is the ability to remove documents which are no longer needed.
Best wishes!

**Comment by langchain4j** [comment]
Duplicate, please track it here: https://github.com/langchain4j/langchain4j/issues/660
