### ISSUE TITLE
[FEATURE] ChatMessage implements Serializable

### ISSUE THREAD

**Issue by chenhaoqiang** [langchain4j/langchain4j#62]
When I want to implement database-based ChatMemory, I want to serialize **List<ChatMessage> previousMessages** to JSON and save it to the database. 
When I use jackson for serialization, I get the error: No serializer found for class dev.langchain4j.data.message.UserMessage; 
![image](https://github.com/langchain4j/langchain4j/assets/20062034/e98384e9-69c8-46ef-9b6b-a99f553d98e8)

then I find Gson, which doesn't rely on Serializable, but when deserializing, I get an error: Abstract class can't be instantiated! Class name: dev.langchain4j.data.message.ChatMessage
![060c04a05e1e4763b11be6bc3b480a59](https://github.com/langchain4j/langchain4j/assets/20062034/9c30054e-649a-4c7b-8685-303249ac96dd)

I can't find another way, please help me, thanks!

**Comment by langchain4j** [comment]
@chenhaoqiang we were planning to implement memory serialization/deserialization soon, I guess now it will be sooner :) Will prioritize this to be done in the coming days. Could you please provide more details on how you want to use it? Just dump the whole ChatMemory into one JSON string and then store it into DB? And then rebuild ChatMemory from this JSON string? Do you need any extra features besides that? Thanks

**Comment by langchain4j** [comment]
@chenhaoqiang untill we add this feature, you can implement a custom GSON `JsonDeserializer` like this:
```java
public class ChatMessageAdapter implements JsonDeserializer<ChatMessage>, JsonSerializer<ChatMessage> {
    @Override
    public ChatMessage deserialize(JsonElement json, Type typeOfT, JsonDeserializationContext context) throws JsonParseException {
        JsonObject jsonObject = json.getAsJsonObject();
        JsonElement jsonType = jsonObject.get("type");
        String type = jsonType.getAsString();
        
        switch (type) {
            case "UserMessage":
                return context.deserialize(json, UserMessage.class);
            case "SystemMessage":
                return context.deserialize(json, SystemMessage.class);
            case "AiMessage":
                return context.deserialize(json, AiMessage.class);
            default:
                throw new JsonParseException("Unknown type: " + type);
        }
    }

    @Override
    public JsonElement serialize(ChatMessage src, Type typeOfSrc, JsonSerializationContext context) {
        JsonElement elem;
        String type;

        if (src instanceof UserMessage) {
            elem = context.serialize(src, UserMessage.class);
            type = "UserMessage";
        } else if (src instanceof SystemMessage) {
            elem = context.serialize(src, SystemMessage.class);
            type = "SystemMessage";
        } else if (src instanceof AiMessage) {
            elem = context.serialize(src, AiMessage.class);
            type = "AiMessage";
        } else {
            throw new IllegalArgumentException("Unknown type: " + src.getClass().getName());
        }

        JsonObject obj = elem.getAsJsonObject();
        obj.addProperty("type", type);

        return obj;
    }
}
```
And then register it:
```java
Gson gson = new GsonBuilder()
    .registerTypeAdapter(ChatMessage.class, new ChatMessageAdapter())
    .create();
```

**Comment by langchain4j** [comment]
@chenhaoqiang I have updated implementation of `serialize()` method in my previous message as it did not include type. BTW this code was generated by GPT-4, so it might not work right away. But the general direction is right: we need to include the type of message in JSON during serialization and then use this type during deserialization to figure out which exact class to use.

**Comment by chenhaoqiang** [comment]
> @chenhaoqiang we were planning to implement memory serialization/deserialization soon, I guess now it will be sooner :) Will prioritize this to be done in the coming days. Could you please provide more details on how you want to use it? Just dump the whole ChatMemory into one JSON string and then store it into DB? And then rebuild ChatMemory from this JSON string? Do you need any extra features besides that? Thanks

yes, This is what I want!

**Comment by chenhaoqiang** [comment]
> @chenhaoqiang untill we add this feature, you can implement a custom GSON `JsonDeserializer` like this:
> 
> ```java
> public class ChatMessageAdapter implements JsonDeserializer<ChatMessage>, JsonSerializer<ChatMessage> {
>     @Override
>     public ChatMessage deserialize(JsonElement json, Type typeOfT, JsonDeserializationContext context) throws JsonParseException {
>         JsonObject jsonObject = json.getAsJsonObject();
>         JsonElement jsonType = jsonObject.get("type");
>         String type = jsonType.getAsString();
>         
>         switch (type) {
>             case "UserMessage":
>                 return context.deserialize(json, UserMessage.class);
>             case "SystemMessage":
>                 return context.deserialize(json, SystemMessage.class);
>             case "AiMessage":
>                 return context.deserialize(json, AiMessage.class);
>             default:
>                 throw new JsonParseException("Unknown type: " + type);
>         }
>     }
> 
>     @Override
>     public JsonElement serialize(ChatMessage src, Type typeOfSrc, JsonSerializationContext context) {
>         JsonElement elem;
>         String type;
> 
>         if (src instanceof UserMessage) {
>             elem = context.serialize(src, UserMessage.class);
>             type = "UserMessage";
>         } else if (src instanceof SystemMessage) {
>             elem = context.serialize(src, SystemMessage.class);
>             type = "SystemMessage";
>         } else if (src instanceof AiMessage) {
>             elem = context.serialize(src, AiMessage.class);
>             type = "AiMessage";
>         } else {
>             throw new IllegalArgumentException("Unknown type: " + src.getClass().getName());
>         }
> 
>         JsonObject obj = elem.getAsJsonObject();
>         obj.addProperty("type", type);
> 
>         return obj;
>     }
> }
> ```
> 
> And then register it:
> 
> ```java
> Gson gson = new GsonBuilder()
>     .registerTypeAdapter(ChatMessage.class, new ChatMessageAdapter())
>     .create();
> ```

I modified it a little based on the code and it worked! Thanks!!!

**Comment by langchain4j** [comment]
@chenhaoqiang we've added an option to persist chat memory in 0.21.0. Please see example [here](https://github.com/langchain4j/langchain4j-examples/blob/main/other-examples/src/main/java/ServiceWithPersistentMemoryForEachUserExample.java).

**Comment by chenhaoqiang** [comment]
> @chenhaoqiang we've added an option to persist chat memory in 0.21.0. Please see example [here](https://github.com/langchain4j/langchain4j-examples/blob/main/other-examples/src/main/java/ServiceWithPersistentMemoryForEachUserExample.java).

Thanks!🥰😀
