### ISSUE TITLE
[Sonar S1130]  "throws" declarations should not be superfluous

### ISSUE THREAD

**Issue by jlerbsc** [langchain4j/langchain4j#630]
**Describe the issue**

Our "Indepth" java code remediation solution told us that the following Sonar violation.  It appears 2 times in the "core" module.

Superfluous exceptions within throws clauses have negative effects on the readability and maintainability of the code. JsonParseException is a runtime exception, so there is no need to declare it.

It's not very important, but we thought you might be interested in improving the quality of this project.

All open source projects can use Indepth free of charge (https://www.indepth.fr). 

    dev\langchain4j\data\message\GsonChatMessageAdapter.java
    @@ -23,5  +23,5 @@
    @Override
    -    public ChatMessage deserialize(JsonElement messageJsonElement, Type ignored, JsonDeserializationContext context) throws JsonParseException {
    +    public ChatMessage deserialize(JsonElement messageJsonElement, Type ignored, JsonDeserializationContext context) {
        String chatMessageTypeString = messageJsonElement.getAsJsonObject().get(CHAT_MESSAGE_TYPE).getAsString();
        ChatMessageType chatMessageType = ChatMessageType.valueOf(chatMessageTypeString);

    dev\langchain4j\data\message\GsonContentAdapter.java
    @@ -19,5  +19,5 @@
    @Override
    -    public Content deserialize(JsonElement contentJsonElement, Type ignored, JsonDeserializationContext context) throws JsonParseException {
    +    public Content deserialize(JsonElement contentJsonElement, Type ignored, JsonDeserializationContext context) {
        String contentTypeString = contentJsonElement.getAsJsonObject().get(CONTENT_TYPE).getAsString();
        ContentType contentType = ContentType.valueOf(contentTypeString);

**Log and Stack trace**

**To Reproduce**

**Expected behavior**

**Please complete the following information:**
- LangChain4j version: 0.27.1

**Additional context**

**Comment by langchain4j** [comment]
@jlerbsc thanks!
