### ISSUE TITLE
[Sonar 1166] Exception handlers should preserve the original exception

### ISSUE THREAD

**Issue by jlerbsc** [langchain4j/langchain4j#631]
**Describe the issue**

Our "Indepth" java code remediation solution told us that the following Sonar violation. It appears only 1 time in the "core" module.

When handling a caught exception, the original exception’s message and stack trace should be logged or passed forward.

"Indepth" also provides you with the appropriate fix.

The project code is of really high quality. Congratulations.

All open source projects can use Indepth free of charge (https://www.indepth.fr). 

    dev\langchain4j\store\memory\chat\cassandra\CassandraChatMemoryStore.java
    @@ -143,5  +143,5 @@
        } catch (Exception e) {
            log.error("Unable to parse message body", e);
    -            throw new IllegalArgumentException("Unable to parse message body");
    +            throw new IllegalArgumentException("Unable to parse message body", e);
        }
    }

**Log and Stack trace**

**To Reproduce**

**Expected behavior**

**Please complete the following information:**
- LangChain4j version: 0.27.1

**Additional context**

**Comment by langchain4j** [comment]
@jlerbsc thanks a lot for reporting! Going to fix asap

**Comment by jlerbsc** [comment]
A little help in spreading the word about Indepth would be greatly appreciated. :-)
