### ISSUE TITLE
Getting started - docs compilation

### ISSUE THREAD

**Issue by sshaaf** [langchain4j/langchain4j#633]
**Describe the bug**
Documentation - Getting started
ref: https://langchain4j.github.io/langchain4j/docs/get-started/

**To Reproduce**
run through the getting started first section. And unable to compile with the following 

`OpenAiChatModel model = OpenAiChatModel.withApiKey(apiKey);`

**Expected behavior**
Should be able to compile as this is the first step in trying it out. 

- LangChain4j version:  0.27.1
- Java version:  21

**Comment by LizeRaes** [comment]
Good catch! I see you have a fix ready, please make a PR, happy to merge it then! Thank you

**Comment by sshaaf** [comment]
@LizeRaes Great! here is the PR https://github.com/langchain4j/langchain4j/pull/634
