### ISSUE TITLE
[FEATURE] Select tools dynamically on incoming message

### ISSUE THREAD

**Issue by andyflury** [langchain4j/langchain4j#637]
With an Assistant interface like this:

```
interface Assistant {
    String chat(String message);
}
```

We can use the AiService like this:

```
assistant = AiServices.builder(Assistant.class)
    .streamingChatLanguageModel(model)
    .tools(tools)
    .build();
```

And then we can just call the Assistant like this:

```
assistant.chat(message);
```

Base on the provided message OpenAI will then select which tool to use, which is great!

Now, imagine there are dozens of tool specifications. These tool specifications will be sent with each chat message, which will count towards Token usage.

My question is, is there a way to select the the tools to be included in chat message, before calling OpenAI?

I was thinking of creating multiple different Assistants, but then each would have its separate Memory, so that would not work.

Would it make sense to create multiple Assistants and have all of them use the same ChatMemoryProvider?

**Comment by TyCoding** [comment]
I also have the same question. If I want to use images as part of the chat context for the model to parse, which object should I use to call the interface

**Comment by langchain4j** [comment]
@andyflury how do you plan to select tools? Manually? On each call?

At the moment using multiple AI services with the same memory/provider should work. Or you can use low-level `ChatLanguageModel`, there is method accepting list of messages and available tools.

**Comment by andyflury** [comment]
thx @langchain4j! I did end up using the same memory for multiple AI services, which seems to work. In case anybody else needs this here is my code:

```
@Service
public class ChatService implements InitializingBean {

    @Autowired
    private StreamingChatLanguageModel streamingChatLanguageModel;

    @Autowired
    @Qualifier("chatModel")
    private ChatLanguageModel chatLanguageModel;

    @Autowired
    private ToolService toolService;

    private Map<Object, ChatMemory> chatMemories = new HashMap<>();
    private Map<ToolType, Assistant> assistants = new HashMap<>();

    @Override
    public void afterPropertiesSet() throws Exception {
        assistants = toolService
                .getTools()
                .stream()
                .collect(Collectors.toMap(t->t.getToolType(), t -> createAssistant(t)));
    }

    private Assistant createAssistant(Object tool) {
        return AiServices.builder(Assistant.class)
                .streamingChatLanguageModel(streamingChatLanguageModel)
                .tools(tool)
                .chatMemoryProvider(memoryId -> getChatMemory(memoryId))
                .build();
    }

    private ChatMemory getChatMemory(Object memoryId) {
        if (chatMemories.containsKey(memoryId)) {
            return chatMemories.get(memoryId);
        } else {
            ChatMemory chatMemory = MessageWindowChatMemory.withMaxMessages(10);
            chatMemories.put(memoryId, chatMemory);
            return chatMemory;
        }
    }
}
```

Then you can retrieve the assistant by tool and invoke chat

```
Assistant assistant = assistants.get(tool);
TokenStream tokenStream = assistant.chat(firstUserMessageHash, lastUserMessage);
```

And the ToolService basically gives access to all Tool-Beans

```
@Service
public class ToolService implements InitializingBean {

    @Autowired
    private ApplicationContext applicationContext;

    private Map<ToolType, Tool> tools;

    @Override
    public void afterPropertiesSet() throws Exception {

        tools = applicationContext
                .getBeansOfType(Tool.class)
                .values()
                .stream()
                .collect(Collectors.toMap(t -> t.getToolType(), t -> t));
    }

    public Tool getTool(ToolType toolType) {
        return tools.get(toolType);
    }

    public Set<ToolType> getToolTypes() {
        return tools.keySet();
    }

    public Collection<Tool> getTools() {
        return tools.values();
    }
}
```

**Comment by langchain4j** [comment]
@andyflury it seems that we can really simplify this, but I need to know a bit more about your use case.
If I understood correctly, you are creating an AiService instance for each tool that you have.
I am not sure about the relationship between `Tool` and `ToolType`, is it 1:1? I assume `ToolType` is an enum and `Tool` is a marker interface for all classes in your app that have `@Tool` methods.

So, do I understand correctly that you need a way to dynamically specify which tool should assistant have access to on each call?
Something like this?
```java
Assistant assistant = AiServices.builder(Assistant.class)
                .streamingChatLanguageModel(streamingChatLanguageModel)
                .chatMemoryProvider(memoryId -> getChatMemory(memoryId))
                .build();

assistant.chat("What is 2+2?", calculatorTool);

assistant.chat("What is the weather in Milan?", weatherTool);

```

**Comment by andyflury** [comment]
Thank you @langchain4j 

Yes, that's exactly the use case we have in mind.

And yes, adding a tool (or tools) to assistant calls would be ideal. 

Is this already possible today?

**Comment by langchain4j** [comment]
WIll the tools be selected deterministically by some condition? Or a human will be selection?
How many tools do you have? Can you give a short descriptions what those tools do?
Sorry for so many questions, I want to better understand your use case.

No it is not possible today, but I am thinking about adding something like this, so I need a clearer picture on your use case.
Thanks!

**Comment by andyflury** [comment]
Yes, the tools would be selected by users. We are thinking about adding a tool selection to our chat UI.
At the moment we have about half a dozen tools, but we will be adding more. Some of the tools are RAG related and pull data from various internal sources (for this we could probably use your new advanced RAG), other tools call REST API endpoints (e.g. Zendesk and Hubspot).

does this help?

Thank you!

**Comment by langchain4j** [comment]
Yes, this helps, thank you!

Another thing I am considering is to have an automatic dynamic tool selection, based on the user intent.
I am not sure if this will work good enough for your use case though.

When the query from the user comes, use something like [this](https://github.com/langchain4j/langchain4j-examples/blob/main/other-examples/src/main/java/embedding/classification/EmbeddingModelTextClassifierExample.java) to classify the intent of the user. Then choose the appropriate tools for each of intents.

Another option is to do a RAG over tools, so each tool will have a detailed description that can be embedded and then user query is embedded as well and a regular RAG (simple or advanced) is done, returning a list of most relevant tools. One can also play with maxResults and minScore, etc.

WDYT?

**Comment by andyflury** [comment]
I think the concept with the `EmbeddingModelTextClassifier` is great. 

Main problem with letting LLM's decide about Tools is that you have to send tool definitions with every LLM call which consumes a lot of tokens. Doing the tool selection locally with the `EmbeddingModelTextClassifier` might not be 100% accurate, but definitely saves a lot of tokens.

The RAG option could work as, but again adding all tool definitions (especially if there are lots of tools) to each LLM call might get costly. Or did you think of only sending the tool description in the initial LLM call, let the LLM decide which tool to use (if any) and only then send the full tool definition.

For our particular case, I think the `EmbeddingModelTextClassifier` option would work better. But I'm sure there are plenty of use-case where the RAG approach makes sense as well

**Comment by langchain4j** [comment]
With both `EmbeddingModelTextClassifier` and RAG options I meant not sending all tools at once on each call to the LLM, but rather first get the set of tools relevant for the user request (without involving LLM, so just embedding model) and then send only this subset to the LLM.

Yes, I was also considering sending a list of tool names and maybe very short descriptions and give the LLM the tool to "select" desired tools. Something like this:

Request 1:
```
System Message:
You are blablabla, you have access to the following tools, but first you need to select them:
- weather
- calculator
... 100 more tools ...
- email

User Message:
Hey what's the weather in Paris?

Tools:
- selectTool(String... toolNames)
```
Response 1:
```
selectTool(weather)
```
Once selectTool is called, AI Services could automatically inject selected tools in the next call to the LLM and even remove previous  message from the LLM (where it invokes selectTool) which is unnecessary.

Request 2:
```
System Message:
You are blablabla. [optionally a list of tools, but probably this is not needed in this case]

User Message:
Hey what's the weather in Paris?

Tools:
- weather(String location, Unit unit)
```
Response 2:
```
weather(Paris, CELSIUS)
```

So there are now at least 3 options :) Any more ideas?

**Comment by andyflury** [comment]
Interesting!

@langchain4j So this LLM based approach would result in two LLM calls for each user request? The first containing the list of tools with short description and the second with the actual selected tool. I assume the LLM might also have the liberty to select no tool at all, if it does not see a need for one. So most likely the actual LLM calls will be smaller than 2x the number of users requests.

I think this option will be much more precise compared to the embedding model based approach we discussed previously, and since you're just sending the list of tools with descriptions it might also not be that expensive in terms of token usage.

I would certainly try both options for our specific case. 

In general I definitely see both options (embedding model and LLM model) used in practice for tool selections. So maybe have an initial simple implementation and then get a feel which option attracts more users to then further develop.

**Comment by langchain4j** [comment]
Yes, although it will do up to 2 times more calls, the number of used tokens should be (much) less, at least for the cases where there are many tools with many parameters. Each tool easily eats 20+ tokens. It can be replaced with a few tokens of the tool name in the system message.

I will think/play with this in the coming weeks, I think we can provide some of these 3 options easily out of the box.
As well as flefibility to explicitly define tools for each call.

**Comment by langchain4j** [comment]
Related: https://github.com/quarkiverse/quarkus-langchain4j/issues/341

**Comment by langchain4j** [comment]
Related: https://github.com/langchain4j/langchain4j/issues/141
