### ISSUE TITLE
[BUG] ServiceWithToolsExample fails when using LocalAI.

### ISSUE THREAD

**Issue by ItsRainingHP** [langchain4j/langchain4j#639]
**Describe the bug**
When using LocalAiChatModel the DefaultAiServices throws a null error on the toolExecutor.

**Log and Stack trace**
```
java.lang.NullPointerException: Cannot invoke "dev.langchain4j.agent.tool.ToolExecutor.execute(dev.langchain4j.agent.tool.ToolExecutionRequest, Object)" because "toolExecutor" is null at dev.langchain4j.service.DefaultAiServices$1.invoke(DefaultAiServices.java:155) ~[LJTest-1.0.0.jar:?]
```

**To Reproduce**
Use the exact code in ServiceWithToolsExample except changing to a LocalAiChatModel.

**Expected behavior**
Run with tools

**Please complete the following information:**
- LangChain4j version: 0.27.1
- Java version: 17

**Comment by Axel-1** [comment]
I have the same issue.
I switched to LocalAI since Ollama integration doesn't support tools.
Are there other local integrations that support tools ?

**Comment by Captainpax** [comment]
I have the same issue

**Comment by langchain4j** [comment]
@ItsRainingHP thanks a lot for reporting! Going to fix asap

**Comment by langchain4j** [comment]
@ItsRainingHP please provide the code to reproduce this error, most importantly how you careate LocalAI model. Thanks.

**Comment by langchain4j** [comment]
Seems to be a bug on LocalAI side, I have opened an [issue](https://github.com/mudler/LocalAI/issues/1735).
