### ISSUE TITLE
[BUG] - not able to view the docs.langchain4j.dev website

### ISSUE THREAD

**Issue by edeandrea** [langchain4j/langchain4j#652]
I'm not able to view the docs.langchain4j.dev website:

![image](https://github.com/langchain4j/langchain4j/assets/363447/b0f151ac-fd87-46dc-a277-ad5c529c9cc5)

**Comment by langchain4j** [comment]
@edeandrea hey, where did you even get this domain? :)
I am just in the process of adding it...

**Comment by edeandrea** [comment]
Its linked to in the main README...

**Comment by langchain4j** [comment]
Ah I see, they now automatically redirect https://langchain4j.github.io/langchain4j/ to docs.langchain4j.dev which I just added as a custom domain. Did not expect this to happen...

**Comment by langchain4j** [comment]
Works now https://docs.langchain4j.dev/
