### ISSUE TITLE
[FEATURE] Return retrieved segments (RAG) when using AiService and streaming

### ISSUE THREAD

**Issue by hannesroth88** [langchain4j/langchain4j#660]
I am using a conversational RAG. I would like to return the Source Documents with Metadata. So that I would be able to show them in the Frontend. 

Haven't found a way to easily do so? Is the only way to do it with a full customized chain?
Right now I am using this setup 

```
    interface RagService {
        String answer(String query);
    }
```

```
        QueryTransformer queryTransformer = new CompressingQueryTransformer(chatLanguageModel);

        ContentRetriever contentRetriever = EmbeddingStoreContentRetrieverCustom.builder()
                .embeddingStore(embeddingStore)
                .embeddingModel(embeddingModel)
                .maxResults(5)
                .minScore(0.6)
                .build();

        RetrievalAugmentor retrievalAugmentor = DefaultRetrievalAugmentor.builder()
                .queryTransformer(queryTransformer)
                .contentRetriever(contentRetriever)
                .build();

        ChatMemory chatMemory = chatMemoryService.getChatMemoryMaxTokens(memoryId);
        RagService ragService = AiServices.builder(RagService.class)
                .chatLanguageModel(chatLanguageModel)
                .retrievalAugmentor(retrievalAugmentor)
                .chatMemory(chatMemory)
                .build(); 
```

**Comment by langchain4j** [comment]
HI @hannesroth88 this feature is in high prio, will be added soon.
Right now you can use a custom `ContentInjector` proxy that would intercept the call to the real `ContentInjector` (.e.g `DefaultContentInjector`) and there you can have access to the injected contents. Ugly, but doable :)

**Comment by hannesro** [comment]
I am struggling to pass the Documents back to the parent class where AiService is called.
What I have already done before this feature request was changing how to retrieve the relevant sources in a proxy ContentRetriever:
```
public class EmbeddingStoreContentRetrieverCustom implements ContentRetriever {

    // .... constructors ...

    @Override
    public List<Content> retrieve(Query query) {
        Embedding embeddedText = embeddingModel.embed(query.text()).content();

        // Pass knowledgeId before embeddedText in the findRelevant method
        List<EmbeddingMatch<TextSegment>> relevant = embeddingStore.findRelevantByKnowledgeId(knowledgeId, embeddedText, maxResults, minScore);

        return relevant.stream()
                .map(EmbeddingMatch::embedded)
                .map(Content::from)
                .collect(toList());
    }
```

Could I start from here? But what would be a good solution to pass it up?
I think I would want to avoid passing the sources all the way up to AiService. Probably a lot of work and really ugly ;)

**Comment by langchain4j** [comment]
An ugly option would be to store retrieved `List<Content>` in a field of `EmbeddingStoreContentRetrieverCustom`, then once AiService returns, go and get it from there.

I will work on adding a nicer way to do that. Maybe something like:
```java
interface Assistant {

    WithSources<String> chat(String userMessage);
}

WithSources<String> answerWithSources = assistant.chat(...);
String answer = answerWithSources.content();
List<Content> sources = answerWithSources.sources();

```

WDYT?

**Comment by hannesro** [comment]
> An ugly option would be to store retrieved `List<Content>` in a field of `EmbeddingStoreContentRetrieverCustom`, then once AiService returns, go and get it from there.
> 
> I will work on adding a nicer way to do that. Maybe something like:
> 
> ```java
> interface Assistant {
> 
>     WithSources<String> chat(String userMessage);
> }
> 
> WithSources<String> answerWithSources = assistant.chat(...);
> String answer = answerWithSources.content();
> List<Content> sources = answerWithSources.sources();
> ```
> 
> WDYT?

This is exactly what I want! 💪

Also thanks for the hint. Of course, I totally was missing that my ContentRetriever EmbeddingStoreContentRetrieverCustom is an instance in the class where AiService is called 🙄. So there's no need to do it with a unique id or so.
Not that ugly after all then.

**Comment by ndkells** [comment]
Hi, are there any news on adding the feature yet?

> HI @hannesroth88 this feature is in high prio, will be added soon. Right now you can use a custom `ContentInjector` proxy that would intercept the call to the real `ContentInjector` (.e.g `DefaultContentInjector`) and there you can have access to the injected contents. Ugly, but doable :)

**Comment by langchain4j** [comment]
Hi @ndkells sorry, did not have time to address it yet

**Comment by langchain4j** [comment]
This feature was implemented in https://github.com/langchain4j/langchain4j/issues/1040

But we should also implement the same for streaming (e.g. `TokenStream`).
Consider multiple solutions before implementing.
One of them:
```java
interface Assistant {

    TokenStream chat(String userMessage);
}

assistant.chat("What is the capital of Germany?")
                .onRetrieved(contents -> ...) // new callback
                .onNext(token -> ...)
                .onComplete(response -> ...)
                .onError(error -> ...)
                .start();
```

But not sure this will work nicely with [Flux](https://github.com/langchain4j/langchain4j/issues/886).
