### ISSUE TITLE
[FEATURE] Upgrade Opensearch java client library to latest 2.9.0 which supports Java 8

### ISSUE THREAD

**Issue by Hrvojeee** [langchain4j/langchain4j#665]
**Describe the issue**
I am working with an application compiled against Java 8 and cannot do any upgrades on it. I need to integrate Opensearch serverless with this application but the latest version of langchain4j declared (with a reason) that this opensearch extension for langchain4j needs to be compiled with Java 11; https://github.com/langchain4j/langchain4j/blob/0.27.1/langchain4j-opensearch/pom.xml. Hence, i cannot use it in my project. 

**Describe the solution you'd like**
This enforcement was done because the Opensearch Java client initially supported only Java 11, but luckily due to many requests for restoring support for Java 8 https://github.com/opensearch-project/opensearch-java/issues/156 , this newest opensearch-java client just got released yesterday (22.2.2024) in version 2.9.0 which should now support Java 8; https://github.com/opensearch-project/opensearch-java/blob/v2.9.0/CHANGELOG.md  & https://github.com/opensearch-project/opensearch-java/releases . The artifact is already published https://central.sonatype.com/artifact/org.opensearch.client/opensearch-java so it would be fantastic if we can now upgrade the [langchain4j-opensearch](https://github.com/langchain4j/langchain4j/tree/0.27.1/langchain4j-opensearch) module to use this latest version of opensearch-java.
There is an additional complexity around this feature request because i saw that the tests in this langchain4j-opensearch module have dependency on artifact https://mvnrepository.com/artifact/org.opensearch/opensearch-testcontainers and this one requires Java 11 because the Opensearch server supports only Java 11. This fact will probably never change since this opensearch-testcontainers artifact is more related to the Opensearch server and not the client. Hence i would propose to have the compile version of sources set to Java 8 and compile version of test sources set to Java 11 so that people that want to use this, but are working with Java 8 projects can still use the great langchain4j!
PR here https://github.com/langchain4j/langchain4j/pull/663

**Describe alternatives you've considered**
At this moment i could use the opensearch-java client directly, but then i would miss all the benefits of langchain4j, so would really like this to get implemented.

**Additional context**
None.

**Comment by langchain4j** [comment]
Hi @Hrvojeee sounds good! please open a PR.

Be aware that we plan to migrate to java 11+ soon...

**Comment by Hrvojeee** [comment]
Then i guess it does not make sense to merge it. Please close the PR and this feature request.

**Comment by langchain4j** [comment]
Not all modules have to be migrated though. The main reason why we migrate is to get rid of the problematic retrofit/okhttp client and use java's HttpClient instead (by default). But there will be a way to plug in other clients (including existing okhttp), so I guess we can try to keep core and main module on java 8. Will see soon.

**Comment by langchain4j** [comment]
Implemented in https://github.com/langchain4j/langchain4j/pull/663
