### ISSUE TITLE
Streaming doesn't work with CustomStreamingResponseHandler. Okhttp3 error occured

### ISSUE THREAD

**Issue by kevintanhongann** [langchain4j/langchain4j#670]
**Describe the bug**
Error occured during streaming for getting response. 

**Log and Stack trace**
2024-02-24T01:17:40.732+08:00 ERROR 27155 --- [alhost:1337/...] c.m.m.l.CustomStreamingResponseHandler   : error processing stream to save question answer pairs 

java.lang.IllegalArgumentException: byteCount < 0: -1
        at okio.RealBufferedSource.request(RealBufferedSource.kt:204)
        at okio.RealBufferedSource.require(RealBufferedSource.kt:202)
        at okio.RealBufferedSource.readFully(RealBufferedSource.kt:276)
        at okhttp3.internal.sse.ServerSentEventReader$Companion.readData(ServerSentEventReader.kt:148)
        at okhttp3.internal.sse.ServerSentEventReader$Companion.access$readData(ServerSentEventReader.kt:112)
        at okhttp3.internal.sse.ServerSentEventReader.processNextEvent(ServerSentEventReader.kt:57)
        at okhttp3.internal.sse.RealEventSource.processResponse(RealEventSource.kt:75)
        at okhttp3.internal.sse.RealEventSource.onResponse(RealEventSource.kt:46)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)

**To Reproduce**
LocalAiStreamingChatModel model = LocalAiStreamingChatModel
            .builder()
            .baseUrl("http://localhost:1337/v1")
            .modelName("openhermes-2.5-mistral-7b")
            .maxTokens(2048)
            .timeout(Duration.ofMinutes(2))
            .temperature(0.7)
            .topP(0.95)
            .build();

List<ChatMessage> messages = Arrays.asList(
                systemMessage(
                    """
                    <your system prompt>
                    """
                ),
                userMessage(<your message>)
            );
chatLanguageModel.generate(
                messages,
                new CustomStreamingResponseHandler());

```
public class CustomStreamingResponseHandler implements StreamingResponseHandler<AiMessage> {

    private final Logger log = LoggerFactory.getLogger(CustomStreamingResponseHandler.class);

    @Override
    public void onNext(String token) {}

    @Override
    public void onComplete(Response<AiMessage> response) {
        log.debug("response from AI : {}", response.content().text());
    }

    @Override
    public void onError(Throwable error) {
        log.error("error processing stream to save question answer pairs", error);
    }
}
```

**Expected behavior**
I should be able to get my responses normally, but it hit onError instead.

**Please complete the following information:**
- LangChain4j version: e.g. 0.27.1
- Java version: e.g. 11
- Spring Boot version (if applicable): e.g. 3.2

**Additional context**
I believe the problem occurs at the okhttp level during streaming.

**Comment by langchain4j** [comment]
Hi @kevintanhongann thanks a lot for reporting!
Are you using LocalAI? Which version?

**Comment by kevintanhongann** [comment]
Yes I am using LocalAI. 0.27.1. OpenHermes, but it doesn't matter which local AI that I use. I can see that it doesn't work across LMStudio and Jan.ai.

**Comment by nhh1603** [comment]
![image](https://github.com/langchain4j/langchain4j/assets/69860012/c1d2960f-8690-4d71-8891-07a653a6b049)
![image](https://github.com/langchain4j/langchain4j/assets/69860012/d27479bd-bce9-4b84-a581-014b728c7ae3)

Hello,
I'm having exactly the same issue, I'm using local Mistral AI 7B.  When i inspect with Postman it seems to me that the last token has no content in it (to indicate that it's done) but somehow the code continues to pass in the onNext block which causes this IllegalArgumentException instead of entering the onComplete block. For the streaming code, I literally copied paste the one from the example.

**Comment by langchain4j** [comment]
@nhh1603 which version are you using? And which `StreamingChatLanguageModel `implementation? Thanks

**Comment by nhh1603** [comment]
![image](https://github.com/langchain4j/langchain4j/assets/69860012/8a0b7a4f-adc4-4f2c-a3a1-ab75e07ebd58)
![image](https://github.com/langchain4j/langchain4j/assets/69860012/13e3fb38-716b-4d4a-ab49-95a8b5bd6a84)

Every import of LangChain4j that I'm using is in version 0.30.0, and this is my implementation for the StreamingChatLanguageModel. The local AI Model is running through LM Studio, and it works perfectly with the non-streaming version. I also attach here more detail of the response that I have.

**Comment by langchain4j** [comment]
> this is my implementation for the StreamingChatLanguageModel

What do you mean by that? Are you using [MistralAiStreamingChatModel](https://github.com/langchain4j/langchain4j/blob/94b04721c2ff1b138e01724cf286114a1d1b7ef1/langchain4j-mistral-ai/src/main/java/dev/langchain4j/model/mistralai/MistralAiStreamingChatModel.java#L27) or completely re-implemented yourself?

I would recommend using `LocalAiStreamingChatModel` with LM Studio:

```java
    StreamingChatLanguageModel model = LocalAiStreamingChatModel.builder()
            .baseUrl("http://localhost:1234/v1")
            .modelName(...)
            .logRequests(true)
            .logResponses(true)
            .build();
```

**Comment by nhh1603** [comment]
I meant my code parameters of MistralAiStreamingChatModel, sorry for the confusion. Anyways, by switching to LocalAiStreamingChatModel the error is gone now. Thank you so much!
