### ISSUE TITLE
[FEATURE] Apache POI for CSV

### ISSUE THREAD

**Issue by rafgitdz** [langchain4j/langchain4j#671]
**Is your feature request related to a problem? Please describe.**
I have a need to parse CSV that implements DocumentParser

**Describe the solution you'd like**
ApachePoiDocumentParser implements DocumentParser
That include "CSV"

**Comment by hkuhn42** [comment]
As an alternate aproach, with support for Apache Tika, a lot of [formats ](https://tika.apache.org/3.0.0-BETA/formats.html) including xls, xlsx and csv could be supported with one module. POI is not the best choice for csv anyway.

**Comment by langchain4j** [comment]
Since we do not (yet?) have a way to represent tables in LangChain4j, csv will be anyway parsed into a `String`.
So you can use `TextDocumentParser` for this: `Document csvDocument = FileSystemDocumentLoader.loadDocument(".../file.csv", new TextDocumentParser())`

**Comment by langchain4j** [comment]
Both Apache POI and Tika are supported now.
