### ISSUE TITLE
[FEATURE] Monitor Token usage in Chains and AIServices

### ISSUE THREAD

**Issue by hkuhn42** [langchain4j/langchain4j#675]
**Is your feature request related to a problem? Please describe.**
I need to know how many tokens are used overall

**Describe the solution you'd like**
In extending the Chain interface and AIServices with a getTokenUsage method, token usage could be made available 

**Describe alternatives you've considered**
One could directly use ChatLanguageModel#generate(ChatMessage...) but the necessary wrapper code in effect duplicates the Chain / AiServices 

**Additional context**
I am currently using the following extended version of ConversationalRetrievalChain 

```java
public class ConversationalRetrievalChain implements Chain<String, String> {

   private final ChatLanguageModel chatLanguageModel;
    private final ChatMemory chatMemory;
    private final RetrievalAugmentor retrievalAugmentor;
    private TokenUsage               tokenUsage = new TokenUsage();
...
 @Override
    public String execute(String query) {

        UserMessage userMessage = UserMessage.from(query);
        Metadata metadata = Metadata.from(userMessage, chatMemory.id(), chatMemory.messages());
        userMessage = retrievalAugmentor.augment(userMessage, metadata);
        chatMemory.add(userMessage);

        Response<AiMessage> response = chatLanguageModel.generate(chatMemory.messages());

        tokenUsage = tokenUsage.add(response.tokenUsage());

        AiMessage aiMessage = response.content();
        chatMemory.add(aiMessage);
        return aiMessage.text();
    }
....
    public TokenUsage getTokenUsage() {
        return tokenUsage;
    }
}
```

**Comment by langchain4j** [comment]
HI @hkuhn42, did you try using AI Services? Here is an example on how to do RAG with AI Services: https://github.com/langchain4j/langchain4j-examples/blob/main/rag-examples/src/main/java/_2_naive/Naive_RAG_Example.java

You can define the return type of AI Service method as `Result<T>` and then easily access `TokenUsage`:

```java
interface Assistant {

    Result<String> chat(String userMessage);
}

Assistant assistant = AiServices.builder(Assistant.class)
                .chatLanguageModel(chatLanguageModel)
                .chatMemory(chatMemory)
                .contentRetriever(...)
                .build();

Result<String> result = assistant.chat(...);

String answer = result.content();
TokenUsage tokenUsage = result.tokenUsage();
```

**Comment by langchain4j** [comment]
Related: https://github.com/langchain4j/langchain4j/issues/199

**Comment by jrsperry** [comment]
This solution works for when an AiService returns a string, however how can i monitor the token usage for when an AiService returns a POJO or an enum, or anything else other than a string? There's obviously problems by having it return a Response<AiMessage> instead of a pojo as the pojo schema won't be injected to the prompt, and parsing has to be done manually. 

My use case is I'm looking to monitor and track usage amongst users, but I currently use the AiServices. Returning the token usage (optionally) from the AiServices would be ideal.

**Comment by langchain4j** [comment]
@jrsperry I have updated the example above as it was outdated (it used `Response<AiMessage>` instead of `Result<T>`).

You can access both POJO and `TokenUsage` when using `Result<T>` return type:

```java
interface Assistant {

    Result<Pojo> chat(String userMessage);
}
```

**Comment by jrsperry** [comment]
awesome. Just what I was looking for.
