### ISSUE TITLE
[FEATURE] ReRankingContentAggregator incl. MaxResult

### ISSUE THREAD

**Issue by andyflury** [langchain4j/langchain4j#680]
The new Advanced RAG provides the `ReRankingContentAggregator` which can re-rank results based on a `ScoringModel` (e.g. the `CohereScoringModel`).

this works great, the re-ranked list of results is definitely better (i.e. more relevant results are more likely to be at the top) than what the vector database returns

However I noticed that the scores Cohere assigns vary a lot, I have seen the largest scores within one batch at around 0.98, but then there are batches where the highest score is 0.03. So the `minScore` property turned out to be not so helpful. What would be great is to have a `maxResults` property as well similar to the one in the `EmbeddingStoreContentRetriever`

**Comment by andyflury** [comment]
Slightly related, the `EmbeddingMatch` returned by the `EmbeddingStore` contains both the `embeddingId` and the `score`. 

However the `EmbeddingStoreContentRetriever` returns `dev.langchain4j.rag.content.Content` which does neither contain `embeddingId` nor `score`. 

Reason for asking is that some might want to use the the new Advanced RAG functionality to retrieve relevant content (through `QueryTransformer`, `QueryRouter`, `ContentRetriever`, `ContentAggregator` & `ContentInjector`), for example to present as a list of related content to the user.

**Comment by langchain4j** [comment]
Good points. thanks!

**Comment by emredmrcan** [comment]
@langchain4j  It looks like this issue has been addressed with the PR for issue #1944. Should we close it? If I've missed anything, please let me know—I’d be happy to contribute further!

**Comment by langchain4j** [comment]
@emredmrcan AFAIU this issue consists of 2 issues:
- adding `maxResults` configuration, which was indeed implemented in https://github.com/langchain4j/langchain4j/pull/2043
- adding `score` and `embeddingId` to the `Content`, which you are implementing in https://github.com/langchain4j/langchain4j/pull/2222

Once https://github.com/langchain4j/langchain4j/pull/2222 is merged, we could close this issue, right?

**Comment by emredmrcan** [comment]
Yes, that's right!
