### ISSUE TITLE
[FEATURE] Add support for Neo4jGraph and GraphCypherQAChain

### ISSUE THREAD

**Issue by theawesomenayak** [langchain4j/langchain4j#685]
**Is your feature request related to a problem? Please describe**
The Python version of LangChain has support for Neo4j Graph database and ability to query the graph in natural language

**Describe the solution you'd like**
Having `Neo4jGraph` and `GraphCypherQAChain` similar to the ones available in the Python version of LangChain will allow us to do natural language queries to Neo4j - https://python.langchain.com/docs/use_cases/graph/graph_cypher_qa

**Describe alternatives you've considered**
I have currently built the functionality for my use but would like to contribute it back to the community. If this feature makes sense, I'll be glad to share a PR with the changes 🙂

**Additional context**
None

**Comment by theawesomenayak** [comment]
@langchain4j thoughts?

**Comment by langchain4j** [comment]
HI @theawesomenayak this sounds interesting!
But I would implement it not as a chain (old concept which we are deprecating), but as a custom `ContentRetriever` from [Advanced RAG](https://github.com/langchain4j/langchain4j/pull/538).
Something like `Neo4jContentRetriever` that will accept an instance of a `ChatLanguageModel` and Neo4j details about the graph in the constructor/builder and then when the `Query` comes, it will use that `ChatLanguageModel` to create a cypher query?

**Comment by langchain4j** [comment]
Duplicate of https://github.com/langchain4j/langchain4j/issues/158, please comment there

**Comment by theawesomenayak** [comment]
Fixed in #741
