### ISSUE TITLE
io.grpc.StatusRuntimeException: UNAVAILABLE: io exception，这咋办呢，各位大佬

### ISSUE THREAD

**Issue by 1863thuser** [langchain4j/langchain4j#69]
![image](https://github.com/langchain4j/langchain4j/assets/71204147/b9e067d0-2a0d-4921-9573-251735a4ea05)

**Comment by langchain4j** [comment]
Hi @1863thuser please make sure you specify the right environment, projectName and index in pinecone builder. At least projectName seems wrong. Pls check the comment on that line.

**Comment by langchain4j** [comment]
@1863thuser did you manage to fix the issue?

**Comment by 1863thuser** [comment]
> @1863thuser did you manage to fix the issue?
No, I use the free pinecone, environment configuration is not a problem really, but there is still a "java.net.SocketException:connection reset" this exception.
![image](https://github.com/langchain4j/langchain4j/assets/71204147/e3655b44-264b-4747-be8b-ab72ad39b278)
![image](https://github.com/langchain4j/langchain4j/assets/71204147/206503b0-ee6b-45d3-b357-416f7bfc6d23)

**Comment by 1863thuser** [comment]
> @1863thuser did you manage to fix the issue?

Resolved, the projectName in the configuration is too misleading. I think projectId will be better as the projectName, but this will not be a problem. Thank you for your reply.
![image](https://github.com/langchain4j/langchain4j/assets/71204147/5c088b71-5fbc-4137-98eb-639195165c60)
![image](https://github.com/langchain4j/langchain4j/assets/71204147/729d693f-0dc0-476c-96ad-424b0848771f)

**Comment by langchain4j** [comment]
@1863thuser agreed. I just copied the name they use in their java sdk. Will rename to project or projectId.
