### ISSUE TITLE
[BUG] @UserMessage does not work

### ISSUE THREAD

**Issue by langchain4j** [langchain4j/langchain4j#694]
`retrievalAugmentor` in `DefaultAiService` seems to not copy `name` from the original `UserMessage`

**Comment by OTR** [comment]
I was trying to reproduce this example:

https://github.com/langchain4j/langchain4j-examples/blob/10d96a93097e87189deff323a48971bde8d22ade/other-examples/src/main/java/OtherServiceExamples.java#L306

And I got an unexpected answer from the language model. According to the tutorial example it should reply with:

`Hello! Your name is Klaus. How can I assist you today?`

But I got:

`I'm sorry, but I am not able to see or know your name as I am an AI assistant and do not have access to personal information. How can I assist you today?
`

## Code sample to reproduce

https://gist.github.com/OTR/e742c38a8c9c77ac2b83d2fc81f37d10

## Logs

https://gist.github.com/OTR/a12a233308852c75f80aaa505f656925

**Comment by langchain4j** [comment]
Fixed by https://github.com/langchain4j/langchain4j/pull/740
