### ISSUE TITLE
[FEATURE] Streaming for Anthropic

### ISSUE THREAD

**Issue by jamfor999** [langchain4j/langchain4j#714]
**Is your feature request related to a problem? Please describe.**
At the moment, the only way to access Anthropic Claude using Langchain4J is via the AWS Bedrock library, but there doesn't seem to be a documented method to use Langchain4J with the API as hosted by Anthropic (for example, at https://api.anthropic.com/v1/messages) 

**Describe the solution you'd like**
A module for Anthropic Claude.

**Describe alternatives you've considered**
I have custom code that does this. However, other AI models all use Langchain4J so it's the odd one out, and ideally I'd like to use the same library across all of them for consistency (have some awkward conditional logic)

**Comment by langchain4j** [comment]
@kuraleta is adding dedicated Anthropic integration right now, will be released on monday

**Comment by jamfor999** [comment]
That's great news, searched for it but couldn't find info on it anywhere!

**Comment by jamfor999** [comment]
Hi @kuraleta and @langchain4j  thanks for your hard work on release 0.28.0, it works well, thanks for this!

Just wondering, are there any plans for a `StreamingLanguageChatModel` version of this?

I'm working around it by using a FakeStreamingLanguageChatModel in my app, and just pretending the overall result is the first and final token, which works as a stub, but a proper version where `.stream(true)` was enabled for the message would be really useful


(stub/fake StreamingChatLanguageModel in my Quarkus/Kotlin app, if anyone else is interested)
```
class FakeStreamingChatLanguageModel(
  val originalChatLanguageModel: ChatLanguageModel
) : StreamingChatLanguageModel, TokenCountEstimator {
  override fun generate(messages: MutableList<ChatMessage>?, handler: StreamingResponseHandler<AiMessage>?) {
    Uni.createFrom().item(messages)
      .emitOn(Infrastructure.getDefaultExecutor())
      .onItem().transform { msgs -> originalChatLanguageModel.generate(msgs) }
      .onItem().invoke { response ->
        handler?.onNext(response.content().text())
        handler?.onComplete(response)
      }
      .onFailure().invoke { failure ->
        handler?.onError(failure)
      }
      .subscribe().with(
        { },
        { handler?.onError(it) }
      )
  }

  // completely inaccurate, just returning the number of words as a placeholder
  override fun estimateTokenCount(messages: MutableList<ChatMessage>): Int {
    TODO()
  }
}
```

**Comment by kuraleta** [comment]
Hi @jamfor352, the next version will include support for the streaming chat model.

**Comment by jamfor999** [comment]
> Hi @jamfor352, the next version will include support for the streaming chat model.

Thanks!
Again, great work so far, really appreciated

**Comment by langchain4j** [comment]
Was implemented in https://github.com/langchain4j/langchain4j/pull/750
