### ISSUE TITLE
Allow @Description on Enum values

### ISSUE THREAD

**Issue by BlueJoneleth** [langchain4j/langchain4j#725]
Hi, 

I mentioned it in Discord. It would be handy if you could annotate enumvalues with a description so you could tell the AI when to use it. 

What currently work is this:    
` @Description("
            "Extract the following values based on {{it}}" +
            "Possible values and when to use them: " +
            "-ENUMVALUE1: description1," +
            "-ENUMVALUE2: description2")
    private List<ENUMTYPE> enumList;`

What would be handy is this: 

` public enum ENUMTYPE{

    @Description("description1")
    ENUMVALUE1,
    @Description("description2")
    ENUMVALU2`

**Comment by langchain4j** [comment]
@BlueJoneleth good idea, thanks! Are you going to open a PR? 🙏

**Comment by langchain4j** [comment]
Also need to make sure that `List<Enum>` works as well:
```java
enum Tag {
    RoomEnvironment, Catering, Timing
}

class Pojo {
    List<Tag> tags;
}
```

**Comment by PrimosK** [comment]
I am also interested in the following functionalities:

1. Annotating enums with @Description annotation
2. Properly supporting the return of a list of enums

**Side note:**

**a.)** While looking at the code I've noticed that `dev.langchain4j.model.output.EnumOutputParser#parse` is not called anywhere.

**b.)** [Sentiment_Extracting_AI_Service_Example](https://github.com/langchain4j/langchain4j-examples/blob/201e07d33c6361cc35d84a351fb96161609cd048/tutorials/src/main/java/_08_AIServiceExamples.java#L117) does not work well with the gpt-4o model. It returns enums enclosed in [ and ] which causes deserialization to fail. This issue occurred several times during my testing.

**Proposed Solution**

In addition to features (1. and 2.) my plan is to also fix both issues:

**Fix Issue (a)**: This seems like an easy fix.

**Fix Issue (b)**: This will require more detailed instructions, preferably with an example. Here is a suggested approach:

```
Please answer with valid JSON strictly according to this JSON Schema Definition:
|||
{
  "type": "string",
  "oneOf": [
    {
      "const": "SUNNY",
      "description": "Clear skies with no clouds or rain."
    },
    {
      "const": "CLOUDY",
      "description": "Mostly cloudy with minor chances of rain."
    },
    {
      "const": "RAIN",
      "description": "Precipitation with a majority of the time being rainy."
    }
  ]
}
|||

Example answer:
"A"
```

Such prompt works perfectly fine for me with `gpt-4o` + it should be easily re-used for returning list of enums.

If none is already looking into this then I can start with it tomorrow.

Any early feedback is appreciated.

**Comment by langchain4j** [comment]
@PrimosK sounds good!
Ragarding b) it is hard to say if this approach is the right one without testing multiple prompts with multiple models. I could imagine removing [ and ] from the response could be viable option as well.

Please feel free to implement this. It would be great if you could make these (4, I guess?) changes in separate PRs, it will be much easier and faster to review and approve them 🙏

**Comment by PrimosK** [comment]
Yes. Makes perfect sense to create 4 separate PRs.

Are there maybe any existing integration tests covering AI services returning 'enum' I could test this with?

**Comment by langchain4j** [comment]
@PrimosK please check `AiServicesIT.test_extract_enum`

**Comment by PrimosK** [comment]
When approximatelly can I expect feedback on this PR (draft)?

No hurry actually - I am asking just so I can better organize my work.

**Comment by langchain4j** [comment]
@PrimosK most probably on Friday or next week, I am busy with the release today and tomorrow

**Comment by PrimosK** [comment]
Short update. I've just completed with PR 4 / 4. 

This is how prompt will look for annotated enums when returning a list:
```
Please analyse the following review: |||Our stay at hotel was a mixed experience. The location was perfect, just a stone's throw away from the beach, which made our daily outings very convenient. The rooms were spacious and well-decorated, providing a comfortable and pleasant environment. However, we encountered several issues during our stay. The air conditioning in our room was not functioning properly, making the nights quite uncomfortable. Additionally, the room service was slow, and we had to call multiple times to get extra towels. Despite the friendly staff and enjoyable breakfast buffet, these issues significantly impacted our stay.|||
You must answer strictly with zero or more of these enums on a separate line:
MAINTENANCE_ISSUE - The feedback mentions issues with the hotel's maintenance, such as air conditioning and plumbing problems
SERVICE_ISSUE - The feedback mentions issues with the service provided, such as slow room service
COMFORT_ISSUE - The feedback mentions issues affecting the comfort of the stay, such as uncomfortable room conditions
FACILITY_ISSUE - The feedback mentions issues with hotel facilities, such as problems with the bathroom plumbing
CLEANLINESS_ISSUE - The feedback mentions issues with the cleanliness of the hotel, such as dust and stains
CONNECTIVITY_ISSUE - The feedback mentions issues with internet connectivity, such as unreliable Wi-Fi
CHECK_IN_ISSUE - The feedback mentions issues with the check-in process, such as it being tedious and time-consuming
OVERALL_EXPERIENCE_ISSUE - The feedback mentions a general dissatisfaction with the overall hotel experience due to multiple issues
```
... and response:
```
MAINTENANCE_ISSUE
SERVICE_ISSUE
COMFORT_ISSUE
OVERALL_EXPERIENCE_ISSUE
```

I've tested it with `gpt-3.5-turbo` and it seems to be working reliably.

**Comment by PrimosK** [comment]
@langchain4j, could you please assign this Issue to me... Just so to make it clear it's being worked on.

**Comment by PrimosK** [comment]
I suppose this warrants an update of [documentation](https://docs.langchain4j.dev/tutorials/ai-services#enum-and-boolean-as-return-types)...

**Comment by langchain4j** [comment]
@PrimosK right, totally forgot about it.. Could you open a PR please?

**Comment by PrimosK** [comment]
PR opened...

Note that I've also added additional example (PR):
https://github.com/langchain4j/langchain4j-examples/pull/97

**Comment by cardsharp** [comment]
This is still erroring occasionally, though not always on GPT-4o. I get this:

java.lang.RuntimeException: Unknown enum value: FRUSTRATION - Anger

In my case there was a comma in the string right after "Anger". The original code that triggers it:

@Description("Fear, anxiety, or emotional distress related to perceived danger")
    FEAR(1.0),
    
    I think the problem is in the prompt, not in the response parsing.
    
When I remove all the commas from the @Description annotation the problem goes away

**Comment by langchain4j** [comment]
@cardsharp the return type of you AI SErvice is enum? Or is it a POJO with enum inside?

**Comment by cardsharp** [comment]
It's currently an enum in an AI service (below), I haven't duplicated this in a POJO scenario:

    @SystemMessage("Act as an expert in hospice and home health")
    private interface AiTopicTypeClassifier {
        @UserMessage("Extract a list of topic types found in {{it}}")
        List<TopicType> classify(String text);
    }

**Comment by cardsharp** [comment]
As an additional note, I replaced all the commas in the @Description annotation with just "or" and it seems to have eliminated the issue.

Like, before: "Find this, that, another thing, or one more thing" vs. "Find this or that or another thing or one more thing"

**Comment by langchain4j** [comment]
@cardsharp what LLM are you using?

Can you please provide code for `TopicType` (just an exerpt will be enough)?

**Comment by cardsharp** [comment]
gpt-4o-mini

Current version is now:
```java
public enum TopicType {
    @Description("concerns or compliments or experiences related to customer service including staff responsiveness communication professionalism or care coordination")
    CUSTOMER_SERVICE,

    @Description("distractions from hospice or expense including emergency services or desire to go back to a prior doctor or mention of medical services outside hospice or lack of understanding about hospice")
    LEVEL_OF_CARE,

    @Description("signs of behavioral safety issues related to patient care including threats or risks related to signs of violence or abuse or derogatory language.")
    BEHAVIORAL_SAFETY,

    @Description("specific devices or tools or supplies used in hospice patient care such as oxygen or wheelchair or pain management device or bed including references to equipment delivery or setup or functionality.")
    MEDICAL_EQUIPMENT,

    @Description("mentions of interactions with others including family involvement or social support or companionship provided by caregivers")
    SOCIAL,

    @Description("symptoms of complicated grief including prolonged or intense emotional distress or unresolved grief or difficulty coping with loss")
    COMPLICATED_GRIEF
}
```

**Comment by cardsharp** [comment]
BTW, it also fails if the response from GPT is "", fails with

Unknown enum value: 
java.lang.RuntimeException: Unknown enum value: 
	at dev.langchain4j.service.output.EnumOutputParser.parse(EnumOutputParser.java:28)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at dev.langchain4j.service.output.EnumListOutputParser.parse(EnumListOutputParser.java:18)
	at dev.langchain4j.service.output.EnumListOutputParser.parse(EnumListOutputParser.java:8)
	at dev.langchain4j.service.output.ServiceOutputParser.parse(ServiceOutputParser.java:66)
	at dev.langchain4j.service.DefaultAiServices$1.invoke(DefaultAiServices.java:275)
	
	I think the list parser doesn't like a blank result

**Comment by cardsharp** [comment]
The AI service is:
```
   @SystemMessage("Act as an expert in hospice and home health")
    private interface AiTopicTypeClassifier {
        @UserMessage("Extract a list of topics found in {{it}}")
        List<TopicType> classify(String text);
    }
```

**Comment by cardsharp** [comment]
And if I comment out the @Description annotations, it doesn't error but also doesn't allow me to specify the enum descriptions:

`public enum TopicType {
    //@Description("concerns or compliments or experiences related to customer service including staff responsiveness communication professionalism or care coordination")
    CUSTOMER_SERVICE,

    //@Description("distractions from hospice or expense including emergency services or desire to go back to a prior doctor or mention of medical services outside hospice or lack of understanding about hospice")
    LEVEL_OF_CARE,

    //@Description("signs of behavioral safety issues related to patient care including threats or risks related to signs of violence or abuse or derogatory language.")
    BEHAVIORAL_SAFETY,

    //@Description("specific devices or tools or supplies used in hospice patient care such as oxygen or wheelchair or pain management device or bed including references to equipment delivery or setup or functionality.")
    MEDICAL_EQUIPMENT,

    //@Description("mentions of interactions with others including family involvement or social support or companionship provided by caregivers")
    SOCIAL,

    //@Description("symptoms of complicated grief including prolonged or intense emotional distress or unresolved grief or difficulty coping with loss")
    COMPLICATED_GRIEF
}`

**Comment by cardsharp** [comment]
Ok, I seemed to have resolved it. Here's how: I removed the words "Extract a list of..." and replaced it with "Analyze the topics found in..." Seems like something about the verbiage throws enum @Description handling in GPT-4o-mini

Doesn't work:
```
  private interface AiTopicTypeClassifier {
        @SystemMessage("Act as an expert in hospice and home health")
        @UserMessage("**Extract a list of topics** found in {{it}}")
        List<TopicType> classify(String text);
    }
```

Does work:
```
  private interface AiTopicTypeClassifier {
        @SystemMessage("Act as an expert in hospice and home health")
        @UserMessage("**Analyze topics** found in {{it}}")
        List<TopicType> classify(String text);
    }
```

**Comment by langchain4j** [comment]
@cardsharp I feel like we can improve this a lot, using [Structured Outputs](https://github.com/langchain4j/langchain4j/pull/1590).

You could wrap a `List<TopicType>` into a POJO and enable structured outputs:
```java
OpenAiChatModel.builder()
    ...
    .responseFormat("json_schema")
    .strictJsonSchema(true)
    .build();

class TopicTypes {
    @Description(...)
    List<TopicType> topicTypes;
}

private interface AiTopicTypeClassifier {
        @SystemMessage("Act as an expert in hospice and home health")
        @UserMessage("**Analyze topics** found in {{it}}")
        TopicTypes classify(String text);
    }
```

**Comment by simonhype** [comment]
Hi, I wanted to use `@Description` on enums and saw that the documentation on this has been changed again in https://github.com/langchain4j/langchain4j/commit/143a5dc2882cb8e98abe8d4091a19067feeb09bc
It now claims that `@Description` doesn't work on enums, however the code for this in https://github.com/langchain4j/langchain4j/blob/main/langchain4j/src/main/java/dev/langchain4j/service/output/EnumOutputParser.java still seems to be there. Can anyone clarify?

**Comment by simonhype** [comment]
In my testing it seems that Lists of enums don't work as return types (anymore?) either, even though the documentation on structured outputs still claims it does. I'm using GPT-4o and JSON Schema, but the returned list cannot be parsed into a list of my enum objects.
