### ISSUE TITLE
[BUG] NullPointerException when using AIServices with LocalAI

### ISSUE THREAD

**Issue by quachc** [langchain4j/langchain4j#732]
**Describe the bug**
`NullPointerException` when using `AIServices` with LocalAI

**Log and Stack trace**
I don't have the stacktrace here right now, but it occurs on these lines:
https://github.com/langchain4j/langchain4j/blob/6c49573dc537b206531b9ef97fff0245fff638d9/langchain4j/src/main/java/dev/langchain4j/service/DefaultAiServices.java#L166
https://github.com/langchain4j/langchain4j/blob/6c49573dc537b206531b9ef97fff0245fff638d9/langchain4j/src/main/java/dev/langchain4j/service/AiServiceStreamingResponseHandler.java#L85
https://github.com/langchain4j/langchain4j/blob/6c49573dc537b206531b9ef97fff0245fff638d9/langchain4j/src/main/java/dev/langchain4j/service/AiServiceStreamingResponseHandler.java#L92

**To Reproduce**
Use `AIServices` to chat with a LocalAI model.

**Expected behavior**
Chat response from `AIServices` assistant.

**Please complete the following information:**
- LangChain4j version: 0.27.1
- Java version: 17
- Spring Boot version (if applicable): 3.2.2 (not using langchain4j starter)

**Additional context**
It seems that `Response.tokenUsage` is always `null` when using LocalAI.
https://github.com/langchain4j/langchain4j/blob/6c49573dc537b206531b9ef97fff0245fff638d9/langchain4j-local-ai/src/main/java/dev/langchain4j/model/localai/LocalAiChatModel.java#L105
https://github.com/langchain4j/langchain4j/blob/6c49573dc537b206531b9ef97fff0245fff638d9/langchain4j-open-ai/src/main/java/dev/langchain4j/model/openai/OpenAiStreamingResponseBuilder.java#L175

I've been able to workaround the issue by providing a custom `LocalAiChatModelBuilderFactory` and ignore `null` from `Response.tokenUsage`, but that might not be the best solution.
I noticed that the JSON response from LocalAI does include token usage (set to 0), it's currently ignored by Langchain4J and `Response.tokenUsage` is just set to `null`.
LocaLAI might add something like quotas in the future, so it might be a better solution to just extract token usage from the response..?

**Comment by langchain4j** [comment]
@quachc thanks a lot for reporting!

**Comment by vikasrajputin** [comment]
Hello @langchain4j - is this up for grab? Would like to work on this

**Comment by langchain4j** [comment]
@vikasrajputin it looks like it has been fixed already: https://github.com/langchain4j/langchain4j/pull/1119

Could you please check? 🙏
