### ISSUE TITLE
[FEATURE] Add missing foundational Bedrock models

### ISSUE THREAD

**Issue by bottlerocketjonny** [langchain4j/langchain4j#734]
**Is your feature request related to a problem? Please describe.**
At the moment we are missing the following Bedrock foundational models:
- Cohere Claude 3 Sonnet
- Meta Llama 2 Chat 13B/70B
- Mistral AI 7B and Mixtral 8x7B

**Describe the solution you'd like**
Have these models added in to Langchain4J. I'm happy to do the work and submit a PR :)

**Describe alternatives you've considered**
Using the Bedrock API directly to access these models.

**Comment by langchain4j** [comment]
@bottlerocketjonny sure, that would be awesome, go ahead!
BTW don't BedrockAnthropicChatModel support Claude 3?

**Comment by bottlerocketjonny** [comment]
> @bottlerocketjonny sure, that would be awesome, go ahead!
> BTW don't BedrockAnthropicChatModel support Claude 3?

Cool, thanks! I'll get right to work.

Hmm from what I can see it looks like just Claude instant, v1 and v2 are supported at the mo. The new models were only announced last week: https://aws.amazon.com/blogs/aws/anthropics-claude-3-sonnet-foundation-model-is-now-available-in-amazon-bedrock/

**Comment by langchain4j** [comment]
@bottlerocketjonny awesome! Since you are already at it, it would be great to allow defining models not only using an enums, but also as strings, so when new models come out next time, users will be able to use them right away, without waiting for us to update the enums.

**Comment by bottlerocketjonny** [comment]
> @bottlerocketjonny awesome! Since you are already at it, it would be great to allow defining models not only using an enums, but also as strings, so when new models come out next time, users will be able to use them right away, without waiting for us to update the enums.

Yeah sure thing, that's a great idea!

**Comment by langchain4j** [comment]
Has been implemented in https://github.com/langchain4j/langchain4j/pull/773
