### ISSUE TITLE
[BUG?] Many clients do not work with Native Image services

### ISSUE THREAD

**Issue by jamfor999** [langchain4j/langchain4j#739]
**Describe the bug**
Some clients, for example the new Anthropic client, the Mistral clients, etc work fine when running in a standard JVM mode, but when a utilising service runs as a GraalVM native image, it no longer works. **As far as I can see, it is due to the usage of Retrofit, [which does not support Native Images](https://github.com/square/retrofit/issues/3188)**. This does _not_ occur with other clients that do not use Retrofit, such as the OpenAI client which uses OkHttp. The error messages indicate that the issue is with fields not being serialized properly when sent to the consuming service.

**Log and Stack trace**
When not adding any `proxy-config.json`/`reflection-config.json`:
```
Proxy class defined by interfaces [interface dev.langchain4j.model.anthropic.AnthropicApi] not found. Generating proxy classes at runtime is not supported. Proxy classes need to be defined at image build time by specifying the list of interfaces that they implement. To define proxy classes use -H:DynamicProxyConfigurationFiles=<comma-separated-config-files> and -H:DynamicProxyConfigurationResources=<comma-separated-config-resources> options.
```

From the new Anthropic client, this still fails as the payload isn't serialized properly, after adding the relevant `proxy-config.json` and `reflection-config.json` 
```
024-03-12 15:55:29,569 INFO  [com.jam.aim.dom.LLMPort] (vert.x-eventloop-thread-5) Processing 1 messages from auth0|65e76490858d1fb60b75f0ab
2024-03-12 15:55:29,852 WARN  [dev.lan.int.RetryUtils] (vert.x-eventloop-thread-5) Exception was thrown on attempt 1 of 3: java.lang.RuntimeException: status code: 400; body: {"type":"error","error":{"type":"invalid_request_error","message":"messages: Field required"}}
        at dev.langchain4j.model.anthropic.AnthropicClient.toException(AnthropicClient.java:85)
        at dev.langchain4j.model.anthropic.AnthropicClient.createMessage(AnthropicClient.java:74)
        at dev.langchain4j.model.anthropic.AnthropicChatModel.lambda$generate$0(AnthropicChatModel.java:130)
```

^ This does _not_ happen when running as a standard Java application, only when compiled as a Native Image.

**To Reproduce**
- Use Anthropic, Mistral, Ollama etc client
- Compile application to Native Image
- Run Native Image and invoke chat message

**Expected behavior**
Clients work fine regardless of whether the service uses Native Image or not.

**Please complete the following information:**
- LangChain4j version: e.g. 0.28.0
- Java version: e.g. 17
- Quarkus Platform version: 3.8.2

**Additional context**
I suspect this is due to the usage of Retrofit to create clients, which does not support Native Images, unlike OkHttp which does.

**Comment by jamfor999** [comment]
Closing this as it seems like this is known fromt he main README - apologies for missing that

**Comment by langchain4j** [comment]
Hi @jamfor352, thanks for reporting! I think it is an oversight. OpenAI client (openai4j) also uses retrofit, but I have explicitly added config files for graal, thus it works. We should do the same for each module explicitly. Do you know if this can be automated somehow? And tested as both jvm and native images.

**Comment by jamfor999** [comment]
Hi @langchain4j , hmm I was looking at the openai client and it seemed to use okhttp... I'll have to give it another look, maybe I was looking at the wrong thing. 
I'm sure it can be automated somehow to make lives for developers easier and ideally not have to worry about this kind of thing, I know Graal has a tracing agent for example that autogenerates config/reflect files for you on a basic boot.

**Comment by langchain4j** [comment]
We use retrofit in openai4j for sync requests: https://github.com/ai-for-java/openai4j/blob/main/src/main/java/dev/ai4j/openai4j/OpenAiApi.java

And okhttp/okhttp-sse to handle streaming: https://github.com/ai-for-java/openai4j/blob/d6e2a3c7fef6dea63503b495b289d1f05782ce2b/src/main/java/dev/ai4j/openai4j/StreamingRequestExecutor.java#L144

**Comment by jamfor999** [comment]
> We use retrofit in openai4j for sync requests: https://github.com/ai-for-java/openai4j/blob/main/src/main/java/dev/ai4j/openai4j/OpenAiApi.java
> 
> 
> 
> And okhttp/okhttp-sse to handle streaming: https://github.com/ai-for-java/openai4j/blob/d6e2a3c7fef6dea63503b495b289d1f05782ce2b/src/main/java/dev/ai4j/openai4j/StreamingRequestExecutor.java#L144

Ah, that explains it - I use streaming requests most of the time, I guess that's the code I was looking at. Makes sense why streaming requests works if support was specifically added!
