### ISSUE TITLE
[FEATURE] Get tool execution output from generation calls/Utility to run tool execution request

### ISSUE THREAD

**Issue by davisuga** [langchain4j/langchain4j#755]
I would like to only run the tool and get the results and not generate a text response with it. The goal is to be able to use a different model for function calling. Some easy utility to execute a `ToolExecutionRequest` with a given "toolbox" class would be enough.

**Comment by langchain4j** [comment]
Duplicate of https://github.com/langchain4j/langchain4j/issues/124, please track it there
