### ISSUE TITLE
Empty content for an AI response leads to IllegalArgumentException

### ISSUE THREAD

**Issue by wolfc** [langchain4j/langchain4j#756]
https://github.com/langchain4j/langchain4j/blob/91db3d354ae00e6989efc9add182454738845f33/langchain4j-core/src/main/java/dev/langchain4j/data/message/AiMessage.java#L30

The AI can send back a response which is effectively empty.

```
[2024-03-14 18:10:58.886] [INFO] [LM STUDIO SERVER] Generated prediction: {
  "id": "chatcmpl-8vki6awl83gowbpiwr0ot",
  "object": "chat.completion",
  "created": 1710436258,
  "model": "lm-studio\\models\\ibm\\merlinite-7b-GGUF\\merlinite-7b-Q4_K_M.gguf",
  "choices": [
    {
      "index": 0,
      "message": {
        "role": "assistant",
        "content": ""
      },
      "finish_reason": "stop"
    }
  ],
  "usage": {
    "prompt_tokens": 7,
    "completion_tokens": 0,
    "total_tokens": 7
  }
}
```

**Comment by langchain4j** [comment]
@wolfc do you know why it is happening? In my understanding it is a bug in the LLM inference engine.

**Comment by seeseemelk** [comment]
As far as I know, there is nothing stopping an LLM from immediately outputting a stop token.

There is another problem with this bug that I ran into: when it's triggered from a streamingChat request, the exception does get logged, but there is no way to catch or detect it in your application.

The dev.langchain4j.model.ollama.OllamaClient#streamingChat#onFailure callback only gets executed for errors in the HTTP request itself, not for exceptions thrown from the onResponse.

**Comment by langchain4j** [comment]
@seeseemelk good point regarding stop token. Here is a fix: https://github.com/langchain4j/langchain4j/pull/782

**Comment by langchain4j** [comment]
> The dev.langchain4j.model.ollama.OllamaClient#streamingChat#onFailure callback only gets executed for errors in the HTTP request itself, not for exceptions thrown from the onResponse.

Good point, added a fix in scope of https://github.com/langchain4j/langchain4j/pull/782
