### ISSUE TITLE
[BUG] Failures in Vertex AI Gemini calls due to unsupported @SystemMessage

### ISSUE THREAD

**Issue by ddobrin** [langchain4j/langchain4j#757]
`@UserMessage` is supported and can be used with VertexAiGeminiChatModel
`@SystemMessage` is not supported for Vertex.

Behaviour: call fails and indicates the reason for the failure as SystemMessage not being supported in Vertex.

Suggestion:
As all `ChatMessage` implementation will be send to the model via Vertex, suggest converting, transparent to the developer, the @SystemMessage to a @UserMessage. 

Future:
Code will remain unchanged for a developer if Vertex adds support for @SystemMessage and Langchain4J updates the codebase.

- LangChain4j version: 0.28.0
- Java version: 21
- Spring Boot version: 3.2.3

**Comment by langchain4j** [comment]
Hi @ddobrin, system and user messages are very different in nature. This exception is thrown to let the developer aware that system messages are not supported by this model, so he should avoid using them. I would avoid silently converting one to another.

**Comment by ddobrin** [comment]
Hello, thank you for the quick reply. The distinction between the 2 is understood, certainly.

The rationale for opening this issue comes down to the fact that developers would have to change their code when testing with different models, or when building tests using Testcontainers and testing different models, which could lead to a diminished UX

**Comment by langchain4j** [comment]
@ddobrin good point!

**Comment by langchain4j** [comment]
cc @glaforge I plan to fix this today
