### ISSUE TITLE
[FEATURE] Add implementation of ann(Approximate kNN) in ElasticsearchEmbeddingStore

### ISSUE THREAD

**Issue by CharleyXu** [langchain4j/langchain4j#759]
**Is your feature request related to a problem? Please describe.**

The search method in ElasticsearchEmbeddingStore is implemented using Script Score and cosineSimilarity. With this approach, a script_score query must scan each matching document to compute the vector function, which can result in slow search speeds.

**Describe the solution you'd like**
Add implementation of ann([Approximate kNN](https://www.elastic.co/guide/en/elasticsearch/reference/current/knn-search.html#approximate-knn)).
**Describe alternatives you've considered**
I'll make it happen

**Comment by CharleyXu** [comment]
PR #760

**Comment by langchain4j** [comment]
This was implemented in https://github.com/langchain4j/langchain4j/pull/712
