### ISSUE TITLE
[FEATURE] Integrated multilingual embedding model (for exemple multilingual-e5-large)

### ISSUE THREAD

**Issue by Adel-DAH** [langchain4j/langchain4j#777]
The already existing integrated embedding models are very fast and above all very practical, but I am currently developing an application which the embedding model must include French for greater relevance.

Currently I use all-minilm-l6-v2 (which lacks relevance when it comes to the French language), I tried a paid solution and also deploying an embedding model on a VM, but the costs and latency will increase, and I really need the solution to be as fast as possible.

**Comment by langchain4j** [comment]
Hi @Adel-DAH, you can download `multilingual-e5-large` manually and use it with `OnnxEmbeddingModel`, here is an [example](https://github.com/langchain4j/langchain4j-examples/blob/08a997f96d82a730b4439b04fc2ae19080a9d981/other-examples/src/main/java/embedding/model/InProcessEmbeddingModelExamples.java#L44).

This model is too big to be packaged into the repository and then released to maven...

**Comment by langchain4j** [comment]
Feel free to reopen if needed!

**Comment by Adel-DAH** [comment]
Thank you @langchain4j
