### ISSUE TITLE
[BUG] StructuredOutput is broken in 0.28.0

### ISSUE THREAD

**Issue by theawesomenayak** [langchain4j/langchain4j#778]
Please provide as much details as possible, this will help us to deliver a fix as soon as possible.
Thank you!

**Describe the bug**
StructuredOutput is broken in 0.28.0. This is caused by PR #625 

The JSON output prompt is now 
```
"\nYou must answer strictly in the following JSON format: dev.langchain4j.service.ServiceOutputParserTest$PersonWithParents: {\n" +
                        "\"firstName\": (type: string),\n" +
                        "\"lastName\": (type: string),\n" +
                        "\"parents\": (type: array of dev.langchain4j.service.ServiceOutputParserTest$PersonWithParents),\n" +
                        "}");
```
This is producing a JSON object like
```
dev.langchain4j.service.ServiceOutputParserTest$PersonWithParents: {\n" +
                        "\"firstName\": (type: string),\n" +
                        "\"lastName\": (type: string),\n" +
                        "\"parents\": (type: array of dev.langchain4j.service.ServiceOutputParserTest$PersonWithParents),\n" +
                        "}");
```

This is not a valid JSON and cannot be parsed further.

**Log and Stack trace**
Please provide a log and a stack trace (with exception), if applicable.

**To Reproduce**
Run any structured output with a POJO

**Expected behavior**
The JSON output should be
```
 {\n" +
                        "\"firstName\": (type: string),\n" +
                        "\"lastName\": (type: string),\n" +
                        "\"parents\": (type: array of dev.langchain4j.service.ServiceOutputParserTest$PersonWithParents),\n" +
                        "}");
```

**Please complete the following information:**
- LangChain4j version: e.g. 0.28.0
- Java version: e.g. 11
- Spring Boot version (if applicable): e.g. 2.7.14

**Additional context**

**Comment by langchain4j** [comment]
Hi @theawesomenayak thanks a lot for reporting the bug!
Which model are you using? can you please provide more code to reproduce?
Thank you!

**Comment by theawesomenayak** [comment]
I was using gpt-3.5-turbo. This seems to be working fine now with Ollama models. Let me debug this to understand why its happening only with a specific model. Closing this bug till I get back with more info.
