### ISSUE TITLE
[FEATURE] Dynamic system message/prompt in AI Services

### ISSUE THREAD

**Issue by 7010G** [langchain4j/langchain4j#785]
Because some model tools have poor invocation ability, we are trying to solve this problem through prompt word engineering. 
  We plan to do semantic matching through the vector library to select tools, and put the tool list returned by the vector library into the system content. In this way, the effect is good when selecting multiple tools, and the tool expansion is also relatively convenient.
  **For example:**
**first step:** "messages": [
    {
      "role": "system",
      "content": "Follow the user\u0027s instructions carefully. Respond using markdown."
    },
    {
      "role": "user",
      "content": "Testing the dialog"
    },
    {
      "role": "assistant",
      "content": "\n I\u0027m sorry, I\u0027m not sure what you mean by \"testing the dialog\". Can you please provide more information or clarify your question?"
    },
    {
      "role": "user",
      "content": "what can you do"
    }
  ]
**User questions change system content after vector matching.**
"messages": [
    {
      "role": "system",
      "content": "You are an intelligent assistant to help users book flights, check the weather, arrange travel and more"
    },
    {
      "role": "user",
      "content": "Testing the dialog"
    },
    {
      "role": "assistant",
      "content": "\n I\u0027m sorry, I\u0027m not sure what you mean by \"testing the dialog\". Can you please provide more information or clarify your question?"
    },
    {
      "role": "user",
      "content": "what can you do"
    },{
      "role": "assistant",
      "content": "I can help you book flights, check the weather, make travel arrangements and so on."
    }
  ]

**Comment by 7010G** [comment]
In addition to being able to modify the system content content, I also hope that there can be a program that can modify the content of the historical conversation during the conversation, and at present, only model.generate() can achieve this operation, but after I implement AiServices, such an operation seems to be difficult to complete. The purpose of this is to freely insert the dialogue content of the assistant or function, so that the final output of the LLM can be manually intervened, after all, not all models are GPT4, and the ability is relatively weak

**Comment by LizeRaes** [comment]
Interesting points @7010G. A couple of thoughts:
- is it an option to start a new dedicated service when you want to change the SystemMessage or conversation memory? Optionally you can reuse parts of the former ChatMemory, it has some nice methods like memory.messages() that you can use for building up the next ChatMemory
- I'm wondering if you can solve part of your problem by updating your memory using the methods .clear() and .add() when you want to switch history. Except if it gets dynamically decided by the LLM when the switch needs to be made and what needs to be altered. Something I didn't test yet, but might work, is to make an own implementation of ChatMemory and define some tools to upgrade or change is, and provide these tools + instructions to the LLM itself?
- I think it makes sense to have a method on the AiService to update the SystemMessage to cover use cases like: 
   - change SystemMessage language based on language user is using (if the SystemMessage stays English and the user uses another language, the output language becomes inpredicatble)
   - change SystemMessage to describe something about the user so the LLM adapts better to their personality / mood / insterests / ...

**Comment by 7010G** [comment]
As for the third point, in fact, the significance of modifying SystemMessage is not only that, here we can define some relatively real-time updated dialog global variables, such as current time, current location information, etc., and this information can be added as the conversation progresses.

**Comment by 7010G** [comment]
> 有趣的点.几点想法：
> 
> * 当您想要更改 SystemMessage 或会话内存时，是否可以选择启动新的专用服务？或者，您可以重用以前的 ChatMemory 的某些部分，它有一些不错的方法，例如 memory.messages（），您可以使用它们来构建下一个 ChatMemory
> * 我想知道当您想切换历史记录时，您是否可以通过使用 .clear（） 和 .add（） 方法更新内存来解决部分问题。除非它是由 LLM 动态决定何时需要进行切换以及需要更改的内容。我还没有测试过，但可能会起作用的东西是制作自己的 ChatMemory 实现并定义一些要升级或更改的工具，并将这些工具 + 指令提供给 LLM 本身？
> * 我认为在 AiService 上有一个方法来更新 SystemMessage 以涵盖以下用例是有意义的：
>   * 根据用户使用的语言更改 SystemMessage 语言（如果 SystemMessage 保持英语，并且用户使用另一种语言，则输出语言将变得不可预测）
>   * 更改 SystemMessage 以描述有关用户的某些信息，以便 LLM 更好地适应他们的个性/情绪/内斯特/......

Regarding the first and second points, my description is not accurate enough, I don't need to create a new ChatMemory from my side, I just need to be able to use the role of function and assistant in the session to insert the execution result of the tool or the corresponding inference step, now I can only use the user role to insert. 

As for the third point, in fact, the significance of modifying SystemMessage is not only that, here we can define some relatively real-time updated dialog global variables, such as the current time, current location information, etc., and these information can be continuously added with the conversation process, so that the model can understand some key information at any time.

**Comment by langchain4j** [comment]
Available in 0.30.0: https://github.com/langchain4j/langchain4j/pull/862
