### ISSUE TITLE
Guardrails support

### ISSUE THREAD

**Issue by radoslavdodek** [langchain4j/langchain4j#80]
**Is your feature request related to a problem? Please describe.**
It would be great if langchain4j supported some kind of guardrails functionality. See Guardrails AI for example (https://shreyar.github.io/guardrails/).

**Comment by langchain4j** [comment]
Hi @radosdesign, could you please provide more details? Guardrails has a lot of features, which one(s) are you interested in? Thanks

**Comment by langchain4j** [comment]
@radosdesign closing this issue because no response. Feel free to reopen.
