### ISSUE TITLE
[FEATURE] Allow to define system prompt for AIServices from an external source (like a DB)

### ISSUE THREAD

**Issue by BlueJoneleth** [langchain4j/langchain4j#805]
AIServices are great but their main drawback is that annotations are immutable. It would be handy to have a way to use them while passing on your prompt from an external source like a DB. 

This would for example allow you to use a simple UI to edit your prompts and maybe other params. 
One possible way is to be able to do something like this : 
String method(@SystemMessage String systemMessage, 
@UserMessage String userMessage, 
@V("param") String param, 
@V("param2") String param2);

It's currently possible to pass a userMessage like this but unfortunately, it doesn't inject the params if you do it that way.

**Comment by BlueJoneleth** [comment]
This could also be expanded to other params like the temperature you want for a method or which model. 

Here's a simple mongo collection I made as an example of what could be used for config. 

`@Document
public class PromptEntity {


    @Id
    private String name;

    private String systemMessage;

    private String userMessage;

    private String provider;

    private String llm;

    private double temperature;`

**Comment by langchain4j** [comment]
Similar to https://github.com/langchain4j/langchain4j/issues/785
Is being addressed in https://github.com/langchain4j/langchain4j/pull/862

**Comment by langchain4j** [comment]
@BlueJoneleth would it be more convenient to define system message provider during creation of AI Services?

```java
AiServices.builder(Assistant.class)
                .chatLanguageModel(chatLanguageModel)
                .systemMessageProvider(chatMemoryId -> "You are a helpful assistant") // different users/conversations can have different system messages
                .build();
```

Or via `@SystemMessage` annotated parameter?
```java
String chat(@SystemMessage String systemMessage, @UserMessage String userMessage, @V("param") String param);
```

As for the user message, changing `AiServices` to inject parameters into `@UserMessage String userMessage` should be easy to do.

**Comment by BlueJoneleth** [comment]
I think it's indeed interesting you can provide a system message on the service level that's used for all methods by default. And if you provide one on a specific method, it overwrites the one specified in the service.

**Comment by langchain4j** [comment]
Thanks, good point. Do you have multiple methods in you AI service? Could you please share?

**Comment by BlueJoneleth** [comment]
`public interface AIToolkit {

    @SystemMessage("You are a professional translator into {{language}}")
    @UserMessage("Translate the following text: {{text}}")
    String translate(@V("language") String language, @V("text") String text);

    @SystemMessage("You are a professional assistant to a news agency. Your task consist in assisting journalists in their daily work.")
    @UserMessage("Expand the article below. Rewrite the article by increasing the total length by {{percent}}%." +
            "The rewrite should be in the same language as the original article." +
            "Stick to the facts presented in the original text, do not invent new ones."+
            "Article: {{text}}")
    String expand(@V("percent") int percent, @V("text") String text);

    @SystemMessage("You are a professional assistant to a news agency. Your task consist in assisting journalists in their daily work.")
    @UserMessage("Shorten the article below. Rewrite the article by decreasing the total length by {{percent}}%." +
            "The rewrite should be in the same language as the original article." +
            "Article: {{text}}")
    String shorten(@V("percent") int percent, @V("text") String text);

    @SystemMessage("You are a professional assistant to a news agency. Your task consist in assisting journalists in their daily work.")
    @UserMessage("Check the spelling of the article below and correct spelling mistakes." +
            "The language of the output should be the same language as the input." +
            "Only return the text, do not start with 'Article:'."+
            "Article: {{text}}")
    String spellcheck(@V("text") String text);

    @SystemMessage("You are a professional assistant to a news agency. Your task consist in assisting journalists in their daily work.")
    @UserMessage("Try to improve the article below. Correct spelling mistakes and if you judge a sentence is poorly written, rewrite it." +
            "The language of the output should be the same language as the input." +
            "Only return the text, do not start with 'Article:'."+
            "Article: {{text}}")
    String optimize(@V("text") String text);


    @SystemMessage("You are a professional assistant to a news agency. Your task consist in assisting journalists in their daily work.")
    @UserMessage("Suggest {{nrTitles}} different title(s) for the article below. " +
            "The title should consist of a single sentence and contain a maximum of {{maxCharacters}} characters and only consist of full words." +
            "Do not use punctuation at the end."+
            "The language of the output should be the same language as the input." +
            "Article: {{text}}")
    List<String> headlineGenerator(@V("nrTitles") int nrTitles,
                                   @V("maxCharacters") int  maxCharacters,
                                   @V("text") String text);


    @SystemMessage("You are a professional assistant to a news agency. Your task consist in assisting journalists in their daily work.")
    @UserMessage("Suggest synonyms for the input below. " +
            "The input will be in either French or Dutch so reply in the same language."+
            "If the input is a single word, return a list of options, if it's a phrase, write it differently."+
            "Input: {{text}}")
    List<String> synonyms(@V("text") String text);

    
}`

Here's an example of a class I have. Most methods have the same systemMessage except the translate one.

**Comment by langchain4j** [comment]
@BlueJoneleth [dynamic system messages](https://github.com/langchain4j/langchain4j/pull/862) are now available in 0.30.0. 
Let me know if this is enough or you need `@SystemMessage` annotated parameters.

**Comment by langchain4j** [comment]
Closing for now, feel free to reopen

**Comment by BlueJoneleth** [comment]
Thanks for the update, seems promising. 

I'll try to refactor my stuff using the new version in the coming days.
