### ISSUE TITLE
[FEATURE] Text Splitter

### ISSUE THREAD

**Issue by tonybaloney** [langchain4j/langchain4j#808]
Please add a Text splitting service for breaking up text into chunks for LLMs that have a token input limit beneath the size of the data, that takes:

- A large piece of text as input
- Parameters such as the size of each chunk
- Separators to split text by
- Optionally splitting into chunks measured by the maximum number of tokens (with tokenizer)

See RecursiveTextSplitter in langchain as the most popular option for splitting with langchain.

**Comment by langchain4j** [comment]
@tonybaloney it is all already implemented, please take a look [here](https://github.com/langchain4j/langchain4j/tree/main/langchain4j/src/main/java/dev/langchain4j/data/document/splitter).
"RecursiveTextSplitter" can be created like [this](https://github.com/langchain4j/langchain4j/blob/fa110d33fdc12b2aa7064a66adda88f8a5e30096/langchain4j/src/main/java/dev/langchain4j/data/document/splitter/DocumentSplitters.java#L21) or [this](https://github.com/langchain4j/langchain4j/blob/fa110d33fdc12b2aa7064a66adda88f8a5e30096/langchain4j/src/main/java/dev/langchain4j/data/document/splitter/DocumentSplitters.java#L45).
