### ISSUE TITLE
[BUG] NullPointerException thrown when a tool has no parameters (vertex-ai-gemini)

### ISSUE THREAD

**Issue by mpelnens** [langchain4j/langchain4j#827]
https://github.com/langchain4j/langchain4j/blob/d6b5a7965630662daa1d1df5582bd0d995e266f6/langchain4j-vertex-ai-gemini/src/main/java/dev/langchain4j/model/vertexai/FunctionCallHelper.java#L115

Tools with no parameters (for example, `getCurrentTime()`) fail with a NullPointerException when the `required()` method is invoked since the `parameters` object is null.

**Comment by langchain4j** [comment]
cc @glaforge
