### ISSUE TITLE
[BUG] Unquoted JSON object value causes InvalidProtocolBufferException (vertex-ai-gemini) 

### ISSUE THREAD

**Issue by mpelnens** [langchain4j/langchain4j#828]
The value of the `result` key (`functionResponseText`) in line 73 is not enclosed in quotation marks:

https://github.com/langchain4j/langchain4j/blob/d6b5a7965630662daa1d1df5582bd0d995e266f6/langchain4j-vertex-ai-gemini/src/main/java/dev/langchain4j/model/vertexai/PartsMapper.java#L73

This causes the merge method in line 75 to throw an `InvalidProtocolBufferException`:

https://github.com/langchain4j/langchain4j/blob/d6b5a7965630662daa1d1df5582bd0d995e266f6/langchain4j-vertex-ai-gemini/src/main/java/dev/langchain4j/model/vertexai/PartsMapper.java#L75

Current workaround is to construct and return JSON object strings from Tools.

**Comment by langchain4j** [comment]
cc @glaforge

**Comment by glaforge** [comment]
@mpelnens What kind of function response do you have that triggers this problem?
I'm trying to reproduce this, but not succeeding so far.

**Comment by glaforge** [comment]
I could add another nesting `try`/`catch` with quoting, something like this:
```java
Struct.Builder structBuilder = Struct.newBuilder();
try {
    JsonFormat.parser().merge(functionResponseText, structBuilder);
} catch (InvalidProtocolBufferException e) {
    // TODO do a proper fix
    String functionResponseTextAsMap = "{\"result\":" + functionResponseText + "}";
    try {
        JsonFormat.parser().merge(functionResponseTextAsMap, structBuilder);
    } catch (InvalidProtocolBufferException e2) {
        String functionResponseTextWithQuotesAsMap = "{\"result\":" + quoted(functionResponseText) + "}";
        try {
            JsonFormat.parser().merge(functionResponseTextWithQuotesAsMap, structBuilder);
        } catch (InvalidProtocolBufferException e3) {
            throw new RuntimeException(e3);
        }
    }
}
```
But I haven't managed to reproduce the problem you encountered, so I'm a bit reluctant to add this change.

@mpelnens if you can provide a reproducer, that would be nice, thank you.

**Comment by glaforge** [comment]
I think I found a situation where this happens. I'll add the change I suggested in the previous comment.

**Comment by langchain4j** [comment]
Implemented in https://github.com/langchain4j/langchain4j/pull/1278
