### ISSUE TITLE
[FEATURE] Add in-process embedding models for Chinese

### ISSUE THREAD

**Issue by langchain4j** [langchain4j/langchain4j#83]
See https://github.com/FlagOpen/FlagEmbedding/tree/master/C_MTEB

**Comment by Gierry** [comment]
ok ,thank you very much

**Comment by langchain4j** [comment]
@Gierry we've added bge-small-zh in 2 versions: full (`langchain4j-embeddings-bge-small-zh`) and quantized (`langchain4j-embeddings-bge-small-zh-q`) in 0.20.0
