### ISSUE TITLE
[BUG] DocumentByParagraphSplitter does not split properly when \r\n line endings are used

### ISSUE THREAD

**Issue by langchain4j** [langchain4j/langchain4j#833]
It seems that `\r\n` is treated as a paragraph separator, which is wrong

**Comment by Kugaaa** [comment]
I found that there are different results under JDK8 and JDK17
- Java HotSpot(TM) 64-Bit Server VM (build 25.241-b07, mixed mode)
- Java HotSpot(TM) 64-Bit Server VM (build 17.0.9+11-LTS-201, mixed mode, sharing)

```java
public static void main(String[] args) {
    String s = "Hello\r\nWorld";
    String[] split = s.split("\\s*\\R\\s*\\R\\s*");
}
```

There is a discussion on similar issues here
https://stackoverflow.com/questions/47871962/why-does-r-behave-differently-in-regular-expressions-between-java-8-and-java-9
> In other words, it can only match a two code-point CR+LF (carriage return + linefeed) sequence or else a single code-point from that set provided that it is not just a carriage return alone that is then followed by a linefeed. That’s because it is not allowed to back up. CRLF must be atomic for \R to function properly.
> 
> So Java 9 no longer conforms to what R1.6 strongly recommends. Moreover, it is now doing something that it was supposed to NOT do, and did not do, in Java 8.

I replaced `//R` to `(?>\\R)` according to the suggestions in the document
It can work normally in both versions
