### ISSUE TITLE
[FEATURE] ChatLanguageModel: allow setting parameters dynamically

### ISSUE THREAD

**Issue by lbjfish** [langchain4j/langchain4j#837]
**Spring Boot , i want to dynamically call params，but it is limited too die:**
```
@Bean
    public ChatLanguageModel myCustomChatModel() {
        return OpenAiChatModel.builder()
                .apiKey("dynamically ")
                .stop(dynamically )
                .topP(dynamically )
                .temperature(dynamically )
                .modelName("dynamically ").build();
    }
```

**Comment by Kugaaa** [comment]
I am also thinking about it

1. Usually, different businesses will have different parameters, maybe should create different `AiService`
2. Supply method level parameters

**Comment by langchain4j** [comment]
@lbjfish @Kugaaa could you please describe your use cases? Why do you want to change parameters on the fly?

@Kugaaa, yes, the idea was to have a different `AiService`/`ChatLanguageModel` instances per use case/customer/etc, SRP

**Comment by langchain4j** [comment]
Related: https://github.com/langchain4j/langchain4j/discussions/1190#discussioncomment-9591461

**Comment by fmatar** [comment]
A much needed feature for our use case as well. 

@langchain4j our users have the capability of using different models (example gpt-3.5, gpt-4, gpt-4o with different API keys.

**Comment by geoand** [comment]
I am not still not clear why changing parameters makes more sense and not just creating a new `ChatLanguageModel` for example.

**Comment by langchain4j** [comment]
@geoand one use case I have in mind: automatically enabling json mode for structured data extraction. If `ChatLanguageModel` instance does not have it enabled and AI Service method returns a POJO, we could automatically enable json mode to increase the  probability of correct output.

**Comment by geoand** [comment]
That does indeed make sense.

**Comment by langchain4j** [comment]
Related: https://github.com/langchain4j/langchain4j/discussions/2123

**Comment by langchain4j** [comment]
Related: https://github.com/langchain4j/langchain4j/issues/2218
