### ISSUE TITLE
[FEATURE] Allows persistent storage of historical messages

### ISSUE THREAD

**Issue by yhan219** [langchain4j/langchain4j#84]
**Is your feature request related to a problem? Please describe.**
Hello, this is the best java LLM framework I have ever used, I have been using and learning it lately.Thank you for your dedication.

But now I have a problem, `MessageWindowChatMemory `seems to be put in memory, every time my app is restarted, it will be lost. I tried serializing the MessageWindowChatMemory into redis for example, but this class doesn't have a default constructor, so it fails, and even if I add a default constructor to this class, the ChatMessage class and its children need to add a default constructor only then. 

**Describe the solution you'd like**
If it is convenient, is it possible to add default constructors to these classes, or do you have any better ideas?

**Describe alternatives you've considered**
Is it possible to provide a method to store the chat history, allowing the user to overwrite it

**Additional context**
nothing

**Comment by yhan219** [comment]
Is it possible to provide the MessageWindowChatStore class, which provides methods for adding/modifying/deleting/searching for persistent storage and allows users to override it.
Please note that you need to provide a unique identifier parameter to distinguish different businesses, for example, use the `userId` parameter to obtain historical chat records of different users.

For example, if you have a better name, please modify the userId parameter

```
public abstract class MessageWindowChatStore implements ChatMemory {
    

    @Override
    public void add(String userId,ChatMessage message) {

    }

    @Override
    public List<ChatMessage> messages(String userId) {

    }

    @Override
    public void clear(String userId) {

    }


}
```

**Comment by yhan219** [comment]
Sorry, I found that there is already a similar issue #62, I didn't pay attention to it just now, but I think it may be a better choice to provide a MessageWindowChatStore class.
Of course, I am only based on my business considerations, maybe you have better ideas. expect.

**Comment by langchain4j** [comment]
Hi @yhan219 thank you for kind words!
We are working on adding an option to support multiple users and serialize/persist ChatMemory.
Do you use ChatMemory directly or via Chain or AiServices?
Do you expect to persist messages synchronously during conversation or before your application shuts down?

**Comment by yhan219** [comment]
I'm using AiService now, but I think it might be possible for Chain in the future too.

Yes, the data should be saved before the program finishes running.And it should be that each dialogue needs to be saved after completion.

The following is a method I use websocket, I need to save the data when steam is complete
```
    interface Chat {

        TokenStream chat(String userMessage);
    }
```
```
 @Override
    protected void handleTextMessage(WebSocketSession session, TextMessage message) throws Exception {
        String msg = message.getPayload();
        log.info("AiWebSocketHandler, sessionId:{}, receive message:{}", session.getId(), msg);

        Long userId = getUserIdFromRequest();
        StreamingChatLanguageModel streamingChatModel = OpenAiStreamingChatModel.builder().apiKey(API_KEY).modelName(API_MODEL).build();

//        get user history from redis
        MessageWindowChatMemory chatMemory = redisMessageWindowChatMemory.getByUserId(userId);

        Chat chat = AiServices.builder(Chat.class).streamingChatLanguageModel(streamingChatModel).chatMemory(chatMemory).build();

        StringBuilder answerBuilder = new StringBuilder();

        chat.chat(msg).onNext(it -> {
            answerBuilder.append(it);
            try {
                session.sendMessage(new TextMessage(it));
            } catch (IOException e) {
                log.error("send message error userMessage:{},answer:{}", msg, it);
            }
        }).onComplete(() -> {
            String answer = answerBuilder.toString();
            log.info("AI Finish，answer:{}", answer);

            // save to redis, refresh user chat memory
            redisMessageWindowChatMemory.refresh(userId, chatMemory);
        }).onError(it -> {
            log.error("AI error", it);
        }).start();
```

I modified the source code of langchain4j, added the default constructors of the classes mentioned above, and then wrote the following class

```

/**
 * CacheUtils is a redis cache service
 */
@Slf4j
@Component
public class RedisMessageWindowChatMemory {


    private static final String cache_name = "langchain_history#1h";

    private static final int maxMessages = 30;

    public void systemMessage(Long userId, String message) {
        MessageWindowChatMemory messageWindowChatMemory = MessageWindowChatMemory.withMaxMessages(maxMessages);
        messageWindowChatMemory.add(SystemMessage.systemMessage(message));
        refresh(userId, messageWindowChatMemory);
    }


    public MessageWindowChatMemory getByUserId(Long userId) {
        return CacheUtils.get(cache_name, userId);
    }

    public void refresh(Long userId, MessageWindowChatMemory messageWindowChatMemory) {
        CacheUtils.put(cache_name, userId, messageWindowChatMemory);
    }

    public void delete(Long userId) {
        CacheUtils.evict(cache_name, userId);
    }
}

```
Now my business works fine, but it doesn't seem very elegant.
The above is just a reference

**Comment by langchain4j** [comment]
@yhan219 we've added an option to persist chat memory in 0.21.0. Please see example [here](https://github.com/langchain4j/langchain4j-examples/blob/main/other-examples/src/main/java/ServiceWithPersistentMemoryForEachUserExample.java).

BTW you don't have to create model and service on each request, now you can configure them once per app and each new request can use the same service (providing user ID as a parameter annotated with @MemoryId)
