### ISSUE TITLE
[Question] How to configure AiServices to use Tools only?

### ISSUE THREAD

**Issue by tess1o** [langchain4j/langchain4j#854]
I'd like to configure AiServices that uses some Tools I've developed.  I want the AiServices to use the Tools only and do not answer other questions not related to the Tools (or answer something like "I don't have an answer for that"). 

There is a similar question in python version of the library (https://github.com/langchain-ai/langchain/issues/13059) but not sure if it is supported in the Java version.

Thanks!

**Comment by langchain4j** [comment]
HI @tess1o please describe your use case in more details.

**Comment by tess1o** [comment]
I'm trying to build a bot that should be able to  do some actions (using tools) and reply to the user. Just an example of tools I've implemented:
1. "call Peter Parker and notify about issue" - the bot understands the user's name and invokes correct method (tool)
2. "send sms to +1 555 000000 with text blah-blah" - the bot understand that it needs to send sms, can parse phone number and the text and invokes the tool
3. "find David's email address" 
4. etc

To handle such requests I've implemented tools and AI successfully uses the tools to do the required action.

I want the AI (bot) to handle only those requests which can be covered by the tools. All other requests (for instance "is 2024 a leap year?") should not be handled or handled by some pre-defined tool / response / etc.  Currently the AI (OpenAI in my case) tries to answer using it's knowledge base, which I don't want it to do.

So in my case I need the AIService to parse the user's request, invoke correct tool (or default one, when non of the other tools works) and handle the response from the tool. Everything else is not required.

I hope it's more clear, let me know if you need more information.

Thanks.

**Comment by Kugaaa** [comment]
I think this requirement like `MultiRouteChain` in LangChain
Can specify default_chain when use LangChain

```python
multi_prompt_chain = MultiPromptChain(
    router_chain=router_chain,
    destination_chains=chain_map,
    default_chain=default_chain,
    verbose=True)
```

It will call the default_chain when LLM believes there is no suitable destination
User can be customized this default_chain Instance, even throwing exceptions

**Comment by tess1o** [comment]
@Kugaaa,

Yes, that looks similar to what I'd like to achieve.  If LLM thinks that tools (functions) can't be used I'd like to get some default message or throw an exception that I can later handle properly.

Thanks.

**Comment by langchain4j** [comment]
There are multiple ways to achieve this.

1. Routing. It can be done either using LLM, embedding model or deterministic rules (e.g. keywords, etc).
1.1. For LLM routing, take a look at [this example](https://docs.langchain4j.dev/tutorials/ai-services#chaining), maybe it can help. 
1.2 For embedding model routing, take a look at [EmbeddingModelTextClassifier example](https://github.com/langchain4j/langchain4j-examples/blob/main/other-examples/src/main/java/embedding/classification/EmbeddingModelTextClassifierExample.java). 

2. Make a "default tool" with description like "call this if no other tool is suitable"

I feel like the best option for your use case is 1.2 (embedding model routing). If you can come up with a list of sample allowed queries, it can work very well and very cheap/fast. There is `minScore` parameter in `EmbeddingModelTextClassifier` which you can set to some higher value to filter out not allowed/not relvant queries.

In the future, for questions, please use [discord](https://discord.gg/JzTFvyjG6R) or [github discussions](https://github.com/langchain4j/langchain4j/discussions).

I am closing this issue, but feel free to open a discussion on discord/github and/or comment here.

**Comment by langchain4j** [comment]
Related: [comment](https://github.com/langchain4j/langchain4j/issues/952)
