### ISSUE TITLE
[FEATURE] Support embedding using Cohere

### ISSUE THREAD

**Issue by stephanj** [langchain4j/langchain4j#866]
**Describe the solution you'd like**
Include Cohere embedding next to the ReRanker

**Additional context**
Allow Langchain4J to also support Cohere embedding.

**Comment by stephanj** [comment]
I've developed the feature and refactored/cleaned up the existing Cohere code with backward compatibility. 
👉🏼 https://github.com/stephanj/langchain4j-cohere

**Comment by langchain4j** [comment]
Implemented in https://github.com/langchain4j/langchain4j/pull/1145
