### ISSUE TITLE
Initializing ChatMemory, ChatLanguageModel takes too long?

### ISSUE THREAD

**Issue by 0cothucluc** [langchain4j/langchain4j#87]
I'm following the second [example](https://github.com/langchain4j/langchain4j-examples/blob/main/other-examples/src/main/java/ChatMemoryExamples.java) but when init both chat memory and LLM takes too long (20 - 30s), can you explain why and give me some best practices when initializing it?

**Comment by langchain4j** [comment]
Hi @0cothucluc do you have some logs? When exactly does it freeze?
Could be a problem with OpenAI, sometimes they have long response times.
Please provide logs, thanks!

**Comment by langchain4j** [comment]
@0cothucluc also, if you are using "demo" key, there is extra latency in our proxy service (should be less than a second) because we first moderate each request via https://platform.openai.com/docs/api-reference/moderations before sending it to OpenAI.

**Comment by 0cothucluc** [comment]
What do you mean? I see the log but don't see anything about OpenAi, Langchain

**Comment by langchain4j** [comment]
Could you please provide the log? It is hard to help otherwise. Thanks.

**Comment by langchain4j** [comment]
@0cothucluc closing this issue due to no response. Feel free to reopen.
