### ISSUE TITLE
[BUG] The method 'toEmbedTexts' in DefaultZhipuAiHelper may have a bug.

### ISSUE THREAD

**Issue by viccP** [langchain4j/langchain4j#876]
When processing textSegments in the 'toEmbedTexts' method of DefaultZhipuAiHelper, only the first item of the result after streaming conversion is taken. If the size of the passed List<TextSegment> is greater than 1, this handling will cause: 1. Data loss, 2. An inconsistency between the entries of 'embeddings' and 'segments' during the subsequent embeddingStore.addAll(embeddings, segments), resulting in detection exceptions. It is unclear whether the 'return embedText.get(0)' is simply a bug or intentionally designed this way.
![bug](https://github.com/langchain4j/langchain4j/assets/11806067/74b8c531-c874-4e9a-b48b-125a8f78cca6)

**Comment by xermaor** [comment]
Hello, ZhipuAi vectorization interface only supports the vectorization of a single text and does not support multiple texts, so only the first text is used for vectorization. Perhaps here, each text in the list can be vectorized separately and then returned. , I will try my best to add this in the next version.
