### ISSUE TITLE
Broken link in the tutorial docs 

### ISSUE THREAD

**Issue by GuyKe** [langchain4j/langchain4j#880]
In the tutorial, under RAG there are examples - (https://docs.langchain4j.dev/tutorials/rag#examples),
the "Rag + Tools" is broken and bring me to a 404. I assume this is correct link? https://github.com/langchain4j/langchain4j-examples/tree/main/customer-support-agent-example

**Comment by remyohajinwa** [comment]
I am taking a look at this

**Comment by langchain4j** [comment]
Fixed in https://github.com/langchain4j/langchain4j/pull/889
