### ISSUE TITLE
[FEATURE] Google Gemini Gemini 1.5 Pro Experimental

### ISSUE THREAD

**Issue by luismospinam** [langchain4j/langchain4j#882]
**Describe the solution you'd like**
Google has enabled a new model which is expertiamental yet "Gemini 1.5 Pro Experimental". Is this new model planned to be incorpoated?
I get the following error when try to use it but not sure if this because it is experimental and I don't have acces to it:

`com.google.api.gax.rpc.NotFoundException: io.grpc.StatusRuntimeException: NOT_FOUND: Publisher Model `projects/xxxxxx-project/locations/us-central1/publishers/google/models/gemini-1.0-pro-latest` not found.`

**Additional context**
I'm able to use this new model in the console
![image](https://github.com/langchain4j/langchain4j/assets/25059970/22ea7de6-7fbf-461c-8719-6fcc949835b4)

**Comment by langchain4j** [comment]
cc @glaforge

**Comment by glaforge** [comment]
The API is not available yet.
You can only experiment in the cloud console for now. 
It should be available via the API very soon though, like maybe this week or the next hopefully.

**Comment by luismospinam** [comment]
@glaforge it seems the API is already available but an additional flag needs to be passed: `{apiVersion: 'v1beta'}`
Is there anyway to specify this flag in `langchain4j` ?

https://github.com/google-gemini/generative-ai-python/issues/227
https://ai.google.dev/gemini-api/docs/api-versions?hl=es-419

**Comment by glaforge** [comment]
Could you please try to use `gemini-1.5-pro-preview-0409` as model name/version? (this works for me)

**Comment by luismospinam** [comment]
that worked, thanks @glaforge

**Comment by glaforge** [comment]
Great news!
So I guess we can close this issue?
