### ISSUE TITLE
[BUG] embedding model AllMiniLmL6V2EmbeddingModel seem not work well for chinese.

### ISSUE THREAD

**Issue by mahonelau** [langchain4j/langchain4j#884]
**Describe the bug**

**Log and Stack trace**

**To Reproduce**

**Expected behavior**

**Please complete the following information:**
- LangChain4j version:
- LLM(s) used: 
- Java version: 
- Spring Boot version (if applicable): 

**Additional context**

**Comment by langchain4j** [comment]
Can you provide more context?

**Comment by mahonelau** [comment]
No problem yet, minScore too high. thanks.
