### ISSUE TITLE
[BUG] ZhipuAiEmbeddingModel return not correct size

### ISSUE THREAD

**Issue by mahonelau** [langchain4j/langchain4j#885]
**Describe the bug**

pass a list of segments with 6 segment to method embedAll, return a list with only on embedding.
when call embeddingStore.addAll(embeddings, segments), exception occur: embedding size not match embedd size.

**Log and Stack trace**

**To Reproduce**

**Expected behavior**

pass a list of segments with 6 segment to method embedAll, return a list with 6 embedding.

**Please complete the following information:**
- LangChain4j version: 0.28.0
- LLM(s) used:  Qwen
- Java version:  21
- Spring Boot version (if applicable): 2.3.5

**Additional context**

**Comment by langchain4j** [comment]
Duplicate of https://github.com/langchain4j/langchain4j/issues/876
