### ISSUE TITLE
[FEATURE] Anthropic tools/functions

### ISSUE THREAD

**Issue by langchain4j** [langchain4j/langchain4j#890]
Anthropic now supports tools, we should too: https://docs.anthropic.com/claude/docs/tool-use

**Comment by daixi98** [comment]
@langchain4j  May I work on this task please?

**Comment by langchain4j** [comment]
@daixi98 sorry, I am almost done with this already

**Comment by langchain4j** [comment]
@daixi98 draft PR is here: https://github.com/langchain4j/langchain4j/pull/897
Could you please review?
