### ISSUE TITLE
[FEATURE] Ability to provide entire connection string for pgvector

### ISSUE THREAD

**Issue by bbideep** [langchain4j/langchain4j#893]
**Is your feature request related to a problem? Please describe.**
Unable to setup connection to SSL enabled postgres since the `setupConnection()` method in langchain4j-pgvector/src/main/java/dev/langchain4j/store/embedding/pgvector/PgVectorEmbeddingStore.java supports only host and port.

**Describe the solution you'd like**
Ability to set up the connection using a connection string.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by kchaber** [comment]
You can pass the [additional driver options](https://jdbc.postgresql.org/documentation/use/#connection-parameters) as query parameters using the `database(…)` method of the `PgVectorEmbeddingStoreBuilder`:
```java
PgVectorEmbeddingStore.builder()
    .host("<host>")
    .port("<port>")
    .database(String.format("%s?ssl=allow&sslfactory...", "<database>"))
    ...
    .build();
```

**Comment by langchain4j** [comment]
Implemented in https://github.com/langchain4j/langchain4j/issues/1160
