### ISSUE TITLE
[FEATURE] Support more advanced POJO/JSON extraction features

### ISSUE THREAD

**Issue by langchain4j** [langchain4j/langchain4j#904]
See https://github.com/LizeRaes/feedback-analyzer/blob/main/src%2Fmain%2Fjava%2Fengineering%2Fepic%2FAtomicFeedback.java

For example, possible values of `Tag` in `List<Tag> tags` are not propagated in the prompt

**Comment by remyohajinwa** [comment]
Hi I am taking a look at this

**Comment by langchain4j** [comment]
Hi @LizeRaes, the link does not work any more :(
Do you still remember what was the problem with `List<Tag> tags`?
Thanks!

**Comment by LizeRaes** [comment]
Here's the [working link](https://github.com/LizeRaes/feedback-analyzer/blob/main/src/main/java/engineering/epic/datastorageobjects/AtomicFeedback.java).
This was a List of Enum and was not supported back then, I think it's long okay right now :)

**Comment by langchain4j** [comment]
@LizeRaes thanks!
