### ISSUE TITLE
How to pass prompt in spring boot integration

### ISSUE THREAD

**Issue by deepakn27** [langchain4j/langchain4j#906]
### Discussed in https://github.com/langchain4j/langchain4j/discussions/905

<div type='discussions-op-text'>

<sup>Originally posted by **deepakn27** April  9, 2024</sup>
I am writing a spring boot app.

 @SystemMessage("""
            You are an intelligent assistant user will execute sql query
            question will be in format question  {{userQuestion}}--- {{sqlQuery}}
            """)
    TokenStream chat(@MemoryId String chatId, @UserMessage List<String> userMessage);
    
    My user message in in format  Userquestion --- sql query.
    
    How can i do this, above is not working.</div>

**Comment by langchain4j** [comment]
Please do not open duplicate issues. https://github.com/langchain4j/langchain4j/discussions/905 is enough
