### ISSUE TITLE
[Question] How to configure other models?

### ISSUE THREAD

**Issue by RaymonZhang1011** [langchain4j/langchain4j#915]
How to configure other models?I want to use other internal models in this framework.thanks

**Comment by langchain4j** [comment]
Hi, you can find supported models here: https://docs.langchain4j.dev/integrations/#supported-llm-integrations
And many more examples here: https://github.com/langchain4j/langchain4j-examples

Please do not use issues for questions, you can open a discussion [here](https://github.com/langchain4j/langchain4j/discussions) or [here](https://discord.gg/JzTFvyjG6R)

**Comment by RaymonZhang1011** [comment]
> Hi, you can find supported models here: https://docs.langchain4j.dev/integrations/#supported-llm-integrations And many more examples here: https://github.com/langchain4j/langchain4j-examples
> 
> Please do not use issues for questions, you can open a discussion [here](https://github.com/langchain4j/langchain4j/discussions) or [here](https://discord.gg/JzTFvyjG6R)

sorry  i want to configure  a non-local private model    i will open a discussion and ask this question
