### ISSUE TITLE
[FEATURE] Demo key should support tools and other parameters/features

### ISSUE THREAD

**Issue by langchain4j** [langchain4j/langchain4j#927]
Demo key should support tools and other parameters/features

**Comment by langchain4j** [comment]
See https://github.com/langchain4j/langchain4j-examples/issues/18

**Comment by kdubois** [comment]
This would be a really nice feature for testing purposes, especially for Hands-on-Lab scenarios so the attendees can try out some more advanced features without having to create an OpenAI key.

**Comment by langchain4j** [comment]
It's been supported for some weeks now
