### ISSUE TITLE
[BUG] Anthropic: first message must use the "user" role

### ISSUE THREAD

**Issue by langchain4j** [langchain4j/langchain4j#940]
When using Anthropic models with `ChatMemory`, it can happen that messages do not fit into the memory any more and the first `UserMessage` gets evicted. In this case, Anthropic will raise an error.

Potential solutions:
- if `Anthropic*Model.generate()` methods receive a list and the first message is not a `UserMessage`, drop messages from the beginning of a list untill first message is `UserMessage`
- if `Anthropic*Model.generate()` methods receive a list and the first message is not a `UserMessage`, prepend a dummy `UserMessage`

**Comment by johnsosoka** [comment]
I'll address this, feel free to assign the ticket to me.

**Comment by johnsosoka** [comment]
https://github.com/langchain4j/langchain4j/pull/1197

**Comment by langchain4j** [comment]
Fixed by https://github.com/langchain4j/langchain4j/pull/1197
