### ISSUE TITLE
[FEATURE] Support (Metadata) FIlter in Pinecone

### ISSUE THREAD

**Issue by langchain4j** [langchain4j/langchain4j#949]
Pinecone integration should support [Metadata Filtering](https://github.com/langchain4j/langchain4j/pull/610).

**Comment by hrhrng** [comment]
Hi, @langchain4j I'd like to support this.
Is it right to impletment dev.langchain4j.store.embedding.EmbeddingStore#search in dev.langchain4j.store.embedding.pinecone.PineconeEmbeddingStore?

**Comment by langchain4j** [comment]
Hi @hrhrng, awesome!


> Is it right to impletment dev.langchain4j.store.embedding.EmbeddingStore#search in dev.langchain4j.store.embedding.pinecone.PineconeEmbeddingStore?


Yes, correct
