### ISSUE TITLE
[BUG] ZhipuAiChatModel does not support tools without parameters

### ISSUE THREAD

**Issue by langchain4j** [langchain4j/langchain4j#950]
**Describe the bug**
When using a tool without input parameters, a NPE is happening.

**Log and Stack trace**
`Cannot invoke "dev.langchain4j.agent.tool.ToolParameters.properties()" because "toolParameters" is null`

**To Reproduce**

```java
ToolSpecification currentTime = ToolSpecification.builder()
    .name("currentTime")
    .description("currentTime")
    .build();
```

**Expected behavior**
Should work without NPE.

**Please complete the following information:**
- LangChain4j version: 0.30.0
- LLM(s) used: ZhipuAiChatModel
- Java version: any

**Comment by langchain4j** [comment]
@1402564807 fyi

**Comment by yongxingMa** [comment]
Once again, I went to test and found the zhipu API requires that tools must carry parameters ,So does this bug still need to be fix?

**Comment by yongxingMa** [comment]
Or we can add a judgement that throws the specified exception

**Comment by langchain4j** [comment]
@yongxingMa what do you mean? This bug should still be fixed

**Comment by xermaor** [comment]
@langchain4j Sorry I just saw this question, I will deal with it now
