### ISSUE TITLE
[FEATURE] QianfanChatModel does not support http proxy setting

### ISSUE THREAD

**Issue by MRPanyu** [langchain4j/langchain4j#951]
**Is your feature request related to a problem? Please describe.**
While QianfanClient has proxy setting, QianfanChatModel which uses the client does not have proxy setting parameters, which makes it impossible to use under certain network condition.

**Describe the solution you'd like**
Add proxy setting parameters in QianfanChatModel / QianfanStreamingChatModel / QianfanEmbeddingModel

**Describe alternatives you've considered**
Any alternative methods for setting proxy for service based AI models will do.

**Additional context**
- LangChain4j version: 0.29.1

**Comment by langchain4j** [comment]
Implemented in https://github.com/langchain4j/langchain4j/pull/1159
