### ISSUE TITLE
[BUG]  qianfan model QwenStreamingChatModel Response Invalid content-type: application/json

### ISSUE THREAD

**Issue by w4901** [langchain4j/langchain4j#958]
QianfanStreamingChatModel model= QianfanStreamingChatModel.builder()
                    .modelName(QianfanChatModelNameEnum.ERNIE_BOT_8.getModelName())
                    .endpoint(QianfanChatModelNameEnum.ERNIE_BOT_8.getEndpoint())
                    .build();
                      model.generate(historyList2, new StreamingResponseHandler<AiMessage>() {
                                @Override
                                public void onNext(String token) {
                                    System.out.print(token);
                                }

                                @Override
                                public void onError(Throwable error) {
                                    error.printStackTrace();
                                    System.out.println("error="+error);
                                }

                                @Override
                                public void onComplete(Response<AiMessage> response) {
                                    StreamingResponseHandler.super.onComplete(response);
                         
                                    System.out.println("");
                                }
                            });

**Comment by Hwongyohong** [comment]
请问解决了吗？
