### ISSUE TITLE
When will the azure-openai-chat/embedding model be supported?

### ISSUE THREAD

**Issue by TylorWu** [langchain4j/langchain4j#96]
When will the azure-openai-chat/embedding model be supported? It seems that LocalAIChatModel does not support it,If there are any other solutions, please let me know. Thank you.
![image](https://github.com/langchain4j/langchain4j/assets/103818678/993b88b6-4d4e-40b3-b64e-231419b968d4)

**Comment by TylorWu** [comment]
Is it helpful to add some parameters to LocalAI, such as apiPrefix and custom header parameters, to solve this problem?

**Comment by langchain4j** [comment]
@TylorWu we are going to add support for Azure OpenAI in the coming days. Will keep you posted.

**Comment by radhakrishna67** [comment]
@langchain4j , we are also looking for it.

**Comment by langchain4j** [comment]
@TylorWu we've added integration with Azure OpenAI in 0.21.0 (see `AzureOpenAi*Model` classes). Unfortunately we don't have access to it, so we've developed it blindly by docs without ability to test. Please check and provide your feedback, thank you!
