### ISSUE TITLE
[BUG] ZhipuAiEmbeddingModel embedAll function textSegments not same  List<Embedding> size

### ISSUE THREAD

**Issue by yongxingMa** [langchain4j/langchain4j#965]
**Describe the bug**

use ZhipuAiEmbeddingModel  split the document for vectorization ,the following error was found
`The list of embeddings and embedded must have the same size`

Check the code probably here bug
```
Class ZhipuAiEmbeddingModel:
    public Response<List<Embedding>> embedAll(List<TextSegment> textSegments) {
        EmbeddingRequest request = EmbeddingRequest.builder().model(this.model).input(new String[]{DefaultZhipuAiHelper.toEmbedTexts(textSegments)}).build();
        EmbeddingResponse response = (EmbeddingResponse)RetryUtils.withRetry(() -> {
            return this.client.embedAll(request);
        }, this.maxRetries);
        return Response.from(DefaultZhipuAiHelper.toEmbed(response), DefaultZhipuAiHelper.tokenUsageFrom(response.getUsage()));
    }

Class DefaultZhipuAiHelper:

    public static String toEmbedTexts(List<TextSegment> textSegments) {
        List<String> embedText = (List)textSegments.stream().map(TextSegment::text).collect(Collectors.toList());
        return Utils.isNullOrEmpty(embedText) ? null : (String)embedText.get(0);
    }

```
Why embedText.get(0)?

Th textSegments is a List, may need to for loop calls zhiPuAPI Embedding API
API address: https://open.bigmodel.cn/dev/api#text_embedding

**Please complete the following information:**
- LangChain4j version: 0.30.0
- LLM(s) used:  zhipuAi
- Java version: 17
- Spring Boot version (if applicable): 3.2.4

**Comment by langchain4j** [comment]
Duplicate of https://github.com/langchain4j/langchain4j/issues/876
