### ISSUE TITLE
langchain4j integration with redis

### ISSUE THREAD

**Issue by radhakrishna67** [langchain4j/langchain4j#97]
I am waiting for a redis integration with langchain4j.

**Comment by langchain4j** [comment]
@radhakrishna67 redis as an embedding store? we will add this to our backlog.

**Comment by radhakrishna67** [comment]
Yes, Vectore Store

**Comment by radhakrishna67** [comment]
is there any update when this is going to be implemented?

**Comment by Martin7-1** [comment]
> is there any update when this is going to be implemented?

Hi! I'm trying to contribute redis integration. PR is expected to be mentioned within a week. Draft PR can see [PR](https://github.com/Martin7-1/langchain4j/pull/3)

**Comment by langchain4j** [comment]
Was added long ago
