### ISSUE TITLE
[FEATURE] Jina embeddings

### ISSUE THREAD

**Issue by langchain4j** [langchain4j/langchain4j#973]
Integrate [Jina Embeddings](https://jina.ai/embeddings/) as `EmbeddingModel`.

**Comment by lucifer-Hell** [comment]
Hi @langchain4j  can you please assign this issue to me if some hasn't picked this already ?

**Comment by lucifer-Hell** [comment]
Hi @langchain4j , i have started working on integration . Is it okay if i follow AzureOpenAIEmbeddingModel as standard ref for building ?

**Comment by langchain4j** [comment]
Hey, Azure uses official SDK. I guess for Jina we will have to make our own client. Please take a look here:https://github.com/langchain4j/langchain4j/blob/main/CONTRIBUTING.md#guidelines-on-adding-a-new-embedding-store-integration

**Comment by lucifer-Hell** [comment]
Yes for jina ai currently python and javascript sdks are there only . So we have to build our own client . Thanks for sharing the  guidelines i hv gone through that but the standard examples mentioned anthropic and chroma doesn't have any implementation of embedding model. I hv understanding but i just wanted to confirm if we hv to follow any standard ref/example for implementing Embedding Models .

**Comment by langchain4j** [comment]
Pardon, I mixed up embedding model and store :D 
For `EmbeddingModel` implementation example, please check `NomicEmbeddingModel`

**Comment by lucifer-Hell** [comment]
Thanks for sharing we can add this point in contribute guideline doc also.

**Comment by lucifer-Hell** [comment]
Hi @langchain4j  can you please review [PR](https://github.com/langchain4j/langchain4j/pull/997)

**Comment by langchain4j** [comment]
Hi @lucifer-Hell thank you a lot! I will review it, in the order of priorities

**Comment by lucifer-Hell** [comment]
Hi @langchain4j  just wanted know if u got the time to review it

**Comment by langchain4j** [comment]
@lucifer-Hell unfortunately not yet

**Comment by lucifer-Hell** [comment]
Hi @langchain4j just checking on this issue . If your bandwidth is less you may assign someone else as reviewer if its possible.

**Comment by lucifer-Hell** [comment]
Hi @langchain4j  i have updated the changes as mentioned and tagged you in the pr. Please take a look at it whenever you get time .

**Comment by langchain4j** [comment]
Implemented in https://github.com/langchain4j/langchain4j/pull/997
