### ISSUE TITLE
Azure OpenAI Service LLM provider support

### ISSUE THREAD

**Issue by radhakrishna67** [langchain4j/langchain4j#98]
I am looking for Azure OpenAI Service LLM provider support with langchain4j

**Comment by langchain4j** [comment]
@radhakrishna67 we are working on it, will be available soon.

**Comment by langchain4j** [comment]
@radhakrishna67 which type of authentication do you plan to use?

> API Key authentication: For this type of authentication, all API requests must include the API Key in the api-key HTTP header. The [Quickstart](https://learn.microsoft.com/en-us/azure/ai-services/openai/quickstart) provides guidance for how to make calls with this type of authentication.
> 
> Azure Active Directory authentication: You can authenticate an API call using an Azure Active Directory token. Authentication tokens are included in a request as the Authorization header. The token provided must be preceded by Bearer, for example Bearer YOUR_AUTH_TOKEN. You can read our how-to guide on [authenticating with Azure Active Directory](https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/managed-identity).

Source: https://learn.microsoft.com/en-us/azure/ai-services/openai/reference

**Comment by langchain4j** [comment]
@radhakrishna67 we've added integration with Azure OpenAI in 0.21.0 (see `AzureOpenAi*Model` classes). Unfortunately we don't have access to it, so we've developed it blindly by docs without ability to test. Please check and provide your feedback, thank you!

**Comment by radhakrishna67** [comment]
Thank you so much for quick help here. I will update it.
